### PR TITLE
Debug builds fails at commit if reallocated

### PR DESCRIPTION
**Pull request by gerhardol**
Fix as seen in #4031

Changes proposed in this pull request:
 - Possibility to move the installation files for Debug builds to paths shorter than build path
 
Screenshots before and after (if PR changes UI):
-No

How did I test this code:
 - Copied bin/Debug to upper directories

Has been tested on (remove any that don't apply):
 - GIT 2.14 (not Git dependent)
 - Windows 7 and Win10

### CODE REVIEW

**Comment by RussKie** [comment]
Could you please clarify the use case for this?

**Comment by gerhardol** [comment]
I have built the debug package at home and want to test it at work

The change only affects debug build and is obviously incorrect...

**Comment by RussKie** [comment]
I have no probs just copying folder from one computer to another....

**Comment by gerhardol** [comment]
It sure works if you copy it to a deep enough path, if the new path length is larger than the path it was compiled in

Current code
            int len = debugPath.Length;
            var path = gitExtDir.Substring(gitExtDir.Length - len);

New
            int len = debugPath.Length;
            if (gitExtDir.Length > len)

**Pull request merged**
