### PR TITLE
Fixes on jira commit hint plugin

### PR DESCRIPTION
**Pull request by pmiossec**
Changes proposed in this pull request:
 - (improve perf) Don't block FormCommit opening during http request to jira (the plugin made the commit form slow to open :( ). Introduce some async (remove a `.Result`)
- Fix display of multiline text in multiline setting textbox ( of jira setting panel "Message template" textbox )
- (minor) Better display of the preview message
 
What did I do to test the code and ensure quality:
 - manual test

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

**Comment by pmiossec** [comment]
@ierof If you could have a look...

**Comment by RussKie** [comment]
I haven't tested but it looks good

**Comment by ierof** [comment]
@pmiossec  code reviewed and approved

**Comment by RussKie** [comment]
@ierof then click the magic button 😉 
have you had a chance to test it?

**Comment by ierof** [comment]
@RussKie yes, i've spent some time right now and tested it. There is no any problem on my settings :)

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
