### PR TITLE
Experimental grid/list layout

### PR DESCRIPTION
**Pull request by ivangrek**
Fixes #8739, #8740

## Proposed changes

- Ref #8739, #8740
- Add experimental settings for controversial cases to speed up implementation.

## Test methodology 

- Manually
- Visually

## Test environment(s) 

- Git Extensions 33.33.33
- Build 0c943f78935f53de769ba7ee920ff25bfb5eeaf1 (Dirty)
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Blocking until we discuss the experimental settings approach, see: https://github.com/gitextensions/gitextensions/pull/8844#issuecomment-779193235

**Comment by ivangrek** [comment]
> Blocking until we discuss the experimental settings approach, see: #8844 (comment)

Maybe just transfer the setting to "Appearance"?

**Comment by RussKie** [comment]
> Maybe just transfer the setting to "Appearance"?

👍

**Comment by ivangrek** [comment]
image

image

**Pull request closed without merging**
