### PR TITLE
Better ergonomic around commit form

### PR DESCRIPTION
**Pull request by pmiossec**
- save amend checkbox state when closing form
- disable commit form minimize button when open from browse window (because that's absolutely not ergonomic)

### CODE REVIEW

**Comment by KindDragon** [comment]
> save amend checkbox state when closing form

I don't know, in my use-case I often do ordinary commit after amend.

**Comment by vbjay** [comment]
I can see remembering it till they click commit.  Then reset it.

**Comment by pmiossec** [comment]
>I don't know, in my use-case I often do ordinary commit after amend.

Not sure of the exact case you describe here...

>I can see remembering it till they click commit. Then reset it. 

Indeed, the state is remember until we click on "commit" but lost if we close the commit form (for example to see a commit message, a diff or something else). When we come back to the commit form to finish our commit message, we have to remember (or see!) that the checkbox was not checked anymore.

This fix just remember the state until we commit.
I think that's a better behavior...

**Comment by matkoch** [comment]
Agree on remembering the state. Message is also restored, so let's make it consistent.

**Comment by ghanique** [comment]
I don't want the Amend check box to be persisted if I close the form!
Sounds very dangerous!

If by mistake I create a new commit instead of amending it then that is
easily fixed. Amending a commit by mistake is much harder to fix!

**Comment by vbjay** [comment]
The flow is this. 

User checks amend
User closes form
User brings commit window back
Amend is still checked
When they commit unchecked amend

This way it still remembers the state but you never accidently amend.

**Comment by matkoch** [comment]
@ghanique as far as I remember, you will get a message box asking if you want to amend.

**Comment by pmiossec** [comment]
@ghanique  As @vbjay and @matkoch told you, their is a popup that prevent you to do the mistake if you click too quickly.

I highly believe that there is a lot more chance that someone that just click on the amend checkbox want his choice remembered instead of wanting to disappear...

>If by mistake I create a new commit instead of amending it then that is
easily fixed. Amending a commit by mistake is much harder to fix!

Not a lot. You just have to look at the reflog. And I did a pull request for that :laughing:  #3242

**Comment by jbialobr** [comment]
>I don't know, in my use-case I often do ordinary commit after amend.

When a commit gets committed the Amend state is not remembered (it is actually cleared). So it will be only restored when you close window not committing.
@pmiossec Maybe to be super safe GitExt could remove the amend file right after reading it in?
We can also add an option to disable this behavior. I think it should be enabled by default.

**Comment by pmiossec** [comment]
>Maybe to be super safe GitExt could remove the amend file right after reading it in?

no problem. I will do it.

>We can also add an option to disable remembering amend state. I think it should be enabled by default.

I thought about that but found out that it was a little overkill and a pitty that, what I found a (little) ergonomic improvment, be disabled by default and consequently never enabled by nearly all the users.

But I will do it, especially if that permit to merge it ;)

**Comment by jbialobr** [comment]
>I thought about that but found out that it was a little overkill and a pitty that, what I found a (little) ergonomic improvment, be disabled by default and consequently never enabled by nearly all the users.

As I said - it should be **enabled** by default.
Since there are very strong votes to not doing this, it would be good to let them disable this feature.
FYI, the amend warning can be disabled.

**Comment by pmiossec** [comment]
>As I said - it should be enabled by default.

Oh, ok! Make more sense ;-) I read twice your original sentence but understand the contrary.

I understood: add an option "disable remembering amend state" with enable state by default ;-)

I'm happy, so!

**Comment by pmiossec** [comment]
Done! ;)

I've put the setting in `Advanced` > `General` >  `Don't remember 'Amend commit' checkbox on commit form close`

**Comment by jbialobr** [comment]
Thank you. I moved the setting to the Commit dialog settings page as it does not look like an advanced one.

**Pull request merged**
