### PR TITLE
Replace some lambdas with local functions

### PR DESCRIPTION
**Pull request by drewnoakes**
Local functions offer some performance benefits, as well as looking a bit nicer (see the example in `GitCommandHelper.cs` where the `null` assignment can be removed in favour of a single declaration).

The main performance improvement is the compiler's ability to avoid heap allocation when closing over state.

For more information, see https://stackoverflow.com/a/40949214/24874

Has been tested on:
 - GIT 2.16
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you

**Comment by drewnoakes** [comment]
You're welcome. Thanks for all your work on this awesome project.

If there's interest, I can make a PR with some other changes that take advantage of newer language features. For example, browsing through the code last night, I found several places where code could be simplified via things like auto-properties, null coalescence, replacing lambdas with method groups, nameof, making fields readonly, etc. These should reduce the amount of code, reduce allocations, and reduce the chance for certain classes of error to be introduced. If this sounds useful I would make a PR with one commit per type of change.

**Comment by crypto-rsa** [comment]
Local fuctions are a feature of C# 7. Does this mean that the solution could no longer be built in VS 2015?

**Comment by drewnoakes** [comment]
If 2015 is required then this should be reverted. I tried to build the solution in VS2015 and received compile errors, so assumed 2017 was required. I can't find any documentation stating the required VS or C# level.

**Comment by drewnoakes** [comment]
If a specific level of C# is required, perhaps the `<LangLevel>` attribute should be specified in the csproj files.

**Comment by gerhardol** [comment]
VS2015 is supported. Until just recently, VS2015 was the default (changed in #4434).
Build instructions are pointing at VS2017:
https://github.com/gitextensions/gitextensions/wiki/Build-Instructions
(I should have stated the supported versions slightly differently).

For users without Pro licenses, supporting VS2015 makes no difference as you only can istall VS2017 Community anyway.
VS2015 Pro users may want to keep support.

What benefits do C#7 and VS2017 give?

**Comment by drewnoakes** [comment]
This PR will have broken compilation under VS2015. If 2015 is required, would it be possible to set up an equivalent build under AppVeyor that would have failed this PR? Adding `<LangVersion>6</LangVersion>` to the project file would have flagged local methods are being invalid in VS2017 too.

I've dropped all but VS2017 on my open source .NET projects, as community edition is available for all open source purposes.

C# 7.0, C# 7.1 and C# 7.2 introduced a long list of performance and developer convenience features that allow things to be expressed more succinctly. It's possible to use the newer compiler's features and target older platforms.

- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7
- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1
- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2

The most useful features in my opinion are:

- local functions
- out variable declarations
- pattern matching
- throw expressions
- expression bodied members

**Comment by gerhardol** [comment]
I submitted #4475 to have a discussion about VS2017. I vote in favor to require V2017

> If a specific level of C# is required, perhaps the <LangLevel> attribute should be specified in the csproj files.

Need to be set...

**Comment by RussKie** [comment]
https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015

**Comment by gerhardol** [comment]
> https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015

Then let us document this and go on?

**Comment by RussKie** [comment]
Given that you have access to VS2015, could you please confirm it actually
works.
If it does, we can probably add these packages to the solution.

**Comment by drewnoakes** [comment]
@RussKie I ran a test and commented about it [here](https://github.com/gitextensions/gitextensions/issues/4479#issuecomment-365423250).

**Comment by gerhardol** [comment]
I have tried to build, have not succeeded in building from Visual Studio 2015
Installed Microsoft.Net.Compilers 2.6.1 (same compiler as VS2017 15.5) and added it to all relevant packages. This nuget will have to be maintained also for VS2017.
Installed Build Tools 12017 (15.0) (not sure I got all packages).

The instructions are a little unclear, maybe it is just possible to override build tools from the command line, with "/tv:15". This works on my PC but I have 2017 installed, so no good test case. Appveyor fails, but I have not found how to install build tools 15 with VS2015.

Summary: It is probably possible to get VS2015 working, but it may be hard to maintain.
Maybe just describe the workaround (if there is...) and offer a cherry pick for those that cannot use 2017?

**Comment by RussKie** [comment]
I admit, I haven't thought of VS2015, since the recent work was
concenteated around deprecating VS2015 and migrating to VS2017.

Do we *need* to support VS2015?
I have used VS2015 and moved to 17 because the new version offers
significantly reacher dev experience and supports a lot of tools (e.g.
Typescript, editor config) natively.

I understand that it may be harder for some users to install VS2017 in
corporate environments, but arguably contributing to an OS projects during
business hours may be in direct breach of their employment contracts and
our licence.

On 14/02/2018 9:43 AM, "Gerhard Olsson" <notifications@github.com> wrote:

I have tried to build, have not succeeded in building from Visual Studio
2015
Installed Microsoft.Net.Compilers 2.6.1 (same compiler as VS2017 15.5) and
added it to all relevant packages. This nuget will have to be maintained
also for VS2017.
Installed Build Tools 12017 (15.0) (not sure I got all packages).

The instructions are a little unclear, maybe it is just possible to
override build tools from the command line, with "/tv:15". This works on my
PC but I have 2017 installed, so no good test case. Appveyor fails, but I
have not found how to install build tools 15 with VS2015.

Summary: It is probably possible to get VS2015 working, but it may be hard
to maintain.
Maybe just describe the workaround (if there is...) and offer a cherry pick
for those that cannot use 2017?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/pull/4475#issuecomment-365430763>,
or mute the thread

**Comment by vbjay** [comment]
I say no. I think requiring 2017 is not a problem because community is
available.

**Comment by crypto-rsa** [comment]
I won't miss VS 2015 either. I just wanted to point out that with this commit merged in, we are effectively stopping support for it.

**Comment by RussKie** [comment]
We are permanently switching to VS2017

**Pull request merged**
