### PR TITLE
Remove currents repository and branch from recent lists

### PR DESCRIPTION
**Pull request by pmiossec**
Changes proposed in this pull request:
- Remove current repository from recent lists
- Remove current branch from list of branches

because that make no sense to select it (and it clutter the GUI as it is the first in the list)
 
Screenshots before and after (if PR changes UI):
- The current repository is no more in the list (on top)
image

- The current branch is no more in the list (on top)
image

Has been tested on (remove any that don't apply):
- GIT 2.17
- Windows 10

### CODE REVIEW

**Comment by sharwell** [comment]
🤔 this might be confusing. Not sure though.

**Comment by RussKie** [comment]
I am finding the proposal really confusing, sorry

**Comment by pmiossec** [comment]
I don't really understand what you find confusing.
I have just remove of the 2 lists the only option that is **never** used and that no one will ever want to select and, due to the default settings, is always the one displayed first (which is boring).


I could also add that if selected, the behavior is strange (what I found much more confusing than hiding the items). One is doing nothing, the other one reload the repository (and in this case, that's better to use the refresh button). 

I have tested it one month and I can assure you that it's better than the actual state. 

And I could assure you that no one will ever notice the change.

I think that is confusing for you because you are the developer behind the soft. From a user standpoint, I think that make sense (we could see the one currently selected as the top one of the list).

But I really like to understand what you find confusing...

**Comment by vbjay** [comment]
It's not invalid to check out current branch.  Leave the branch drop down
alone.

I agree with the current repo not being in that dropdown.

**Comment by pmiossec** [comment]
> It's not invalid to check out current branch. Leave the branch drop down alone.

I'm interested by this point of view. That's not invalid, but that do nothing. So what is the matter to keep a "button" that do nothing? Just let the user click on it inadvertently and retry again with the real branch he want to select?

**Comment by RussKie** [comment]
I am afraid I don't entirely understand the underlying desire to remove these entries. 

> I don't really understand what you find confusing.

To me personally this creates a disjoined UX. The behaviour is also unexpected, as I _do expect_ to see the currently selected item in the dropdown when I open it.

For instance, VS doesn't remove options that are selected from its dropdowns:
image
Another example, Word provides an indicator for currently select font:
image



. . .

That's what I get:
image

The branch is not present (when there is one checked out) in the branches dropdown though.

**Comment by pmiossec** [comment]
>Not if there are changes. It can be a reset or stash option.

@vbjay I discover this behavior and I think at the same time the most hidden feature and most misleading feature. I'm not sure there is another person than you using this feature by checking out the current branch to stash or reset changes..
And seeing that, I'm even more convinced that the current branch item should be removed...

@RussKie I better understand your point of view. Your are seeing these menus as dropdown.
I have never even thought it was dropdowns and this for multiple reasons:

* they are not technically dropdowns and looks more than menus ;)
* a dropdown is essentially used to set a setting/value ( look in your 2 examples) and not to do actions (like checking out branched, like we do)
* in dropdowns, the selected item should be highlighted when dropdown is reopen (see your 2 examples)
* we apply different order depending settings (more recent or alphabetically)
* they are submenus and menu items
* reselecting the current item selected has not just for effect to close the dropdown

For all these reasons, these 2 menus can't be viewed as dropdown and we should not try to reproduce dropdown UX without risking to end in "disjoined UX"...

I see more the branch list as "all the branches that you can checkout" more than "all the existing branches". And the current tooltips "Change current branch" & "Change working directory" seems aligned with this point of view otherwise they would have been something like "Checkout a branch".

To conclude, there are, IMHO, 2 options to make the ergonomy right:

* either you merge this PR ;)
* or the current item should be highlighted from one way or another (like a check like in your 2nd example) and the click on it should only close the menu, all that, to fake a "dropdown behavior". If you choose this option, I let you do that ;)

PS: I don't want to end up in a drama like in #5413 for something that seems trivial to me. So, make your choice and if needed, close this PR...

**Comment by RussKie** [comment]
Thank you for clarification. Whilst they are not technically dropdowns, I always viewed them as such 😄 
To me the current implementation is used to offer a richer UX, that can't be provided by a standard dropdown list.
But your points are absolutely valid.

What if,
* we stop constantly sorting, and
* highlight the current selections?

**Comment by pmiossec** [comment]
>What if,
>    we stop constantly sorting, and

No, I don't think that we should do that because that's the added value of this list (except when we enable the alphabetic order). That's just one reason why it's not a dropdown. But now that I understand your point of view, I won't argue, I accept that (and this PR could be closed). This PR was not of great added value so I could live with that ;)

>    highlight the current selections?

I think we must! But something not intrusive like the "Word" example you gave (I don't like the highlighted checked in the "View" menu)
And disable actions when clicking in the current selection (it should just close the submenu)

**Comment by RussKie** [comment]
While we're discussing it, I think it would be good to add icons to the branches "dropdown", similar to the left panel:
image

The currently selected item can be in **bold** and have different icon (e.g. highlighted or illuminated).  This can be applied to the left panel as well.

. . . 

I also think we probably need to move _Open..._ item in the repositories "dropdown" to the top of the list, similar to how we have the branches "dropdown". _Configure the menu_ item should stay at the bottom.


. . . 

Thoughts?

**Comment by gerhardol** [comment]
> Thoughts?

No to icon, yes to current in bold. But I have no strong preference to the new discussion suggestion, the change in this PR or the current implementation. (I still want #4942, maybe the status list information can be used, otherwise it will take far to long to open the menu).

**Comment by RussKie** [comment]
> No to icon

Any particular reason?

**Comment by gerhardol** [comment]
> Any particular reason?

Just do not see a need for it

If you intended to show as tree too: Displaying a tree will sort branches in a different way. I rather use this menu for last recently used and the side panel for alphabetic.

**Comment by drewnoakes** [comment]
If the icon would be the same for every item then it's not conveying much information.

+1 for the idea of showing any currently checked out branch as bold.

**Comment by ivangrek** [comment]
How about moving this list to the menu and possibly the submodule list too?
Or provide an option to hide these elements?

**Comment by gerhardol** [comment]
> 
> 
> How about moving this list to the menu and possibly the submodule list too?
> Or provide an option to hide these elements?

* Submodules are more or less identical for the left panel and menu. The menu stays for consistency and speed of handling (by default the submodules are below branches, so they are hard to reach). It is also convenient to go from sub to superproject.
* Recent branches can kindof be seen in the left panel after recent changes, but it is not so smooth if you have sorted in another way.
* Recent repos could be put in the left panel (was this what the message was about?) Same problem as for submodules, it can be scrolled out of reach. 

RussKie had some ideas to remove the search boxes too and use left panel instead.
Currently branches an

**Comment by RussKie** [comment]
I'd been toying with an idea of allowing to move toolbars (https://github.com/RussKie/gitextensions/tree/rework_toolbars). This way a user can move (and maybe show/hide) toolbars they don't use.
IIRC I stumbled across a bug in Windows Forms code pertaining to layout restore. Which we can now fix in .NET version of it :)

**Comment by RussKie** [comment]
> * Recent repos could be put in the left panel (was this what the message was about?) Same problem as for submodules, it can be scrolled out of reach.

We'd probably want to have multi-tab for this, but this may turn into be a UX disaster. We already have https://github.com/gitextensions/gitextensions/issues/6014 for this.
What we truly need is a docking solution, discussion related to this are here: https://github.com/gitextensions/gitextensions/issues/3679

**Comment by ivangrek** [comment]
Thanks for the comments.

All thoughts on this part.
If this is a menu, place in the menu.
If these are tools, provide an option to hide.

image

Toolbar in left panel and in particular search.

image

To improve the work with the left pane, the search should filter the tree values. It doesn't work now.

image

Show/hide sections menu should not hide after select section.

image

After selection should select one value. (like a radio button)
After selecting with the Ctrl key pressed, add the value to the selection. (like a checkbox)

"Checkout branch..." menu item could be added to Branches context menu in the left panel.

image

Collapse All / Expande All  for selected section should apply only for this section.

image

I would be glad if any of this is valuable.

**Comment by RussKie** [comment]
> Toolbar in left panel and in particular search.
> 
> image

Yes 👍 

> To improve the work with the left pane, the search should filter the tree values. It doesn't work now.
> 
> image

Yes 👍 

> Show/hide sections menu should not hide after select section.
> 
> image

Maybe... I wouldn't spent too much time on this. It maybe a little annoying but I won't consider this to be a frequently used user flow.
Very low priority, and this change may have a breaking UX.



> "Checkout branch..." menu item could be added to Branches context menu in the left panel.
> 
> image

Yes 👍 

> Collapse All / Expande All for selected section should apply only for this section.
> 
> image

Maybe... Again if you want to collapse only this node - collapse it. No need for the contextmenu.

> If this is a menu, place in the menu.
> If these are tools, provide an option to hide.
> 
> image

I wouldn't touch this right now.

**Comment by ivangrek** [comment]
> I'd been toying with an idea of allowing to move toolbars (https://github.com/RussKie/gitextensions/tree/rework_toolbars). This way a user can move (and maybe show/hide) toolbars they don't use.
IIRC I stumbled across a bug in Windows Forms code pertaining to layout restore. Which we can now fix in .NET version of it :)

Could you please rebase on master if needed.

> What we truly need is a docking solution, discussion related to this are here: #3679

I think this should be the main direction of the interface development!

**Comment by RussKie** [comment]
@ivangrek we have a discussion pertaining to the left panel - https://github.com/gitextensions/gitextensions/issues/4814.
I think this discussion belongs there.

**Comment by RussKie** [comment]
> Could you please rebase on master if needed.

I tried it few weeks ago, it was not that simple. It may need to be re-implemented from a scratch.

**Comment by RussKie** [comment]
Thank you. I'm closing this for the reasons discussed above.

**Pull request closed without merging**
