### PR TITLE
WIP Feature/3475 pull dropdown and dialog should have a --ff-only choice

### LINKED ISSUE #3475: pull dropdown and dialog should have a --ff-only choice
If you've forgotten you have local commits its good to be reminded on pull, making --ff-only a good pull default.

### PR DESCRIPTION
**Pull request by alexDevBR**
Fixes #3475 

### Changes proposed in this pull request:
allow pull with --ff-only option

FormPull: MergeFFOnly radiobutton added, with accompanying icon
FormBrowse: added mergeFFOnlyToolStripMenuItem with accompanying icon
GitCommands: PullCmd has new parameter fastForwardOnly which adds --ff-only. Test included.
Updated English.xlf with new messages for the menuitem and formbrowse
 
### Screenshots before and after (if PR changes UI):
before:
image
after:
image

menuItem:
image

### What did I do to test the code and ensure quality:
Added a test to ensure pull command has --ff-only flag
Generally I followed the code for the normal Merge option

### Has been tested on (remove any that don't apply):
- GIT 2.18 and above
- Windows 10

### CODE REVIEW

**Comment by pmiossec** [comment]
I think you did a mistake in your pull request. There is too much commits in it.

I think your branch should be created from 'master' (seems you did your changes in 'release/2.51') and your pull request asking to merge into 'master'.

I think you should close this one and do a fine one or 'rebase onto' and 'push force'

**Comment by alexDevBR** [comment]
> I think you did a mistake in your pull request. There is too much commits in it.
> 
> I think your branch should be created from 'master' (seems you did your changes in 'release/2.51') and your pull request asking to merge into 'master'.
> 
> I think you should close this one and do a fine one or 'rebase onto' and 'push force'

My mistake. I actually meant to merge it into release/2.51.
I wanted to add this feature to master but since I started a few days ago, before issue #5420 got merged, none of the pull options seemed to work so I decided to add it to 2.51.
I'll try to add the same features to 3.00 so maybe the issue should remain open, or maybe a new one should be created.

**Comment by vbjay** [comment]
2.5.1 only accepts bug fixes.  Master is where new dev is done.  You will
need to check out master and run git clean -d -f -x and then do your work
on a branch off of master.

**Comment by GintasS** [comment]
This is an old PR and should be closed or set to a draft. @gerhardol

**Comment by gerhardol** [comment]
This should have been included `--ff-only` is the sensible default.

**Pull request closed without merging**
