### PR TITLE
Add "Show SHA1" to View menu; Show SHA1 column in log (using Consolas fo...

### PR DESCRIPTION
**Pull request by ugumba**
This satisfies issue #2659, hopefully.

### CODE REVIEW

**Comment by KindDragon** [comment]
I think user will be rarely switch this setting. Maybe better move it to settings dialog (page Git Extension).
Maybe it was also useful to add an option to display a short hash

**Comment by ugumba** [comment]
Move to Settings:  
Personally, I like it in the View menu, and I think it needs to be quickly accessible, at least as much so as "Relative date" and the other View options.  

Most other apps with GridViews allow column selection by right-clicking the column headers.  Having to open Settings to customize columns seems counterintuitive to me, especially as View already contains so many similar options.

Short hash:
The column is already resizable, making it very easy to show as little or as much of the hash as you want.

Anyway, if you decide that you want either of these changes before you pull, I'll see what I can do.

**Comment by ugumba** [comment]
Arkady, any idea on the Travis CI failure on bfb8c84?  It doesn't make much sense to me.

**Comment by KindDragon** [comment]
@ugumba Just ignore it, some problems with mono

**Comment by ugumba** [comment]
Rebased and squashed

**Comment by jbialobr** [comment]
@ugumba As mentioned in #2981 there is an inconvenience while trying to locate the parents of a merge commit under the Diff tab. I thought it would help if the sha1 ids were displayed in bold.

**Comment by ewgoforth** [comment]
I did an internet search for how to display the hash in Git Extensions and came across #2981 which led me to this page.  It appears that the Show SHA1 was added to the Settings - Git Extensions page, but I'm not seeing it.  What version was it added on?  I did a search on the https://github.com/gitextensions/gitextensions/releases page and didn't see it.  I'm running 2.48.05.

**Comment by gregerc** [comment]
It's there in 2.49.

tis 22 nov. 2016 kl. 21:51 skrev ewgoforth <notifications@github.com>:

**Comment by ewgoforth** [comment]
Do I need to uninstall 2.48.05 before I can install 2.49?

**Comment by ewgoforth** [comment]
I uninstalled 2.48.05 and installed 2.49.  I'm not seeing Show SHA1.  In Settings-Git Extensions I see:

Performance
-----------------------
Show repository status in browse dialog (number of changes in toolbar, restart required) 
Show current working directory changes in revision graph (slow!) 
Use FileSystemWatcher to check if index is changed 
Show stash count on status bar in browse window 
Check for uncommitted changes in checkout branch dialog 
Show file differences for all parents in browse dialog. 
Limit number of commits that will be loaded at statup 

```
Behaviour
-----------------------
Close Process dialog when process succeeds 
Show console window when executing git process 
Use patience diff algorithm 
Include untracked files in stash 
Follow renames in file history (experimental) 
Open last working directory on statup 
Follow exact renames and copies only 
Play Special Startup Sound 
Default clone destination 
Revision grid quick search timeout [ms] 

Email settings for sending patches
----------------------- 
SMTP server name 
Port 
Use SSL/TLS 
```

**Comment by gregerc** [comment]
Iirc I just installed the new version directly.

tis 22 nov. 2016 kl. 22:03 skrev ewgoforth <notifications@github.com>:

**Comment by ewgoforth** [comment]
I'm not seeing it as a setting in Git-Extensions, but I did find it in the View menu and ticked it

**Pull request merged**
