### PR TITLE
WIP Update appveyor.yml

### PR DESCRIPTION
**Pull request by RussKie**
Set version to 3.1.0 instead of 3.01.00

### CODE REVIEW

**Comment by gerhardol** [comment]
Should update versions in GE source too, as well as #6096

**Comment by RussKie** [comment]
Do you mean `AssemblyInfo`s?
```
[assembly: AssemblyVersion("3.01.00.0")]
[assembly: AssemblyFileVersion("3.01.00.0")]
[assembly: AssemblyInformationalVersion("3.01.00.0")]
```

**Comment by gerhardol** [comment]
> Like this

Yes, but it is required to always update all these versions?
For instance set AssemblyInformationalVersion to something neutral so it does not have to be changed?

**Comment by vbjay** [comment]
It's standard to have a version bump commit. Run prepare release script and
look at the changes.

**Comment by gerhardol** [comment]
> It's standard to have a version bump commit. Run prepare release script and look at the changes.

Yhese are not in the prepare release script. (Several of them were changed just before 3.0.0 release. Even if they are added, this means more maintenance, submodules must be added too which is inconvenient, a submodule should never contain a reference to the superproject.)

**Comment by vbjay** [comment]
No. Prepare release is in main repo. So is setversion script. They are in
setup folder. If other version files need to be changed, then add them to
the python script.

**Comment by RussKie** [comment]
I think we should update these as part of the build, we shouldn't be doing this manually.
I'll add/modify our scripts to do so.

**Comment by vbjay** [comment]
They already are submodules. They are already forked. We have already
adjusted some things on them.

**Comment by gerhardol** [comment]
> They already are submodules. They are already forked. We have already adjusted some things on them.

We do not want to have multiple branches if not needed: One for each GE branch we are working with as they contain information about the superproject. It is this scenario that users to hate submodules.

**Comment by RussKie** [comment]
@vbjay may I please get help?
I've update the python script to update **all** `AssemblyInfo.cs` files, including submodules.
https://github.com/gitextensions/gitextensions/blob/release/3.0.2/Setup/set_version_to.py#L26-L28

As a result the build comes out as dirty, e.g. 
image
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22050162#L68

How should I script it to ignore the changes to `AssemblyInfo.cs` files?

**Comment by vbjay** [comment]
So the fix is to turn on the git status debugging piece of the appveyor script.  It will give you a status artifact.  Then add skipworktree for each path that is dirty.  If in a submodule do what I did for the docs submodule.  

Non release builds are always dirty.

**Pull request closed without merging**
