### PR TITLE
Quick search in whole commit message if loaded

### PR DESCRIPTION
**Pull request by mstv**
## Proposed changes

- Quick search `Body` - instead of just `Subject` - if available

## Test methodology 

- manual:
  - focus RevisionGrid
  - type "cherry"
  - hit <kbd>Alt</kbd>+<kbd>Down</kbd>
    should find cherry-picks

## Test environment(s) 

- Git Extensions 33.33.33
- Build 2e3fce40b207c8ff4c3ee5c4b442e58a3f812b7b
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.7
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Is this the second part of https://github.com/gitextensions/gitextensions/pull/9317#issuecomment-871772235?

**Comment by mstv** [comment]
Yes, it is.

**Review by gerhardol — COMMENTED** [review]
I expect that this quick search applies to what you see in the grid. This should maybe be related to the new setting to see the body in the grid.

**Review by RussKie — APPROVED** [review]

**Comment by mstv** [comment]
> I expect that this quick search applies to what you see in the grid.

That would be a clear definition. But the result would be counterintuitive to me since the whole message of the selected commit is visible always - located right of the RevisionGrid, (where it should be displayed by default - perhaps left for RTL languages).

It should behave similar as
grafik

**Comment by gerhardol** [comment]
I meant if this is set:
image

Like searching in a document

**Comment by mstv** [comment]
> I expect that this quick search applies to what you see in the grid.
> Like searching in a document

I think I had understood what you mean.
What about "quick search applies to what you _can_ see in the grid - including the tooltip"?

**Comment by gerhardol** [comment]
> > I expect that this quick search applies to what you see in the grid.
> > Like searching in a document
> 
> I think I had understood what you mean.
> What about "quick search applies to what you _can_ see in the grid - including the tooltip"?

Ok

**Pull request merged**
