### PR TITLE
Remember the IgnoreWhitespaceChanges settings for FileViewer.

### PR DESCRIPTION
**Pull request by EbenZhang**

### CODE REVIEW

**Comment by jbialobr** [comment]
I think that users should be able to decide whether they want GE to remember this setting or not.
You can add a setting for that on the Advanced settings page.

**Comment by EbenZhang** [comment]
@jbialobr advanced setting added.

**Comment by jbialobr** [comment]
Thanks! Could you also update the [changelog](https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md) and the [doco](https://github.com/gitextensions/GitExtensionsDoc/blob/master/source/settings.rst#advanced) or create an issue in the GitExtensionsDoc indicating that the documentation needs to be updated?

**Comment by EbenZhang** [comment]
Hi @jbialobr, thanks for reviewing. I've added another commit to this pull request for the change log and created a new pull request  gitextensions/GitExtensionsDoc#66  in the  GitExtensionsDoc  repository to update the doc.

**Comment by jbialobr** [comment]
Great! Thank you.

**Pull request merged**
