### PR TITLE
Comparing to Another Branch or Commit

### LINKED ISSUE #3036: "Mark" feature or other mean to compare distant commits
I would like to be able to compare distant commits conveniently. A usual case is when a want to compare a feature branch against its base (which is somewhere in mainline). Clicking on "parent" in the first commit brings me many commits away. Then I would like to compare the found parent with head of the feature branch. I could press "Back" and select it manually, but I would lose then selection of the base. All I could do is to manually scroll the view trying to locate locate the commit. Or try to limit the output with "Branches:" selector, hoping the interesting commits will be close.

The `gitk` program has a feature called "mark" - I can run "Mark this commit" command on a commit, and the mark stays on that commit however I navigate the history. Then I can compare a commit with the mark.

I'm not requesting that exact feature, but it would be nice to be able to navigate commits without losing selection, or otherwise compare commits which are far from each other

### PR DESCRIPTION
**Pull request by EbenZhang**
A preview version can be downloaded from [here](https://github.com/EbenZhang/gitextensions/releases/latest)

------

Using this handy feature, you’re able to compare a commit (or branch) to another, thus easily review the changes on your branch.

## Context menu to access the feature

The feature is accessible from the context menu:
comparebranches

## The diff dialog

Then you’ll see the differences in a popup dialog like below.

comparebranchesdetails

As you may already aware of, there is a `Compare HEAD commit to merge base` option. With it ticked, you’re able to compare a branch to the most recent common commit between the BASE and HEAD commits instead of comparing to the BASE directly. This is useful if your branch was created based on an old commit of the target branch to where your branch is going to be merged.

The `swap` button in the top-middle of the windows is designed to swap the BASE and HEAD commit. 

Moreover, you can pick up another branch or commit to compare by clicking the `Another Branch` or `Another Commit` button.

## Select a Commit as BASE and Compare to it

As you may have already seen from the context menu, there are two more items, one is `Select as BASE to compare`, another is `Compare to BASE`. With these two items, you can select one commit as the BASE using the `Select as BASE to compare` menu, then right click another commit and select the `Compare to BASE` menu to compare the later selected commit to the BASE you selected before.

-------
fixes #3036

### CODE REVIEW

**Comment by Radrik5** [comment]
I think using the "HEAD" word in the branch comparison dialog is a bit confusing. HEAD is a reference to commit for the working directory.

Maybe move new menu items into a sub menu? I often use custom scripts that are added to the end of the menu, so after your changes the way from the selected commit to my scripts will be 4 items longer.

**Comment by Radrik5** [comment]
Could you extact fix for #2956 into a separate PR? I would definitely merge it into my version.

**Comment by EbenZhang** [comment]
> Could you extact fix for #2956 into a separate PR? I would definitely merge it into my version.

There's no actual fix for #2956, I said this pull request fixes it because it obsoletes the old way to compare commits.

**Comment by EbenZhang** [comment]
> using the "HEAD" word in the branch comparison dialog is a bit confusing

I was following the GitHub API https://developer.github.com/v3/repos/commits/#compare-two-commits

But I think your point makes sense, GitHub displays as `Compare` instead of `HEAD` (but when comparing two forks, it still says `BASE` fork and `HEAD` fork :-) )

**Comment by EbenZhang** [comment]
menu items are moved to sub menu. And added two hot keys for the `Select BASE to Compare` and `Compare to BASE`.

**Comment by Radrik5** [comment]
> >Could you extact fix for #2956 into a separate PR? I would definitely merge it into my version.

> There's no actual fix for #2956, I said this pull request fixes it because it obsoletes the old way to compare commits.

I don't think we should close #2956 when this pull request get merged. There are other use cases that suffer from this bug. For example, filtering by commit message and them removing the filter to see the context.

**Comment by johnddx** [comment]
> > Could you extact fix for #2956 into a separate PR? I would definitely merge it into my version.

> There's no actual fix for #2956, I said this pull request fixes it because it obsoletes the old way to compare commits.

@EbenZhang Does this _remove_ the ability to use selection to compare commits?  It is hard to match the efficiency and intuitiveness of using selection to compare two commits which are both accessible in the grid.  I see the ability to "mark" a commit is really just about implementing a stickier form of selection for when navigation gets in the way of using simple selection.

**Comment by EbenZhang** [comment]
> Does this remove the ability to use selection to compare commits

You can still use old function to compare commits. I didn't change that.

**Comment by KindDragon** [comment]
> The swap button in the top-middle of the windows is designed to swap the BASE and HEAD commit.

It is not clear what it does/why from a user perspective.

**Comment by EbenZhang** [comment]
> It is not clear what it does/why from a user perspective.

In case you select the two commits in the wrong order, you can easily swap them.

**Pull request merged**
