### PR TITLE
ConEmu 220807

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

https://conemu.github.io/blog/2022/08/07/Build-220807.html
Reason to update is signing of executables, which could be important later

Depends on ClamAV being green https://www.virustotal.com/gui/file/894f7b2d08ea386ed3c84e5378a6e1b8d21acdf88c0250ce99b0beb9e67f5566/detection

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
Seems to work, of course. I am using it in my build.

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
Merge was a little quick (I should have set this as draft, not just described) as ClamAV reports this version of ConEmu still, so a build will be flagged as a virus.
But the previous version was handled quickly by ClamAV, hopefully this too.

**Comment by RussKie** [comment]
Did anyone make ConEmu author aware of this issue?

**Comment by gerhardol** [comment]
> Did anyone make ConEmu author aware of this issue?

https://github.com/Maximus5/ConEmu/issues/2476#issuecomment-1260049243
But it is not ConEmu fault.
I have reported it to ClamAV too. Someone else may upload ConEmu releases to ClamAV too.

**Comment by RussKie** [comment]
Thank you for doing this.

**Comment by gerhardol** [comment]
ClamAV is now OK, reported to MaxSecure but no contact with Jiangmin
This should not be blocking.

**Comment by gerhardol** [comment]
Latest beta is green
https://www.virustotal.com/gui/file/1bb294268cbc5e42eb332154612a2dfa20c97b642e614655c0df2ff34ed6d4a9/detection

**Pull request merged**
