### PR TITLE
"Illegal Characters in Path" if %PATH% Contains Quotes #2924

### PR DESCRIPTION
**Pull request by hypersw**
Added unquoting.
Added ignoring of certain exceptions which might result from invalid %PATH% while checking for file existence, assuming it does not exist.

#2924

### CODE REVIEW

**Comment by ghanique** [comment]
Why? Shouldn't people simply not have quotes in the PATH variable? I
suspect having quotes in the PATH variable is, in fact, an invalid syntax.

A little bit more elaborate:
Suppose there is a
PATH=C:\Directory one;"C:\Directory two";C:\Directory three

Splitting that up using the ; delimiter gives:
1. C:\Directory one
2. "C:\Directory two"
3. C:\Directory three

If we would want to use these values then for 1. and 3. we would need to
enclose it in quotes and for 2. we would not need to.

Bottomline: having quotes in the PATH variable makes its values ambiguous.

I'd advise the user to fix the environment variable before writing code to
fix data that you do not own.
(Git Extensions is not responsible for the PATH variable, because it's used
for much more than just Git Extensions. So Git Extensions shouldn't fix it).

Kind regards,

Guillaume

**Comment by ghanique** [comment]
Better example: suppose we would need a file "foo.txt" in each of those
directories, then we would get the following file names:

* C:\Directory one\foo.txt --> legal filename
* "C:\Directory two"\foo.txt --> illegal filename
* C:\Directory three\foo.txt --> legal filename

So, again, PATH should NOT contain quotes. The user should fix it, IMHO,
not Git Extensions.

**Comment by hypersw** [comment]
First and foremost, what backs the assumption that people should not have quotes in `%PATH%`?

Any references to a formal document?

Because the facts are:
* It actually works with CMD and FAR. Command/executable files on such quoted paths get detected and executed by their local name. People might have such `%PATH%`s for ages and see no problems at all before they open GE.
* It's easy to get the quotes if you're adding a path quickly for the current console session with `set PATH=%PATH%;smth`, because all console completions in CMD, PowerShell, and FAR would eagerly quote the path for you. As it just works, you won't always care of cleaning it up, why bother?
* It's not about *fixing the path* and whose responsibility this is. It's about not crashing GE with an exception on the data which every other tool eagerly consumes.

**Comment by hypersw** [comment]
> If we would want to use these values then for 1. and 3. we would need to
enclose it in quotes 

Enclosing a path in quotes is not a correct operation anyway. Example: `C:\Program Files\;C:\Windows\` ?

**Comment by trojanobelix** [comment]
What about this from a MSDN blog:

(...) the PATH environment variable doesn't use spaces to separate directories. It uses semicolons.

This means that if you want to add a directory with spaces in its name to the path, you don't need quotation marks since spaces mean nothing to the PATH environment variable. (...)

On the other hand, if the directory you want to add contains a semicolon in its name, then you do need the quotation marks, because it's the semicolon that you need to protect.

**Pull request merged**
