### PR TITLE
Draw smoother Bezier curves; Cache points outside loop

### PR DESCRIPTION
**Pull request by ugumba**
Minor enhancements:
1. I didn't like the very curvy lines in the graph.  This commit smoothes them significantly.
2. The inner loop recalculates the end points and control points.  The commit precalculates what's needed for  slightly better performance, and readability.

Before and after:
image image

### CODE REVIEW

**Comment by KindDragon** [comment]
I like it.
@spdr870, @jbialobr What you think?

**Comment by ghanique** [comment]
+1!

**Comment by spdr870** [comment]
Looks very nice! No impact on performance?

**Comment by ugumba** [comment]
If anything, performance should be improved by calculating the end and control points outside the (short) inner loop, but I doubt it's measurable.
The DrawBezier call is the same as before, I just reduced the severity of the control points (moved them closer to the end points).

**Comment by phillijw** [comment]
Great improvement!

**Pull request merged**
