### PR TITLE
Issue 4885 - Integration of PluginManager

### PR DESCRIPTION
**Pull request by maraf**
This pull integrates download and inclusion of a latest PluginManager from its releases in GitHub repository.

Downloaded content is stored in Plugins\GitExtensions.PluginManager and is excluded from git.
New download is executed only when a new PluginManager release is found.
HeatDirectory build task is used for integration into Setup.wixproj.

### CODE REVIEW

**Comment by maraf** [comment]
@RussKie  Is `Prepare-Release.ps1` used in AppVeyor build? I have placed download there...

**Comment by RussKie** [comment]
> `Prepare-Release.ps1` used in AppVeyor build? I have placed download there...

It is the right place. The script is currently run manually whenever a release is prepared. 
There is a plan to fully automate this, but time is an issue right now.

**Comment by RussKie** [comment]
The build is failing - https://ci.appveyor.com/project/gitextensions/gitextensions/builds/20304184/messages
I think we need to check in an empty folder with .gitignore, so the setup project can build.

**Comment by vbjay** [comment]
The standard is to use a .gitkeep file with optional why the file is there.
Just a text file.

**Comment by sharwell** [comment]
Is there a link to a documented versioning strategy I can review?

**Comment by sharwell** [comment]
@RussKie I'm assuming an installer will be available without this bundled executable, correct?

**Comment by maraf** [comment]
@sharwell @RussKie I can solve it either by committing empty folder with .gitkeep or I can integrate PluginManager download into Setup project build, What do you prefer?

The second option is better in handling possible future changes to PluginManager structure (additional folders or something like that).

**Comment by maraf** [comment]
@sharwell About versioning, do you mean PluginManager versioning or plugin installation requirements?

**Comment by maraf** [comment]
I have integrated PluginManager download into Setup build, so AppVeyor builds contain it.

**Comment by RussKie** [comment]
> Is there a link to a documented versioning strategy I can review?

There are no documents of any kind in the department, they will need to be developed at some point in the future.
If you have any thoughts, ideas or experience to share - please do.

Few thoughts:
* the bundling of the plugin manager is an enabler to start unbundling existing plugins and allowing new plugin development
* the plugin manager versioning strategy lies with @maraf, but we're as a consumer have certainly a degree of responsibility for it
* the GE plugin API versioning strategy is absent at the moment, the plugin API has been (somewhat) stable for some time and I'll let it be for now. API versioning would likely be a breaking change, so we will need to work through this.

@maraf did raise a question about compatibility, here are my thoughts on the subject - https://github.com/maraf/GitExtensions.PluginManager/issues/36#issuecomment-427729429.

> I'm assuming an installer will be available without this bundled executable, correct?

No, the plugin manager is bundled in its entirety, including the executable.
Do you see it as a problem?

**Comment by maraf** [comment]
@spdr870

**Comment by spdr870** [comment]
I got a little further. But now I get this error. I can workaround it, but just mentioning.
image

Wouldn't it be a lot easier to just include the pluginmanager as a submodule and build it directly instead of having to download a binary?

**Comment by RussKie** [comment]
I'm back. I'll have a look at it tonight

**Comment by RussKie** [comment]
@spdr870 what did you do to get this error?
I run the following command:
```
gitextensions\Setup>powershell .\Prepare-Release.ps1 -oldVersion 2.51.05 -newVersion 3.00.00.04 -milestones '47'
```

Admittedly I had to further tweak our scripts (I will rework them one day), but everything downloads and bundles just fine.

**Comment by gerhardol** [comment]
Builds for me.
We need to adapt the plugin manager to debug builds (at least so it is included).
It would be good to have at least a dummy plugin online too, to see that the manager works.

**Comment by maraf** [comment]
@gerhardol I was thinking about reference GE plugin repo. 
Containing empty plugin, nuget package setup etc.

**Pull request merged**
