### PR TITLE
Highlighting of authored commits

### PR DESCRIPTION
**Pull request by tomasdeml**
Adds highlighting of user's commits. This feature comes in handy (at least for me) when you are skimming through the commits while looking for something related to your work.

Commits are matched with current user's email address. The feature is enabled by default and can be configured in the 'Settings' dialog on the 'Colors' page. Commits are highlighted with LighYellow color by default.

revisiongraph
settings

### CODE REVIEW

**Comment by ghanique** [comment]
Nice!

**Comment by mnaoumov** [comment]
+1

**Comment by jbialobr** [comment]
Nice! What would you say if we change it a little bit:
1. When no revision is selected, then highlight the current user's revisions
2. When there is a selected revision, then highlight revisions authored by the author of the selected revision.

**Comment by tomasdeml** [comment]
That may make the feature more useful, hang on.

**Comment by tomasdeml** [comment]
@jbialobr I modified the feature according to your suggestions, it is certainly better now :). 

One note about the implementation: I had to introduce a flag indicating an ongoing row count update (see *DvcsGraph.cs*) to prevent flickering of the selection right after a refresh of the revision grid. The *SelectionChanged* event is fired multiple times during the refresh because of multiple row count modifications. If you can think of more correct / elegant solution I'm more than eager to improve this part.

**Comment by jbialobr** [comment]
@tomasdeml Well done, thanks!

**Pull request merged**
