### PR TITLE
StagedStatus.Unknown is an invalid status.

### PR DESCRIPTION
**Pull request by jbialobr**
It causes a failure of the assert inside of GitItemStatus.Staged.

### CODE REVIEW

**Comment by RussKie** [comment]
Could you please clarify under what conditions the assertion fails, and what is the value when it fails?

**Comment by jbialobr** [comment]
> Could you please clarify under what conditions the assertion fails, and what is the value when it fails?

1. Modify a tracked file.
2. Go to commit dialog
3. Right click on that file and choose Skip worktree
4. Switch on the `Show skip-worktree files` option and refresh the commit dialog (hit F5)

The value is `StagedStatus.Unknown` as specified in the assertion.

**Comment by gerhardol** [comment]
> In my opinion it can be only WorkTree

I can fix this tonight. The status should be set elsewhere

**Comment by gerhardol** [comment]
Introduced in #5128, so a regression 2.x->3.0 only

**Pull request merged**
