### PR TITLE
Add a context menu command for copying the commit hash to the clipboard

### LINKED ISSUE #3505: Add a quick way to copy the current commit hash to the clipboard
When working with other git-related software one has to frequently copy commit hashes. It would be useful if there was a quick way to copy the hash of the current commit - either using a hotkey or a button in the commit info window (or preferably, both).

### PR DESCRIPTION
**Pull request by crypto-rsa**
Fixes #3505.
Since the commit info is displayed in a `RichTextBox`, I couldn't simply add a copy button. Therefore I've added a context menu command.

Changes proposed in this pull request:
 - a *Copy commit hash* context menu command has been added
 - the command for copying the commit info was renamed to *Copy **full** commit info* to better differentiate it from the first command
 
Screenshots before and after (if PR changes UI):
Before:
obrazek

After:
obrazek

Has been tested on (remove any that don't apply):
 - GIT 2.10.1
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
Perhaps it would be better to add "Copy" option which becomes available where there is a selection. If there is no selection then "Copy" is disabled.

This way the user would be able to copy information they need, not just hash.
For instance, it annoys me that I can't copy commit message with the mouse and have to press ctrl+c.

**Comment by vbjay** [comment]
Instead add a submenu and have options like
Hash
Author
Commiter
...

**Comment by RussKie** [comment]
Wouldn't it be less flexible and require more work?

**Comment by vbjay** [comment]
No. Have a full option too along with different options like hash,
commiter...

**Comment by RussKie** [comment]
FYI - copying doesn't work under Mono
https://github.com/gitextensions/gitextensions/issues/3729#issuecomment-306187256

**Comment by crypto-rsa** [comment]
Update: Added a submenu for copying individual parts of the revision info.

**Comment by l-inc** [comment]
@crypto-rsa
Yes, it does. At least for me (Fedora 26, mono 5.2.0.224) all the submenu entries copy the respective piece of the commit info. Not all paste targets can however receive the copied text. But at least gedit can.

**Comment by gerhardol** [comment]
You know you can copy the hash from the revision grid?
Not opposing this PR, just for information
image

**Comment by crypto-rsa** [comment]
@gerhardol Yes I know. This PR provides a richer set of data to copy (including author e-mail and commiter info, if available). It also makes the copy commands available in the commit info panel which is much larger compared to the area of the revision row in the graph, making it easier to hit it with a mouse.

**Comment by RussKie** [comment]
I still maintain we are using the wrong approach to the issue breaking the expected and familiar behavior.

**Comment by crypto-rsa** [comment]
@RussKie this is the current state:
Copy commit info

Can you please describe what's wrong with that approach?

**Comment by gerhardol** [comment]
@crypto-rsa I am not opposing this. From a user's perspective, it has been implemented so why not use it.
But @RussKie as a maintainer wants the right code. He wanted to have normal select and copy functionality: Mark with mouse and ctrl-c to copy.

**Comment by crypto-rsa** [comment]
I have added a "copy selection" command. It is disabled when there is no selection both in the revision header and in the revision info. I hope this will cover all use cases.
Copy selection

**Comment by crypto-rsa** [comment]
@RussKie any opinion about the _Copy Selection_ command I've added in my last update?

**Comment by sharwell** [comment]
💭 I would prefer to see a little button like this one added next to the commit hash: 
image

Is there really no way to add a new image to the text area?

**Comment by crypto-rsa** [comment]
_Inserting_ an image directly into a `RichTextBox` is possible but complicated. However, it seems to me that _detecting_ a click on the image inside the RTB is not possible.
We could of course add the image as a separate control on top of the text area, but then how do you position it so that it lines up nicely on the right side of the commit hash?

**Comment by RussKie** [comment]
Sorry Pavel, but this doesn't quite align with my vision for the UX. 
One of the issues is overloaded standard behaviors, like the right click, which replaces the familiar to users system context menu with a custom one, thus creating confusion. Adding options for copying every bit of information the control provides is a futile exercise, and a weak remedy to the issue.

The commit info control will be redesigned in the following version, and adding this functionality just adds to the tech debt we will have to deal in the future.

**Comment by crypto-rsa** [comment]
OK, no problem. The PR had perhaps lost its direction. Originally I was just looking for a quick way to copy the hash of the selected commit using a mouse without the need to focus it first in the revision grid. Based on @vbjay's [comment](https://github.com/gitextensions/gitextensions/pull/3661#issuecomment-305051936) I added options to copy other commit items, too, and also the _Selection_ item you [asked](https://github.com/gitextensions/gitextensions/pull/3661#issuecomment-305051179) for. So yeah, the PR is perhaps unnecessarily complex but I am still not sure what your idea for the UX is. You said the control will be redesigned in the next version - will it be easier to extract commit information in it?

**Comment by gerhardol** [comment]
The selection part of this PR (at least) is still interesting

**Comment by gerhardol** [comment]
> I'm lost :) Could you please clarify

This PR added a menu option to copy selected text: copySelectionToolStripMenuItem
Not visible in the screenshots
This was handy, just a few lines of code
(Ctrl-C is working though)

**Comment by crypto-rsa** [comment]
> This PR added a menu option to copy selected text: copySelectionToolStripMenuItem
Not visible in the screenshots

It is visible in my [comment](https://github.com/gitextensions/gitextensions/pull/3661#issuecomment-339237318).

**Comment by RussKie** [comment]
Oh, it is something I missed.
How about we do an MVP here and add "Copy" menu item which copies the selection. This way the functionality is generic and provides all-familiar UX.

This can also go to 2.51 branch, I'm planning to release 2.51.02 within next few weeks. So if you are able to do it quickly, I'm happy to include the change in the release as well.

**Comment by crypto-rsa** [comment]
@RussKie, now that #5611 is merged, does it affect this PR in any way? Do you still maintain that we shouldn't add any shortcuts to copy interesting parts of the commit info _using the mouse only_? It was actually my original goal - to allow copying the commit hash and message without touching the keyboard.

**Comment by drewnoakes** [comment]
As a user I think it'd be more consistent to see the same "Copy" menu from the revision grid in the commit info area, if we're going to add something there.

Ideas about including additional copyable items apply equally in the grid. If we add something to the commit info panel's context menu, let's please make it the same in both places, and a submenu in both cases.

**Comment by RussKie** [comment]
@crypto-rsa I appreciate your submission. However I'm still not entirely convinced this change in its current form improves the UX, I am sorry. I think @drewnoakes's idea is possibly a direction we need to consider as it offers a consistent UX across the app. 

I'd like to have a review of commit info panel after v3 is released (this is a top priority for me right now). There are a number of improvements we can make to the panel, both on UI and UX levels. This includes layout and presentation of additional information (such as branches and tags), configuration (and discoverability of it), and interactions aspects (e.g. context menus, copy, navigation etc).

The primary drive for #5611 was to give the panel a touch up inline with the "new UI". It actually turned to be more demanding than I anticipated and required follow up work (e.g. #5641).

**Comment by crypto-rsa** [comment]
I like the @drewnoakes's suggestion, too. So then I think this PR could be closed as it doesn't go in the desired direction.

**Comment by RussKie** [comment]
We are all volunteers here, and I appreciate all submissions.
It is a tough gig to judge and decide how all submissions fit together
organically, and send them back for rework, when required.

Few reasons to keep unfinished PRs open:
- original author may fix/update it
- another contributor may take over/leverage the proposal
- reminder for us there is something we need to consider

We have thousands of closed/merged  PRs, so if an unfinished PR is closed
we may never revisit it.

**Comment by crypto-rsa** [comment]
> We have thousands of closed/merged PRs, so if an unfinished PR is closed we may never revisit it.

My reasoning was that the solution we agreed upon (i.e. use the copy submenu from the revision grid) is totally different from the contents of this PR, so there is nothing to use from it. But it's true that the discussion is valuable, too.

> We are all volunteers here, and I appreciate all submissions. It is a tough gig to judge and decide how all submissions fit together organically, and send them back for rework, when required.

It still amazes me how this project moves forward and significant features and improvements are being added given the volunteer status, sheer number of contributors and lack of any funding. You (and other maintainers, of course) are doing a great job! 👍

**Comment by RussKie** [comment]
Thank you. We are doing our best :)

**Comment by gerhardol** [comment]
The copy selection is implemented (in another PR?).

Unrelated to this PR, the menu looks strange in 100%
image

**Comment by RussKie** [comment]
That's pretty bad. Please open an new issue for it, it's a blocker for the beta2

**Comment by GintasS** [comment]
This is an old PR and should be closed or set to a draft. @RussKie

**Comment by crypto-rsa** [comment]
@RussKie I've re-read the discussion and I am still interested in the topic. What's your opinion about @drewnoakes's [suggestion](https://github.com/gitextensions/gitextensions/pull/3661#issuecomment-433845057) about reusing the _Copy to clipboard_ submenu from revision grid in the commit info control?
obrazek

**Comment by gerhardol** [comment]
> @RussKie I've re-read the discussion and I am still interested in the topic. What's your opinion about @drewnoakes's [suggestion](https://github.com/gitextensions/gitextensions/pull/3661#issuecomment-433845057) about reusing the _Copy to clipboard_ submenu from revision grid in the commit info control?

Fine for me (the large number of open PRs need to be reduced this was included as as it had no recent activity).
Current context menu copying seem to copy "raw" links as well as duplicate them, I would consider the handling broken.

**Comment by mstv** [comment]
> Current context menu copying seem to copy "raw" links as well as duplicate them, I would consider the handling broken.

works in 3.5.x yet

**Comment by gerhardol** [comment]
> 
> 
> > Current context menu copying seem to copy "raw" links as well as duplicate them, I would consider the handling broken.
> 
> works in 3.5.x yet

Regression in master, adding task to #8522

**Comment by RussKie** [comment]
Apologies for the delay. I'll do my best to respond over the weekend.

**Comment by RussKie** [comment]
I fully support the idea of reusing the existing "copy" menu to provide consistent UX.

**Comment by RussKie** [comment]
Please open

**Pull request closed without merging**
