### PR TITLE
Fix not being able to save changes to an existing remote

### LINKED ISSUE #6347: Unable to save changes for a remote
## Current behaviour

Unable to save changes for a remote

## Expected behaviour

Changes should be saved instead of showing a dialog with information as in the screenshot below

## Steps to reproduce

1. Open Remote repositories window
2. Change remote URL
3. Save

## Screenshots

image

## Did this work in previous version of GitExtensions

Yes, Git Extensions 3.00.00.4433 works.

## Environment

- GitExtensions version: 5c0d503576e82f503ced0eca4be97a86ab2cd2ba

### PR DESCRIPTION
**Pull request by amaiorano**
Fixes #6347

## Test methodology 

- Manual testing
- Ran all unit tests

## Test environment(s) 

- GIT version 2.19.1.windows.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by amaiorano** [comment]
Ugh, looks like I just crossed the threshold for CodeFactor's complex function. I suppose I need to fix that before we can merge?

**Comment by gerhardol** [comment]
> Ugh, looks like I just crossed the threshold for CodeFactor's complex function. I suppose I need to fix that before we can merge?

Probably should, I will not protest if you merge anyway (just await comments).

**Comment by amaiorano** [comment]
Okay, pushed a commit to reduce complexity of function. Looks like it passed CodeFactor. @gerhardol still good?

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
