### PR TITLE
UI icons from VS2015

### PR DESCRIPTION
**Pull request by seralexeev**
Some icons from Visual studio 2015

### CODE REVIEW

**Comment by KindDragon** [comment]
I think their license doesn't allow this

**Comment by vbjay** [comment]
Their license is here.
https://www.microsoft.com/en-us/download/details.aspx?id=35825

**Comment by RussKie** [comment]
I had a look at the licencing terms set out by Microsoft and to me it looks fine to use them

> The Visual Studio Image Library contains application images that appear in Microsoft Visual Studio, Microsoft Windows, the Office system and other Microsoft software. The libraries for Visual Studio 2012, Visual Studio 2013, and Visual Studio 2015 are available and each library contains over thousands of images **which can be used to create applications that look visually consistent with Microsoft software.** 

> Visual Studio 2015 Image Library 
> ...By downloading and using the Microsoft Visual Studio 2015 Image Library you agree to the terms of the Microsoft Software License Terms ([link](http://download.microsoft.com/download/0/6/0/0607D8EA-9BB7-440B-A36A-A24EB8C9C67E/Visual%20Studio%202015%20Image%20Library%20EULA.docx)).

Clause 2 of the EULA:

> 2.	DISTRIBUTABLE CODE. The software contains code that you are permitted to distribute (“Distributable Code”) in applications you develop as described in this Section.  (For this Section the term “distribution” also means deployment of your applications for third parties to access over the Internet.)
> a.	Right to Use and Distribute.
> •	Images.  **You may copy, distribute, and deploy the images in the Image Library in applications that you develop with the Visual Studio Family of products** .
> •	Third Party Distribution. You may permit distributors of your applications to copy and distribute the Distributable Code as part of those applications.
> b.	Distribution Requirements. For any Distributable Code you distribute, you must
> •	**add significant primary functionality** to it in your applications;
> •	**require distributors and external end users to agree to terms** that protect the Distributable Code at least as much as this agreement; and,
> •	**indemnify, defend, and hold harmless Microsoft** from any claims, including attorneys’ fees, related to the distribution or use of your applications, except to the extent that any claim is based solely on the Distributable Code.

I think GitEx ticks all boxes here. If these images are used the GitEx's EULA must include a clause stating that it contains MS's images and the user agrees to the terms of use of these images set out by MS.

Happy to stand corrected.

**Comment by carl-di-ortus** [comment]
Would not recommend to depend to MS licence only because of some image reusage. MS may change their licence agreement, and nobody will be following it as close as their own lawyers. This might endanger open source solution to a well-known-for-law-suits commercial company

**Comment by RussKie** [comment]
I'm not a lawyer but I do not believe a change to an agreement can be applied retrospectively. Especially if there is a copy of agreement granting a right to use and re-distribute.
They can only change an agreement for a new set of artifacts.

**Comment by jbialobr** [comment]
Do we really need to maintain two sets of icons?

**Comment by KindDragon** [comment]
I agree, better support only one set of icons (maybe the new one, IDK).
And these changes did not update our shell extension and VS addin.

**Comment by regs01** [comment]
Having ability to select between different icon themes would actually be great.

Though personally I prefer fatcow icons.

**Comment by quetzalcoatl** [comment]
Regardless of their licensing status, I see no real gain in importing VisualStudio icons. What do we need that for? Are there any icons missing right now that this would fill the gap?

If I wanted to have the VisualStudio look&feel, I would just use the VisualStudio built-in client :)

Personally, I like the current iconset much more. Sure, it's a bit old, but I'm used to it over the years. Sure, some people probably are not. However, I think that mantaining a separate look&feel is important. Like, for example, brand awareness. I really wouldn't like to see that people start perceiving GitExtensions as a VisualStudio's sidekick. I use Git and GitExtensions extensively outside of VS and its ecosystem and I if I have any choice, I don't want to feel like using VS everywhere.

Moreover, over the last few editions VS actually changed their look and feel (iconset including) may times. Will GitExtensions follow every change from now on? If not, then maybe it's better to stick to that style that survived so long.

Also, from the style point of view, I feel that the VS icons are designed for a metro-style application which doesn't fit well with git extensions. In my opinion, it even does not work well with VS either. There are many icons that are too indistinct and you still often need to scan-read the labels to find what you want. That's against the idea of an icon: icons should allow you to visually find things quickly - and the current iconset (with colors) seems to do it better. That's again strictly personal view of course.

This change does not add any functional gain, it's purely cosmetic change. Some may like it, some may not. For some, it may make them feel better (people sued to VS and its TFS UI), but for some it may actually hinder usability (probably others).

I think that, if you don't want to support both iconsets, then before merging it in, you should run some poll or something like that? Then, it may be prone to spam and scam.. Maybe for some time, issue two releases - keep main with old icons, and an alternative build with new icons, and see which gets more attention and praise?

Just thinking though. Personally, I dont like this change, but I will still use git-extensions. VS built-in client is .. so much inferior.

**Comment by vbjay** [comment]
Amen on the inferior part. It's like trying to do fit the TFS way. Staging
lines is a deal breaker for me. Being able to add specific lines of a
project file for example. Microsoft dropped the ball. I do like seeing the
status in solution explorer. That is about all I like with vs git
functionality.

**Comment by jbialobr** [comment]
We want to support only one set of icons. 
Perhaps some funds from donations could be spent on improving the existing icons.
/cc @spdr870

**Pull request closed without merging**
