### PR TITLE
Feature/visibility adjustments

### PR DESCRIPTION
**Pull request by Nochdarus**
Hello!

here is another pull request (first, with more verbose comment, is https://github.com/gitextensions/gitextensions/pull/3198)

On this branch I made slight visibility adjustments for the grid (very minor ones and may be not mature, but they, in my opinion, improve visual perception): striped alternating rows and "decreased" white outlining for the branches

Here are screenshots (as you requested in Contributing.md):

Alternating rows change is visible here:
rows

White outlining decrease is visible here:
selectedrows

As for alternating Rows, ideally I think their should be an option to select their color int the Settings->Colors, so that people can have then totally white background as before (if they select White for alternated color). Or any other color, and then they get striped rows. 
But I didn't want to make people bother with translation of a new string, so for now (it is a premature pull request anyway just to know if you like the change) I hardcoded the colors. I, if necessary in general, can do german, russian and french translations. 

Anyhow, thanks for a nice product!

### CODE REVIEW

**Comment by Radrik5** [comment]
How does alternating rows work with highlighting commits of the same author?

**Comment by Nochdarus** [comment]
@Radrik5  Very good point. For the moment  highlighting commits of the same author overwrites alternating rows in the grid (but not in the graph, because that highlighting didn't apply for the graph).
If you can propose something better (like aggregating colors in a proper way or something else) I am open to suggestions.

**Comment by Radrik5** [comment]
It looks fine to me. Thanks.

**Comment by Nochdarus** [comment]
Update: rebased it on the master. It is still mergable without conflicts.

**Comment by jbialobr** [comment]
>As for alternating Rows, ideally I think their should be an option to select their color int the Settings->Colors, so that people can have then totally white background as before (if they select White for alternated color). Or any other color, and then they get striped rows.

Can you do that?

**Comment by vbjay** [comment]
Also did you try it with the different layouts?

**Pull request merged**
