### PR TITLE
Fixes #8146 "Keyboard navigation : Enter Key should open a recent repository"

### LINKED ISSUE #8146: Keyboard navigation : Enter Key should open a recent repository
## Feature description

When on the startup screeen, 
and navigating through the recent repositories 
should be able to press enter to open a repository

## Environment
- GitExtensions version:  3.3.1.7897
- GIT version:  2.22.0
- OS version: MSWNT 10.0
- .NET version: 4.8.4180

### PR DESCRIPTION
**Pull request by lhiginbotham**
Fixes #8146 "Keyboard navigation : Enter Key should open a recent repository"

## Proposed changes

- intercept "Enter" key event and attempt to open the selected repository, if anything is selected

## Test methodology 

- I've attempted to use the enter key in a variety of scenarios, including when there is no repository selected, when there is a repository selected, when there is no repository selected but the list group is collapsed, and when there is a repository selected but the list group is collapsed
- - Out of these scenarios, there seems to be an issue only when pressing enter when a repository is selected but the list group is collapsed.  Since the list group was collapsed, I would have expected a no-op, since we cannot visually tell what repository is selected.  I cannot fix this, however, as it seems like the `ListViewGroup.CollapsedState` property is not accessible (maybe we need to use a newer version of .NET in order to see the API implemented and exposed in [this WinForms PR](https://github.com/dotnet/winforms/pull/3155)? @RussKie )

## Test environment(s) 

- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
> * it seems like the `ListViewGroup.CollapsedState` property is not accessible

Yes, the `ListView` control was enhanced in .NET 5.0, so we'll have access to new features when we upgrade.

> * Out of these scenarios, there seems to be an issue only when pressing enter when a repository is selected but the list group is collapsed.

I suppose we can live with that until we upgrade to .NET 5.0.
The only thing I'd suggest is adding a comment in the code noting this behaviour.

**Review by RussKie — COMMENTED** [review]
🚀

**Comment by lhiginbotham** [comment]
@RussKie I've added the comment

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
