### PR TITLE
Update GitExtensions.releases

### PR DESCRIPTION
**Pull request by cristianst85**
Not sure if 2.51.04 is a ReleaseCandidate or a HotFix.

### CODE REVIEW

**Comment by vbjay** [comment]
image

**Comment by cristianst85** [comment]
For example, version 2.51.RC1 had RC in the name and also the _Pre-release_ checked. So that's why the confusion.

P.S. Didn't wanted to be presumptions, but I wondered why the Check for updates didn't advertise the latest release available. So I investigated a little bit and instead of opening an issue I directly created a merge request. Feel free to merge it or close it. Either one is fine with me.

**Comment by RussKie** [comment]
2.51.04 is currently in a beta stage - we publish a release and give it few days before it goes public to ensure there are no major issues with it.
It will go public over the weekend.

**Comment by RussKie** [comment]
Thanks for doing it, by the way 👍 Makes my life easier

**Comment by cristianst85** [comment]
Changed _ReleaseType_ for 2.51.04 from _ReleaseCandidate_ to _hotfix_.

**Pull request merged**
