### PR TITLE
Add SonarQube code quality analysis [for reference]

### PR DESCRIPTION
**Pull request by wachulski**
Complimentary material to the discussion started in #6030

### CODE REVIEW

**Comment by gerhardol** [comment]
This is awaiting installation of AppVeyor GitHub app (must be done by repo owner), to avoid unpacking the encrypted key in PRs.

**Comment by RussKie** [comment]
> This is awaiting installation of AppVeyor GitHub app

Has it been done or do we need to pester @spdr870 for it more?

**Comment by wachulski** [comment]
Ok folks, I see it hardly makes any progress, and I understand the peculiarity here. Quite recently I came across another great analysis service, codescene.io. It takes a different approach:

* no build, no need to build programming
* no direct C# issues, instead careful examination of git history and code distribution
* some interesting vis

See a sample here: https://codescene.io/projects/4180/jobs/11779/results

E.g. suspects: 

* FormStash.cs https://codescene.io/projects/4180/jobs/11779/results/code/hotspots/complexity-trend?name=gitextensions%2FGitUI%2FCommandsDialogs%2FFormStash.cs
* and some clustering vs: https://codescene.io/projects/4180/jobs/11779/results/code/hotspots/system-map

PR is in place, awaiting account ID substitution: https://github.com/gitextensions/gitextensions/pull/6272

**Comment by gerhardol** [comment]
> Ok folks, I see it hardly makes any progress, and I understand the peculiarity here.

We are waiting for our great founder @spdr870 to install the AppVeyor app. As the owner of this repo, he is the only one that can do it.
(I did not get a confirmation that this plugs the hole for the AppVeyor credentials in the open.)
I had been thinking about Codacy instead, will look at codescene.io too.

**Comment by spdr870** [comment]
As far as I know, appveyor is already connected to GitHub. I didn't got a request for approving appveyor, but it could be that I missed something.

I did add an gitextensions account to sonarcloud: https://sonarcloud.io/dashboard?id=gitextensions_gitextensions. This was done after I received the approval request from GitHub. I expected that approving the request was enough, but maybe more needs to be done. There is an environment variable in AppVeyor that contains the token that can be used to run sonarqube.

The environment variable is: SONARCLOUD_TOKEN

The commands that needs to be executed are:
```
SonarScanner.MSBuild.exe begin /k:"gitextensions_gitextensions" /d:sonar.organization="gitextensions" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="[TOKEN]"

[Build solution]

SonarScanner.MSBuild.exe end /d:sonar.login="[TOKEN]"
```

The sonarqube runner can be downloaded here:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

**Comment by bellingard** [comment]
Hey guys, would you be interested to get help on this? I'm sure we can get something setup quite easily if we're trying to rely on Azure Pipelines for this specific part (code analysis on SonarCloud). :)

**Comment by wachulski** [comment]
That's cool you @bellingard stepped into this 😃

**Comment by RussKie** [comment]
We have configured integration with CodeScene: https://codescene.io/projects/5326
Thank you for the effort.

**Comment by gerhardol** [comment]
The SonarQube suggestions are still interesting.

**Comment by RussKie** [comment]
Feel free to re-open and continue, if you see value in this.

**Pull request closed without merging**
