### PR TITLE
Handle detached HEAD for orphan branches

### LINKED ISSUE #9910: [NBug] Object reference not set to an instance of an object.
### Environment

- Git Extensions 33.33.33
- Build 2cfed902608d4809c353733d8674f73285b7fa34
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

The Commit Info for Artificial Commits of the initial / a new orphan branch is incorrect. NRE is thrown.

branches from different repo appear for `Working directory` without any exception popup:

image

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at string ResourceManager.LinkFactory.CreateCommitLink(ObjectId objectId, string linkText, bool preserveGuidInLinkText) in D:/Build/gitextensions3/ResourceManager/LinkFactory.cs:line 100
   at bool System.Linq.Enumerable+SelectArrayIterator<TSource, TResult>.MoveNext()
   at string string.Join(string separator, IEnumerable<string> values)
   at string ResourceManager.CommitDataRenders.CommitDataHeaderRenderer.Render(CommitData commitData, bool showRevisionsAsLinks) in D:/Build/gitextensions3/ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs:line 68
   at void GitUI.CommitInfo.CommitInfoHeader.ShowCommitInfo(GitRevision revision, IReadOnlyList<ObjectId> children)+() => { } in D:/Build/gitextensions3/GitUI/CommitInfo/CommitInfoHeader.cs:line 75
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token) in D:/Build/gitextensions3/GitUI/GitUIExtensions.cs:line 243
   at async void GitUI.ThreadHelper.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in D:/Build/gitextensions3/GitExtUtils/GitUI/ThreadHelper.cs:line 112
```

### Steps to reproduce

- create a new orphan / initial branch
- stage first files
- select artificial commit `Working directory`
- select artificial commit `Commit index`

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### LINKED ISSUE #9913: [NBug] fatal: ambiguous argument 'HEAD': unknown revision or path ...
### Environment

- Git Extensions 33.33.33
- Build df51d5061d8c22f6ccaf4295ac4a603be743c4ff
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

FormCommit trying to get commit messages while a new orphan branch is checked out (see also #9910)

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z -n 6 HEAD --pretty=format:%B

```
GitExtUtils.ExternalOperationException: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 ---> System.Exception: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in D:\Build\gitextensions3\GitCommands\Git\ExecutableExtensions.cs:line 152
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in D:\Build\gitextensions3\GitCommands\Git\ExecutableExtensions.cs:line 48
   at GitCommands.GitModule.GetPreviousCommitMessages(Int32 count, String revision, String authorPattern) in D:\Build\gitextensions3\GitCommands\Git\GitModule.cs:line 3621
   at GitUI.CommandsDialogs.FormCommit.CommitMessageToolStripMenuItemDropDownOpening(Object sender, EventArgs e) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormCommit.cs:line 2327
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in D:\Build\gitextensions3\GitUI\UserControls\ToolStripEx.cs:line 60
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

- create a new orphan branch
- in FormCommit open the `Commit messages` dropdown

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #9913
Fixes #9910
Create Stash
Goto Common ancestor

## Proposed changes

HEAD is not set for orphan branches or initial commits.

## Test methodology 

manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
LGTM

**Review by mstv — COMMENTED** [review]
LGTM
I think I found yet another location: 69a66e5a1673a3ac34b27d482ef6132c371643ac.

**Comment by gerhardol** [comment]
> LGTM I think I found yet another location: [69a66e5](https://github.com/gitextensions/gitextensions/commit/69a66e5a1673a3ac34b27d482ef6132c371643ac).

Pushed a variant of this that handles !AppSettings.ShowDiffForAllParents too.
It would probably have been better to to remove NRT for ParentIds as it is almost handled already.

**Review by mstv — APPROVED** [review]
Thank you

**Pull request merged**
