### PR TITLE
Shell extension icons

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

Shell extensions icons are not updated to the changes in 3.x by @drewnoakes in #5087 (some are partly adapted to 3.0). Some icons are refreshed by @NikolayXHD for the dark theme and do look better also in light themes, does not seem be be any of these though.

- Renamed icon files so they match the GE icons 
- Converted the icons with https://hnet.com/png-to-ico/
- Removed a few unused png files
- Changed ResetToFile icon from blue to red in Browse, to be consistent with Commit and ShellExt

Not high priority for myself really, but several co workers use the shell extensions a lot, I then saw the GE2.x icons...

I looked at the VSIX icons too, they seem to be in sync. (As the code to adapt icons in GE is not available in vsix, some icons could be improved.)

To be squashed

### Before

shext-file
shext-dir
shext-nogit

### After

shext-dir-2
shext-file-2
shext-nogit-2

## Test methodology

Dark mode in Win10 100%dpi

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by tompollok** [comment]
I think the old difftool icon was more intuitive. Also reset in red is better to not confuse it with checkout.

**Comment by gerhardol** [comment]
> I think the old difftool icon was more intuitive. Also reset in red is better to not confuse it with checkout.

Thanks for the comments but can you open a separate issue?
The master UI will not be changed now and the shell extensions should follow the master UI.

**Comment by NikolayXHD** [comment]
> > I think the old difftool icon was more intuitive. Also reset in red is better to not confuse it with checkout.
> 
> Thanks for the comments but can you open a separate issue?
> The master UI will not be changed now and the shell extensions should follow the master UI.

We do have red reset icon in 3.3.1 at least

image

It is `GitUI/Resources/Icons/ResetWorkingDirChanges.png`

**Comment by gerhardol** [comment]
> We do have red reset icon in 3.3.1 at least

In Browse Revert commit is purple, Reset is red for commits, green for branches, blue for files and red for lines
In FormCommit Reset file and line are both red.
So consistency is needed

**Comment by NikolayXHD** [comment]
> > We do have red reset icon in 3.3.1 at least
> 
> In Browse Revert commit is purple, Reset is red for commits, green for branches, blue for files and red for lines
> In FormCommit Reset file and line are both red.
> So consistency is needed

I believe red is used in FormCommit because it's a dangerous operation, one can lose uncommited changes, which is also true for `Reset file changes...` menu item in Shell extension context menu, making red icon the consistent choise here.

**Comment by gerhardol** [comment]
(edited)
> In Browse Revert commit is purple, Reset is red for commits, green for branches, blue for files, Revert lines is blue
In FormCommit Reset file and line are both red.

Pushing a change to change to red reset for "maybe destructive operations", slightly more consistent.
For Browse red for files.
Keeping green for branches, even if Reset hard will reset work tree changes (but that is red with a description).
Revert line in file viewer kept as blue as the operation will normally fail right now anyway. (This is changed in #7825 that has Reset line if artificial commits are selected.)

Screenshots are not updated.

**Comment by gerhardol** [comment]
The new icon files were much bigger from 16x16 and 3KB to 256x256 to 100 KB
I converted them again with another service to 16x16, with size down to 2KB

Updated description and screenshots

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
