### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by CDAGaming**
Please Visit Externals/conemu-inside for the Associated PR - Arriving Soon

### CODE REVIEW

**Comment by CDAGaming** [comment]
Well then, guess WiX Installer also needs to be edited, thanks Newtonsoft xD

**Comment by RussKie** [comment]
It looks like your rebase didn't work correctly...

**Comment by CDAGaming** [comment]
Aw Sh*t, RIP PR lol
I'll try to get this fixed somehow someway 💯

**Comment by RussKie** [comment]
Take your time, the merge-button-keepers aren't around anyway 😏

**Comment by CDAGaming** [comment]
Closing for Replacement PR

**Pull request closed without merging**
