### PR TITLE
Fixed an issue that caused an exception when switching languages.(#10332)

### LINKED ISSUE #10332: [NBug] Sequence contains no matching element
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at GitUI.UserControls.RevisionGrid.RevisionGridMenuCommands.<CreateOrUpdateMenuCommands>g__UpdateMenuCommandShortcutKeyDisplayString|14_0(IReadOnlyList`1 targetList, IEnumerable`1 sourceList)
   at GitUI.UserControls.RevisionGrid.RevisionGridMenuCommands.CreateOrUpdateMenuCommands()
   at GitUI.RevisionGridControl.ReloadHotkeys()
   at GitUI.CommandsDialogs.FormBrowse.OnShowSettingsClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Changed language EN → RU in STARTING page with red/green stripes.

### Steps to reproduce

Change language EN←→RU. Tested: works in every screen, with every way of changing language.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by Dub1shu**
Fixes #10332

## Proposed changes

- Prevent exceptions from being thrown when switching languages.
    - The CreateGroupHeader function in MenuCommand.cs does not expect different strings to be entered depending on the language. 
    - Change it to enter a fixed string so that no exception occurs.
    - ~~Displaying commands in the View menu in multiple languages probably requires another fix.~~

## Test methodology 

- Switch language, no exceptions(manual test)
- I ran automated tests and found no new errors with this fix.

## Test environment(s) 

- Git version 2.38.1.windows.1
- Windows 11 Pro 21H2 22000.1098

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vbjay** [comment]
Better fix is to adjust code that looks for that groupheader to use the translation string.

**Comment by Dub1shu** [comment]
Thank you for your code review.

When I applied the latest xlf files and checked, the translation was displayed even without using the translation string (e.g. "TranslatedStrings.Branches") in the CreateGroupHeader function.
So it seems to me that there is no need to use the translated text here.

Highlighted in yellow in the image below is the group header in Japanese.
GroupHeaders

I withdraw the following statement from the PR:
> Displaying commands in the View menu in multiple languages probably requires another fix.

**Review by RussKie — APPROVED** [review]
Passing the translated string is a mistake, in other places we don't do this:
image

The argument is used to derive the toolstrip item's name:
https://github.com/gitextensions/gitextensions/blob/fa210ff8484eef4ef713e7dd8c706df9a0c08759/GitUI/CommandsDialogs/BrowseDialog/MenuCommand.cs#L19-L27

**Comment by RussKie** [comment]
@Dub1shu we need your sign off in https://github.com/gitextensions/gitextensions/blob/master/contributors.txt before we can merge this. Thank you.

**Comment by Dub1shu** [comment]
Thank you for your review.
I have signed the contributor.txt.

**Review by RussKie — APPROVED** [review]

**Pull request merged**
