### PR TITLE
fix Appveyor artifacts

### LINKED ISSUE #4838: Appveyor: Build Artifacts Missing?
**Do you want to request a *feature* or report a *bug*?** Reporting a Bug

**What is the current behavior?** Appveyor isn't uploading any Build Artifacts

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Not Applicable besides just going to the Appveyor Artifacts page.

**What is the expected behavior?** Appveyor usually uploads a Portable ZIP Build Artifact

**Environment you encounter the issue:** Not Applicable

- GitExtensions version: Master - Latest (Appveyor)
- GIT version: N/A
- OS version: N/A

**Did this work in previous version of GitExtensions (which)?** Appveyor Artifacts has shown in previous Builds

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #4838

### CODE REVIEW

**Comment by sharwell** [comment]
This change introduces a regression in the AppVeyor build verbosity. Can you describe why it was necessary to fix the problem?

**Comment by RussKie** [comment]
As described in #4838 [the script failed](https://ci.appveyor.com/project/gitextensions/gitextensions/build/3.00.00.2451#L440) and stopped producing artifacts after the original change was introduced.

**Comment by sharwell** [comment]
Thanks. It looks like in this release the solution is the following:

> %szip% a -tzip %normal% GitExtensions > NUL

**Comment by RussKie** [comment]
If it works☺

**Pull request merged**
