### PR TITLE
fix #3073 Need staged file count

### LINKED ISSUE #3073: Need staged file count
I wonder sometimes, how many of files are added to staged.
So it is difficult to see and count manually.

### PR DESCRIPTION
**Pull request by JohnnyKwon**
#3073

### CODE REVIEW

**Comment by spdr870** [comment]
Would it be possible to move the text to the statusbar? This takes less space and might look better.

**Comment by cgKwon** [comment]
OK. It's possible.

**Comment by cgKwon** [comment]
Move to statusbar is Complete.

DataSourceChanged event had a bug.
If FileStatusList item is zero, but not raise event.
So, I fix it.

**Comment by JohnnyKwon** [comment]
My commit rebase to current Head.

Check Please

**Pull request merged**
