### PR TITLE
No Opening EventHandler called for Commit Unstaged Menu

### PR DESCRIPTION
**Pull request by gerhardol**
Regression from #4390

Fixes #4390

What did I do to test the code and ensure quality:
 - Manual tests

### CODE REVIEW

**Comment by RussKie** [comment]
It says it "Fixes #4390".
Is that correct?

**Comment by RussKie** [comment]
I haven't pulled down and tested but looks fine to me

**Comment by gerhardol** [comment]
> It says it "Fixes #4390".
Is that correct?

Yes, this is a merge error, restoring the enabling of menu items (too many are visible now)

**Comment by gpongelli** [comment]
@gerhardol which is the error and when does it happens ?
is it related to [this change](https://github.com/gitextensions/gitextensions/pull/4390/files#diff-854f3222e6341653f495bc84c355fc1eL214) ?

**Comment by gerhardol** [comment]
> is it related to this change ?

Yes

**Comment by gpongelli** [comment]
This PR is ok for me, I didn't noticed the change on "Designer" file on my PR.

**Pull request merged**
