### PR TITLE
Make portable build use portable config

### LINKED ISSUE #5758: Portable build should set IsPortable in config
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

The portable build doesn't alter GitExtensions.exe.config

```xml
<GitCommands.Properties.Settings>
      <!--Set this setting to True to store settings with the application, False to  store settings in user's application data path.-->
      <setting name="IsPortable" serializeAs="String">
        <value>False</value>
      </setting>
    </GitCommands.Properties.Settings>
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

This value should be True on a portable build.
**Environment you encounter the issue:**

- Git Extensions 3.00.rc2
- ef05b7cb0130133180792211e99f64672ffe4124 
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:100.00% Y:100.00%

**Did this work in previous version of GitExtensions (which)?**

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5758

Changes proposed in this pull request:
- Make Portable Build store IsPortable: True in GitExtensions.exe.config

Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
- Ran Prepare-Release and opened zip

Has been tested on (remove any that don't apply):

### CODE REVIEW

**Comment by gerhardol** [comment]
Good change, but I would rather have changed the settings in all portable builds, including the AppVeyor builds by calling the snippets from MakePortable.cmd (in a new .ps script).

**Comment by vbjay** [comment]
Calling powershell in a cmd is tough.  

I made a powershell script that can be run to set a build to portable.

```powersehell
.\Set-Portable -IsPortable
```
Sets release build to be portable


```powersehell
.\Set-Portable.ps1
```
Sets release build to not be portable


```powersehell
.\Set-Portable -IsPortable Debug
```
Sets debug build to be portable

```powersehell
.\Set-Portable Debug
```
Sets debug to not be portable.

**Comment by vbjay** [comment]
@RussKie @gerhardol Please let me know if there are any issues.

**Comment by vbjay** [comment]
Squash?

**Comment by RussKie** [comment]
Absolutely :)

**Pull request merged**
