### PR TITLE
Fix failure to add repository path as safe directory

### LINKED ISSUE #11414: Trusting a repository by adding a security exception fails
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When attempting to open a repository that has an ownership issue (i.e. the directory is owned by a user other than the current user), the dialog offers to add an exception to the `.gitconfig` to trust the repository:

Screenshot of Git security error dialog

However, I'm seeing a trailing `\n` being added into the `.gitconfig`, so that the experience is that I click to trust the repository, and then Git Extensions reloads and I still can't open the directory and get the same error dialog.

### Steps to reproduce

1. Open untrusted repository
2. Click _Trust this repository_ button
3. Attempt again to open the untrusted repository

### Did this work in previous version of GitExtensions?

I believe this worked in the past, but I'm not certain when.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by bdukes**
Fixes #11414

## Proposed changes

- Trim white space from the command before running it

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
LGTM

**Review by gerhardol — APPROVED** [review]
not run

**Review by RussKie — COMMENTED** [review]
Thank you.

Could you please add a regression test to https://github.com/gitextensions/gitextensions/blob/master/UnitTests/GitUI.Tests/NBugReports/BugReportInvokerTests.cs?

**Comment by bdukes** [comment]
Sorry, I don't think I'll have time in the near future to work through adding that regression test.

**Pull request merged**
