### PR TITLE
Icon for delete file

### PR DESCRIPTION
**Pull request by gerhardol**
Delete file (copied from BisectBad.png) in Browse-Diff, Commit
"Open in explorer" icon in FormCommit Stage differed from other similar icons
In Browse: FileTree, change text from "Reveal in Explorer" to "Open containing folder"
(maybe all of these should be renamed to Open in File Explorer)
 
Screenshots before and after (if PR changes UI):
- 
image
image
image
image

For last icon, compare for instance to
image

image
image
image
image

What did I do to test the code and ensure quality:
- manual test

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
VS uses "Open containing folder" wording, whilst VSCode has (writing from memory) "Reveal in Exporer".
I think what you've done is good.

**Comment by pmiossec** [comment]
>VS uses "Open containing folder" wording, whilst VSCode has (writing from memory) "Reveal in Exporer". I think what you've done is good.

Let me disagree ;)
I think that the VSCode wording is a little better because it express also that the file will be highlighted (in fact selected and the file view scrolled if needed) once the folder is opened in the explorer.

**Comment by gerhardol** [comment]
And Chrome uses "Show in folder", clearer than "Reveal in Explorer" (I do not think Reveal is the right word here). I agree that the "show" variant has slightly more information to the user than "open", but I find it better to present one method, the show/selection is the expected action.

Some of the other GE seem to be like "show", other like "open". If this is changed, the use should be investigated.

**Comment by pmiossec** [comment]
I like "Show in folder" (perhaps better than "Reveal in Explorer" ;) )

**Comment by gerhardol** [comment]
I suggest "Show in folder" for all occurrences of "Open containing folder" (or "Open containing folder(s)", a construct that cannot be directly translated to all languages).

**Comment by RussKie** [comment]
> See the file where she lies matey.

I'll take that one 😆

**Comment by gerhardol** [comment]
#5597 is to change to "Show in folder"

**Pull request merged**
