### PR TITLE
fix Visual Studio form designer - revert previous workaround in SearchForUICommandsSource

### LINKED ISSUE #4937: form designer in Visual Studio is broken
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
form designer cannot be used because of two recent changes:
1. GitModuleControl has been made abstract in 68e98e4a95c016e6e4ea0c5f550a37875dd0164c
image
2. there was a change in a2e1251477d8faa04b5ec1c27a2ca606a3ea8013 which added a specific workaround to `SearchForUICommandsSource`: this caused an infinite loop when the designer is opened in Visual Studio

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open GitExtensions.sln
- open RevisionGpgInfo with View Designer (Shift+F7)

**What is the expected behavior?**
form designer can be used

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: irrelevant
- OS version: Windows 8.1
- Visual Studio 2017 Community 15.7

**Did this work in previous version of GitExtensions (which)?**
yes, before the two commits mentioned in the current behavior section

### PR DESCRIPTION
**Pull request by szaliszali**
This reverts commit a2e1251477d8faa04b5ec1c27a2ca606a3ea8013.

Fixes #4937 - part 3 of 3

Changes proposed in this pull request:
- commit a2e1251477d8faa04b5ec1c27a2ca606a3ea8013 added a workaround in `SearchForUICommandsSource` for a bug where an exception happened in the "Recover lost objects" dialog when copying text from a file in the viewer
    - the reverted change change caused Visual Studio to become unresponsive when opening the form designer
    - after PR #4940 this workaround is no longer necessary
 
Screenshots before and after (if PR changes UI):
- before 
image
- after 
image

What did I do to test the code and ensure quality:
- form designer: find `RevisionGpgInfo.cs`, then open it in form designer in VS
- exception on copying text: open Repository->Git maintenance->Recover lost objects..., right click a row in the table, click View, select and copy a part of the text

Has been tested on (remove any that don't apply):
- Windows 8.1
- Visual Studio 15.7

### CODE REVIEW

**Comment by szaliszali** [comment]
why do I think that this commit should be reverted:
- I found this revision to be the first one where VS hangs using bisect (on each step reload the sln in VS, rebuild, open the form in designer, check if VS hangs or not)
- after reverting this change the form designer started to work normally
- I identified that this change did not fix the real problem in `FormEdit`, but introduced a workaround for this very specific bug in a widely used component instead, which was a very risky choice, so I decided that reverting to the old method and fixing `FormEdit` is safer for the other components than trying to patch this workaround with another workaround

**Comment by pmiossec** [comment]
I can't work on the subject at least before 2 days.

But my development was made to fix an exception and fix the copy of the hash in the recovery form.

This feature is not very used, so I'm OK to revert!

**Comment by RussKie** [comment]
@szaliszali are you able to confirm with the revert we are not regressing
back?

**Comment by szaliszali** [comment]
@RussKie yes, #4940 (already merged) fixes the issue

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
