### PR TITLE
Update English.xlf

### PR DESCRIPTION
**Pull request by 1Jesper1**
Fix labels

Fixes #

## Proposed changes

- 
- 
- 

## Test methodology 

- 
- 
- 

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
This file is generated so it is not the right way to fix it as your changes will be overwritten (and the build will not pass so not chance it will be merged)...

**Comment by gerhardol** [comment]
The text is used for menu items where the keyboard accelrator is used as well as for tooltips.
Either the label is duplicated or the label is 'cleaned' before being added as a ToolTip (maybe a hack but the least effort for everyone).

As pmiossec wrote: Must be changed in the .cs files.

**Comment by pmiossec** [comment]
I think we already fixed it somewhere for simple toolbar button but I can't find where anymore. For example for "File Explorer", in v4.1 it's fixed. But not for the split button subitems tooltips....

**Comment by pmiossec** [comment]
So partly done in v4.1 here: #10781

**Comment by 1Jesper1** [comment]
@pmiossec Nice, also this one? 
image

**Pull request closed without merging**
