### PR TITLE
Multiple tfs build defs

### PR DESCRIPTION
**Pull request by kine**
Support for using Regex to set Builds used to report statuses of the builds on TFS.

Business Case example:
Build Definitions are created per Branch.

### CODE REVIEW

**Comment by pmiossec** [comment]
Seems good to me...

**Comment by DanielTheCoder** [comment]
Anything preventing this PR to be merged?

**Comment by pmiossec** [comment]
There is nothing very scary in this PR, so the only real reason, in my opinion, is that gitextensions is no more very active since some months :-(

I understand that it's hard to find some free time sometimes...

**Comment by vbjay** [comment]
I think part of the slow down is the catching up we have to do based on the
ramp up on git releases.

**Comment by jbialobr** [comment]
From my experience when I actively participated in maintaining the GitExt I can tell that there was enough work to fill a plate of a full time maintainer. I can see that now there is much more work to be done. What about starting a discussion on how to remove the bottleneck which is lack of sufficient maintainer work force?

Sorry about off topic.

**Comment by jbialobr** [comment]
>Seems good to me...

@pmiossec I assume you have reviewed and tested it. Would you merge it?

**Comment by pmiossec** [comment]
> @pmiossec I assume you have reviewed and tested it.

Yes, I have reviewed the code and the changes are somewhat trivial...
And I have tested it and it is working well.

>Would you merge it?

I'm not very sure about the exact meaning of you question...
If you're asking me if we could merge it, I think we could do it without problem.

If I can do something else to help...

**Comment by jbialobr** [comment]
@pmiossec Thanks.

**Pull request merged**
