### PR TITLE
Fix dark theme visually corrupt after dpi change

### LINKED ISSUE #8798: Dark theme visually corrupt after dpi change
## Current behaviour

If the app is configured to use a custom theme (e.g. the dark), and there is a user changes preferences that include dpi scaling (e.g. 100%->150%, 200%->150%) certain pars of the app become rendered incorrectly, e.g.

| Current | Expected |
|---|---|
| image | image |

Related: https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-688719768

## Expected behaviour

Currently the only way to resolve the issue is to restart the app. Which in some circumstances could be rather destructive to the current user flow (e.g. being in a middle of debug session, with various diff opened), and should be avoided, if possible.

It could be possible to react to [`SystemEvents.UserPreferenceChanged`](https://docs.microsoft.com/dotnet/api/microsoft.win32.systemevents.userpreferencechanged) and update theming hooks.
However the event must be handled with an utmost care to avoid deadlocking the app (e.g. ["Debugging Windows Forms Application Hangs During SystemEvents.UserPreferenceChanged"](https://docs.microsoft.com/en-us/archive/blogs/dsui_team/debugging-windows-forms-application-hangs-during-systemevents-userpreferencechanged) and [".NET 4.0 and the dreaded OnUserPreferenceChanged Hang"](https://stackoverflow.com/q/4077822/2338036).

## Steps to reproduce

1. Configure the app to use a custom theme, e.g. the dark.
2. (In multi monitor setup) Move the app to the monitor that will have its scale factor changed
2. Change the current scale factor (e.g. 100%->150%) while running the app
3. Observe various visual artifacts

## Environment

- GitExtensions version: 3.4.3 and the current master

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #8798

## Test methodology 

- manually change scaling factor back and forth.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by NikolayXHD — APPROVED** [review]

**Comment by NikolayXHD** [comment]
Some parts of UI do not look dark in dark theme, from RDP. I need to figure out if this has to do with this PR or not.

https://yadi.sk/d/dmUwPHz4hs7hXQ

**Comment by RussKie** [comment]
Omg I had the same issue yesterday, and I thought the app was totally broken... It took me about 30 minutes of panic, reset-rebuild-rerun, until I realised I had this checkbox checked:
image

**Comment by NikolayXHD** [comment]
>  until I realised I had this checkbox checked:

Exactly, that was it. The checkbox should have been turned off automatically.

One thing to do before merge, though. The colors are still broken if I disconnect and reconnect to RDP. Hopefully this is fixable by handling another `UserPreferenceCategory`

**Comment by RussKie** [comment]
Can you debug it? Feel free to pile on top of this commit.

**Pull request merged**
