### PR TITLE
refactor: Management of remote repositories

### PR DESCRIPTION
**Pull request by RussKie**
Remote repositories are accessible on a several forms, however the experience is quite inconsistent.
The management of the remotes is quite poor too, UX is confusing and buggy.
In the original implementation the UI and the BL concerns intertwined which makes it difficult to maintain, extend and test.
- The new implementation moves the functionality concerning dealing with the remotes repositories into a separate controller abstracting the data management from the UI.
- The controller enables testing
- The controller also simplifies the remotes management (FormRemotes). The "remote repositories" tab's layout has also been reworked and updated.
- All affected forms now need to instantiate a controller, load the remotes and bind them to the desired UI control (i.e. to a combo).

The following reported bugs are fixed:
- #3154 - Saving new remote clears URL entry
- #2550 - Remote Repositories > Separate Push URL not working 
- #1465 - Tab Stop Order in Remote Repositories dialog is very messed up 

The following change was undone, as it introduced quite inconsistent and confusing UX:
- #1208 - Rearrange buttons in "Manage Remote Repositories" dialog 

Translations:
The following items added in FormRemotes:
- lblMgtPuttyPanelHeader.Text
- _gitMessage.Text
- _gbMgtPanelHeaderNew.Text
- _gbMgtPanelHeaderEdit.Text
- lblMgtDetailsPanelHeader.Text
  The following items removed from FormRemotes:
- New.Text
- Delete.Text
- buttonClose.Text
- PuTTYSSH.Text
- _hintDelete.Text
- groupBox1.Text

### CODE REVIEW

**Comment by RussKie** [comment]
Original:
image
image

New:
image
image

**Comment by RussKie** [comment]
@jbialobr and other admins, could you please let me know whether this PR will be considered at all.
I wouldn't want to spend time rebasing it for the code to go stale again.
Thanks

**Comment by jbialobr** [comment]
It will be merged for sure. We have devoted a lot of time recently fixing bugs assigned to the 2.49 milestone in order to release a new version. I will come back to it after the 2.49 version is released.
Thanks for the contribution.

**Comment by RussKie** [comment]
Rebase was a bit of a nightmare, but I think it come out alright.
I've run it locally and everything seems to work as expected.

**Comment by RussKie** [comment]
@jbialobr do you think you could merge this in?

**Comment by jbialobr** [comment]
When I open the FormPull the selected remote is the first one from the list. Before it was the remote for the current branch.

**Comment by RussKie** [comment]
I'll investigate in next few days

**Pull request merged**
