### PR TITLE
Support CombinedDiff for merge commit.

### LINKED ISSUE #525: Toggle to see only files that were changed in both parents of a merge commit
Qgit has the nice option of seeing only "interesting" files of a merge commit, where an interesting file is defined as a file that was changed in both parents. Such files may be listed through the command line:

git diff-tree --cc --name-status SHA1_of_merge

On way of implementing this in the gitextensions UI would be in the right click menu of the diff tab of a merge commit. A toggle could be used to choose the what files are to be displayed, but other UI solutions are equally welcome!

### LINKED ISSUE #2851: Show combined diff for merge commits in Diff tab
Combined diff lists only files modified from both parents and shows diffs from both parents in one place. It's much more informative for merge commits than two diffs with parents. It's default for `git show`.

Example from documentation:

    diff --combined describe.c
    index fabadb8,cc95eb0..4866510
    --- a/describe.c
    +++ b/describe.c
    @@@ -98,20 -98,12 +98,20 @@@
    - static void describe(char *arg)
     -static void describe(struct commit *cmit, int last_one)
    ++static void describe(char *arg, int last_one)
      {
     +	unsigned char sha1[20];
     +	struct commit *cmit;

It would be great if Git Extensions showed combined diff in the Diff tab in addition to diffs with parents (three sections: combined diff, diff with first parent, diff with second parent).

### PR DESCRIPTION
**Pull request by EbenZhang**
This pull request adds the support to display the combined diff for a merge commit.

* some context menu items are disabled for the time being
* Octopus merge commit hasn't been supported.

Fixes #2851, Fixes #525

### CODE REVIEW

**Comment by EbenZhang** [comment]
Change log and doc will be updated later once we decide to merge this pull request thereby avoid potential merge conflicts.

**Comment by EbenZhang** [comment]
@KindDragon I've removed for other languages and added the entry for only `English.xlf`

**Comment by KindDragon** [comment]
@EbenZhang Thanks. Please squash 1da9452 and 917f7c2

**Comment by EbenZhang** [comment]
@KindDragon squashed all the commits and added a new one for the `changelog.md`

Do you think it's necessary to update the user manual? If so, I think maybe add a new section below the `images/commit_diff_view.png` of the `browse_repository.rst`.

**Comment by jbialobr** [comment]
The diff view provided by GitExt isn't useful, moreover it is misleading.
git1
git2

There is an empty diff view for FormBrowse in commit 511f273b99af4529f6eb30069bb9070dc73fbbb4. Can you explain why?

**Comment by EbenZhang** [comment]
The first one,  are you concerning about the space before the `+` which means the line was not presented in the left parent? I think might need to improve the diff viewer to support ` +`, ` -`, `++`, `--`.

The second is because there is actually no conflict. `diff-tree -c -p` will show the diff but you will see the changes are either from the right parent or the left parent(no conflict), this is so called non-interesting changes which are excluded by the `--cc`. Haven't found a way to avoid this.

**Comment by Radrik5** [comment]
I think GitExt should provide an option to switch between `-c` and `--cc`, but we can implement it later in a separate PR.

**Comment by EbenZhang** [comment]
I will have a look the diff view this weekend to see if I can fix the highlight issue.

**Comment by EbenZhang** [comment]
Hey guys, 

* Added the ability for the diff viewer to display the combined diff
* Now it will display 'Uninteresting diff hunks are omitted' for the empty files. As Radrik5 said, we can add the `-c` option later run.

**Comment by jbialobr** [comment]
Combined diff view ignores encoding and number of visible lines.

**Comment by jbialobr** [comment]
>The second is because there is actually no conflict. diff-tree -c -p will show the diff but you will see the changes are either from the right parent or the left parent(no conflict), this is so called non-interesting changes which are excluded by the --cc. Haven't found a way to avoid this.

It seems that parsing the diff output and seeking for file names is the only available way atm.

**Comment by EbenZhang** [comment]
@jbialobr 

* Fixed the bug where Combined diff view ignores encoding and number of visible lines.
* We can added an option in the future to toggle `-c` and `--cc` for the omitted diff.

**Comment by jbialobr** [comment]
>We can added an option in the future to toggle -c and --cc for the omitted diff.

I think that the `-c` option should be used by default - there is no warning that the diff is shown with not interesting hunks omitted and non advanced users may be not aware that the given diff is not complete.
When the option is added then the user has to do a conscious action to omit not interesting hunks.

**Comment by EbenZhang** [comment]
@jbialobr,
 * Fixed the encoding issue.
 * For the `-c` `--cc` option, how about add an button with the icon of icondiff  to the toolbar of the diff viewer?

Here is the current toolbar: differviewtoolbar

**Comment by EbenZhang** [comment]
Advanced `omit uninteresting diff settings` added

**Comment by pmiossec** [comment]
Works quite well! Good improvement ;)

**Comment by EbenZhang** [comment]
Close as it's included in #2988, so I don't have to solve conflicts for two branches.

**Pull request closed without merging**
