### PR TITLE
Tweak settings dialog

### PR DESCRIPTION
**Pull request by RussKie**
Changes proposed in this pull request:
- somewhat re-order the settings tree
- extract fonts settings from under the 'Appearance' tab into its own
- scaling fixes to 'General', 'Appearance', 'Fonts' and 'Advanced' tabs
 
Screenshots before and after (if PR changes UI):
Before (v2.51.02) 200% scale:
image
image
image

After 200% scale:
image
image
image
image

What did I do to test the code and ensure quality:
- a lot of manual runs

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
> I would have preferred to have Git Settings before GE settings.

Initially I had the Git node above the GE node. However to me it looked a bit awkward - our app's preferences should be above any other preferences. I am open for discussions about the order.

> How to handle the settings in Detailed in a more logical way, some distributed to other, some separated.

There is heaps more work to be done in re-arranging settings and presenting them in more logical way.  I suppose I should have started a new discussion about it. I was on a plane tinkering with stuff and this come out of that.

I'll start a new thread so we can discuss further changes to the settings.

**Comment by drewnoakes** [comment]
WIP with two approvals already! Doing something right :)

I've been spending some time trying to look through all the UI with 'fresh' eyes and spotting things that could be simply improved to make 3.0 feel much nicer to use. I'll submit some stuff soon. Totally agree there's more we can do in the settings area to improve things.

**Comment by gerhardol** [comment]
(There is one thing I did not test and since we will likely refine this more anyway I will not check right now. Git and GitExtensions should be expanded when normal settings are opened and collapsed when Plugin Settings are opened.)

**Comment by RussKie** [comment]
Sure, can do that

**Comment by gerhardol** [comment]
Note: Documentation must be updated due to this change. As there may be more changes, it may not be efficient to update right now.

**Comment by RussKie** [comment]
Yes it did cross my mind 😕

**Pull request merged**
