### PR TITLE
Save windowPositionlist as a separated XML

### LINKED ISSUE #2710: [mono] An exception was thrown by the type initializer for GitCommands.AppSettings
https://gist.github.com/ArsenShnurkov/d3c29df6d79c15171ea6

System.TypeInitializationException: An exception was thrown by the type initializer for GitCommands.AppSettings ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 104, position 9.

### PR DESCRIPTION
**Pull request by EbenZhang**
So we don't have to escape the nested XML for Mono. 
Fixes #2710

### CODE REVIEW

**Comment by Carbenium** [comment]
It would be great to see this one merged since mono probably will need some time to fix the issue on their side.
Patch tested and seems to be working as expected.

---
Rev. 527cfc9c with this change applied
Mono Stable 4.2.1.102/6dd2d0d on Linux Mint 17.2

**Comment by Carbenium** [comment]
Actually there is an issue: The call to [Properties.Settings.Default.Save()](https://github.com/EbenZhang/gitextensions/commit/e364e0fa3c42bf9dbb9bb5977dd23fccc1a98c85#diff-f525897870d64f91af5ca7e32451e149L311) gets removed so the user settings aren't saved at closing the application.

**Comment by EbenZhang** [comment]
> Actually there is an issue: The call to Properties.Settings.Default.Save() gets removed so the user settings aren't saved at closing the application.

The `SavePosition` is only called when the form is closing and `_enablePositionRestore` is `true`, so I believe the function was designed to just save the position of the window rather than all the application settings.

**Comment by Carbenium** [comment]
Yes. It seems like there is a design failure. Anyway this call has to be made somewhere, otherwise the settings can only be saved from the settings window.

**Comment by Carbenium** [comment]
@EbenZhang: Are you still working on this?

**Comment by spdr870** [comment]
The last commit seems to solve the issue that @Carbenium  mentioned. I am reviewing the changes..

**Comment by markathomas** [comment]
This saving of the window list XML is adding the XML header declaration at the top of the window list causing the entire document to be invalid.

**Comment by EbenZhang** [comment]
Can you provide a specific example, and potentially how to reproduce?

**Comment by markathomas** [comment]
i downloaded latest, opened via `mono GitExtensions.exe`, closed by clicking the X in the top-right corner, then tried to re-open and received a stack trace. opening settings file via `vi ~/.local/share/GitExtensions/GitExtensions.exe_Url_20a500f6d4dfba7656e7c5d3d1008ed9e18bd7ce/user.config` shows the following:

<setting name="WindowPositions" serializeAs="Xml">
    <value>
      <?xml version="1.0" encoding="utf-16"?>
<WindowPositionList>
  <window>
    <name>FormBrowse</name>
    <state>Normal</state>
    <position>44, 44, 931, 600</position>
  </window>
</WindowPositionList></value>
  </setting>

notice the <?xml version="1.0" encoding="utf-16"?> embedded in the document.  this is incorrect and makes the XML document invalid.  removing this declaration allows the app to open successfully.

**Comment by EbenZhang** [comment]
After my change, it will save to windowsposxxxx.xml not the user.config. the change was merged to master but haven't been released.
Can you check the version number of your gitextensions.

**Comment by LoudMurmur** [comment]
There is no snapshot availables (can't find them)?
I tried compiling the mono build from the source (master) myself but the compilation always fail.
(It also behave like that on the git repo so I guess the mono build is broken)

Lastest sourceforge version is one year old.

**Pull request merged**
