### PR TITLE
WIP: Fix viewing file history for files that don't exist in current HEAD

### PR DESCRIPTION
**Pull request by mdonatas**
## Fixes
When trying to view history for a file which does not exist in currect HEAD (i.g. has just been created in another branch) an empty History/Blame form opens and doesn't load any changes to display.

## Proposed changes

- Because same variable was re-used to retrieve exact file path in the case of failure it would be reset to null and thus later could not be used to load history for it. Fix: Use separate variable for exact path check.

## Test methodology

- Manual testing by viewing history of the file which does not exist in current HEAD

## Test environment(s) 

- Git Extensions 3.1.0
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Can we construct a test to verify the behaviour?

**Comment by RussKie** [comment]
Please send your sign off to contributors.txt in a separate PR

**Comment by mdonatas** [comment]
@RussKie sign off PR submitted.

As for the test at first I thought that would be mission impossible as not only would I need to test the FormFileHistory but it also loads data in an async fire-and-forget way.. but using FormBrowseTests.cs as a starting point I have a prototype test working so I'll try to finish it over today/tomorrow.

**Comment by RussKie** [comment]
> As for the test at first I thought that would be mission impossible... but using FormBrowseTests.cs as a starting point I have a prototype test working so I'll try to finish it over today/tomorrow.

Please shout, if you get stuck, and I'll try to help
I suppose once we have a model git repo (created via `ReferenceRepository`) executing a UI test shouldn't be a big problem

**Comment by mdonatas** [comment]
Haha, daughter fell asleep in the car and we didn't want to wake her, that gave me time to finish the test. Waiting for feedback.

#DadWantsToCode
Dad wants to code

p.s. I guess I'll need to rebase on master when currently failing tests are fixed, right?

**Comment by illfated** [comment]
Looks like a rebase should be most useful. 75 errors is a lot more than normal in AppVeyor.
BTW, if you did intend to post that picture, the upload link returns `Non-Image content-type returned`.

**Comment by RussKie** [comment]
Haha! Nice 👍
I know the feeling, been there, done the same 😆

You seem to have more space than me in my cruiser, I don't fit with my MBP on the driver's seat (and I'm not fat).

**Comment by illfated** [comment]
Looks like commit https://github.com/gitextensions/gitextensions/commit/19977de69331c95495b6ecfa6d91369356efcc96 (PR #6264) made changes to `UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs` , thereby making it necessary to rebase this PR once again to have your PR files up to date.

**Comment by RussKie** [comment]
The failing tests are fixed now, please rebase.

**Comment by mdonatas** [comment]
Hmm, the tests seem to be failing more or less randomly

**Comment by RussKie** [comment]
I pulled it down locally, I had a large number of tests failed.
I think it is an indication that the proposed implementation is a regression 😞

**Comment by mdonatas** [comment]
Hmm, I've had numerous tests fail on master right under my fixes, have you
tried master? I'll check a bit later.

**Comment by RussKie** [comment]
The master is failing with tests in FormCommitTests, this is getting fixed.

**Comment by mdonatas** [comment]
Hmm, made a fix but not sure why AppVeyor has so many failing tests. Locally the only tests that failed were seemingly DPI related (running at 200% scale).

image

**Comment by mdonatas** [comment]
It's a bummer that tests don't run in isolation. If I modify somehow the ReferenceRepository in a test the Module created during this test leaks into other tests and many of them fail.
For instance something as simple as `_gitModuleTestHelper = new GitModuleTestHelper("repo-FormFileHistoryTests");` end up showing up in other tests failing with can't find the directory exception.

**Comment by mdonatas** [comment]
Going through a callstack of some other test when getting "The directory name is invalid" exception I can see that at some point in the callstack the repo path changes from "repo1" into "repo-FormFileHistoryTests". Am I doing something wrong with my setup?

(this is when running all the tests and some of them start failing randomly)

**Comment by gerhardol** [comment]
Is this needed with #6909?

**Comment by mdonatas** [comment]
I am pretty sure #6909 has fixed this.

**Pull request closed without merging**
