### PR TITLE
Reflog: display also reflog for remotes

### PR DESCRIPTION
**Pull request by pmiossec**
to be able to revert a `--force-with-lease` more easily, if needed...

### CODE REVIEW

**Comment by pmiossec** [comment]
I no more split in 2 columns "Actions" and "Message" (so updated the regex) because it makes not a lot of sense and cause a problem with remotes (that don't have this distinction)

**Comment by RussKie** [comment]
could you explain how it makes the revert easier?

**Comment by pmiossec** [comment]
I use perhaps the bad word (should perhaps have been "fix" because "revert" as already a meaning in git ;) )

In fact, with this pull request, you could see the reflog of the remotes which was not possible before (we could see only the reflog of local branches).
So, by looking the reflog of the remote, that reflog must be less cumbersome than the one of the local branch and line at fault should be easier to find (especially for beginners).

I agree that it's not the **main** argument to merge this PR ;) (but it could help...)

**Comment by RussKie** [comment]
righto... it would have been worth mentioning that in the original description
image

while you're at it, do you think you could alphabetize the dropdown as well?

**Comment by pmiossec** [comment]
>while you're at it, do you think you could alphabetize the dropdown as well?

Will do it...

**Pull request merged**
