### PR TITLE
Make DropDownWidth in BranchSelector adjust to longest item

### PR DESCRIPTION
**Pull request by joergpichler**
Fixes #

https://github.com/gitextensions/gitextensions/issues/7822

### Before

grafik

### After

grafik

## Test methodology 

- Manual

## Test environment(s) 

- Windows 10 1909

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by joergpichler** [comment]
Sure. I can have a look tomorrow. Where is the best place to put helper
methods in the code base?

**Comment by pmiossec** [comment]
You could look at `ComboBoxExtensions` to add an extension method if needed (because it seems that there is already a method doing the same).

I let you see in details...

**Comment by RussKie** [comment]
OT: this whole form is a mess
ge-compare-branch-resize

**Comment by joergpichler** [comment]
> 
> 
> Please use existing extensions methods from `ComboBoxExtensions`

Done

>
> OT: this whole form is a mess

I removed the resize grip from the form to prevent this ugly behavior for now

**Pull request merged**
