### PR TITLE
fix: Branch filter isn't truly reset

### LINKED ISSUE #8484: Branch filter isn't truly reset
Originally reported by @ivangrek in https://github.com/gitextensions/gitextensions/pull/8414#issuecomment-699523919.

## Current behaviour

Whenever a branch filter is applied via the `FormBrowse` toolstrip, and then the filter textbox is cleared, the filter isn't reset.

The bug appears to be here:
https://github.com/gitextensions/gitextensions/blob/4b8024547f58f96802475cf5b448bccb887fb14c/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs#L513-L523

## Steps to reproduce

- Filter by branch
- Clear filter
- Select "Show filtered branches"

image

- Filter by commit message
- Select "Show filtered branches"
- Select "Show all branches"

image

## Did this work in previous version of GitExtensions

Appears to be a bug from day 1

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #8484

## Proposed changes

Whenever the filter value is being cleared in the UI, the filter isn't getting reset in the underlying plumbing.
The fix resets the filter.

This unblocks #8414 

## Test methodology 

- manual
- integration tests

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
@ivangrek please have a look

**Comment by RussKie** [comment]
@msftbot merge in 36 hours

**Comment by ivangrek** [comment]
Select "Show filtered branches"

Not equals

Change repository
Show this branch only
Change repository
Select "Show filtered branches"

I guess we need last changes from #8414 also.

image

BranchFilter.Text is not cleared now.

**Comment by ivangrek** [comment]
Select "Show filtered branches"
With no filter selection.

At first time shows all branches. It is right?

**Comment by RussKie** [comment]
> BranchFilter.Text is not cleared now.

Does https://github.com/gitextensions/gitextensions/pull/8489 solve it?

**Comment by RussKie** [comment]
> Select "Show filtered branches"
> With no filter selection.
> 
> At first time shows all branches. It is right?

I presume so. I don't use filters, but I think I will, once filtering is made more usable.
If there is no filter what else would you want to show?

**Comment by ivangrek** [comment]
> Does #8489 solve it?

Passed.

**Comment by RussKie** [comment]
> > Does #8489 solve it?
> 
> Passed.

Awesome! Is there anything else outstanding or missing?

**Comment by ivangrek** [comment]
Show filtered branches

Not equals

Show this branch only
Show all branches
Clear branches filter
Show filtered branches

**Comment by ivangrek** [comment]
Is it right?

image

**Comment by RussKie** [comment]
You're good! :D How did you end up in this state?

**Comment by ivangrek** [comment]
> How did you end up in this state?

Show this branch only
Show all branches
Clear branches filter
Show filtered branches

After last step сheckbox not checked on "Show filtered branches".

Show filtered branches (Again)

**Comment by RussKie** [comment]
> Is it right?
> 
> image
>
> ...
> Clear branches filter
> ...

If you do this why does the filter still has text?

**Comment by ivangrek** [comment]
> If you do this why does the filter still has text?

Show this branch only

Work too.

**Comment by RussKie** [comment]
Are you available for a chat? If so, drop me a line on my email, and I'll set up a call.

**Comment by RussKie** [comment]
One thing I can tell for sure filtering is utterly broken - the menu options available via the toolstrip are executing directly on the revision grid, which doesn't have access to the toolstrip filter textbox. Actions invoked from the left panel executed via filter proxy that does have access to the toolstrip filter textbox....
So in some cases when the filter is reset - the filter textbox isn't getting cleared. I can't see an easy way of fixing it. 

Ultimately I want to remove the toolstrip filter textbox completely, and allow branch filtering via the left panel. Related discussion in #8441.

**Comment by RussKie** [comment]
I pushed some crutches in, but boy is it ugly...

I think it should work now, but would be great to cross check. I'll add some more tests, once we settle on the behaviour.
Thanks for being my tester.

**Pull request merged**
