### PR TITLE
Improve exception reporting

### LINKED ISSUE #10543: [NBug] Exit code: -1073741510 Using username "git".
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@github.com:mrveress/my-farming-grp.git""

```
GitExtUtils.ExternalOperationException: Using username "git".
 ---> System.Exception: Using username "git".
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

Well, it throws when you just use PuTTy SSH key to Github.
Reproducing:
- Load PuTTy .ppk key for Github.com
- Click "Load SSH Key" - ok
- Click "Test Connection" - Terminal opens with "Access Granted. Click Return..." blablabla. Click "Enter" key, then close terminal window
- TADA Exception (at least for me)

### Steps to reproduce

- Load PuTTy .ppk key for Github.com
- Click "Load SSH Key" - ok
- Click "Test Connection" - Terminal opens with "Access Granted. Click Return..." blablabla. Click "Enter" key, then close terminal window
- TADA Exception (at least for me)

### Did this work in previous version of GitExtensions?

Yes, but not sure about version

### Diagnostics

_No response_

### LINKED ISSUE #11165: [NBug] Exit code: -1073741510
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.21
- DPI 192dpi (200% scaling)
- Portable: False

### Issue description

Exit code: -1073741510
Command: C:\Program Files\Git\cmd\git.exe
Arguments: add --patch "file_based_dynamic_parameters.h"
Working directory: D:\AT_Prj\AT_Src\FO, AnC\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at async Task<bool> GitCommands.GitModule.AddInteractiveAsync(GitItemStatus file) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 1907
   at async void GitUI.CommandsDialogs.FormCommit.interactiveAddToolStripMenuItem_Click(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 3351
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

I closed the window that was opened when I clicked "interactive add" and then received this error.

### Steps to reproduce

-Go to the commit window
-Right-click a file
-Choose "Interactive Add"
-Close the window that opens

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10543
Fixes #11165
Fixes https://github.com/gitextensions/gitextensions/pull/11074#issuecomment-1688928982

## Proposed changes

- Throw `OperationCanceledException` instead of plain `ExternalOperationException` on `Ctrl+C` exit code from external process in order to avoid (bug report) popup
- Fixup `ReportFailedToLoadAnAssembly`:
  - only if the `FileNotFoundException` message starts with the specific "Could not load file or assembly"
  - remove lengthy version info from displayed message
  - handle `isTerminating`
  - simplify (like other usages)
  - use warning icon
- Add descriptions to `Ignore` / `Report` buttons and use warning icon in case of `ExternalOperationException`
- Disable `Send and quit` for `UserExternalOperationException` (The `Copy` button can be used.)
- Add exception text "External program returned non-zero exit code." in case of empty StandardError output

### Before

image

for other exceptions: direct invocation of BugReporter

### After

image

image   image

image   image

image   image

image   image

image   image

image   image

### BEFORE

image   image

## Test methodology 

- manual

## Please do not squash merge

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
+1 Speed review
This is getting complex, but the alternative is to disable NBug....

**Comment by RussKie** [comment]
> Fixup `ReportFailedToLoadAnAssembly`:
> * only if the `FileNotFoundException` message starts with the specific "Could not load file or assembly"
> * show actual exception message instead of own construction
> * add `Ignore` button
> * handle `isTerminating`
> * simplify (like other usages)



> ### After
> image

The message is too long and carries no added useful information for a user over what's currently implemented. The full message is provided in the collapsible footer for any users that **want** too see it.
The ignore button in this case must not be shown either because we can't guarantee the correct behaviour of the application. There are only two viable options - to restart or to report.

**Comment by RussKie** [comment]
>  image

This is passive-aggressive (or outright aggressive), I can't approve this either.

**Review by RussKie — CHANGES_REQUESTED** [review]
As noted above

**Comment by mstv** [comment]
> This is passive-aggressive (or outright aggressive), I can't approve this either.

Yes, I am softening it and moving it to the `Ignore` and `Report bug` buttons description.

> The ignore button in this case must not be shown either because we can't guarantee the correct behaviour of the application. There are only two viable options - to restart or to report.

I added the ignore option when *all* `FileNotFoundExceptions` triggered this TaskDialog yet.
Since this is not that catchy any longer, I can remove it again.

> The message is too long and carries no added useful information for a user over what's currently implemented. The full message is provided in the collapsible footer for any users that want too see it.

The error message is not much longer.
I switched to the exception message when *all* `FileNotFoundExceptions` triggered this TaskDialog yet, which showed a misleading message for "normal" file issues then.
If you really want that extra code and that translatable string, I can change it back.

image

**Comment by RussKie** [comment]
What do you think of changing the icon from 🛑  to ⚠️ ? Perhaps it could help making users not think "the app crashed"....

**Comment by RussKie** [comment]
I do think that this much text is excessive, and largely meaningless to an average user:
image

E.g., if Word or Paint would show you such error how much would you care? The issue won't be actionable (unless, of course, you'd be purposefully trying to delete files and see how far you can go :)).

**Comment by mstv** [comment]
> I do think that this much text is excessive, and largely meaningless to an average user:
> image

No, but you approved it with the display of "version" etc. (refer to https://github.com/gitextensions/gitextensions/pull/11074#issuecomment-1675756874)
Changed.

I have updated the description and all screenshots.

**Review by RussKie — APPROVED** [review]
Thank you

**Comment by mstv** [comment]
> The ignore button in this case must not be shown either because we can't guarantee the correct behaviour of the application. There are only two viable options - to restart or to report.

It's Windows Update Day. It occurred several times in the Process dialog when trying to push.
There is no need to restart, just wait a few minutes and try again. 
So I choose "Report the issue" and close the BugReportForm using the X button.

**Comment by RussKie** [comment]
Funnily enough, I for the first time observed the issue too yesterday. And, yes, I had a pending Windows update. 
However, for me it manifested when I tried to open the "multiple branches/tags" tab in the Push dialog. Otherwise, the app functioned as usual. Since I used an official release I could ignore the issue, however, the desired functionality was not available to me, so the app had to be restarted.

**Pull request merged**
