### PR TITLE
Hide build server status tab if not configured

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

The WebBrowser control uses IE11 and may give a bad experience. Disable it unless explicitly enabled.

image

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
+0

**Review by RussKie — APPROVED** [review]

**Comment by vbjay** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by RussKie** [comment]
WebView doesn't come inbox as the old webbrowser control. It requires Edge
installed and requires quite a bit of space on a hard drive.... So, whilst
it could be a replacement, it's not a trivial piece of work.

**Comment by gerhardol** [comment]
I would like to promote the link to the external browser instead. The summary in the grid is often enough for me.

**Comment by vbjay** [comment]
Note evergreen mode. https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Pull request merged**
