### PR TITLE
Incorrect references and dependencies

### PR DESCRIPTION
**Pull request by gerhardol**
Corrects #4269

    GitExtensions (cs project) has References to the plugin .dll which should not occur (no direct access to the .dll)
    Build dependencies do not include all subprojects. So for instance when debugging, a clean was required first (partly hidden by the previous issue).

How did I test this code:
 - Clean the solution.
 - Verify that .dlls are removed. GitExtUtils.dll is still remains though.
 - Start debugging GitExtensions
 - Verify that the AppVeyor plugin is loaded

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
I can understand the change to csproj (sort of). Can you please explain the
change to the sln file?

**Comment by gerhardol** [comment]
Right click on the GitExtensions project and select Build Dependencies.
Previously, for instance AppVeyor was listed after GitExtensions, so it was not built when debugging.
A full build would have generated the .dll, but if you make a change to the plugin, you have to force rebuild it again.
For the BitBucket plugin that was listed as a Reference, it was enough to clean the project before debugging.

**Comment by RussKie** [comment]
VS is somwhat dumb when it comes to rebuilding. Resharper build is much
smarter (if you have Re#) and reduces build time

**Comment by RussKie** [comment]
> Previously, for instance AppVeyor was listed after GitExtensions

I can only guess that the reason all projects are referenced from GitExtensions project is to ensure they all get built before it. 
This may not be necessary, as per your suggestion, and can be achieved by setting the build order. This is, however, manual work and can get out-dated...

This is what copies all plugins to the target directory https://github.com/gitextensions/gitextensions/blob/master/TranslationApp/TranslationApp.csproj#L167-L185
This is why TranslationApp is built last.

**Comment by gerhardol** [comment]
> This is what copies all plugins to the target directory

The same when building GitExtensions.csproj

For debug to work properly the build system must understand that it should build all plugins first. This can be done in several ways (not mutually exclusive or complete list).
 * Depending on a project that collects all plugins, possibly with checks (this how I would have implemented this with GNU make or CMake or gradle, not so easy with MSBuild).
 * Use manual dependencies in the project so all plugins are built before the .exe (what this PR proposes)
 * Use manual project references as was done for some plugins. Not recommended as the plugin code can be used directly by the application.
 * Let the build system figure out the dependencies. I cannot see how this can be done here. Just because a plugin has references to the application, it does not mean that it has too be included.

The references were not really a problem, just done the wrong way. 

The TranslatorApp is not built last right now. This PR pushes the build of the translator app later, but some plugins as well as GitExtensions and the Setup are built after TranslatorApp. Only tests should be after. (The translator app do not need dependencies to all plugins as long as they are referenced by the main app). Without knowing the details how the translator app should work, I assume this and will push an update.

**Comment by gerhardol** [comment]
I ran the TranslationApp again after the update.
The Bitbucket Server binaries were renamed in #4210 an the app seem to have run where the internal .dll was not cleaned, so bitbucket resources should be duplicated on the server (I just get Load error when trying to view).

Also missing (should not be translated?)
      <trans-unit id="IdDataGridViewColumn.HeaderText">
        <source>SHA1</source>
        <target />
      </trans-unit>

**Comment by RussKie** [comment]
Ideally we In ideal world plugins would live in own/separate repo(s) and get installed/loaded by the user. We had some high level discussions before but nothing of substance. 
Such move comes with a lot of overhead, e.g. we will probably need to build some sort of plugin store, delivery mechanisms, compatibility checks etc....

I don't think any of the methods mentioned above address the issue of renamed assemblies in the target directory.
As I said, I don't have the issue you're facing, but I am happy to consider alternatives if they make DevEx easier.

**Comment by gerhardol** [comment]
I would suggest that the Setup project is removed from GitExtensions.VS2015.sln.
The msi package is built from BuildInstallers.VS2015.cmd (that calls MakeInstallers.cmd) to build the shell extension different targets and SshAskPass. The last are C++ projects and not included in the general solution, the setup project could be enhanced to handle this I assume, but for now it is clearer to remove .wixproj from GitExtensions.VS2015.sln.

**Comment by RussKie** [comment]
Once we get the 2.51 released we can start rejigging the solution (if
sensible).

**Comment by RussKie** [comment]
I've been getting dramas with the dependencies lately - not all files are getting copied into Debug/bin folder and then Fusion is complaining...
So, if this helps, it will be a ripper!
I will test it ASAPP

**Comment by gerhardol** [comment]
I suggest I rebase and make some adjustments first.
Both due to the projects have changed and that due to I have tuned some more locally

I have done some other changes to the build and dependencies too as well as 201572017 unification, that could go in later

**Comment by gerhardol** [comment]
Rebased and squashed, no changes was needed

After this, the maintenance that need to be done is to add new GEPlugins as dependencies for GitExtensions

**Comment by RussKie** [comment]
Great, thanks

**Comment by gerhardol** [comment]
I took a look at the second step I had worked on some time ago. Will submit a PR if this is merged.

https://github.com/gerhardol/gitextensions/tree/feature/n4269-build-dependency-pt2

After that, I would like to solve #4311 and #4312 and simplify the release process some. Seem to complicated now.

**Comment by RussKie** [comment]
Merge it if it is working.

**Pull request merged**
