### PR TITLE
Share common GitUI.Strings.Error

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes 

Various non localized uses of "Error" (mostly in message boxes) as well
as a few module private definitions of Error

Also for Warning, Yes, No (few occurrences)

Discussed in some other issues

Most of the new strings were added in #7334 , so not included in any release yet

## Test methodology 
Code review

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
@msftbot merge in 48 hours

**Comment by gerhardol** [comment]
Leaving two days for this non critical change, to allow for comments to amend changes or do this in another way

> Boring to review (but surely much more boring to do

Not so bad, search and replace. 

OT: gitk is good when reviewing this type of changes.
@pmiossec did you resurrect your branch?

**Comment by RussKie** [comment]
Boring to review (but surely much more boring to do

@pmiossec <https://github.com/pmiossec> you haven't seen "boring" yet 🤣

**Comment by pmiossec** [comment]
>OT: gitk is good when reviewing this type of changes.

GitHub is good enough for this one also

> @pmiossec did you resurrect your branch?

Yes, I did ( https://github.com/pmiossec/gitextensions/tree/better_diff_scroll )

What it is doing is switching to the next file when scroll end is reached if you keep the 'alt' key pressed.

I was not remembering in which state it was. It is working but I feel that the UX is not good enough. It needs more work.
But I have no time to dedicate to the project with the events that are happening now 😢
And it should not change soon... 😢 😢

**Comment by RussKie** [comment]
> GitHub is good enough for this one also

I use GH for reviews

> And it should not change soon... 😢 😢

Not sure whether it is intended, but it sounds like you don't want the situation to change.

**Comment by pmiossec** [comment]
>Not sure whether it is intended, but it sounds like you don't want the situation to change.

@RussKie 😮 I'm not sure to know how to take it.......  

But I could assure you that the 2 mains reasons why I no more have (a lot of) time to contribute to the project are not from my own and I will be much more pleased if/when these reasons will be fixed. And that I'm again be able to spend more time on the project.

I have some features that are mostly finished and that I also want to see merged and no time to finished them....

I take advantage of this off-topic message to tell the team that I'm very impressed to see that much activity on the project since a couple of weeks (even if it was already huge before).

**Pull request merged**
