### PR TITLE
Remove custom ToHashSet() methods. Fixes #9159

### LINKED ISSUE #9159: Remove custom `ToHashSet`
## Current behaviour

.NET 5.0 has introduced its own [`ToHashSet`](https://docs.microsoft.com/dotnet/api/system.linq.enumerable.tohashset), and our home-made methods can now be removed:
https://github.com/gitextensions/gitextensions/blob/169999f6b241bc256d2a1ebd6f2d851b67e2a3de/GitExtUtils/Linq/LinqExtensions.cs#L12-L17

## Expected behaviour

Use the .NET runtime functionality.

### PR DESCRIPTION
**Pull request by GintasS**
Fixes #9159.

## Proposed changes

- Removed custom methods.
- Started using methods from .NET 5.
 
## Test methodology 

- Existing tests are used for now.
- 
- 

## Test environment(s) 

- GIT 2.21.0.windows.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Please squash and it is ready to go

**Review by gerhardol — APPROVED** [review]

**Comment by GintasS** [comment]
> Please squash and it is ready to go

Just two questions before I squash it:

1.  Do I need to write explicit tests for all of these changes?
2.  Locally, even then I have master branch selected, two UI integration tests fail, is this ok, can I simply ignore them?

UI.IntegrationTests -> FormCommitTests:
image

**Comment by RussKie** [comment]
1. Do we have an existing test coverage?
2. What errors are seeing?

**Comment by GintasS** [comment]
> 1. Do we have an existing test coverage? 

3rd column (Status) explanation:
- No tests - no tests (direct or indirect) that cover the changed (2nd column) method.
- Partial - there are tests that cover the mehod directly or indirectly.
- Full - tests cover all methods and **ToHashSet** method directly




| File name     | Method name | Status (No tests, partial, full) | How? |
| ----------- | ----------- | ----------- |----------- |
| GitRef.cs     | GetAmbiguousRefNames(IEnumerable<IGitRef> refs)      |  Partial | GetAmbiguousRefNames is getting called by ForceRefreshRevisions() method, that has 3 tests inside RevisionGridControlTests.cs. ForceRefreshRevisions() is being tested, but not specifically ToHashSet() method.
| FormCommit.cs  | RestoreSelectedFiles(IReadOnlyList<GitItemStatus> unstagedFiles, IReadOnlyList<GitItemStatus> stagedFiles, IReadOnlyList<GitItemStatus>? lastSelection)       | Partial | StartCommitDialog is being tested. A lot of cases here are directly used from the Designer, so no tests. |
|FormPush.cs|UpdateRemoteBranchDropDown()| Partial |FormPush.cs is being called by GITUIComamnds.cs StartPushDialog, which is tested in FormPushTests, but yet, no direct test on ToHashSet().  TabControlTagBranch_Selected (which uses UpdateRemoteBranchDropDown) method seems to not have any tests. |
|LineCounter.cs|FindAndAnalyzeCodeFiles(string filePattern, string directoriesToIgnore, IEnumerable<string> filesToCheck)| No tests | - |
|FileStatusList.cs|UpdateFileStatusListView(bool updateCausedByFilter = false)|Partial|It is being tested, there are 4 tests (not directly again). in FileStatusListTests.cs and FormCommitTests.cs. FilterComboBox_SelectedIndexChanged is not being tested.|

**TL:DR**: For some of the files, there are indirect tests, but for all of them, there are no direct tests that test ToHashSet() correctly, most of the tests test the whole block (that includes ToHashSet logic).



2. What errors are seeing?

### **StageAll:**
image

**Line 264 (Red Line)**:
image

**Stacktrace:**

```
   at GitExtensions.UITests.UITest.<>c__DisplayClass1_0`1.<<RunForm>b__0>d.MoveNext() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 54
--- End of stack trace from previous location ---
   at GitExtensions.UITests.UITest.<>c__DisplayClass1_0`1.<<RunForm>b__0>d.MoveNext() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 65
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions, Delegate entrypointOverride)
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at GitExtensions.UITests.UITest.RunForm[T](Action showForm, Func`2 runTestAsync) in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 71
   at GitExtensions.UITests.CommandsDialogs.FormCommitTests.RunFormTest(Func`2 testDriverAsync, CommitKind commitKind) in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormCommitTests.cs:line 476
   at GitExtensions.UITests.CommandsDialogs.FormCommitTests.Should_stage_only_filtered_on_StageAll() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormCommitTests.cs:line 246
Result Message:	
Expected: 2
  But was:  0
```






###  **UnStageAll:**
image

**Line 305 (Red Line)**:
image

**Stacktrace:**
```
at GitExtensions.UITests.CommandsDialogs.FormCommitTests.<>c.<<Should_unstage_only_filtered_on_UnstageAll>b__16_1>d.MoveNext() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormCommitTests.cs:line 305
--- End of stack trace from previous location ---
   at GitExtensions.UITests.UITest.<>c__DisplayClass1_0`1.<<RunForm>b__0>d.MoveNext() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 54
--- End of stack trace from previous location ---
   at GitExtensions.UITests.UITest.<>c__DisplayClass1_0`1.<<RunForm>b__0>d.MoveNext() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 65
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at GitExtensions.UITests.UITest.RunForm[T](Action showForm, Func`2 runTestAsync) in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\UITest.cs:line 71
   at GitExtensions.UITests.CommandsDialogs.FormCommitTests.RunFormTest(Func`2 testDriverAsync, CommitKind commitKind) in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormCommitTests.cs:line 476
   at GitExtensions.UITests.CommandsDialogs.FormCommitTests.Should_unstage_only_filtered_on_UnstageAll() in C:\Open Source Projects\gitextensions\IntegrationTests\UI.IntegrationTests\CommandsDialogs\FormCommitTests.cs:line 290
Result Message:	
Expected: 3
  But was:  0
```

**Comment by mstv** [comment]
What git commands are executed? You can open the Git Command Log using `F12` before opening FormCommit.
What's their output if run on the command line?

The tests pass for master c033b008fe781c588e0eca98553217146209b29f both on AppVeyor and on my local PC.

**Comment by RussKie** [comment]
Do these test pass without your change?

**Comment by GintasS** [comment]
> What git commands are executed? You can open the Git Command Log using `F12` before opening FormCommit.
> What's their output if run on the command line?
> 
> The tests pass for master [c033b00](https://github.com/gitextensions/gitextensions/commit/c033b008fe781c588e0eca98553217146209b29f) both on AppVeyor and on my local PC.

Opening Commit window.

image

**Comment by GintasS** [comment]
> Do these test pass without your change?

If you're talking about **1.** tests, yes, they do pass without my change (locally - master branch for example).

If about **2.**, they're failing both on my changes and on master branch locally.

**Comment by RussKie** [comment]
Passes on the CI, good enough I suppose.
Thank you

**Comment by GintasS** [comment]
> Passes on the CI, good enough I suppose.
> Thank you

Appreciate the support too, thanks ;)

**Pull request merged**
