### PR TITLE
bugfix: ignore specific ActiveDocument exception

### PR DESCRIPTION
**Pull request by itsho**
When there's no active document. for example - "project properties" dialog, 
calling application.ActiveDocument will throw the following exception:
_The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))_

## Fixes 
An exception is displayed when clicking on 'commit' when "project properties" dialog is open.

## Proposed changes
ignore this specific exception.

## Test methodology 

- ran and tested multiple buttons while different 'documents' are open

## Test environment(s) 

- GIT 2.23
- Windows 10 1909

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Please provide your sign off to contributors.txt and we can merge it. Thank you

**Comment by itsho** [comment]
I'm confused.

Can someone please explain how come it **is** merged to the master at 29/Feb/2020,
but it is **not** part of any of the builds produced [after the merge](https://github.com/gitextensions/gitextensions/releases)? 
Tested on the latest 3.4.1.9675 and the issue still occurs. 


Thanks.

**Comment by pmiossec** [comment]
The fix has been made in the vsix project (and not in the application) that is not released in the same pipeline than the application.

You have to upload it in the marketplace. And indeed, now that we've released the latest version, we could release also a new version of it.

**Comment by RussKie** [comment]
Uh-ho, we're not building the vsix since the build pipeline restructure...

**Comment by RussKie** [comment]
I split the VSIX into [own repo](https://github.com/gitextensions/gitextensions.vsix), but we'll need to setup a CI/CD pipeline

**Pull request merged**
