### PR TITLE
Correctly reset unstaged changes without affecting staged

### LINKED ISSUE #11216: FormCommit: Reset unstaged file resets the staged changes, too
### Environment

- GitExtensions version: vNext since #10980 6434e770fa9d4389e66fcaa5b22d3fce204fa9c6

### Issue description

In FormCommit, resetting an unstaged file resets the staged changes of this file, too - as the confirmation dialog states.
This is unexpected though, particularly because it works well with the artificial commits in FormBrowse.

image

image

### Steps to reproduce

- stage some of the changes to a file
- select this file in the unstaged area
- reset changes

### Did this work in previous version of GitExtensions?

yes
- Git Extensions 4.1.0.16654
- Build 6084cf43185d40298ccdb63dadbefdfe7165e274
- Git 2.42.0.windows.1

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #11216

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
Nice refactoring.
But the issue is not about selected vs. all files.
The issue is that resetting a file from the unstaged area affects the index (refer to STR).

In preparation of the rework of FileStatusList (to unify the at least two implementations), I am searching for a usable design pattern...

**Comment by RussKie** [comment]
This fixes the problem - resetting the unstaged (portion of a) file no
longer affects the staged (portion of the same) file.

**Comment by mstv** [comment]
> This fixes the problem - resetting the unstaged (portion of a) file no
longer affects the staged (portion of the same) file.

Indeed, but only for users of the context menu.
`ResetSelectedFiles()` should also make use of `ResetChanges(bool onlyWorkTree, IEnumerable<FileStatusItem> filesToReset)` or call the `PerfomClick` method of the regarding items.

**Comment by gerhardol** [comment]
This change resets all files, just not the selected

Existing presentation issue for conflicts, you get a NBug popup (if you choose to report):

image

--

- Git Extensions 33.33.33
- Build 9badc6e090d4bc04bcec50b37b1dd754d86ca74f
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout -- .
Working directory: C:\dev\gc\tmp\both_changed_xxx\
image

```
GitExtUtils.ExternalOperationException: error: path 'ab' is unmerged
 ---> System.Exception: error: path 'ab' is unmerged
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\dev\gc\gitextensions_4\GitCommands\Git\ExecutableExtensions.cs:line 129
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\dev\gc\gitextensions_4\GitCommands\Git\ExecutableExtensions.cs:line 43
   at GitCommands.GitModule.ResetAllChanges(Boolean clean, Boolean onlyWorkTree) in C:\dev\gc\gitextensions_4\GitCommands\Git\GitModule.cs:line 1266
   at GitUI.GitUICommands.<>c__DisplayClass107_0.<StartResetChangesDialog>g__Action|2() in C:\dev\gc\gitextensions_4\GitUI\GitUICommands.cs:line 725
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\dev\gc\gitextensions_4\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartResetChangesDialog(IWin32Window owner, IReadOnlyCollection`1 workTreeFiles, Boolean onlyWorkTree) in C:\dev\gc\gitextensions_4\GitUI\GitUICommands.cs:line 721
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass196_0.<ResetChanges>b__0() in C:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\FormCommit.cs:line 2660
   at GitUI.CommandsDialogs.FormCommit.BypassFormActivatedEventHandler(Action action) in C:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\FormCommit.cs:line 2676
   at GitUI.CommandsDialogs.FormCommit.ResetChanges(Boolean onlyWorkTree, IEnumerable`1 filesToReset) in C:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\FormCommit.cs:line 2660
   at GitUI.CommandsDialogs.FormCommit.tsmiResetUnstagedChanges_Click(Object sender, EventArgs e) in C:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\FormCommit.cs:line 2093
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

--

For Worktree commit, there is a check:
image

**Review by gerhardol — APPROVED** [review]
Approved with the change I pushed.
Also addresses mstv comment.

The refactoring made this change harder to review...

**Comment by mstv** [comment]
The above git error can be seen on button `Reset unstaged changes`, too, if there are conflicted files. This is a separate, low-prio issue.

image

BTW: @RussKie, `TaskDialog` should not truncate texts (at least not after a few characters). And it would benefit from being resizable.
What type of WinForms issues should I create? Or do I already know the answer? "This is a design decision and done on purpose."

**Review by mstv — APPROVED** [review]
Thank you both!

**Comment by RussKie** [comment]
> Approved with the change I pushed.
> Also addresses mstv comment.

Thank you

> The above git error can be seen on button `Reset unstaged changes`, too, if there are conflicted files. This is a separate, low-prio issue.
> 
> image

What are the steps to repro this?



> `TaskDialog` should not truncate texts (at least not after a few characters). And it would benefit from being resizable.
> What type of WinForms issues should I create? Or do I already know the answer? "This is a design decision and done on purpose."

It's possible that we're not resizing the dialog (i.e., not using `SizeToContent` property).
I don't believe the TD trims the text, the text should be coming from git.

Once I have repro steps, I can have a look. ...Or you can ;)

**Comment by RussKie** [comment]
> Existing presentation issue for conflicts, you get a NBug popup (if you choose to report):
> 
> image

What are the steps to repro this?

We ought to add regression tests for all of these.

**Comment by gerhardol** [comment]
> What are the steps to repro this?
> 
> We ought to add regression tests for all of these.

Create a merge conflict. There are several variants.
There are 14 flags in GitItemStatus, there are about 2^14 combinations (most are irrelevant though).
It is hard to recreate these scenarios, I tried some in the reset refresh.

**Comment by mstv** [comment]
> > image
> 
> What are the steps to repro this?

Use your initial solution in order to reset a conflicted file.
I.e. resolved by Gerhard's solution.

**Comment by mstv** [comment]
> > `TaskDialog` should not truncate texts (at least not after a few characters). And it would benefit from being resizable.
> > What type of WinForms issues should I create? Or do I already know the answer? "This is a design decision and done on purpose."
> 
> It's possible that we're not resizing the dialog (i.e., not using `SizeToContent` property).

No, `SizeToContent = true` is specified for all `TaskDialogPage`s except for AzureDevOps.
It even looks better with `SizeToContent = false` but not good.

image

> I don't believe the TD trims the text, the text should be coming from git.

TD does trim it. Git prints the complete relative pathname:
```
$ "C:\Program Files\Git\bin\git.exe" checkout -- .
error: path 'IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs' is unmerged
```

> Once I have repro steps, I can have a look. ...Or you can ;)

>> can be seen **on button** `Reset unstaged changes`, too, if there are **conflicted files**.

**Comment by RussKie** [comment]
> TD does trim it. Git prints the complete relative pathname:
> 
> ```
> $ "C:\Program Files\Git\bin\git.exe" checkout -- .
> error: path 'IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs' is unmerged
> ```

Thanks for checking. In this case, it's probably Windows that's trimming it. I can't recall any special logic in the Windows Forms TaskDialog for trimming messages.
In both of these cases I don't think we'll get much traction here, even if we raised issues.

**Comment by RussKie** [comment]
I'm going to merge it as-is, we can tinker with the conflicted files later.
Thank you for your help and reviews.

**Pull request merged**
