### PR TITLE
Sign contributors.txt

### PR DESCRIPTION
**Pull request by wischi-chr**
As requested by `CONTRIBUTING.md` here my PR signing the contributors.txt

Thank you
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by wischi-chr** [comment]
Seems like I killed the build pipeline by signing the contributors.txt

**Comment by pmiossec** [comment]
Indeed, very strange. I have relaunched the build...

**Review by gerhardol — APPROVED** [review]
You can obfuscate the @ in the email if you prefer

**Comment by wischi-chr** [comment]
Thanks you, but it's fine.

**Pull request merged**
