### PR TITLE
Bugfix/settings appearance

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

Translation related
- Settings-Appearance got lost earlier in 3.1 (#6287 c28c023b5b9bdc50af97962a306818ea0e158cb2),(visible after TranslationApp ran). This is now being updated in the translations, the English.xlf source should be pushed again.
- NoImageService items were translated, with anonymous references. The newly added AuthorInitials in #6499 screwed up this list as it was added first (this is the correct place for this service, but adding must not reorder translations). 

### Before
image

### After

image

## Test methodology 
Manual

To avoid issues like this, we must enforce running the TranslationApp at updates, and fail builds if there are updates.

## Test environment(s)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you

**Comment by mast-eu** [comment]
> To avoid issues like this, we must enforce running the TranslationApp at updates, and fail builds if there are updates.

I second this, because I remember I had some trouble the first time I had to deal with TranslationStrings:
- first I did it manually in XLF files, than by change I read there's a TranslationApp
- the TranslationApp didn't work (now fixed in #6501). I made it work locally but was not confident enough to file a PR.
- once it ran, it updated more strings than I actually changed. This was because the strings were changed in earlier commits but without running the TranslationApp.

**Comment by RussKie** [comment]
Related #5189

**Comment by gerhardol** [comment]
The hard check is to run at all AppVeyor builds and fail if .xlf files updates

Hopefully the PR submitter calls out if he/she cannot figure out the error themselves...

**Comment by RussKie** [comment]
Yes.
Let's continue xlf specific discussions in the dedicated thread

**Pull request merged**
