### PR TITLE
Next selection as default

### PR DESCRIPTION
**Pull request by RussKie**
Changes proposed in this pull request:
- Centralise pull behavior and remove per-repository pull behavior
- Reorder pull menu
- Rename `FormPullAction` to `DefaultPullAction`
 
Screenshots before and after (if PR changes UI):
- before
image

- after
image

What did I do to test the code and ensure quality:
- manually

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you for checking. I don't believe #1931 is relevant, I'm proposing to reorder menu items in the dropdown not toolbar menus.

I think CodeFactor is complaining because I've touched `GitModule` file, the CC there is crazy, but I can't do anything about it.

**Comment by gerhardol** [comment]
> I think CodeFactor is complaining because I've touched GitModule file, the CC there is crazy, but I can't do anything about it.

Should have added a smiley. At least code was removed from GitModule.

**Comment by RussKie** [comment]
😁

**Comment by pmiossec** [comment]
2 more ideas of possible improvements :

* add also another separator between pull and fetch
* update the 'fetch all' label to better understand what it does by fetching all the remote repositories without being obliged to stick to the 'git fetch --all' command line. Because a lot of people don't really understand it (and the difference with fetch).

Something like 'fetch from all remotes' or 'fetch all remote repositories' or ...

I think that's Gitextensions duty to let users better understand what they are doing ;-)

**Comment by pmiossec** [comment]
Oups, too long to comment. PR merged :-(

**Pull request merged**
