### PR TITLE
Simplify revision grid repainting

### PR DESCRIPTION
**Pull request by MaxKoll**
## Proposed changes

Repaint by invoking Update() at the end of each BackgroundUpdater operation instead of using a quasi-periodic approach.

### Before

Repaints are triggered periodically by the Scroll event and do not coincidence with the asynchronous revision graph updates.

### After

- Repaint after every revision graph update.
- Simpler code.

## Test methodology 

- Observing WM_PAINT messages via WndProc() override.
- Lots of scrolling the revision grid.

## Test environment(s) 

- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 134dpi (140% scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
Occasionally, only one graph lane is shown on refresh after an operation - for long time or until a manual refresh. It might be related to some background git commands which can take very long on the affected (private) repos. I need to observe it longer.

**Review by gerhardol — COMMENTED** [review]
Seem OK, have not used it

**Comment by MaxKoll** [comment]
> Occasionally, only one graph lane is shown on refresh after an operation - for long time or until a manual refresh. It might be related to some background git commands which can take very long on the affected (private) repos. I need to observe it longer.

I must admit I have not tested it intensely. I'm unsure how this could affect anything other than repaints during scrolling, as the only thing gone is the periodic call to `Update()` in `OnScroll()`. Every other line is just overhead.

I would therefore assume that the added `await this.InvokeAsync(Update);` inside `UpdateVisibleRowRangeInternalAsync()` is causing problems, but how?

**Comment by RussKie** [comment]
The rebase operation is notorious for leaving the graph incomplete and undrawn (e.g., https://github.com/gitextensions/gitextensions/issues/9223). Perhaps, this could provide more testing opportunities.

**Comment by mstv** [comment]
It is different from #9223 where no graph is displayed at all.

**Comment by mstv** [comment]
Thank you for bringing this up. Included in and superseded by #11719.

**Pull request closed without merging**
