### PR TITLE
String handling review

### LINKED ISSUE #4271: Inconsistent short commit hash
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Different parts of the code shorten commit hashes differently:
E.g.
image

**What is the expected behavior?**
The behavior must be centralised and used universally.
Something like the following:

```
public interface ICommitHashFormatter
{
    string ToShort(string hash);
}
public sealed class CommitHashFormatter : ICommitHashFormatter
{
    private const string ShortLength = 8;

    public string ToShort(string hash)
    {
        if (string.IsNullOrEmpty(hash))
        {
            return string.Empty;
        }
        return hash.Length < ShortLength ? hash : hash.Substring(0, ShortLength);
    }
}
```

Also, as per https://github.com/gitextensions/gitextensions/pull/4310#discussion_r159726082 in the target state `ShortLength` should not be hardcoded and use `core.abbrev` instead (https://git-scm.com/docs/git-config#git-config-coreabbrev)

**Environment you encounter the issue:**
current master

Affected API (not complete list):
* GitRevision.ToShortSha

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #4271 

We do a lot of string manipulation. Finding indexes and obtaining substrings can lead to verbose and confusing code, and bugs.

This change introduces a few extension methods for working with strings that leads to clearer code in several places.

- `RemovePrefix`
- `RemoveSuffix`
- `Until`
- `UntilLast`
- `After`
- `AfterLast`

It replaces some older versions of these (`SkipStr`, `SubstringUntil`) with versions that don't special case `null`.

What did I do to test the code and ensure quality:
- Add unit tests 
- Manual tests

Has been tested on:
- GIT 2.18
- Windows 10

### CODE REVIEW

**Comment by drewnoakes** [comment]
I am happy with that. The API would become:

- `RemovePrefix`
- `RemoveSuffix`
- `SubstringUntil`
- `SubstringUntilLast`
- `SubstringAfter`
- `SubstringAfterLast`

**Comment by drewnoakes** [comment]
API updated.

**Comment by RussKie** [comment]
Apologies, it looks like I missed these changes as part of my first review.
Overall I approve most of the changes, however collectively they don't give an impression of "togetherness".

I am happy with 55545bb5baece909112b6f4a872363e4a078ab60 that introduces the advertised changed. However the rest I would like to be separate.

* e2cb243cecca42197a1bd0614dd225aca239fd6f and 51efd24e97a48f780f56ea702c44fa6729cc5c4f deal with `ObjectId` and are unrelated to the string reviews. These relate to #4271 I believe.
* 15531f433fceea2bf7954f81971128d29558d756 deals with `PatchManager` and doesn't feel related.
* 798cd3dc39baf79e4ff7f955d5fea1c738c1e538 is also unrelated
* 84319d9da76527dbc630b1b92a2ab4574addfb9c is unrelated as well

Please raise the above separately.

* 3feff023a0257c91c065828100a51592bcaa6265, 68c3adefe3ce41d5d14f6af6bee4195539ba3b36 and 80e6cd29ecff22acb6051178948c81721f4676a4 are unrelated and non-functional - we can probably push them straight in
047af3b2c5299ea6a2602cc8c9e5521ba541fcbf also looks benign and can just go in.
Or they can be submitted as a "cleanup" PR, which we'll just merge.

I have reservations about d1e0de0d25190327b4332c33d2612d5fe565fba4 - let discuss it separately.

I also have questions about 6f96aac4f0a6d26910d962d7929b9796bf7d9c64 - it feels the method should be deprecated and replaced with `Path.GetExtension()` call. Again a separate discussion from "string review".
There's a possible NRE in there too.

**Comment by drewnoakes** [comment]
The theme here was all around usage of strings. I went through all usages of `Substring` and took the opportunity to reduce code complexity (`StringExtensions` methods) and the number of string usages/allocations (almost everything else).

I'll split this up into new PRs as requested. Some of the commits conflict and I'll just leave them out. For example the `PatchManager` improvements. That class is one of the worst when it comes to string handling, but it's not on any critical execution path. Those changes made my head hurt, so I doubt they're easy to review, and I don't want to go there afresh.

Happy to discuss your questions/reservations in other PRs.

**Comment by RussKie** [comment]
I've cherry-picked `PatchManager` and it was reasonably straight forward with two small conflicts.
I'm happy to look at other conflicts

**Comment by drewnoakes** [comment]
With other parts merged, the parts that conflicted before cherry-picked without issue. Created #5267 and #5268. I think that is everything from here.

**Pull request closed without merging**
