### PR TITLE
GUID conflict for IndexGuid and CombinedDiffGuid

### LINKED ISSUE #5015: Artificial GUID for Staged was set to the same as for CombinedDiff
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
regression from #4988  (still great PR)
The GUID for Staged commit was changed from 1111... to 2222... which is the same as for CombinedDiff.
Checks for Combined Diff failed, for instance RevisionDiff difftool was not allowed for WorkingDir

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
yes

### PR DESCRIPTION
**Pull request by gerhardol**
Handling of CombinedDiffGuid was kept in FileStatusList.
When GUIDs for other artificial GUIDs were changed, the CombinedDiffGuid was not changed

Fixes #5015

Changes proposed in this pull request:
- Move CombinedDiffGuid  to GitRevision

What did I do to test the code and ensure quality:
- Manual tests

Has been tested on (remove any that don't apply):
- Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
I added tests as well. One test currently fails (need to rethrow?), pushing is someone want to review

**Comment by RussKie** [comment]
I'm a little bit concerned about the existing disconnect - we have values declared in `GitCommands/Git/GitRevision.cs` as well as in `Plugins/GitUIPluginInterfaces/ObjectId.cs`...
Can they be somehow consolidated?

**Comment by gerhardol** [comment]
> Can they be somehow consolidated?

I guess the idea was to migrate from GitRevision to ObjectId where needed, starting where ObjectId made most differences.
I added tests that the artificial commits are identical at least in ObjectId and GitRevision.

**Comment by drewnoakes** [comment]
This looks good for merge, in my eyes.

**Pull request merged**
