### PR TITLE
Preserve original byte order mark when editing files

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by sharwell** [comment]
> Is it feasible to have some tests around it?

That's my hope! I was also hoping to use coverage to see what's already covered, but that appears to be none of it 😆

**Comment by sharwell** [comment]
@RussKie Tests are added. Took me a few tries to get them just right. I didn't add complete tests for this form but I added a couple and covered both paths of the new functionality.

**Comment by RussKie** [comment]
> I didn't add complete tests for this form but I added a couple and covered both paths of the new functionality.

It would be totally unreasonable to expect to have full test coverage. But it is good to have tests for the code that changed.
Thank you

**Comment by sharwell** [comment]
@RussKie this code _may_ increase flakiness because it exacerbates a race condition for file save operations, but it's being addressed by #6327.

**Pull request merged**
