### PR TITLE
Tell users they should seek for a similar issue before creating a new one.

### PR DESCRIPTION
**Pull request by jbialobr**

### CODE REVIEW

**Comment by RussKie** [comment]
I like the idea, but I'm not sure about the checkbox - it will generate unnecessary visual noise

**Comment by jbialobr** [comment]
Yes, you are right, now I remember it was already discussed.

**Comment by RussKie** [comment]
@vbjay - for me it is a visual noise.

**Comment by drewnoakes** [comment]
If we're changing the language...

```
If the current behavior is a bug, have you searched [open](https://github.com/gitextensions/gitextensions/issues?q=is%3Aopen) and [closed](https://github.com/gitextensions/gitextensions/issues?q=is%3Aclosed) issues for already reported issues?
```

I think this applies equally to features.

How about just:

```
Have you searched [existing issues](https://github.com/gitextensions/gitextensions/issues?q=)?
```

Another observation is that the link won't be clickable. Maybe it's easier to just have:

```
Have you searched existing issues, both open and closed?
```

**Comment by vbjay** [comment]
Think of it this way. If it doesn't say 1 out of 1 items checked, you can
now not even open the issue and look at the ones that were checked first.
It's information that helps you review the issues that are more likely to
be done correctly. Then you can tag the issues with non correctly filled
out with a tag like closedxml does. He uses a RTFM tag.

**Comment by jbialobr** [comment]
>Have you searched existing issues, both open and closed?

It suggests 'No' is an option, which it should not be.

**Comment by sharwell** [comment]
💭 I find wording like this discourages new participants for a marginal (at best) reduction in duplicates.

**Comment by jbialobr** [comment]
>I would like to encourage users to test the portable builds from AppVeyor too.

I feel little uneasy with that. The latest build is not tested enough to encourage all to give it a try.

> I find wording like this discourages new participants for a marginal (at best) reduction in duplicates.

Do you suggest removing it at all or change the wording?

**Comment by gerhardol** [comment]
> I feel little uneasy with that. The latest build is not tested enough to encourage all to give it a try.

The suggestion should maybe not be in the template, but somehow more porominent then now - I want more testers then we have now.

> I was not able to find an [open](https://github.com/gitextensions/gitextensions/issues?q=is%3Aopen) or [closed](https://github.com/gitextensions/gitextensions/issues?q=is%3Aclosed) issue matching what I'm seeing

A negated question is confusing to answer, should be changed to the suggestion from drewnoakes.

**Comment by sharwell** [comment]
> Do you suggest removing it at all or change the wording?

No real suggestion, just a weak observation

**Comment by RussKie** [comment]
Shall we roll back?

**Comment by drewnoakes** [comment]
> Shall we roll back?

It's possible to use HTML comments in the template. Check out the change in #4798 for an example of how this might work.

**Pull request merged**
