### PR TITLE
Support for #1664 “View Tag annotations”

### PR DESCRIPTION
**Pull request by new-mikha**
Hi,

Support for showing annotated tags added, see Feature Request https://github.com/gitextensions/gitextensions/issues/1664

Menu added for switching this feature ON and OFF:
image

When it’s ON (the default), the messages of annotated tags displayed in CommitInfo panel:
image

If “Show indicator for multiline messages” setting is ON (this is an old setting, not added by me), then an indicator similar to the standard one is displayed for annotated tags. I.e. not just for multiline annotated tags – but for any annotated tag, to distinguish it from the lightweight ones.

Lightweight tags are still not shown in the CommitInfo panel, and not intended to (apart from the “Contained in tags” list, as usual)
image

### CODE REVIEW

**Comment by ghanique** [comment]
Nice!

**Comment by KindDragon** [comment]
I think better move "Show annotated tags" to commit tab context menu.
Also, maybe useful display annotated tag date/time.

**Comment by new-mikha** [comment]
That's right, looks like a good idea.
Will do.

**Comment by new-mikha** [comment]
>
> I think better move "Show annotated tags" to commit tab context menu.
>
This is done.


> Also, maybe useful display annotated tag date/time.
>
Tag date/time is a bit harder to fetch & arrange for showing, so giving up
on showing it for the moment. Might be will add later.


Is there anything else requiring to be fixed for this pull request?

Cheers,
Michael.

**Comment by new-mikha** [comment]
Hi @KindDragon & all,

Any news on this pull request? I think I did all required changes? Please let me know if anything else is needed.

Cheers.

**Comment by new-mikha** [comment]
Hi @KindDragon, @jbialobr, @x2764tech, @sharwell ,

Sorry for bothering all of you guys with that - but could any of you please let me know if this pull request can be merged & what do you expect from me for that?

I merged it yesterday with the latest changes from your master, and earlier did everything Arkady asked for. Is there anything else I need to do?

Thanks, I would appreciate this feature to be added to the master.

Cheers,
Michael.

**Comment by pmiossec** [comment]
Really nice!!
I hope to see it it land in GitExtensions!

**Comment by j-a-b** [comment]
Hi @KindDragon, is there any chance of getting this pull request merged at some point? Viewing tag annotations seems to be one of the few remaining areas of basic git functinonality that GitExtensions doesn't support in any way.

**Comment by magebarf** [comment]
Can only echo wishes by others, any hope of getting this feature merged, @KindDragon?

**Pull request merged**
