### PR TITLE
Issue fix for 5575

### LINKED ISSUE #5575: Diff viewer does not show the current encoding name.
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

gitext

gitext

**What is the expected behavior?**

Both combos should use the same method to get the encoding name.

**Environment you encounter the issue:**

- GitExtensions version: 7c18463730bebfcfdabf29c8ac150b93aa80341c
**Did this work in previous version of GitExtensions (which)?**
Yes: 2.51.4

### PR DESCRIPTION
**Pull request by AbhiAgarwal192**
Fixes #5575 

Changes proposed in this pull request:
-  Set Encoding value to Default instead of null at startup

 
Screenshots before and after (if PR changes UI):
- None

What did I do to test the code and ensure quality:
- Executed test cases and all passed.

Has been tested on (remove any that don't apply):
- GIT 2.18
- Windows 10

### CODE REVIEW

**Comment by spdr870** [comment]
Can you squash the commits?

**Comment by AbhiAgarwal192** [comment]
This only includes change in one file. Dont know why it is showing this list.

**Comment by RussKie** [comment]
image

Please base the change on top of the master and not on top of other branches.

**Comment by gerhardol** [comment]
@AbhiAgarwal192 
Please fetch gitextensions/gitextensions
Reset --hard your branch to gitextensions/master
push --force-with-lease to your repo

**Comment by AbhiAgarwal192** [comment]
Will raise another request.

**Pull request closed without merging**
