### PR TITLE
Add `BugReporter.exe` to installer

### PR DESCRIPTION
**Pull request by mstv**
Related to #9166

## Proposed changes

- Add `BugReporter.exe` to installer

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build fec693532c9cc0e23e0e91c841b9a343c64f86c2
- Git 2.31.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.7.2633.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]
So this will be cherrypicked to master?

This explains why there are so few NBug for 3.5...

**Comment by mstv** [comment]
> So this will be cherrypicked to master?

IIUC, the installer will be replaced for .NET 5.0.
BTW: Is there a shorter abbreviation which is easier to type?

> This explains why there are so few NBug for 3.5...

Only uncaught exceptions from background threads are affected.

**Comment by RussKie** [comment]
OMG facepalm.... 
Thank you!

**Comment by RussKie** [comment]
I don't believe there is a config.... Is there?

**Comment by mstv** [comment]
Juliette mentioned `BugReporter.exe.config`, and yes, it is copied to several artifacts folders.

**Comment by mstv** [comment]
@RussKie:
1. There is created a `BugReporter.exe.config`. In my test install, it works without. Should I add it to the 3.5 installer yet?
2. For .NET 5.0, I presume the planned installer adaption will include `BugReporter.*`, too. Or else should I prepare a PR for master?

**Comment by RussKie** [comment]
Sorry. Yes, I had a look, the config is probably needed - it has the
binding redirects.

In .NET redirects are stored in runtime.configs IIRC. We'll cross that
bridge when we get there.

**Pull request merged**
