### PR TITLE
Add winget

### PR DESCRIPTION
**Pull request by DavideDunne**
Replace Appget with Winget as first one is no longer maintained

### CODE REVIEW

**Comment by gerhardol** [comment]
But WinGet only have versions up to 4.0.2, to my knowledge the GitExtensions team is not involved at all.
Remove the link instead?

**Review by pmiossec — APPROVED** [review]

**Comment by pmiossec** [comment]
> But WinGet only have versions up to 4.0.2, to my knowledge the GitExtensions team is not involved at all. 

Work seems to have been done for the last version ( https://github.com/microsoft/winget-pkgs/pull/109318 ) but for a reason it is not available...

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
> But WinGet only have versions up to 4.0.2, to my knowledge the GitExtensions team is not involved at all. Remove the link instead?

This is an external distribution channel (similar to the Chocolatey), I think it's worth having it - it's giving an option to users.

**Comment by RussKie** [comment]
Thank you!

**Pull request merged**
