### PR TITLE
WIP: Added subproject for Gitlab CI integration

### PR DESCRIPTION
**Pull request by gpongelli**
## Proposed changes

- Add Gitlab CI into Build server integration #3584 

### Before
immagine

### After

immagine

The UI is work in progress yet, I'm not sure which way is better, I add some comment related to this.

## Test methodology 

- actually with manual test using private Gitlab CI server

## Test environment(s) 

- GIT 2.20.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gpongelli** [comment]
During my tests, the only working way to correctly receive answers from the Gitlab server is to use the [personal access tokens](https://docs.gitlab.com/ee/api/README.html#personal-access-tokens).

Trying to use [other kind of tokens (like Bearer one)](https://docs.gitlab.com/ee/api/oauth2.html) to get a plugin like already existing, led to "unauthorized" answer by the server.

Seems that the personal access token is an authentication way that works in most cases.

Ps 
how can I clear the credentials inserted during debug/test phase ? I cannot clear what the BuildServerWatcher had stored.

Thanks,

**Comment by gerhardol** [comment]
Edit GitExtensions.settinges

**Comment by RussKie** [comment]
@maraf @mast-eu this plugin may be a perfect candidate for a split straight off the bat.
Do you think there is much involved?

**Comment by maraf** [comment]
I think it will be pretty easy transforming this into nuget-based.
Just base the code on [GitExtensions.EmptyPlugin](https://github.com/maraf/GitExtensions.EmptyPlugin).

**Comment by RussKie** [comment]
@gpongelli we're planning to move all plugins out of the main repo to simplify the management of both the main repo and plugins, as well as to decouple and allow different release schedule for plugins.

The plan is for each plugin author to maintain their plugins, publish them to a NuGet gallery (be that nuget.org or not), and them users will discover plugins and install them via [GitExtensions.PluginManager](https://github.com/gitextensions/gitextensions.pluginmanager).

@maraf  and @mast-eu  are driving the initiative.

Could you please work together to convert this work into a plugin. 
You will be one of the first on this journey (along with Marek and Martin), and there likely be some nuances and annoyances along the way, but at the same time your input and feedback will help to shape the experience.

**Comment by maraf** [comment]
@gpongelli Ping me any time, I would gladly help.

**Comment by RussKie** [comment]
@gpongelli <https://github.com/gpongelli> do you want us to create a repo
in GitExtensions org or in your repo?

**Comment by gpongelli** [comment]
Hi @maraf @RussKie,
I didn’t know of plug-in refactoring.
It’s an interesting way to let things work correctly and decoupling the plugin development flow can led only benefits for GE roadmap.
I’ve seen something about the PluginManager project, I think I’ll ask many dumb questions here in near future about it, how it fits with GE, about the new plugin development style and maybe discuss about PM new features.

Now, I’m new to all the changes GE had since my last PR, I’m new also on GE plugin side and on NuGet package creation and its deployment (I hope that some steps can be automated).

Just for information, at the actual state this PR does not work :) I’ve published it to notify you that someone is trying to create a gitlab ci plugin :)

**Comment by mast-eu** [comment]
@gpongelli : Great to hear about your GitLab plugin. By the way, I have a GitLab CE server at work, so I am quite interested :smile: 

I'll point you to the relevant pieces of information for the plan that @RussKie  and @maraf mentioned.
The overall plan is in #6542 . As you can see, we're still at an early stage too.

@maraf created https://github.com/gitextensions/gitextensions.pluginmanager, which is the key element for moving plugins out of the main repo. This will allow plugin-authors, like you, to work independently from GE's release schedule.

@maraf is also the creator of https://github.com/maraf/GitExtensions.EmptyPlugin which is a template to creating GE plugins in an own repo.
It has already been used for https://github.com/maraf/GitExtensions.BundleBackuper, https://github.com/maraf/GitExtensions.SolutionRunner and https://github.com/mast-eu/GitExtensions.SVN.

If you're interested, the next steps would be:
1. Wrap your plugin in, also it's current state, with GitExtensions.EmptyPlugin and push it to it's own repo
2. Make it work :smirk: 
3. Publish a NuGet package and let GE users discover it through the PluginManager, which will be fully integrated in the meantime

Obviously, since it is all work in progress, we will walk this road together and you can count on our help.
Actually, we would be very interested in your feedback as well:
* What needs to be documented to help plugin authors?
* What kind of problems did you encounter when working on your plugin?
* What could be improved?
* Etc

**Comment by maraf** [comment]
@gpongelli We are also new to this and gaining experiences. 

Try to start with mentioned EmptyPlugin. It's a minimal repository to develope separated plugin. When you hit F5, it should download portable GE, copy plugin dll from bin and start GE.

**Comment by RussKie** [comment]
Btw gents we need to migrate the EmptyPlugin repo to our org as well.

@gpongelli <https://github.com/gpongelli> there are stupid questions -
there are stupid answers 😎
So any questions are welcome.
We'll all learn along the way.

**Comment by maraf** [comment]
@RussKie when I get to PC I will transfer it.

**Comment by gpongelli** [comment]
> @gpongelli <https://github.com/gpongelli> do you want us to create a repo in GitExtensions org or in your repo?
> […](#)

I think that some choice&rules should be made, depends on how do you want to organise this decoupling and the people’s role on each plugin development. 
Do you prefer that “official” plugin (like maybe the already existing ones or other you’ll decide) will be developed into GitExtensions org, while other “less official” will be developed in private repos (and maybe then migrated into organisation)?
Or every plugin should be under GE organisation? 
Or the plugin development should be “always free and independent” from GE organisation ?
Do you think that plugin into GE organisation should be “always maintained”, also by whom did not the first release?
I think that having a clear idea on those question can be useful to understand where to put the repo.
Regards.

**Comment by gpongelli** [comment]
> @gpongelli : Great to hear about your GitLab plugin. By the way, I have a GitLab CE server at work, so I am quite interested 😄
> 
> I'll point you to the relevant pieces of information for the plan that @RussKie and @maraf mentioned.
> The overall plan is in #6542 . As you can see, we're still at an early stage too.
> 
> @maraf created https://github.com/gitextensions/gitextensions.pluginmanager, which is the key element for moving plugins out of the main repo. This will allow plugin-authors, like you, to work independently from GE's release schedule.
> 
> @maraf is also the creator of https://github.com/maraf/GitExtensions.EmptyPlugin which is a template to creating GE plugins in an own repo.
> It has already been used for https://github.com/maraf/GitExtensions.BundleBackuper, https://github.com/maraf/GitExtensions.SolutionRunner and https://github.com/mast-eu/GitExtensions.SVN.
> 
> If you're interested, the next steps would be:
> 
> 1. Wrap your plugin in, also it's current state, with GitExtensions.EmptyPlugin and push it to it's own repo
> 2. Make it work 😏
> 3. Publish a NuGet package and let GE users discover it through the PluginManager, which will be fully integrated in the meantime
> 
> Obviously, since it is all work in progress, we will walk this road together and you can count on our help.
> Actually, we would be very interested in your feedback as well:
> 
> * What needs to be documented to help plugin authors?
> * What kind of problems did you encounter when working on your plugin?
> * What could be improved?
> * Etc

Hi @mast-eu,
Thanks for the useful information!
Just to know, how new plugin’s settings will be displayed into GitExtension ? 
Like now into the same menu? 
Or the plugin should create it’s own separated modal window to be opened from GE through menu call? 
Then, how about plugin’s settings storage? 
The BuildServerIntegration will be moved outside GE or not? 
Thanks.

**Comment by mast-eu** [comment]
> > @gpongelli <https://github.com/gpongelli> do you want us to create a repo in GitExtensions org or in your repo?
> > […](#)
> 
> I think that some choice&rules should be made, depends on how do you want to organise this decoupling and the people’s role on each plugin development. 

Glad you ask. I wrote my thoughts about this in https://github.com/gitextensions/gitextensions.extensibility/issues/3
Let's continue discussion of this aspect there.

**Comment by gpongelli** [comment]
Hi @mast-eu
I know that my questions are wider than this PR’s scope, they belong to the “many dummy question” I wrote above :) 
From my previous comment you can open as many discussion as you want, to cover all of my questions.
I’ll write on that discussion.

**Comment by mast-eu** [comment]
> Just to know, how new plugin’s settings will be displayed into GitExtension ?
> Like now into the same menu?

This is actually one of the things we still need to work out.

> Or the plugin should create it’s own separated modal window to be opened from GE through menu call?

This would probably be the cleanest way. Each plugin would be self-contained.
For example the PluginManager already has it's own settings menu. The GE core app itself doesn't even "know" about it.

> Then, how about plugin’s settings storage?

Another open point :grin: . There was some (old) discussion in #5797.
Again, I'd say that ideally each plugin should be self contained and manage it's own settings.
From the PluginManager's perspective we want to put each plugin into one subdirectory. Inside there, you should have free choice to put what you want. Want to bloat your plugin with tons of dependencies? Go for it, but keep them in your subdir. Think you'll need SQLite instead of XML for your settings? Fine, put it in your subdir.
Similar to how PortableApps does it.

> The BuildServerIntegration will be moved outside GE or not?

Technically they are plugins too. I forgot about them when I wrote #6542 , nice catch. I'll add them now.

**Comment by gpongelli** [comment]
> > Just to know, how new plugin’s settings will be displayed into GitExtension ?
> > Like now into the same menu?
> 
> This is actually one of the things we still need to work out.
> 
> > Or the plugin should create it’s own separated modal window to be opened from GE through menu call?
> 
> This would probably be the cleanest way. Each plugin would be self-contained.
> For example the PluginManager already has it's own settings menu. The GE core app itself doesn't even "know" about it.
> 

It’s cleanest, but how many new menu items into the GE gui ?

> > Then, how about plugin’s settings storage?
> 
> Another open point 😁 . There was some (old) discussion in #5797.
> Again, I'd say that ideally each plugin should be self contained and manage it's own settings.
> From the PluginManager's perspective we want to put each plugin into one subdirectory. Inside there, you should have free choice to put what you want. Want to bloat your plugin with tons of dependencies? Go for it, but keep them in your subdir. Think you'll need SQLite instead of XML for your settings? Fine, put it in your subdir.
> Similar to how PortableApps does it.
> 

Dependencies is another interesting topic.
About settings, I think that could be easier to offer some API that can be called like the one existing now, so plugin’s developer can use something already knows and works.
If the plugin dev wants, it remain possible to use a database to store settings under subfolder, but the fastest way is to use GE’s settings.
It also facilitate the job to whom will review plugin’s code to decide if promote as “core plugin” or not.

> > The BuildServerIntegration will be moved outside GE or not?
> 
> Technically they are plugins too. I forgot about them when I wrote #6542 , nice catch. I'll add them now.

Is it possible to have BuildServerIntegration as plugin’s dependency? 
Because it’s a working mechanism that will be used by this PR too.

**Comment by maraf** [comment]
> About settings, I think that could be easier to offer some API that can be called like the one existing now, so plugin’s developer can use something already knows and works.

In BundleBackuper I'm using standard GE settings in [PluginSettings.cs](https://github.com/maraf/GitExtensions.BundleBackuper/blob/master/src/GitExtensions.BundleBackuper/PluginSettings.cs) and it works like a charm.

**Comment by maraf** [comment]
> > About settings, I think that could be easier to offer some API that can be called like the one existing now, so plugin’s developer can use something already knows and works.
> 
> In BundleBackuper I'm using standard GE settings in [PluginSettings.cs](https://github.com/maraf/GitExtensions.BundleBackuper/blob/master/src/GitExtensions.BundleBackuper/PluginSettings.cs) and it works like a charm.

> Is it possible to have BuildServerIntegration as plugin’s dependency?
> Because it’s a working mechanism that will be used by this PR too.

In final solution yes, but until core plugins will be moved out, they will be distributed with GE and no nuget dependency will be required.

**Comment by RussKie** [comment]
Sorry gents, whilst this discussion is immensely valuable, it has gone off topic.
Let's move it to the https://github.com/gitextensions/gitextensions.extensibility repo.

**Comment by RussKie** [comment]
@gpongelli is this something you still wish to pursue?

**Comment by gpongelli** [comment]
Hi Igor,
I don’t know if this patch will correctly work after the recent changes on master branch.
There still are issue already reported about cygpath slashes changed between releases.

**Comment by RussKie** [comment]
Alright, closing it then.
Please ping back if you change your mind.

**Pull request closed without merging**
