### PR TITLE
Browse Diff: No refresh of the index after reset for artificial commits

### PR DESCRIPTION
**Pull request by gerhardol**
As seen in #4031 .

Changes proposed in this pull request:
 - Refresh revisions after reset is not always done. This affects primarily artificial commits, that may need update after these operations
 
Screenshots before and after (if PR changes UI):
- None

How did I test this code:
 - View virtual commits
 - Command -> "Reset changes...", so it affects artificial commits
 - The revision grid is updated (i.e. removing "Current unstaged changes" if only files were modified.)
Note that there are several bugs and limitations for the reset and other options, handled in other pull requests. The reset from the Diff tab was previously refreshing, change removed after refactoring in master.

Has been tested on (remove any that don't apply):
 - GIT 2.14 (not affecting Git interface)
 - Windows 7 and Win 10

### CODE REVIEW

**Comment by gerhardol** [comment]
After the refactoring of RevisionDiff, the primary change due to this PR is no longer possible without further changes.
Resetting in the diff tab can no longer refresh the contents and "arificial commits in Revision Grid" (with a call to RefreshRevisions). I will probably wait with such a change, there are other PRs pending.

**Comment by RussKie** [comment]
> Refresh revisions after reset is not always done.

Could you describe which conditions do not cause the refresh?

**Comment by gerhardol** [comment]
For instance, if you have modified one file only and reset it to HEAD, the artificial commit is not updated.
The diff panel is not updated either.
With the current setup that staged/unstaged are only shown if there are staged/unstaged changes (this should be changed in my opinion, will wait with a PR until other PRs are merged), this is not reflected in the revision grid. (If the staged/unstaged are always shown only the diffpanel may need an update though.)

There are a lot of other situations where the refresh is needed. Due to the RevisionDiff refactoring a new "hook" is needed.

**Comment by RussKie** [comment]
> Due to the RevisionDiff refactoring a new "hook" is needed.

Could you please indicate the order of PRs to be reviewed and merged? Right now there are 6 open PR and I'm finding it hard to review them because of inter dependencies. Perhaps temporarily decline PRs which are sitting on top of or blocked by other PRs, so we can concentrate on the blockers first.

**Comment by gerhardol** [comment]
> Could you please indicate the order of PRs to be reviewed and merged?

I updated #4031 Everything is not done yet, improvement step by step

**Comment by gerhardol** [comment]
Dropping this PR, see #4086 that refers to #4031

**Pull request closed without merging**
