### PR TITLE
Correctly select destination remote branch

### LINKED ISSUE #11899: "Replace tracking reference" doesn't work on the Push dialog
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

The "Replace tracking reference" checkbox doesn't have any effect.
image

### Steps to reproduce

- Open the push dialog
- Check "Replace tracking reference"
- Modify the "to" branch to something else
- Push
- Open the push dialog again

The "to" branch returns to the original value instead of the modified one

### Did this work in previous version of GitExtensions?

Yes Version 4.2.1 

### Diagnostics

It creates the following command:
"C:\Program Files\Git\bin\git.exe" push -u --progress "origin" refs/heads/work1:refs/heads/other

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #11899

## Test methodology 

- manual

## Test environment(s) 

- GIT 
- Windows 

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
@patiqs, @Tinister, does https://ci.appveyor.com/api/buildjobs/2quxk06ca9khvm9h/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-3584cbbae.zip work for you?

**Comment by RussKie** [comment]
> It is not enough and this change introduce another not wanted side effect. I have an improved fix and will like to create a PR soon.

Could you please elaborate?

**Comment by Tinister** [comment]
FWIW, the build linked above fixed my issue.

**Comment by patiqs** [comment]
> @patiqs, @Tinister, does https://ci.appveyor.com/api/buildjobs/2quxk06ca9khvm9h/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17932-3584cbbae.zip work for you?

That works. Thank you

**Comment by RussKie** [comment]
Closing in favour of #11954.

**Pull request closed without merging**
