### PR TITLE
Add `git worktree` feature

### PR DESCRIPTION
**Pull request by pmiossec**
https://git-scm.com/docs/git-worktree

### CODE REVIEW

**Comment by pmiossec** [comment]
I will be VERY happy if someone could tell me how to not display an image in a `DataGridViewImageColumn` cell!

**Comment by KindDragon** [comment]
Whether these changes are related with #2526 or #3212?

**Comment by vbjay** [comment]
Blank image set to the same color as the background color of the cell?

**Comment by pmiossec** [comment]
@KindDragon This commit add 2 forms to manage git worktrees in GitExtensions. So it is the same feature than used in #3212 but do not fix this issue...

**Comment by pmiossec** [comment]
I have updated the pull request and fixed the remaining stuff I wanted to do.

That's ok for me and with it we could now handle git worktrees with GitExtensions...

**Pull request merged**
