### PR TITLE
Wait for threads being finished.

### PR DESCRIPTION
**Pull request by jbialobr**
Threads accessed the barrier after its disposal causing ODE.

A test should wait for async work being completed before performing assertions. 
Perhaps it should use tasks and https://github.com/Microsoft/vs-threading/blob/81db9bbc559e641c2b2baf2b811d959f0c0adf24/src/Microsoft.VisualStudio.Threading/AsyncBarrier.cs in order to not duplicate awaiting for completion and rethrowing exceptions logic.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Maybe simpler to use tasks rather than threads.

```diff
diff --git a/UnitTests/GitUITests/CancellationTokenSequenceTests.cs b/UnitTests/GitUITests/CancellationTokenSequenceTests.cs
index 6993e489a..efc862f0e 100644
--- a/UnitTests/GitUITests/CancellationTokenSequenceTests.cs
+++ b/UnitTests/GitUITests/CancellationTokenSequenceTests.cs
@@ -1,6 +1,8 @@
 ﻿using System;
 using System.Diagnostics.CodeAnalysis;
+using System.Linq;
 using System.Threading;
+using System.Threading.Tasks;
 using GitUI;
 using NUnit.Framework;

@@ -108,7 +110,7 @@ public void Dispose_does_not_throw_if_no_token_yet_issued()

         [Test]
         [SuppressMessage("ReSharper", "MethodSupportsCancellation")]
-        public void Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued()
+        public async Task Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued()
         {
             const int loopCount = 10000;

@@ -130,18 +132,20 @@ public void Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_be
                 var completionToken = completionTokenSource.Token;
                 var winnerByIndex = new int[coreCount];

-                for (var i = 0; i < coreCount; i++)
-                {
-                    new Thread(ThreadMethod).Start(i);
-                }
+                var tasks = Enumerable
+                    .Range(0, coreCount)
+                    .Select(i => Task.Run(() => Actor(i)))
+                    .ToList();

                 Assert.True(countdown.Wait(TimeSpan.FromSeconds(10)), "Test should have completed within a reasonable amount of time");

                 Assert.AreEqual(loopCount, completedCount);

-                Console.Out.WriteLine("Winner by index: " + string.Join(",", winnerByIndex));
+                await Console.Out.WriteLineAsync("Winner by index: " + string.Join(",", winnerByIndex));
+
+                await Task.WhenAll(tasks);

-                void ThreadMethod(object o)
+                void Actor(int i)
                 {
                     while (true)
                     {
@@ -159,7 +163,7 @@ void ThreadMethod(object o)
                         if (!token.IsCancellationRequested)
                         {
                             Interlocked.Increment(ref completedCount);
-                            Interlocked.Increment(ref winnerByIndex[(int)o]);
+                            Interlocked.Increment(ref winnerByIndex[i]);
                         }

                         if (countdown.Signal())
```

**Comment by jbialobr** [comment]
With tasks it looks simpler. Can you create a PR with such a change?
Note, that we should await before asserting:
```
await Task.WhenAll(tasks);
Assert.AreEqual(loopCount, completedCount);
```

**Comment by drewnoakes** [comment]
> Can you create a PR with such a change?

Sure. done.

**Comment by jbialobr** [comment]
Thanks!

**Pull request closed without merging**
