### PR TITLE
fix(Editor): Adapt selection length on replace

### LINKED ISSUE #12084: fileditor find+replace with selection replaces line after selection too
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.11
- DPI 192dpi (200% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The find and replace feature of the built-in file editor replaces any match in the line after the end of the selection

### Steps to reproduce

In the builtin fileeditor, for instance during an interactive rebase:
1. Select a portion of lines in the text except the last 2 lines.
2. CTRL+H to open the find and replace dialog
3. Find "pick" and Replace all by "d"

Expected:
4. All "pick" matches in the selected lines and only these are replaced by "d".

Actual:
4. All "pick" matches in the selected lines are replaced by "d", but is also replaced in the line after the selection.

### Did this work in previous version of GitExtensions?

🤷‍♂️ I just started using the find and replace dialog.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12084

## Proposed changes

- `Editor/FindAndReplaceForm`: Adapt selection length on replace

## Screenshots 

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
The Find function has a minor bug yet: It does not find a match at the very end of the selection (if it does not include the final line end). I will not fix this myself. The reported use case is not affected.
"Replace all" needs a multi-line selection anyway.

**Review by RussKie — APPROVED** [review]
Do we have any tests for this dialog?

**Review by gerhardol — APPROVED** [review]
I failed to reproduce and thereby verifying this change until I realized that original text must be longer than the new text  and the length include the text to replace.

**Comment by mstv** [comment]
> Do we have any tests for this dialog?

The question whether to replace the editor control was raised not only once.
A new control should come with tests.

**Pull request merged**
