### PR TITLE
Feature/authordateorder

### LINKED ISSUE #6826: Can I see commits ordered by author-date instead of commit-date?
## Current behaviour

I have a project with a long history which has recently been rebased. The project has several branches. 

In the main GUI window, it looks like the commits are being displayed based on commit-date order rather than author-date order. In particular, there are two branches which were developed in parallel. After rebasing, I don't see the a 'tic-toc' commit pattern; it looks like the branches were developed serially. 

In the screenshot, a commit authored **1 month ago** is rendered below a commit authored **1 year ago**. For this project, it would be helpful if the commits appeared in chronological-by-author-date.

## Expected behaviour
I expected to see commits happening on two branches in an interleaved manner. 

## Steps to reproduce
Commit a long, linear Git history of development. Rebase development-history to have several branches originating from a common ancestor, rather than a linear progression.

## Screenshots

Screenshot

## Did this work in previous version of GitExtensions
Not as far as I know. This is more of a help-request, not necessarily a bug.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by asfarley**
Fixes #6826 

## Proposed changes

Add option to sort commits in main view by author-date, rather than bycommit-date. Option is selectable as a checkbox under Appearance settings.

### Before
TBD

### After
TBD

## Test methodology 
Tested on one repository where author-date varies from commit-date.

## Test environment(s) 
I'll fill this out later - I am submitting the PR on a different machine from where I did the development and testing.

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by asfarley** [comment]
Woops, I will fix up the merge issue and resubmit so that all checks pass.

**Comment by pmiossec** [comment]
No need to close the PR.
Just prefix the title with 'WIP:' and update it as often as you need by pushing new commits.

Also, is there a specific reason to have put the option in a setting page (not easily switched on and off) instead in the 'View' menu where it is more discoverable and quickly enabled?

**Comment by RussKie** [comment]
The setting will (likely) need to exist in both places

**Comment by asfarley** [comment]
> No need to close the PR.
> Just prefix the title with 'WIP:' and update it as often as you need by pushing new commits.
> 
> Also, is there a specific reason to have put the option in a setting page (not easily switched on and off) instead in the 'View' menu where it is more discoverable and quickly enabled?

Sorry, I closed the PR and then was unable to reopen it, I think because I rebased after submitting. Anyway, a seperate PR with the suggested changes has been submitted.

**Comment by asfarley** [comment]
Hi, I'm not sure how to resolve this; seems like your build system wants some localization or translation of the strings I added. What mechanism is used for localization?

**Pull request closed without merging**
