### PR TITLE
Newer language features

### PR DESCRIPTION
**Pull request by drewnoakes**
Changes proposed in this pull request:
 - Following #4475 (and to some extent #4479) this PR contains several changes that take advantage of newer C# features
 - Some other minor fixes such as spelling mistakes are also included
 - Some perf changes such as:
    - replacing string concat with `StringBuilder` 
    - making methods static where possible
    - replacing lambdas with method groups
 - See the individual commit summaries for info
 - Overall reduction of 2,378 LOC
 
What did I do to test the code and ensure quality:
 - Applied changes systematically, using R# where possible for automation
 - Ran unit tests
 - Ran manual tests
 - Kept changes isolated between commits to aid review
 - Standardised approach to type naming (use C# alias where possible)

Has been tested on (remove any that don't apply):
 - GIT 2.16
 - Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
A lot of changes to review....
I have only reviewed briefly, the changes make sense.

Before inclusion, the "Community" needs to decide if VS2017 only is the way to go.
(In reality, it is @RussKie that is deciding everything right now.)

> making methods static where possible

This will likely not be accepted, RussKie is a strong proponent of SOLID classes

**Comment by RussKie** [comment]
The diff is massive... I'm worried of merge conflicts in pending PRs....

>  Before inclusion, the "Community" needs to decide if VS2017 only is the
way to go.
(In reality, it is @RussKie <https://github.com/russkie> that is deciding
everything right now.)

LOL. I am following your lead in this question. Personally I am leaning
towards VS2017, but if contributors desire 2015 support I am not against it.

>  making methods static where possible

I have no dramas with private static methods, but I don't like public
statics because they make dependency injection and behaviour replacement
impossible.

**Comment by gerhardol** [comment]
> LOL. I am following your lead in this question. Personally I am leaning
towards VS2017, but if contributors desire 2015 support I am not against it.

I cannot do more:
Using C#7 requires updates of Build Tools and the separate NuGet package for VS2015. That will add some maintenance, also for master.
I did not manage to build from the VS2015 GUI, the override for Build Tools 2017/15 did not work. I could build from the command line though, but I have 2017 installed.
It is possible for me to uninstall VS2017 to test at least command line build, I prefer not to. 
AppVeyor builds will not work for 2015 (unless Build Tools 15 can be installed separately).

I say go with VS2017.

About this: Yes, there will be conflicts, but this is "good" so maybe it should be prioritized?
A review of this size will however always be overview, we have to rely on tests and usage.
(For this PR I prefer a merge commit, not a squash merge to see the individual commit messages...)

**Comment by drewnoakes** [comment]
Fixed conflicts.

I understand the pros/cons of this PR. Please decide one way or another. If there are some commits you'd like to remove, that's fine too (and why I structured it like this).

**Comment by gerhardol** [comment]
I want to see if there are any significant arguments against VS2017 and maybe testing with VS2015 a little before deciding that C#7 is the way to go.
This PR will take some time to review too. But I would like to include this PR: It is a step forward.

**Comment by drewnoakes** [comment]
@gerhardol no worries. If you do want to merge in future I may be able to resolve any conflicts that arise in the meantime. Obviously, the longer that takes, the less feasible it becomes. Thankfully the fixes here are all optional, so it's always safe to take the version from master when rebasing.

A little background from my side too. I initially started out looking at ways to reduce flicker in the UI. For example, in the `CommitInfo` view. I noticed a fair few low-hanging performance things and started going through them. I am still looking at `CommitInfo` and will put any functional changes on a separate PR.

ReSharper has suggested a lot of these fixes automatically. I know it's not for everyone, but it is possible to [apply for licenses for open source contributors](https://www.jetbrains.com/buy/opensource/).

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/blob/master/README.md

**Comment by gerhardol** [comment]
> ReSharper has suggested a lot of these fixes automatically. I know it's not for everyone, but it is possible to apply for licenses for open source contributors.

All licenses are used up. I tried to get JetBrains extend the number but they turned that down. (No grudge against them, nice to offer licenses.)

Otherwise, the changes are appreciated, but still need to be reviewed. It would be nice if someone else than RussKie (and me) did a review, even if just partial.

**Comment by RussKie** [comment]
Wow 87 commits...
Do you think we can break the commit into smaller "thematic" commits?
E.g. a single commit which removes redundant code, unused methods and properties, unused variables etc; another for local functions etc....
This will make it easier to review and merge

**Comment by RussKie** [comment]
@jbialobr do you have any objections to completely moving off VS2015 to VS2017?

**Comment by RussKie** [comment]
> A little background from my side too. I initially started out looking at ways to reduce flicker in the UI. For example, in the CommitInfo view. I noticed a fair few low-hanging performance things and started going through them. I am still looking at CommitInfo and will put any functional changes on a separate PR.

Yes, please raise it as a separate issue / fix.
I have my own stale commit on my fork where I looked at uplift/refactor of the UI. Back then Mono was the major sticking point.... Time permitting I'd like to revive that work (in some shape or form)

image

**Comment by jbialobr** [comment]
> @jbialobr do you have any objections to completely moving off VS2015 to VS2017?

No, I don't.

**Comment by drewnoakes** [comment]
If there are specific commits you want removed, I am happy to edit them out. Even going through interactively and squashing some of these commits flagged up internal conflicts, so breaking it up into different PRs sounds good in theory but I'm not going to find the time to do it in practice. If someone else fancies doing so, of course that's fine by me.

@RussKie thanks for sharing the UI work. I've advocated elsewhere for doing something similar to what gitk does and merging the commit, tree and diff tabs into one view that gives you all the information you need in one place. For reviewing commits, I don't know a UI that's better than gitk. In fact, it would be very well suited to reviewing this PR's commits. In particular, the fact that the commit message and diff are visible in one view, and that the diffs of all files are shown out in one big list, as happens on GitHub or on the command line. Having to click on each file to see its changes just takes too long.

image

**Pull request closed without merging**
