### PR TITLE
Improve SynchronizedProcessReader performance

### PR DESCRIPTION
**Pull request by drewnoakes**
Changes proposed in this pull request:

 - Replace creation of two new threads for each external process, instead scheduling lightweight `Task`s on the thread pool. Creating threads is a relatively costly operation and they serve no purpose here that cannot be served by tasks.
 - Use `StreamReader.ReadToEndAsync` and `Stream.CopyToAsync` to take advantage of async IO (completion ports, etc) provided by the underlying platform.
 
What did I do to test the code and ensure quality:
 - Document changed API methods.
 - Reduce the amount of code.
 - Contain the changes to one class, allowing for easier review. There should be no visible change outside of this class, other than things running faster and using fewer kernel resources.

Has been tested on:
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you

**Comment by jbialobr** [comment]
The UI freezes frequently for 5 to 10 seconds after this change.
It seems that git command run from the UI thread waits for the result to be read async by a task. The task waits to be scheduled but due to many other tasks being scheduled before, it has to wait for its turn freezeing the UI.

**Comment by RussKie** [comment]
Thanks Janusz

**Comment by drewnoakes** [comment]
The previous code also waited on the UI thread for the async operation to complete by joining the threads.

A better solution would be to never call `Wait` on tasks on the UI thread, and instead to use more `async` code to keep things responsive.

I haven't seen such lengthy freezes on my machine. I wrapped the code before/after in stopwatch timing and saw it drop about 20%, but it was regularly around 100ms.

You mention other tasks being scheduled. Do you know what these are?

**Comment by jbialobr** [comment]
I think they are related to Jenkins integration plugin.

**Comment by RussKie** [comment]
Do we need/want to rollback?

**Comment by jbialobr** [comment]
>The previous code also waited on the UI thread for the async operation to complete by joining the threads.

Yes, but that took tens of milliseconds. Now it takes seconds because it has to wait for an idle thread.

> A better solution would be to never call Wait on tasks on the UI thread, and instead to use more async code to keep things responsive.

I have to disagree. That way we loose control on priorities. When the number of threads to be used is limited we risk that less important tasks will be running while more important ones have to wait.

I will revert this PR as the GE is now unusable.

**Comment by drewnoakes** [comment]
Can you help me to reproduce this situation on my computer please? I
understand that using the thread pool means giving up priority control, but
the thread pool is usually very large and having all its threads busy is a
bad sign in general, unless the max number is explicitly limited or perhaps
there's a non-default scheduler that introduces its own limits.

In the PR the background take are async so they don't block thread pool
resources when they're not actually doing work. Perhaps there are other
users of the thread pool that are blocking such shared resources and could
be made async themselves, and therefore better citizens. If you can explain
how I might reproduce these slow downs, I am happy to investigate.

**Comment by jbialobr** [comment]
I am able to consistently reproduce a "freez" by:

1. run GE compiled at af78377aab102908a28398acc87e8ae03ac62ad6
2. open GE repository (wait a while until all data is loaded)
3. move mouse over the revisions grid
4. scroll mouse wheel ten times (scroll a good number of rows ~ 40)
5. click (select) any revision on the revisions grid. Now GE freezes.

Let me know if that works for you.

**Comment by drewnoakes** [comment]
@jbialobr, thanks for the detailed steps. I've followed them exactly, but am not seeing any kind of freeze. I've also tried selecting a revision in the grid and holding the down arrow which triggers a lot of activity, but still no freeze. How long would you expect to wait at point 2? I waited two minutes and still couldn't reproduce a freeze.

In this debug session, `ThreadPool.GetMaxThreads` returns 32767 worker threads and 1000 completion port threads. `ThreadPool.GetAvailableThreads` returns 32762 and 999 respectively. I cannot understand how the thread pool would become depleted of threads.

Looking at what's hitting breakpoints in `SynchronizedProcessReader.ReadBytes`, many callers are initiated from an async-capable task, but the APIs invoked between that point and the reading from the stream do not allow the system to function in a properly async fashion. Async code doesn't compose very well, and to take full advantage of it would require quite a few API changes.

I'm currently a server component that does a lot of heavy lifting on a single thread by being careful to never block. I know that if you go all-in on async code, you can get great performance even without a thread pool.

If I can't reproduce this problem, I can't fix it unfortunately. From this debugging I see just how many threads are being created during normal usage, which feels really dirty to me. It just isn't cheap or sensible to create a whole thread for a short-lived bit of asynchrony. Sorting all this out properly will make GE lighter and more responsive.

If you try holding down an arrow key to scroll through revisions, and look at the .NET CLR LocksAndThreads view of Process Hacker or Process Explorer, what values do you get for those perf counters?

I see:

image

On the server I mentioned the queue length never exceeds 1, even when processing thousands of messages a second, async, on a single thread. I suspect this indicates an over-reliance on `QueueUserWorkItem`, but am not sure.

**Comment by RussKie** [comment]
A lot of code has been written prior to .NET providing easy to use async
constructs hence there are a lot of asynchronous calls which are probably
inefficient.
I've noticed running from VS when the application starts there are heaps of
background threads being spawned and completed.

Memory allocation is another big thing - starting the app is causing the GC
to run several times...

**Comment by jbialobr** [comment]
I stopped the debugger and there are a lot of threads. All of them have the same callstack (see below).
https://github.com/gitextensions/gitextensions/blob/453f9b8878a99c1630a4b63f44205919b6115f49/GitUI/UserControls/RevisionGrid.cs#L1891
gitext

Do you have this option enabled? The threads are created only if it is enabled.
gitext

>How long would you expect to wait at point 2?

About 2 secs.

>If you try holding down an arrow key to scroll through revisions, and look at the .NET CLR LocksAndThreads view of Process Hacker or Process Explorer, what values do you get for those perf counters?

I see:
gitext

The CPU usage is around 0.2%, GE does not respond since 1 minute. Queue Length Peak still increases.

**Comment by RussKie** [comment]
I am unable to reproduce the freezing either...
I don't have Jenkins integration though.

**Comment by gerhardol** [comment]
See #4279 for hints about public Jenkins servers.

**Comment by jbialobr** [comment]
The repro steps are for GE repository where there is no Jenkins integration enabled. Jenkins is not needed to get a freeze.

**Comment by RussKie** [comment]
I could not repro it on W10 running in Parallels on a MBP. I will try it on
other PCs I have...

**Comment by drewnoakes** [comment]
@jbialobr awesome, that reproduces the problem on my machine. I will take a look at it when I get a chance. @RussKie did you enable the "Show indicator for multiline message" option? With that enabled once I start scrolling through the revisions it quickly saturates the threadpool.

I'd say the real bug here is related to the fact that this multiline indicator feature saturates the thread pool, blocking all threads. Creating new threads to read process output might avoid the problem, but it's just luck right?

I'll see if we can use this feature as a starting point for more modern async stuff. Converting `ThreadPool.QueueUserWorkItem` to `Task.Run(async () => { ... })` instead (or similar) seems a good starting point.

> A lot of code has been written prior to .NET providing easy to use async constructs

Makes total sense. This project has a lot of history and a commensurate amount of accumulated value. I think it would be interesting to see how easy it'd be to introduce task based asynchrony to a codebase like this incrementally. I've only used it on greenfield stuff before, or in localised corners of an established codebase. Will take a stab as time permits, so long as there's interest. Don't want to make an unmergeable PR ;)

**Comment by drewnoakes** [comment]
Text form of stack, for future reference.

```
GitCommands.SynchronizedProcessReader.ReadBytes(System.Diagnostics.Process process, out byte[] stdOutput, out byte[] stdError) Line 75
GitCommands.GitCommandHelpers.StartProcessAndReadAllBytes(string arguments, string cmd, string workDir, out byte[] stdOutput, out byte[] stdError, byte[] stdInput) Line 326  
GitCommands.GitCommandHelpers.RunCmdByte(string cmd, string arguments, string workingdir, byte[] stdInput, out byte[] output, out byte[] error) Line 339  
GitCommands.GitModule.RunCmdResult(string cmd, string arguments, System.Text.Encoding encoding, byte[] stdInput) Line 603 
GitCommands.GitModule.RunCmd(string cmd, string arguments, System.Text.Encoding encoding, byte[] stdInput) Line 620
GitCommands.GitModule.RunGitCmd(string arguments, System.Text.Encoding encoding, byte[] stdInput) Line 628
GitCommands.CommitDataManager.UpdateCommitMessage(GitCommands.CommitData data, string sha1, ref string error) Line 74 
GitUI.RevisionGrid.LoadIsMultilineMessageInfo(GitCommands.GitRevision revision, int colIndex, int rowIndex, int totalRowCount) Line 1896
GitUI.RevisionGrid.RevisionsCellFormatting.AnonymousMethod__0(object o) Line 1864
```

**Comment by gerhardol** [comment]
I got this once today on a private dev build (without debugger), have not been able to reproduce.

The Browse window initiates a lot of stuff OnActivate, some comments in #4230 
See the Git Command log
A GitStatusMonitor service could be used to find if those commands are really required.
But that is Why services are started, this is about How

**Comment by jbialobr** [comment]
> Will take a stab as time permits, so long as there's interest.

That would be interesting, especially in the context of left panel which I remember tended to freeze on retrieving data directly from a remote server.

**Comment by RussKie** [comment]
I welcome all improvements.
As long as they are in an review-able state and make the codebase cleaner,
leaner, meaner, more maintainable.

On 18 February 2018 at 22:59, Janusz Białobrzewski <notifications@github.com

**Comment by drewnoakes** [comment]
I've made changes based from the revision @jbialobr reported having errors at, and submitted #4501 which makes the code here that blocks on the thread pool async, so the thread pool sees better utilisation. Please continue discussion on that PR.

**Pull request merged**
