### PR TITLE
Git Flow plugin: Fix some combo boxes overlap with labels

### PR DESCRIPTION
**Pull request by linquize**
Git Flow plugin: Fix some combo boxes overlap with labels

### CODE REVIEW

**Comment by Radrik5** [comment]
Please attach before/after screenshots.

**Comment by linquize** [comment]
Before
gitextensions-gitflow-layout1

------

After
gitextensions-gitflow-layout2

**Comment by pmiossec** [comment]
I have successfully tested this PR. It could be merged without problems...

**Comment by pmiossec** [comment]
This fix is really minor. Could we merge it?

**Comment by linquize** [comment]
ping

**Comment by pmiossec** [comment]
@kinddragon I have reviewed it and because it's a minor fix (on something I have developed), I think you could merge it without problem.

**Comment by pmiossec** [comment]
Thanks a lot!

**Pull request merged**
