### PR TITLE
Fix unit test that fails only on CI server

### PR DESCRIPTION
**Pull request by pmiossec**
Test failing: FormCommitTests.Should_display_branch_and_no_remote_info_in_statusbar()

### CODE REVIEW

**Comment by pmiossec** [comment]
@RussKie in fact, it seems good...

**Comment by RussKie** [comment]
Thank you

**Comment by RussKie** [comment]
Bah! It is still failing...
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22439282

I managed to get it to fail running `FormCommitTests` tests repeatedly...

**Comment by RussKie** [comment]
The test failed locally only once and I wasn't debugging...
It kind of feels it is a race condition, where one test checks out a revision whilst this test is expecting to be on master...

**Pull request merged**
