### PR TITLE
Commit info in history form

### PR DESCRIPTION
**Pull request by mdonatas**
Very often when viewing file history I feel the need to see commit info / context when a specific change was made. Opening a commit from a context menu is too slow (too many context switches from UX perspective).

Changes proposed in this pull request:
 - Extract CommitDiff user control from FormCommitDiff
 - Add Commit tab in FormFileHistory and use CommitDiff in it
 - Remove Open Commit context menu item
 - UX bliss :)
 
Screenshots before and after (if PR changes UI):
- Before
image

- After. Notice commit tab in file history
image

Has been tested on (remove any that don't apply):
 - GIT 2.16.1
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
I haven't pulled down and run it, but it looks relatively straight forward in GH

**Comment by mdonatas** [comment]
Currently blocked by #4579 I will rebase after it's fixed.

**Comment by RussKie** [comment]
Looks good. 
It can go in after #4587 goes in. It will likely need to be rebased and tweaked to meet the new requirements.

**Comment by mdonatas** [comment]
Thanks for looking into this and no problem regarding rebase.

**Comment by RussKie** [comment]
Please rebase on top of the master. And it is good to go

**Comment by gerhardol** [comment]
Thanks

**Comment by mdonatas** [comment]
Wow, that was very fast. Thanks @gerhardol :)

**Pull request merged**
