### PR TITLE
Add a hint regarding updates of portable builds

### PR DESCRIPTION
**Pull request by mstv**
## Proposed changes

- add hint to `README.md`

Feel free to tinker / move the text how and where you like it better!

### Before

grafik

### After

grafik

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vbjay** [comment]
Add backup setting and recent repo extensions if desired.

**Comment by vbjay** [comment]
What about plugins?  We may have plugins in plugin manager. I frankly
haven't looked into it but is there a registered plugins file too?  That
way the plugins get re- downloaded.

**Comment by RussKie** [comment]
Thank you

Would it be more appropriate to add to the actual release page, where a user would download a portable version from?
https://github.com/gitextensions/gitextensions/releases/tag/v3.4.2

**Comment by gerhardol** [comment]
I suggest a link from the release page to the readme

**Comment by mstv** [comment]
> What about plugins?

My knowledge about plugins it very limited. Any info?

> Would it be more appropriate to add to the actual release page, where a user would download a portable version from?

We should have it in both places: It applies to dev builds, too.
Is the release page copied automatically when creating a new releases? Or must it be added manually for every release?

> I suggest a link from the release page to the readme.

Yes, it avoids copies, which tend to get out of sync.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
