### PR TITLE
Partly manually convert designer files to newly generated format

### PR DESCRIPTION
**Pull request by pmiossec**
## Proposed changes

Did a manual conversion of all `.Designers.cs` files with no behavior change in the application on the more frequent changes.
**With the goal to make easier the code review for later PRs** (There will still be more or less changes but it's human readable to detect some strange things...)

## Test methodology 

- Compile and run

## Test environment(s) 

- Git Extensions 33.33.33
- Build 7c86a2d6b8f067ef32ff69eea8f809c971876b50 (Dirty)
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash or Rebase merge (I don't really know what is the best in this case) this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
MC. Feel free to merge once resolved

**Review by mstv — APPROVED** [review]
Sorry for the MC. It can easily be resolved by choosing the version from the master branch.

**Review by mstv — APPROVED** [review]
have not run

**Comment by pmiossec** [comment]
> Sorry for the MC. It can easily be resolved by choosing the version from the master branch.

Yes, you're right. The idea is that if we have a conflict on a `.Designer.cs` file on an existing PR during a rebase due to this PR, the action that should be made is to take changes **from the PR rebased and not from this PR**:

image

**Pull request merged**
