### PR TITLE
fix ssh:// with port not working with Putty

### PR DESCRIPTION
**Pull request by SetoKaiba**
fix ssh:// with port not working with Putty

### CODE REVIEW

**Comment by SetoKaiba** [comment]
The Test is wrtten wrong by me. I'll create a new pull request instead.

**Comment by vbjay** [comment]
You don't need to recreate a pull request.  Just add more commits to the
branch your pull request is part of.

**Comment by SetoKaiba** [comment]
I don't know how to add more commits. That's the reason why I create a new pull request. The commits are committed to the branch my pull request.

**Comment by vbjay** [comment]
You just add more commits by committing on that branch and then pushing to
your github repo.

On Fri, Mar 6, 2015 at 12:28 AM, SetoKaiba <notifications@github.com> wrote:

> I don't know how to add more commits. That's the reason why I create a new
> pull request. The commits are committed to the branch my pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/2685#issuecomment-77508927>
> .
>



-- 
*Jay Asbury*
PC Repair and custom programs $30/hr 1hr min
My Biking Blog <http://vbjaybiking.blogspot.com>

**Pull request closed without merging**
