### PR TITLE
Build issue on Windows10 preview and anniversary

### LINKED ISSUE #3316: Cannot build on Windows 10/x64/VS2015
When running `GitExtensions.VS2015.build.cmd`, no installer is generated, I see no errors, just a warning. Some months ago it worked, it is probably because of a Windows update, but I don't know how to fix it.

The warning is:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2398,5): warning MSB3283: Cannot find wrapper assem
bly for type library "stdole". Verify that (1) the COM component is registered correctly and (2) your target platform is the same a
s the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit. [D:\prog\
gitextensions\GitPlugin\GitPlugin.csproj]
```

The log ends like this:
```
  \prog\gitextensions\GitExtensions\\..\Plugins\BuildServerIntegration\TfsInterop.Vs2013\bin\Release\TfsInterop.Vs2013.pdb
  1 File(s) copied
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2398,5): warning MSB3283: Cannot find wrapper assem
bly for type library "stdole". Verify that (1) the COM component is registered correctly and (2) your target platform is the same a
s the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit. [D:\prog\
gitextensions\GitPlugin\GitPlugin.csproj]
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node
   and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
  GitExtensionsTest -> D:\prog\gitextensions\GitExtensionsTest\bin\Release\GitExtensionsTest.dll
  Running Code Analysis...
  Code Analysis Complete -- 0 error(s), 0 warning(s)
```

I run Windows 10 Pro Insider Preview, build 14905.

### PR DESCRIPTION
**Pull request by EbenZhang**
Can some one test it on other versions of windows such as windows7, windows8? I have been using it for couple of month without problem on windows 10 preview 14316 and the nonpreview version.problem

Fixes #3316 

(cherry picked from commit 51b86394c3295c1b8e36c985b4ae8644eb83870d)

### CODE REVIEW

**Comment by vbjay** [comment]
image

**Comment by vbjay** [comment]
image

**Comment by jazzzz** [comment]
It works great for me on Windows 10 build 14915. Thanks!

**Comment by KindDragon** [comment]
I don't have this issue 😕

**Comment by jazzzz** [comment]
I still have the issue with master (1abdf3325fd02f61d1ecd44afc2cd43843262500) on Windows 10 build 14946.

**Pull request merged**
