### PR TITLE
fix ListView column border in dark theme

### LINKED ISSUE #8863: [Theming] ListView incorrect column line colour
## Current behaviour

https://github.com/gitextensions/gitextensions/pull/8849#issuecomment-781774683

| Default | Dark |
--|--
image | image

In the default (system) theme the column vertical line is of a faint light blue colour. In the dark theme - the column line's colour is significantly more prominent, and looks the same as the colour as the border.

## Steps to reproduce

Checkout https://github.com/gitextensions/gitextensions/pull/8849/commits/983b0c320b0a5de53562a04edb4712263b539d14 (or the commit from https://github.com/gitextensions/gitextensions/pull/8849)

### PR DESCRIPTION
**Pull request by NikolayXHD**
Fixes #8863

### Before

image

### After

image

## Test environment(s) 

- Windows10
- 96 dpi

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
+1
Maybe you need to rewrite the commit as the committer is unknown...

No hdpi for me so hardly visible before, works fine.
before/after is slightly different to the description

Good writeup for the theming handling

image

image

**Comment by NikolayXHD** [comment]
> Maybe you need to rewrite the commit as the committer is unknown...

The commit was done from work pc. It so happens that my wife works the same company, it also so happens, that her initials match mine (n.idalgo - nadia idalgo, nikolay idalgo) so gitlab at work beleives my commits belong to my wife.

**Review by RussKie — APPROVED** [review]
Legend! 🚀

**Comment by RussKie** [comment]
> The commit was done from work pc. It so happens that my wife works the same company, it also so happens, that her initials match mine (n.idalgo - nadia idalgo, nikolay idalgo) so gitlab at work beleives my commits belong to my wife.
> 
> I like to keep it that way to confuse my collegues. In this repo however it's not fun at all, so will have to modify the history.

🤣 
Your better half may now need to provide a sign off too 
image

**Comment by pmiossec** [comment]
> > Maybe you need to rewrite the commit as the committer is unknown...
> 
> The commit was done from work pc. It so happens that my wife works the same company, it also so happens, that her initials match mine (n.idalgo - nadia idalgo, nikolay idalgo) so gitlab at work beleives my commits belong to my wife.
> 
> I like to keep it that way to confuse my collegues. In this repo however it's not fun at all, so will have to modify the history.

Even with the use of 'conditional includes'? 

https://blog.jiayu.co/2019/02/conditional-git-configuration/

**Comment by gerhardol** [comment]
> Even with the use of 'conditional includes'?

Don't encourage the use of conditional includes, not supported by the GE config parsing...

**Pull request merged**
