### PR TITLE
fix display of the "git clean" preview

### PR DESCRIPTION
**Pull request by pmiossec**
Enable the 'AcceptReturn' to be able to display the command output
on multiple lines

### CODE REVIEW

**Comment by KindDragon** [comment]
I fix it in this commit https://github.com/gitextensions/gitextensions/commit/eb9e7c959f920a9da26349262edcf94c0cfd2eb1 , but your solution is probably better

**Comment by KindDragon** [comment]
IDK, my solution more general

**Comment by pmiossec** [comment]
Indeed, I was not up to date and didn't see your fix. So, do what you want with this PR ;)

**Comment by KindDragon** [comment]
I will leave my changes. Ty

**Pull request closed without merging**
