### PR TITLE
Fix issue 5672: The caches can be reset, make sure to use the same instance

### LINKED ISSUE #5672: AOOR in RevisionGraph
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I was opening and closing repositories (go to the dashboard), when I received the AOORE. 
The app continued to work, no visible problems observed.

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.GetSegmentsForRow(Int32 row) in C:\Dev\gitextensions\GitUI\UserControls\RevisionGrid\Graph\RevisionGraph.cs:line 207
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.<CalculateGraphColumnWidth>b__22_0(Int32 index) in C:\Dev\gitextensions\GitUI\UserControls\RevisionGrid\Columns\RevisionGraphColumnProvider.cs:line 463
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DefaultIfEmptyIterator>d__93`1.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.CalculateGraphColumnWidth(VisibleRowRange& range, Int32 currentWidth, Int32 minimumWidth) in C:\Dev\gitextensions\GitUI\UserControls\RevisionGrid\Columns\RevisionGraphColumnProvider.cs:line 463
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.OnVisibleRowsChanged(VisibleRowRange& range) in C:\Dev\gitextensions\GitUI\UserControls\RevisionGrid\Columns\RevisionGraphColumnProvider.cs:line 456
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.NotifyProvidersVisibleRowRangeChanged() in C:\Dev\gitextensions\GitUI\UserControls\RevisionGrid\RevisionDataGridView.cs:line 538
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext() in C:\Dev\gitextensions\GitUI\GitUIExtensions.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in C:\Dev\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```   
   
**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- fdc76e3925cfaeed8f7ac6d93e663f0c60444344 
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

### PR DESCRIPTION
**Pull request by spdr870**
Fixes #5672 

Changes proposed in this pull request:
- The caches can be reset, make sure to use the same instance
 
What did I do to test the code and ensure quality:
- Manual testing

Has been tested on (remove any that don't apply):
- GIT 2.19
- Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
Looking at the `RevisionGraph` code, I have a niggling suspicion may be running into more threading issues.

For example, here `_orderedNodesCache = null`
https://github.com/gitextensions/gitextensions/blob/cda113d52e967103be79c88697d24efd8ae88ab1/GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs#L43-L50
In various other places, the `_orderedNodesCache` is dereferenced without checks.

**Comment by spdr870** [comment]
> Looking at the `RevisionGraph` code, I have a niggling suspicion we may be running into more threading issues.
> 
> For example, here `_orderedNodesCache = null`
> https://github.com/gitextensions/gitextensions/blob/cda113d52e967103be79c88697d24efd8ae88ab1/GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs#L43-L50
> In various other places, the `_orderedNodesCache` is dereferenced without checks.

This is not really a problem, when the _orderedNodesCache is replaced with a new instance (due to reordering or when new items are added), the new instance is always at least as big as the old one. Its only the rowcache where the size can vary, because it is build in stages.

**Comment by RussKie** [comment]
I pushed in another refactor, moving the expensive cache rebuild into own pure method. 
It can now be tested, if you could write some tests for it - it would be great.

**Comment by spdr870** [comment]
FYI, this PR also fixes this (the graph is not rendered, because it was reset during the rebuild):
image

**Comment by spdr870** [comment]
My workday just started. Will have some time later to add some more tests where possible.

**Comment by RussKie** [comment]
> Will have some time later to add some more tests where possible.

That'd be awesome. Tests will help us providing some level of confidence when we change things.

**Comment by spdr870** [comment]
@RussKie I needed to do a small fix after your refactor. I think it would me nice if all caches would be moved to its own class. I can do this, but maybe its better to move this refactor into a separate PR. What do you think? (the small fix is in 3b370a408a634237ec4c619a17b1b63d64b4b3de)

**Pull request merged**
