### PR TITLE
FormBisect: Autosize form to prevent content to be clipped

### PR DESCRIPTION
**Pull request by pmiossec**
### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 549f02363b5470696a27a1f002241f5ae4f5c719
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4311.0
- DPI 192dpi (200% scaling)

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Did you verify at 100% and 150% scaling?

**Comment by pmiossec** [comment]
> Did you verify at 100% and 150% scaling?

Yes. By restarting the application after changing the scale. The display was good for all the scaling I tested.

Even if seeing this message below I'm not sure if I did the perfect test:

image

If someone know what is the perfect way to test that. After a scale change

* Is closing and reopening **the form** enough? => easy but I think it is not enough, right?
* Is closing and reopening **the application** enough? => acceptable but I'm not perfectly sure? (the way I did my test...)
* Should we sign out to be sure ? => perfect case but very painful to test if required!!

**Review by gerhardol — COMMENTED** [review]
Only tried in no dpi change
Changes look OK
I would like to remove the resize marker, it is not possible to resize the form anyway
If you try to resize, the form flash some (hard to see in the gif below). If no resize marker, I do not care about that.

image

bisect

**Comment by pmiossec** [comment]
> I would like to remove the resize marker, it is not possible to resize the form anyway
> If you try to resize, the form flash some (hard to see in the gif below). If no resize marker, I do not care about that.

Yes I saw this bad behavior few time after doing the PR.
It is now fixed.

**Comment by RussKie** [comment]
> * Is closing and reopening **the application** enough?

That's how often test scaling 😉

**Review by RussKie — APPROVED** [review]

**Pull request merged**
