### PR TITLE
fix(FormResetAnotherBranch): Do not open ComboBox drop down on Enter

### LINKED ISSUE #11671: Reset action not triggered when pressing Enter in "Reset branch" dialog
### Environment

- Git Extensions 33.33.33
- Build 112c87345e3ddf959aff6f3a412bf4312313ee7b
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 8.0.3
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Opening the "Reset branch" dialog and pressing the Enter key should trigger the reset action, but nothing happens.
Pressing the Escape key once and then pressing Enter allows the reset to be executed.

screenshot

### Steps to reproduce

1. Right-click on a commit in the grid view.
2. Select "Reset another branch to here..." from the context menu.
3. Press the Enter key in the "Reset Branch" dialog that appears.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11671
which is a regression in #11656

## Proposed changes

- Also ignore `Enter` in `Branches_KeyUp`

## Screenshots 

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]

**Review by RussKie — APPROVED** [review]
If it works...

**Comment by RussKie** [comment]
@shirayuki could you please confirm the fix?

**Comment by shirayuki** [comment]
Is it intentional that we now need to press the Enter key twice to execute the 'Reset branch' action?
If so, the fix resolves the issue. Thanks!

**Comment by mstv** [comment]
> Is it intentional that we now need to press the Enter key twice to execute the 'Reset branch' action?

Same as in v4.2.1. Direct activation by selection from the drop down would be kind of unexpected behavior.

**Pull request merged**
