### PR TITLE
submodule status configurable

### LINKED ISSUE #5733: Performance problems in repo with lots of submodules
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When opening a repository with lots of submodules (65 in our case) GitExtensions hangs for about a minute with no UI updates. This then also happens repeatedly when working inside the opened repository. I captured a Git Command Log while opening the repository:

gitext_log_slow_submodules

During the hang nothing happens in the main window or the log window (the mouse cursor changes to the "waiting circle"), then all submodule commands show up at the same time in the log window.

I also profiled a GitExtensions release build  #(89897d085a60823f72ba5045fad6d84dd02bc58b) in VisualStudio which seems to indicate that waiting for all submodule status update tasks in [GetRepositorySubmodulesStatusAsync](https://github.com/gitextensions/gitextensions/blob/c2eb7fee8433d0ead1ca3eb5d0c0df87211f53b5/GitCommands/Submodules/SubmoduleStatusProvider.cs#L99) takes a lot of time:

gitext_perf

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Open a repository with lots of submodules

**What is the expected behavior?**

UI should not hang when opening a repository

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**

2.51.05 is also not ideal in this case (some shorter hangs with lots of submodule related activity in the log window) but does not hang for such a long period of time with no UI updates.

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #5733

Changes proposed in this pull request:
- Submodule Status in the Browse submodule menu is made configurable (default off). The structure is still displayed, just not the status by default.
- Increase size of the Settings form as the lower part was already clipped. (The proper fix should be to split the page).
 
Screenshots before and after (if PR changes UI):
- 
image

-
-
image

What did I do to test the code and ensure quality:
- Manual testing on a repo with GE duplicated 3*9

Has been tested on (remove any that don't apply):
- GIT 2.19
- Windows 7/10

### CODE REVIEW

**Comment by gerhardol** [comment]
> Just to confirm - have you checked the tab index is still logical?

Logical - mostly. Same index as on Stash Count so should be fixed.

**Comment by spdr870** [comment]
I like to keep the option for submodule status off by default, as suggested in this PR. Performance should be optimal out-of-the-box.

**Comment by amaiorano** [comment]
May I suggest we remove "in browse menu" from the settings label, since I'm also using this feature in my submodule ROT change? So perhaps "Show submodule status icon next to module name"?

Personally, I think this option should be on by default as I suspect the majority of users will not be impacted. One question I have is: if we turn this off by default, then later one improve the performance and decide to enable it by default, will existing users who upgrade GE have this option disabled still?

**Comment by gerhardol** [comment]
> May I suggest we remove "in browse menu" from the settings label, since I'm also using this feature in my submodule ROT change? So perhaps "Show submodule status icon next to module name"?

I thought about that, why the the settings name is ShowSubmoduleStatus.
For the the text I did not find anything that does not imply that submodule status in other situations (like submodule manage) is not updated. Maybe the side panel is separate (see below).

> Personally, I think this option should be on by default as I suspect the majority of users will not be impacted. One question I have is: if we turn this off by default, then later one improve the performance and decide to enable it by default, will existing users who upgrade GE have this option disabled still?

Only if we add a new setting.
For the sidepanel, this could be separate, so status is updated only if the submodules side panel is visible.

If submodule status is updated from commit-count only where needed, the overhead will be much lower.

**Comment by gerhardol** [comment]
> My Submodule ROT code is based on the SubmoduleStatusProvider becoming a pub/sub singleton, so both the submodules menu and the submodules ROT tree register for updates, and get updated at the same time. So triggering updates occurs pretty much in the same way as it does now (I fixed a couple of missing cases, and also made sure "Refresh" causes an update). All that to say, I don't think it would be good to add a separate option to update submodule status for the ROT.

Implementation should be the same but may not always be activated.
Submodule ROT could activate this by default if submodules are visible (maybe even do not need a setting). (In that case the menu could maybe be updated too.)

The status is very useful but if we are to prioritize between bad performance and missing features we should avoid bad performance first. If the problem is magically fixed I suggest we make a new setting.

**Comment by RussKie** [comment]
> One question I have is: if we turn this off by default, then later one improve the performance and decide to enable it by default, will existing users who upgrade GE have this option disabled still?

Performance outweighs nice-to-haves.
If we change it in the future, users will have to turn it on. Or we create a new setting.

**Pull request merged**
