### PR TITLE
Redo selection of the first item to fix shift-select of multiple items

### PR DESCRIPTION
**Pull request by mdonatas**
## Fixes

When opening FormCommit - first item in unstaged files is selected. Then when shift-clicking on 2nd and further items to select 1fst through _clicked_ items, the selection is made not from the top but from the bottom.

## Proposed changes

- Reset internal ListView "last selected item" index by resetting `Selected` to `true` for the first selected item.

### Before

Notice that when `shift-clicking` after refresh control acts as if last item in the list has focus and selection happens from it till the item being clicked on.

shift-click-before

### After

shift-click-after

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build cb8954cc0cc839d7b33976e6befa492e5a6fde07 (Dirty)
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.10
- DPI 192dpi (200% scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mdonatas** [comment]
This single-line fix took probably two hours to find and solve 😅

**Review by pmiossec — APPROVED** [review]

**Review by mstv — APPROVED** [review]
👍 Thank you

**Review by gerhardol — COMMENTED** [review]
+1
Have not run

> This single-line fix took probably two hours to find and solve 😅 (and then another hour to record the gifs 🤣)

Changes like this can take a lot more time than that...

**Review by RussKie — COMMENTED** [review]
🚀

**Pull request merged**
