### PR TITLE
Render tabs in the text viewer

### PR DESCRIPTION
**Pull request by gerhardol**
Update  TextViewer to include a submodule update by @lhiginbotham that not yet is applied to the main application.
https://github.com/gitextensions/ICSharpCode.TextEditor/pull/23/files
https://github.com/gitextensions/ICSharpCode.TextEditor/issues/22

## Proposed changes

See submodule changes

## Test methodology 

Manual - see submodule

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
Good catch. But I don't see a difference in the commit-message editor. Tabs have already been rendered.

**Comment by lhiginbotham** [comment]
@mstv 
> Good catch. But I don't see a difference in the commit-message editor. Tabs have already been rendered.

How do you mean?  If you go to reword a commit and put some tabs in the editor, you will not see them, but they exist (can be deleted accordingly i.e. press tab 7 times, you will have to delete or traverse with arrow keys 7 times to account for it).

**Comment by mstv** [comment]
> Good catch

... that the changed submodule is not used yet.

1. I missed that the original issue was just about _rewording_ commits. Other usages of `TextEditor` are able to display tabs (FormCommit and `F4`).
That's why there was no need to alter the submodule.
But you are going to enable it by default. 👍
2. If testing the portable build, the git config for file editor must be updated manually. Works 👍.

**Review by mstv — APPROVED** [review]

**Comment by gerhardol** [comment]
I also had some problems to find the issue...

**Comment by gerhardol** [comment]
@msftbot merge in 24 hours

**Pull request merged**
