### PR TITLE
Collect and publish plugins (portable)

### PR DESCRIPTION
**Pull request by RussKie**
Addendum to #7649, solves parts of #7702.

## Proposed changes

* Partially alter #7850 to not rename any plugins for CI builds
* Enumerate all plugin satellite files
* Publish plugins in the portable artifact

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
I would too, but in #7850 we addressed a perf regression, that led to
renaming plugins.
Whilst it's working well locally, it is a PITA to change the installer.

Speaking of which, I'm currently working on the installer.
I want to release asap, so we can start migrating to .NET Core, where I
expect a lot will change, including bazillion of netstandard dependencies
gone.

**Comment by gerhardol** [comment]
Can we generate the files for the installer?

Go ahead if it is needed.

**Comment by RussKie** [comment]
> Can we generate the files for the installer?

If you're curious, very much WIP: https://github.com/RussKie/gitextensions/tree/Fix_msi

**Comment by RussKie** [comment]
Looks like it broke the build, and the failure hasn't been reported... 😒 

https://ci.appveyor.com/project/gitextensions/gitextensions/builds/31786768

**Pull request merged**
