### PR TITLE
Fix reset function for copied files

### LINKED ISSUE #6297: Copied files in a commit cannot be deleted by 'Reset to parent'
## Current behaviour

Copied files in a commit cannot be deleted from the worktree by using 'Reset to parent' from the context menu item. The menu item does nothing on the file.

## Expected behaviour

The same menu item can delete added files. It must also delete copied files.

## Steps to reproduce

- Right click on the last commit with a copied and modified file from the commit diff tab
- Choose 'Reset file(s) to > Parent' from the context menu.

## Screenshots

image

## Did this work in previous version of GitExtensions

Not since a few versions at least.

## Environment

- GitExtensions version: 2.51.02
- GIT version: 2.16.1.windows.4
- OS version: Windows 10

### PR DESCRIPTION
**Pull request by DeadDuck**
Fixes #6297

## Proposed changes

- Reset to first function will now work for copied files too

## Test methodology 

- Manual testing

## Test environment(s) 

- GIT 2.16.1.windows.4
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Good catch!
Could devise a test we can add to our test suite to ensure this doesn't
reoccur?
I'm happy to help with the infra implementation, if necessary.

**Comment by DeadDuck** [comment]
Thank you. I can take a look at it when I have some time.

**Comment by gerhardol** [comment]
Can you please submit a separate PR signing contributors.txt?

**Comment by DeadDuck** [comment]
@gerhardol submitted #6342 signing contributors.txt.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
