### PR TITLE
WIP: Fix ui for german translation

### PR DESCRIPTION
**Pull request by thimmy687**
TODO <- message not done, but want to submit maybe for cherry picking, rest will follow soon :)

Fixes #

## Proposed changes

- FormCommit buttons now take so much space like button with widest translation need (AutoSize)
- HotKeys Setting reset button now with AutoSize
- 

### Before
FormCommit
image

HotKeys
image

### After

FormCommit
image

HotKeys
image

## Test methodology 

- 
- 
- 

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by illfated** [comment]
From what I remember, it is recommended open a separate PR for `contributors.txt` , to avoid frequent changes during the review period of the main PR content.

**Comment by mast-eu** [comment]
Your enthusiasm is appreciated, but you are trying to rush things too much:

1. Please take your time to finish all aspects discussed in #6548 (I suppose that's what you're working on, but it's not even clear).
2. Update this PR, containing the issue number you are fixing ("Fixes #  ...."), describing what you did and add screenshots before and after your changes (if applicable).
3. Remove the "WIP:" from the title. That's the signal for maintainers that you're done and we will start reviewing the PR.

For more info, please have a look at our [contributor guidelines](https://github.com/gitextensions/gitextensions/wiki/Guidelines%3A-contributor).
Looking forward to see your complete PR :-)

**Comment by thimmy687** [comment]
Yes @mast-eu you are right :)

but I was quick submit the changes, maybe someone work already at this or related topics and can cherrypick what he need.

I will open a new PR for the contributors.txt and I also will split the changes I have made in separate PR's because the work-package will become to big if I submit all changes together.

**Comment by illfated** [comment]
Fair enough. As a "rule of thumb", smaller PRs with limited scope are usually quicker and easier to review & merge than big ones. Smaller PRs are also both easier to manage and to find out if any parallel change is in progress.

**Comment by RussKie** [comment]
The PR is in a conflict state.
Please let us know if you wish to pursue it further.

**Comment by illfated** [comment]
As previously noted, removing `contributors.txt` from this PR will avoid this type of conflict, because that file has a tendency towards being updated more often than the rest of the files in this PR. Then again, seeing that nothing has happened in this PR for more than 2 months now, checking the work status here is quite useful too.

**Pull request closed without merging**
