### PR TITLE
Add statistics for 1C Enterprise and 1Script files

### PR DESCRIPTION
**Pull request by theshadowco**
## Proposed changes

Add code statistics for 1C Enterprise and 1Script files

## Test methodology 

none

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
+1

Could you add your sign off in the `contributors.txt` file, please?

**Comment by theshadowco** [comment]
> +1
> 
> Could you add your sign off in the `contributors.txt` file, please?

done :-)

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Comment by pmiossec** [comment]
Disclamer: I forgot to send my message. I do it because it could raise discussion even if the PR is merged.

I never encountered these type of files.
Is it used by a lot a persons/software or linked to a specific product?

I really wonder if we need to include these extensions if the usage is very limited...

Because you still have the possibility to configure the list of files supported in the plugin settings:

image

Side note: we could add also go and rust file extensions.....

**Comment by RussKie** [comment]
Fair points, thank you for sharing.
Personally I'd rather see all plugins unbundled.

**Comment by theshadowco** [comment]
> Disclamer: I forgot to send my message. I do it because it could raise discussion even if the PR is merged.
> 
> I never encountered these type of files. Is it used by a lot a persons/software or linked to a specific product?
> 
> I really wonder if we need to include these extensions if the usage is very limited...
> 
> Because you still have the possibility to configure the list of files supported in the plugin settings:
> 
> image
> 
> Side note: we could add also go and rust file extensions.....

These are the source files of a popular in Russia (and not only) ERP system.
For example https://github.com/topics/1c-enterprise

**Pull request merged**
