### PR TITLE
5234 part 6

### PR DESCRIPTION
**Pull request by drewnoakes**
Part six from #5234

Changes proposed in this pull request:
- Add ObjectId.ToObjectFilePath

What did I do to test the code and ensure quality:
- Manual tests
- Unit test

Has been tested on:
- GIT 2.18
- Windows 10

### CODE REVIEW

**Comment by drewnoakes** [comment]
Some background on this change. In isolation I agree that a single usage doesn't provide so much value, but I am hoping to use this more in future. A while back I started a [library](https://github.com/drewnoakes/legit) that reads data out of the `.git` folder, and it has an `ObjectId` type that mirrors the one in GE for the most part. Going directly to the file system rather than calling `git.exe` is much faster for certain kinds of low-risk operations. That is a separate discussion, but it's part of the thinking behind this change.

**Comment by RussKie** [comment]
> ...it's part of the thinking behind this change

Thank you, as I have started the review with exactly the same question. 
Though I am not entirely convinced it is a right place for this method, because calling it outside an ascertained git module doesn't make much sense. I've looked through `GitModule` API and it seems we have few somewhat similar (at least semantically) methods there, e.g. `GetGitDirectory` and `GitCommonDirectory`. It feels that `GetObjectsDirectory` fits right there.
Thoughts?

**Comment by drewnoakes** [comment]
`GetObjectsDirectory` makes sense. Would that return the `.git/objects` folder alone, or also take an `ObjectId`?

**Comment by RussKie** [comment]
I haven't given it a sufficient thought, will do so in the evening.

Thinking out loud, `GetObjectsDirectory` should probably return just `.git/objects` folder.
We can have a separate API `GetObjectDirectory(ObjectId)` that return the path to the specific object, if one exists.
Internally `GetObjectsDirectory` should probably just return a property, which is (re-)initialised when `GitModule` instance is created.
Thoughts?

**Comment by drewnoakes** [comment]
Sounds sensible. Late here and I'm not thinking very deeply.

GitModule is so massive right now it's hard to tell what it's all about. I hope we can split out the git operations into other classes and be left with stuff that's intrinsic to the module, such as accessing its directories and status.

**Comment by RussKie** [comment]
Yes, totally on board with this idea

**Comment by drewnoakes** [comment]
Sure. Will close this.

**Pull request closed without merging**
