### PR TITLE
Avoid invalid path exception on invalidated Module.WorkingDir

### LINKED ISSUE #7958: [NBug] The path has an invalid format.
## Current behaviour

exception closing a repo in order to check the dashboard

## Expected behaviour

no exception

## Steps to reproduce

- close current repo (`Ctrl+W`) while it is loading / refreshing
- dashboard appears and exception pops up

## Error Details
```
System.ArgumentException: Der Pfad hat ein ungültiges Format.
   at string System.IO.Path.LegacyNormalizePath(string path, bool fullCheck, int maxPathLength, bool expandShortPaths)
   at string System.IO.Path.NormalizePath(string path, bool fullCheck, int maxPathLength, bool expandShortPaths)
   at string System.IO.Path.GetFullPathInternal(string path)
   at string GitCommands.FullPathResolver.Resolve(string path)
   at void GitUI.Editor.FileViewer.SetVisibilityDiffContextMenu(bool visibleTextFile, string fileName)
   at void GitUI.Editor.FileViewer.ResetForDiff(string fileName)
   at Task GitUI.Editor.FileViewer.ViewPatchAsync(string fileName, string text, Action openWithDifftool, bool isText)+() => { }
   at Task GitUI.Editor.FileViewer.ShowOrDeferAsync(long contentLength, Func<Task> showFunc)
   at async Task GitUI.Editor.FileViewer.ViewPatchAsync(string fileName, string text, Action openWithDifftool, bool isText)
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync()
   at async void GitUI.CommandsDialogs.RevisionDiffControl.DiffFiles_SelectedIndexChanged(object sender, EventArgs e)+(?) => { }
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 4.0.0.9030
- Build f400be654d461aab777a2e7aa8e1f5added0fcd5 (Dirty)
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by mstv**
Fixes #7958

## Proposed changes

- handle empty `WorkingDir` the same way as if it was `null` in `FullPathResolver.Resolve`
- remove the string extension methods `IsNotNullOrWhitespace`, `IsNullOrWhiteSpace` and `IsNullOrEmpty`

## Test methodology 

- added NUnit test

## Test environment(s) 

- Git Extensions 3.3.0
- Build 61acf3fb39e6063f3b705dca6f5b1772f2f370e4
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Just for the record, I personally loath these extensions https://github.com/gitextensions/gitextensions/pull/3638.

**Comment by mstv** [comment]
> I personally loath these extensions

So if we are on it, let's replace `s.IsNot...()` with `!s.Is...()`.
This is more exact because it is a slightly unclear to what `Not` shall apply in `IsNotNullOrCondition2`.
Drawback: It is easy to miss the "!".

I prefer `s.Is...()` over `string.Is...(s)`.

BTW: `ThemeFix.IsNot...` does more than the identifier says! `ThemeFix.add` is lower case.
Not very critical since it is private stuff.

**Comment by RussKie** [comment]
I'd rather remove all of them. In _my_ opinion readability suffers more than with "!" (which has its issue, but it is a language construct).

If memory serves me well long time ago I read an answer from someone from the language team that explained why extensions methods like the ones we have weren't added. In the gist these extensions were redundant and carry very little value.


> BTW: `ThemeFix.IsNot...` does more than the identifier says! `ThemeFix.add` is lower case.
> Not very critical since it is private stuff.

👀 @NikolayXHD

**Comment by RussKie** [comment]
> So if we are on it, let's replace `s.IsNot...()` with `!s.Is...()`.

Sure

**Comment by mstv** [comment]
I find `!string.IsNullOr...(s)` better readable than `!s.IsNullOr...()`.
And `s.IsNullOr...()` should feel incorrect if `s` can be `null`.
So I removed these extension methods. `IsNullOrWhiteSpace` had already been marked for removal.

**Comment by gerhardol** [comment]
> I find !string.IsNullOr...(s) better readable than !s.IsNullOr...()

I prefer the s. variant as it is more compact (but I was confused the the first time I saw it so I am OK in removing).

**Pull request merged**
