### PR TITLE
Submodules window now keeps the splitter position

### LINKED ISSUE #4366: Submodules dialog: list is too narrow
**Do you want to request a *feature* or report a *bug*?**

-> Bug

**What is the current behavior?**

When the dialog is show, the entry in the submodules list on the left side to not fit the table. For some, I can on see the elided prefix like "submodules/ABCD/..." multiple times. This makes the list rather useless.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

You need a repository with submodules that have a longer path.

**What is the expected behavior?**

Adapt the table to the widht of the content or at least save the state so the user can arrange it as needed and it stays like that even when the user opens the dialog again.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.2
- GIT version: 2.15.1.windows.2
- OS version: Windows 7 Pro 64bit

**Did this work in previous version of GitExtensions (which)?**

(unknown)

### PR DESCRIPTION
**Pull request by JurjenBiewenga**
Fixes #4366 by saving the position of the splitter

## Test methodology 
- Manual

## Test environment(s) 
- Windows

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
Seem OK

SplitterManager used in FormBrowse/FormCommit (and RevDiff/RevTree, not saving though?)

**Comment by mstv** [comment]
> RevDiff/RevTree, not saving though?

They are added to the `SplitterManager` of their parent form.

**Review by mstv — APPROVED** [review]
LGTM

**Comment by RussKie** [comment]
Wow, I didn't know we have a splitter on that form!

@JurjenBiewenga please rebase resolving the MC, and squash. And it's good to go.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Bummer, we still have a MC. 
Please leave a comment when you'll have rebased, so I merge it quickly.

**Comment by JurjenBiewenga** [comment]
@RussKie Resolved

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
