### PR TITLE
Update ignore patterns of FormGitIgnore; Fix DPI issues

### PR DESCRIPTION
**Pull request by mdonatas**
## Proposed changes

_This is a bit of fruit-salad of commits, let me know if I should split this up, although they are somewhat related. It's far easier to review these commits one at a time._

- Fix DPI scaling problems with `FormGitIgnore` buttons
- There were ignore patterns for `.vs` and `_ReSharper` but not for `.idea` which is added by Rider so I've added that
	- Example text was not reflecting the default patterns used, at least to me it seems these should match
	- The change I am not too sure of is I've gone through all the translation files and updates these patterns by hand meticulously checking to not break anything 😅
- I've increased the default height of the form
- Enabled the vertical scrollbar for the `Examples` section as it doesn't fit by default
- I've noticed at random a comment by @mstv asking for a mnemonic so added that too :) https://github.com/gitextensions/gitextensions/pull/11661#pullrequestreview-2012080628

### Before

100%
image

200% 😢
image

### After

200%
image

## Test methodology 

- Manually at 100% and 200% scaling

## Test environment(s) 

- Windows 11
- 100% and 200% scaling

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
LGTM, thank you for the mnemonik
Remove all non-English translations. They need to be updated on Transifex.

**Comment by mdonatas** [comment]
Do you know why there is a [git-extensions-**v4**](https://app.transifex.com/git-extensions/git-extensions-v4/dashboard/) and I couldn't find any references to it in this repo, only to the [git-extensions](https://app.transifex.com/git-extensions/git-extensions/dashboard/)?

**Review by mstv — APPROVED** [review]
> Do you know why there is a [git-extensions-v4](https://app.transifex.com/git-extensions/git-extensions-v4/dashboard/) and I couldn't find any references to it in this repo, only to the [git-extensions](https://app.transifex.com/git-extensions/git-extensions/dashboard/)?

This a question about Transifex sub-projects, which I cannot answer.

**Comment by gerhardol** [comment]
> This a question about Transifex sub-projects, which I cannot answer.

I believe russkie set that up to be used for "stable" translations, used for releases, without -v4 for master.

**Comment by RussKie** [comment]
> > Do you know why there is a [git-extensions-v4](https://app.transifex.com/git-extensions/git-extensions-v4/dashboard/) and I couldn't find any references to it in this repo, only to the [git-extensions](https://app.transifex.com/git-extensions/git-extensions/dashboard/)?
> 
> This a question about Transifex sub-projects, which I cannot answer.

[git-extensions-v4](https://app.transifex.com/git-extensions/git-extensions-v4/dashboard/) is a project for the v4.0 release. It is now defunc. We only actively maintain [git-extensions](https://app.transifex.com/git-extensions/git-extensions/dashboard/), and it will be used for the next release.

The translations are largely machine-translations, so if there's common text in multiple releases, that text will be translated in all releases.

**Comment by RussKie** [comment]
The translations are release-specific.

main // release/4.1:
https://github.com/gitextensions/gitextensions/blob/046817e5aa376aee1cadae6d8a5a298fcfba88a3/.tools/transifex/DownloadTransifexTranslations.ps1#L13

release/4.0
https://github.com/gitextensions/gitextensions/blob/release/4.0/.tools/transifex/DownloadTransifexTranslations.ps1#L13

**Review by RussKie — APPROVED** [review]

**Pull request merged**
