### PR TITLE
Git commit version info

### PR DESCRIPTION
**Pull request by vbjay**
Clean Work Tree image
Dirty Work Tree image

This will aid in the issue submissions.  If NBug reports an issue we will know exactly which commit the exe was compiled against.

### CODE REVIEW

**Comment by KindDragon** [comment]
I like changes in About dialog but your PR contains changes in 35 files ¯ \ _ (ツ) _ / ¯

**Comment by RussKie** [comment]
Looks like rebase is in order

**Comment by vbjay** [comment]
Lol. Only 2 years worth of changes to merge.

**Comment by RussKie** [comment]
indeed :)
wonder how much of the actual change is really necessary in the latest master

**Comment by vbjay** [comment]
I'll probably just cherry pick and go through the diffs and re-commit.  If
it's something that would actually be pulled in.

**Comment by jbialobr** [comment]
I am not convinced that the added value is worth the complexity it introduces comparing to the automatically numbered version that AppVeyor does.

**Comment by vbjay** [comment]
The whole point of the feature was to have the exact git hash the current
build is on and if the working directory was dirty or not.

**Comment by vbjay** [comment]
That way the user could not only say I am on version X which doesn't always
lead to an exact commit, but we can say the code was compiled on a
clean/dirty pull of {hash}.

**Comment by vbjay** [comment]
AppVeyor doesn't help if someone builds an installer from the build scripts
we have.

**Comment by jbialobr** [comment]
Yes, I know that. The clean/dirty status does not say much - we don't know the exact changes. The most issues are reported for the regular releases. Test versions are automatically numbered by AppVeyor.

**Comment by jbialobr** [comment]
>AppVeyor doesn't help if someone builds an installer from the build scripts
we have.

IMHO these cases are negligible, I can't even recall a one.

**Comment by vbjay** [comment]
image
So which commit is this from?  

Could be efcfd5d66286d2bebc1e3720d24458da29ee7d8a to 3bfe688893f34df26d46bffc32e7f92e8f88b401^

My point is that if you know from looking at about window which commit to go to, it will speed up debugging and dealing with stuff from nbug.

Oh and the complaining about file mod count is beyond stupid.  I made a common info project that builds the file that gets used by the other projects.  Since we had a lot of projects, wow a lot of project files were touched.  I did the work to make this happen and the work was ignored after I did the work and fixed things.

**Comment by RussKie** [comment]
I think this feature would have been very useful if GE published "nightly builds" and a lot of users were running them.
If users run official discreet versions it probably not such a big deal.

**Comment by vbjay** [comment]
I've done it a few times. I've ran the build script and installed a current
version from head.  I wouldn't be surprised if others do it too.  Why I
created the feature.

**Comment by jbialobr** [comment]
> I wouldn't be surprised if others do it too.

So, do I. But from that kind of people we usually get very detailed report. e.g.
gitext

The real problem for me is lack of the call stack. Many users click Send & Quit when they get an error shown in  NBug report window. **But it does not send anything anywhere.** We often get a screenshot of NBug window where the first tab is selected not providing the call stack. Providing more detailed data about exact commit hash does not make any difference in such cases.

**Comment by vbjay** [comment]
Why not. I used nbug in my own program. It sends me an email. Can't some
GitHub  API be called to create an issue or update some datastore of
crashes.

**Comment by klorinczi** [comment]
Personally I would welcome if at least the AppVeyor build number would show up in the About dialog. 
A branch name on which the build is based, would be also helpful.

**Comment by jbialobr** [comment]
>Why not. I used nbug in my own program. It sends me an email. Can't some
GitHub  API be called to create an issue or update some datastore of
crashes.

Crash report can contain some confidential data - it should not be sent automatically without the user being aware of that.

**Comment by jbialobr** [comment]
> Personally I would welcome if at least the AppVeyor build number would show up in the About dialog.
A branch name on which the build is based, would be also helpful.

Build version and sha1 are added in 889cddbeeacb650ee5dd759fd5798bfbd5ffc914

**Comment by jbialobr** [comment]
If someone wants to build private builds with theirs own version numbering it can be done by modifying BuildInstallers.VS2015.cmd to react to an environment variable(s) indicating that set_version_to.py has to be called before.

**Pull request closed without merging**
