### PR TITLE
Search only for GitExtensions.Plugins.*.dll

### PR DESCRIPTION
**Pull request by RussKie**
Follow up on #10953

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]
pushed removal of definition of the unused constant CI_BUILD and minor code cleanup (that you may want to put on one line).

**Comment by RussKie** [comment]
Thank you!

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions.plugintemplate

https://github.com/gitextensions/gitextensions.pluginmanager

Do we need to note this in these repos?

**Comment by RussKie** [comment]
Thank you @vbjay! I complete overlooked that part. Those plugins (and many others we don't know about) will be broken, I'll have to fix this.

**Comment by RussKie** [comment]
#10982

**Pull request merged**
