### PR TITLE
Improve determination of the GitExt directory (fix of issue #7587)

### PR DESCRIPTION
**Pull request by c3er**
# Fixes

Issue #7587.

## Proposed changes

- Change determination of GitExt loacation from `new Uri(assembly.CodeBase).LocalPath` to `assembly.Location`
- Added some test cases. Though they run also green without the proposed change.

### Before

If the path to the GitExt repository contains a hash sign "#":

- Unit test `Default_values_are_specified_in_invariant_theme` fails.
- Debugging from Visual Studio starts with error message "Failed to read theme"

### After
Mentioned errors are fixed.

## Test methodology 

- Made sure related errors disappeared
- Added some test cases
- Ran all existing unit tests to make sure they are still green
- Searched for other occurrences of `new Uri...` bit did not found anything that causes similar bugs

## Test environment(s) 

- GIT 2.24.1.windows.2
- Windows 10 1909

My actual path to the local Gitext repository is

```
D:\eigene dateien\devel\bsp\c#\gitextensions
```

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
@c3er  I completely missed it, but we need your sign-off in contributors.txt

**Comment by gerhardol** [comment]
Also note 
https://github.com/gitextensions/gitextensions/issues/7587#issuecomment-570042910

URI.Local need to be changed in several other situations. Rules for URI is not the same as for the local file system

**Comment by c3er** [comment]
@gerhardol I searched the code for `new Uri` and other occurrences that involve local path seem not to be affected by truncation. I observed that if the path has the format

```
file:///C:/some#/dir/file.txt
```

the path will e truncated like in the line `var path = new Uri(assembly.CodeBase).LocalPath;`. But if the path has not the file protocol prefix, the path will not be truncated by the Uri constructor. It could be more clean to replace all Uri constructor calls to local paths with more appropriate seeming methods but I hesitated because I don't know how to find and test all related side effects.

@RussKie Shall I make a new pull request for this or how should it be handled?

**Comment by gerhardol** [comment]
> I hesitated because I don't know how to find and test all related side effects.

OK

> Shall I make a new pull request for this or how should it be handled?

Yes

**Pull request merged**
