### PR TITLE
fix: FormCreateBranch label alignment

### LINKED ISSUE #3302: FormCreateBranch dialog labels are right aligned
It's look inconsistent with others WinForms, as all dialogs are left aligned.

### PR DESCRIPTION
**Pull request by RussKie**
* Labels are not left aligned to match the rest of the app
* Orphan group is re-flown

Fixes #3302

### CODE REVIEW

**Comment by RussKie** [comment]
image
image

**Comment by jbialobr** [comment]
Thank you. It looks like #3291 has the same issue.

**Comment by RussKie** [comment]
Ah yes, I'll update that. Thanks

**Comment by RussKie** [comment]
#3291 updated

**Pull request merged**
