### PR TITLE
Fix connection issues with TFS on premise build server

### LINKED ISSUE #5773: Can't connect to build server of TFS 2017 on premise
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to use the build server integration plugin "VSTS and Team Foundation Server (since TFS2015)" with a on premise instance of TFS2017 the plugin can not connect to the build server when entering the build server data as requested by the configuration UI. Build results just won't be listed, as there is no other feedback that there was an connection issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The URL of a TFS project is structured like:
`http://<url of tfs instance>/<team collection name>/<project name>/...`

For a TFS build server that makes the required api available under the following URL:
http://somehost:8080/tfs/DefaultCollection/MyProject/_apis/build/builds?api-version=2.0

The build server data one would enter for a on premise instance would be as followed:
Server Url: http://somehost:8080/tfs
Team collection name: DefaultCollection
Project name: MyProject
Build definition name (all if left empty): §leave empty§
Rest Api Token: §your token§

The connection fails, because:
1. Part of the server URL (in this case "tfs") is disregarded, when the server url misses a trailing slash
2. The plugin completely ignores any input into the team collection name field

**What is the expected behavior?**
Either the UI should be adjusted to request the correct information in the correct way, or the connection to the build server should succeed with the information entered like above. 

Reducing the inputs to the following would make things even easier to configure, as team collections don't exist in VSTS (now Azure DevOps) as far as I know:
Project Url: http://somehost:8080/tfs/DefaultCollection/MyProject
Build definition name (all if left empty): §leave empty§
Rest Api Token: §your token§

**Environment you encounter the issue:**
GitExtensions: 3.0RC1
TFS: TFS2017 on premise

**Workaround**
Enter build server data as followed:
Server Url: http://somehost:8080/tfs/DefaultCollection/
Team collection name: $leave empty$
Project name: MyProject
Build definition name (all if left empty): $leave empty$
Rest Api Token: §your token$

**Did this work in previous version of GitExtensions (which)?**
As far as I know that feature is not available in Version 2.x

### PR DESCRIPTION
**Pull request by Noguai**
Fixes #5773

1. Updated plugin name to "Azure DevOps / VSTS and Team Foundation Server (since TFS2015)"
2. Changed the config UI to just request the project URL, build definition filter and API token
3. Fixed the issue with missing slashes in the URL
4. Extended auto detection of project and token management URLs to accept more forms of the same URL and URLs from Azure DevOps and TFS on premise
5. Added possibility to extract project and build definition information from a build results link
6. Added unit tests for URL conversion to help against regressions on updates because of URL changes by Microsoft
7. Did some minor code cleanup (Extract handling of plugin settings and url conversion, move HttpClient instance into TfsApiHelper, renamed TfsApiHelper to TfsApiClient)

ToDo:
- [x] Test compatibility with older VSTS / Azure DevOps projects (I created a new VSTS project and don't know if and how it differs from older ones)
- [x] Add some tests for parsing build result URLs from on premise TFS installations
- [x] Investigate HiDPI Issue with config UI
 
Screenshots before and after (if PR changes UI):
tfs

Has been tested on (remove any that don't apply):
- Windows 10
- On Premise installation of TFS2017
- New VSTS / DevOps Project created and tested 11/2018

### CODE REVIEW

**Comment by Noguai** [comment]
@RussKie Displaying the config UI on my Surface with 200% scaling revealed some HiDPI issues. I'm mostly a WPF guy and only know about WinForms HiDPI, that it kinda sucks at it and that it most of the time does not work. What did you do to fix the rest of the app and is missing here?
image

**Comment by drewnoakes** [comment]
See also @RussKie's comments at https://github.com/gitextensions/gitextensions/issues/4775.

**Comment by Noguai** [comment]
Hey @drewnoakes, thanks for that hint, the SO link in there is a good one. 👍

**Comment by Noguai** [comment]
Oops, fixed it.

@pmiossec you had offered to test my PR, once it's ready. Could you please give my current implementation a shot on your VSTS instance, if you have the time to do so?

**Comment by vbjay** [comment]
I'd use a PluginID_SettingName

PluginID being a static value that never changes even if the assembly name
changes.  GUID

2ec6be62-d9e2-4b2b-a06b-e037b580e201_ServerUrl

**Comment by Noguai** [comment]
Yeah something like that

**Comment by gerhardol** [comment]
@pmiossec and other TFS users:
Is this working OK?
Can you review?

**Comment by pmiossec** [comment]
I was busy doing some other open-source project but I think I should do a pause to take the time to review it. I'll try to do it at noon...

**Comment by pmiossec** [comment]
@Noguai It is working well from what I have tested.

Some possible improvements that you will find to my branch ( https://github.com/pmiossec/gitextensions/tree/task/%235773-fix-tfs-connection-issues )

I also wonder if we should not rename the project and classes to replace `Vsts` by `AzureDevOps`?

And there is also the problem of the settings key that changes when plugin is renamed (key used `BuildServer.Azure DevOps and Team Foundation Server (since TFS2015).ProjectUrl`) that I would like to see fixed.
I tried to fixed it allowing the specify the key but failed :( There is something I really don't understand how it is read by the `BuildServer` class: https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Settings/RepoDistSettings.cs#L124

**Comment by pmiossec** [comment]
Otherwise, it works well...

**Comment by gerhardol** [comment]
Briefly looked at the code and have no comments. When @pmiossec  is satisfied, I am.

**Comment by RussKie** [comment]
Just to give you heads up - for the v3 I had to re-align assembly information across the solution - dbcbc0ab8de88f1cb770864278a5a9ef0f481d3c. The v3-specific changes will be merged into master once the v3 is released (very soon now). This PR will need to be updated then.

**Comment by Noguai** [comment]
@RussKie Alright, I'll just have to add a little assembly description then, but there is another thing that came to my mind: 

> > Especially (breaking) changes to GitExtensions settings.
>
> This extension is still not released (will be only with v3), so consider that you don't have to handle backward compatibility because beta testers that use it on their own risk should be able to fix there settings…

As this PR is scheduled to be merged with the first release after V3, does this still stand? (From my testing no crashes, just loss of build integration settings)

**Comment by pmiossec** [comment]
I think that either this PR must be merged before v3 is released (not that risky) or we must no package the plug-in in the v3 release at all.

There are indeed renames in settings key and in the plug-in name that is used in the settings key (due to Microsoft renaming of their service).

So I don't want users to use the current version (especially not supporting Azure Devops) and see their settings lost with the minor v3.1 release.

I'm more for the merge because this PR just improve what we already plan to release (even fixing a bug that prevents the use with TFS on premise).

**Comment by RussKie** [comment]
I'm willing to take this into the v3 release, given the plugin functionality is non-essential.
Please rebase your branch on top of `release/3.00`.

I would like to see the number of commits reduced.

**Comment by Noguai** [comment]
I did the rebase and reduced commits to the essential things. My local build still works, but I found that the AppVeyor build is missing the plugin assembly in it's plugins directory among many other files. (Windows Explorer says 118 elements in my local build vs. 43 in the AppVeyor one)

**Comment by RussKie** [comment]
There is no magic to the way we package, it is all in appveyor.yml
```
    & Setup\BuildInstallers.cmd
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    & Setup\Set-Portable.ps1 -IsPortable
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    & Setup\MakePortableArchive.cmd Release $env:APPVEYOR_BUILD_VERSION
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    & Setup\Set-Portable.ps1
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
```

You can generate all packages locally if you fancy to try:
```
pushd Setup
powershell .\Prepare-Release.ps1 -oldVersion 2.51.01 -newVersion 3.00.00 -milestones '49'
```

**Comment by Noguai** [comment]
Works now:
portable-package

**Comment by RussKie** [comment]
I just realised, this plugin won't be translated for v3.

**Pull request merged**
