### PR TITLE
Add Squash feature on GitFlow Plugin

### PR DESCRIPTION
**Pull request by Fabman08**
## Proposed changes
Add new checkbox on GitFlow plugin: "Squash feature"
This checkbox enables the user to squash the merge commit form one feature to develop branch.
Simply adds the `-S` parameter to the `git flow feature finish` command

I think it can be userful :)

## Screenshots 
image

## Test environment(s) 

- GIT 3.2.1.6628
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
Please rebase your work instead of merging from master...

**Comment by Fabman08** [comment]
I'll create another PR with correct translation and rebease instead of merge

**Comment by pmiossec** [comment]
> I'll create another PR with correct translation and rebease instead of
> merge
>

FYI, you're not obligated to open a new PR until you still update the same
branch.

The PR will be updated automatically.

>

**Comment by RussKie** [comment]
As @pmiossec pointed, you could have just force pushed into the existing branch, and the PR would have been updated.

**Pull request closed without merging**
