### PR TITLE
Added check if branch filter is enabled before applying simplify by d…

### LINKED ISSUE #4642: incorrect nesting of `simplify by decoration`
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

image

the option `simplify by decoration` seems to be a suboption of the `branches` option.
Visually, because it is indented, but also logically because it is greyed out if `branches` is not checked.

**What is the expected behavior?**

This feels odd however, because the `simplify by decoration` has effect independent of the `Branches` checkbox state. Indeed it is well defined independent of whether one is showing all branches, just the active branch or a set of filtered branches. So the `simplify by decoration` option should be be nested under `branches`.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: git version 2.15.1.windows.2
- OS version: Windows 7

### PR DESCRIPTION
**Pull request by thomas42**
Fixes #4642

### CODE REVIEW

**Comment by RussKie** [comment]
2.5x branch is at EOL, please send a PR to the master branch instead.
Also please use the PR template provided

**Comment by thomas42** [comment]
The 3.0 branch apparently has no Linux support and thus we can't use it.

**Comment by RussKie** [comment]
We need a matching PR to the master anyway

**Comment by RussKie** [comment]
Just a friendly reminder that we need a PR to the master branch before we merge this.

**Comment by GintasS** [comment]
This is an old PR and should be closed or set to a draft. @RussKie

**Comment by RussKie** [comment]
@GintasS do you think you could apply the fix to the master instead?

**Comment by GintasS** [comment]
> @GintasS do you think you could apply the fix to the master instead?

Could easily do, if nothing has changed and only the same change that @thomas42 did is needed :) Because otherwise, I'm going to work on the bootstrap thing, need to finally finish with the .NET migration.

**Pull request closed without merging**
