### PR TITLE
Jira commit hint plugin: fix some string not translated

### PR DESCRIPTION
**Pull request by pmiossec**
To be merged after #7039 will be (just the last commit is specific to this PR).

## Proposed changes

JiraPlugin: Fix way to define TranslationString that prevent translation

+ remove TranslationString redundant with settings caption
(which is translated when defined in a private field!)

## Test methodology 

- Some more strings appears in `English.Plugins.xlf`

### CODE REVIEW

**Comment by RussKie** [comment]
We can't take that in 3.2, it will go in after the release.

**Comment by pmiossec** [comment]
>We can't take that in 3.2, it will go in after the release.

That was not my intention to merge it before 3.2. I just did the PR once I discovered the problem.

But, just for information, I don't understand why it can't be...

I don't see the problem because the strings are not translated at the moment, so, merging the PR will change nothing, no!?!

**Comment by gerhardol** [comment]
> I don't see the problem because the strings are not translated at the moment, so, merging the PR will change nothing, no!?!

No formal problem before - no problem.
This will maybe confuse translators though

**Comment by RussKie** [comment]
> I don't see the problem because the strings are not translated at the moment, so, merging the PR will change nothing, no!?!

We have announced a release on Transifex and translators have translated supplied strings.
Adding more strings may render languages which currently meet 95% translation bar ineligible for inclusion into the release, thus affecting the users.

**Comment by pmiossec** [comment]
OK. Good to know even if I would have imagined that the inclusion was
calculated only on Gitextensions and not the plugins...

**Comment by RussKie** [comment]
> To be merged after #7039 will be (just the last commit is specific to this PR).

Please rebase

**Comment by pmiossec** [comment]
done.

**Pull request merged**
