### PR TITLE
Fix/5990 release 3.01 

### LINKED ISSUE #5990: Could not load file or assembly 'Microsoft.VisualStudio.Composition
Tested with canary builds 
The last worked is GitExtensions-Portable-3.01.00.4558
From 4559 to 4571 crashed on Startup
```
Could not load file or assembly 'Microsoft.VisualStudio.Composition, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.
```
If replace files from 4558 👍 
GitUI.dll
GitUI.pdb
GitUIPluginInterfaces.dll
GitUIPluginInterfaces.pdb

starting without problem

- Git Extensions 3.01.00.4571
- Build 03616615c075af006d75e3abed76a4e7f6134ad6 (Dirty)
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #6019: Feature: Make installer source files that exist in Gitextensions\bin\release... to use Gitextensions\bin\release files
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Installer sources from project output folders when a copy of the file exists in Gitextensions\bin\release folder.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Source files from Gitextensions\bin\release if at all possible.
**Environment you encounter the issue:**
Master

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**

Rename as html and open in browser.  
[Installer Script File sources.html.txt](https://github.com/gitextensions/gitextensions/files/2717598/Installer.Script.File.sources.html.txt)
Sample entries from this file.  
image

[linqpad ](https://www.linqpad.net/) script that generated the above output
```vb

Sub Main
	Dim doc = XElement.Load("D:\git\gitextensions\Setup\Product.wxs")

	Dim installerFiles = doc...<File>.Select(Function(nd) New With {.Node=nd,.Path=io.Path.GetFullPath(IO.Path.Combine("D:\git\gitextensions\Setup\",nd.@Source.Replace("$(var.Configuration)", "Release")))})
	'installerFiles.GroupBy(Function(f) io.Path.GetExtension(f.Path)).Dump("Installer files By extension")


	Dim installerDetails = installerFiles.Select(Function(f) New With {.Node=f.Node,.ParentNode=f.Node.Parent,.Info = New io.FileInfo(f.Path), .Hash = Sha512Hash(f.Path)})


	Dim releaseFiles = IO.Directory.EnumerateFiles("D:\git\gitextensions\gitextensions\bin\Release\", "*.*", searchOption.AllDirectories)
	'releaseFiles.GroupBy(Function(f) io.Path.GetExtension(f)).Dump("Release files By extension")

	Dim releaseDetails = releaseFiles.Select(Function(f) New With {.Info = New io.FileInfo(f), .Hash = Sha512Hash(f)})

Dim matched = From ReleaseFile In releaseDetails
Group Join InstallerFile In installerDetails On InstallerFile.Hash  Equals ReleaseFile.Hash Into MatchedInstallerFiles = Group
Where MatchedInstallerFiles.Any(Function(f) Not f.Info.FullName.StartsWith("D:\git\gitextensions\GitExtensions\bin\Release\",StringComparison.CurrentCultureIgnoreCase))

matched.Select(Function(f) New With {.ReleaseFile=f.ReleaseFile.Info.FullName, .ReleaseHash=f.ReleaseFile.Hash, .MatchedInstallerFiles=f.MatchedInstallerFiles}).Dump("Installer files that also exist in GitExtensions\bin\Release\")






End Sub

' Define other methods and classes here

Function Sha512Hash(path As String) As String
	Static sha As System.Security.Cryptography.SHA512 = System.Security.Cryptography.SHA512CryptoServiceProvider.Create()
	If Not file.Exists(path) Then Return String.Empty
	Using fstream As New IO.FileStream(path, FileMode.Open, FileAccess.Read)
		Return String.Join("",sha.ComputeHash(fstream).Select(Function(b) b.ToString("X2")))
	End Using

End Function

```
image

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5990 
Closes #6019 

## Proposed changes

- Update MakePortable.cmd and Product.wxs to include needed files.
    - Missing dll's
    - Satellite Assemblies
- Reformat Product.wxs with <kbd>Ctrl</kbd>+<kbd>K</kbd>+<kbd>D</kbd>
- Include MakePortableArchive.cmd in setup project to make it more visible

## Test methodology 

- Ran ``` .\Setup\Prepare-Release.ps1 -oldVersion 3.0.0 -newVersion 3.0.1 -milestones '48'``` and inspected portable zip and msi using 7zip to make sure new files were included.
- Downloaded CI MSI
- Downloaded and extracted CI portable build.
- Installed MSI
- Ran portable as portable and non portable.
    - Opened a repo
- Ran Installed version
    - Opened a repo

### CODE REVIEW

**Comment by RussKie** [comment]
I ran the portable from this branch on a brand new W10 installation and it successfully opened a git repo 👍

**Comment by vbjay** [comment]
Ok.  I'll clean up and fix tomorrow and put in details.  Please merge 6005 and 6085 to allow master CI builds to work again.

**Comment by RussKie** [comment]
My current priority is to get 3.0.1 out.
Once it is resolved, we can get the master back on track.
I'm currently building your branch to generate msi as well - https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21542767

**Comment by vbjay** [comment]
Ok.  Let me see if I can clean up real quick.

**Comment by RussKie** [comment]
Ok, I tried an MSI built from this and it also worked nicely.
I'm happy to merge this.

**Comment by vbjay** [comment]
I ran out of brain power and was so tired.  I'll finish the rebase tonight to have it cleaned up and get it to you later on.

**Comment by RussKie** [comment]
We need to package pdbs as well
@DmitryZhelnin was testing the build and observed both #6094 and #6034 but without pdbs available was unable to debug those.

**Comment by RussKie** [comment]
I see we publish pdbs as part of the portable archive.
I am not sure it is the best approach - it is not obvious. Instead I think we should publish pdbs as a separate downloadable artifact.

**Comment by vbjay** [comment]
I agree that we should publish the pdbs as an artifact for all to download.  I think the portable should contain the pdbs too.  You get the portable, you can debug it. The installer does not include them.  You can download and extract as needed.

**Comment by vbjay** [comment]
I'll duplicate the publish pdbs commit to #6005.

**Comment by vbjay** [comment]
Installed 
- Git Extensions 3.00.00.4828
- Build 5dbd9049f3db03e7b317525a51e5d1d7f4606403 (Dirty)
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

Extracted portable
- Git Extensions 3.00.00.4828
- Build 5dbd9049f3db03e7b317525a51e5d1d7f4606403 (Dirty)
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)


Opened a repository in both.
👍

**Comment by vbjay** [comment]
@RussKie   All cleaned up and tested.  👍

**Comment by RussKie** [comment]
Made obsolete by #6102

**Pull request closed without merging**
