### PR TITLE
Feature/tfs2015 build integration

### PR DESCRIPTION
**Pull request by kine**
Solution for issue #3177. I have used nugget packages for TFS2015 REST API, because I am not C# developer and it was easier for me than working with bare REST. But I think it could be rewritten to clean REST if needed (https://www.visualstudio.com/en-us/docs/integrate/api/overview).

### CODE REVIEW

**Comment by pmiossec** [comment]
I would have prefered to use the REST API :(
When I have developed the TFS plugin for the previous version, I was already worried by being obliged to include references on tfs assemblies. It could sometimes bring some impediments when building...
I was quite happy when heard that TFS2013 (partly) and TFS2015 introduced a REST API.
I think that the REST API is here to stay and that we should do the effort to support it. That way, we will support the actual TFS versions and the next to come...

**Comment by jbialobr** [comment]
@pmiossec What kind of impediments do you think about?

**Comment by pmiossec** [comment]
Impediments is perhaps a little overstated but for each tfs project (2012, 2013 and now 2015), you will have to add the tfs assemblies and package them with GitExtensions with something that could be done not so hardly but using the REST API.

And TFS2015 is adding 15Mo, a lot more than the 2Mo (2012) or 5Mo (2013) previously needed.

**Comment by vbjay** [comment]
That is the whole point of nuget.  It will pull down he right things and
even restore if the packages don't exist.

**Comment by KindDragon** [comment]
So what do we do with this PR? Vote with GitHub reaction 😄

**Comment by jbialobr** [comment]
Nowadays 15MB is only a few seconds added to the download time. I vote for merging to enable the feature sooner.

**Comment by VictorioBerra** [comment]
Just installed 2.50 I dont see the TFS integration in the plugins menu. I was pretty sure it was set to install the feature in the installer. What am I missing?

**Comment by pmiossec** [comment]
It seems that a lot of needed assemblies (`Microsoft.TeamFoundation.*`, `Microsoft.VisualStudio.*`, ....) are not bundled in the setup :(

And `TfsInterop.Vs2013.dll` is no more bundled too (perhaps not build too...) :(

Once again, I think the best way to fix definitively all these problems (and support tfs2017) is to use the rest api. See https://github.com/gitextensions/gitextensions/issues/3779#issuecomment-310197486

**Comment by EbenZhang** [comment]
in2.49 or even 2.48, the dlls for earlier version of tfs were not bundled. i think the one who use this integration should Microsofts installer to install the dlls to gac.

**Comment by pmiossec** [comment]
@EbenZhang yes but that's not the way Microsoft provide tfs assemblies since TFS2015.
Dlls are no more added to the GAC and you should use nuget packages.

From https://www.visualstudio.com/en-us/docs/integrate/get-started/client-libraries/dotnet :

>For .NET developers building Windows apps and services that integrate with Visual Studio Team Services, client libraries are available for integrating with work item tracking, version control, build, and other services are now available. These packages replace the traditional TFS Client OM installer and make it easy to acquire and redistribute the libraries needed by your app or service.

**Comment by EbenZhang** [comment]
thanks for the info

**Pull request merged**
