### PR TITLE
Start with dashboard also if started from valid Git repo

### LINKED ISSUE #4739: GE skips dashboard if started from a Git repo
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
This is in reality just a behavior that affectes starting GE from Visual Studio.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The startup code starts latest dir if AppSettings.StartWithRecentWorkingDir is set
If this setting is not set or latest directory do not exist, GE checks the current directory.
This masks issues in the dashboard and makes changes like PR #3693 harder to test

The working directory does not seem to be used in other situations, like when started from the command line

**What is the expected behavior?**
Follow the setting also in Debug

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
same at least since 2012

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #4739

Changes proposed in this pull request:
 - Show dashboard also when starting with debugger
(see issue for a longer explanation)

What did I do to test the code and ensure quality:
 - Start with/without setting 
 - Test vsix plugin
 - Test shell extension - browse

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by sharwell** [comment]
:memo: I verified that this does not break the **Right Click &rarr; GitExt Browse** operation from Windows Explorer. However, it sounds like the original issue emphasized the debugging experience for GitExtensions developers and on that note I'm still looking into an alternative.

**Comment by gerhardol** [comment]
This is low prio, but it has surprised me several times (and it hide #4739, that was detected in 2.51RC1).
You can still use "Open last working directory on startup" with the debugger.

> I verified that this does not break the Right Click → GitExt Browse operation from Windows Explorer. 

I had tested that too and did a brief look at other usages but did not see any situation where working tree was assumed with arguments.
It would have been safer to use the change seen below, but since I did not see use for it I suggest to remove it.

image

**Comment by vbjay** [comment]
It shouldn't be hard to just alter the debug option to pass in the argument
of currentProjrctDirectory so that debug opens the repo.

**Comment by drewnoakes** [comment]
> the debugging experience 

I don't have all the context, but if that code is useful in debug builds then maybe:

```c#
#if DEBUG
// ...
#endif
```

**Comment by RussKie** [comment]
I'm happy with either option

**Comment by gerhardol** [comment]
To set "if DEBUG" around the piece of code I removed is "safe", similar to check arguments
But it does not _seem_ to be needed, so I removed it

This is low prio, so I will revert to have some condition

**Comment by sharwell** [comment]
My preference is:

1. The code should implement the behavior we want for releases, and it should be the same in Debug and Release configurations
2. If we want the contributor experience (e.g. <kbd>F5</kbd> within Visual Studio) to differ from the production behavior, we modify the command line arguments [like this](https://github.com/gitextensions/gitextensions/blob/6c3185726cf29e95f5dfdfddee4a0f19c2534feb/GitExtensionsVSIX/GitExtensionsVSIX.csproj#L28) to provide the behavior we want by default when working on the project

**Comment by RussKie** [comment]
yes, i was thinking about the same

**Comment by sharwell** [comment]
So what's the desired behavior for average users (not people trying to develop this project)? 😄

**Comment by RussKie** [comment]
IIUC the app must start with the dashboard if no valid working folder
passed as a parameter, else the app opens the working folder.
IIRC there's also a switch to open the last working folder.

**Comment by sharwell** [comment]
I don't disagree with the comment by @RussKie. However, at the same time this is changed I would like to see the **GitExtensions.csproj** file modified to pass the working directory so the default debugging experience for developers doesn't change as a result of the application behavior change.

```xml
<PropertyGroup>
  <StartArguments>browse "$(MSBuildThisFileDirectory).."</StartArguments>
</PropertyGroup>
```

**Comment by gerhardol** [comment]
For normal users, GE is not started within a repo, so there is no difference

For installation in a Git repo which includes debugger builds but also possibility for portable installations, GE automatically starts there. This is what I want to change, to get the same behavior for normal release builds and for debugger builds. I know why the behavior differs, that is what I want to spare other developers. 
I suggest the override when debugging is done for developers if wanted (similar to what sharwell describes, added to *.csproj.user), or change the defaults.

image

If special behavior in repo is desired, this PR can as well be dropped completely.

**Comment by sharwell** [comment]
@gerhardol I would expect this PR to have two changes:

1. The change to **Program.cs**, which is already complete and correct in the pull request
2. A change in **GitExtensions.csproj** (detailed in a comment a couple up from here), which is missing

**Comment by gerhardol** [comment]
@sharwell 
I see what you mean, but then this PR can as well be dropped as it provides no benefit. (I have no problems with that at all, a discussion is better than just forcing changes, this is very minor...)

Let us go on with more important matters...

**Comment by sharwell** [comment]
@gerhardol the benefit would be you can right click on the project, go to Debug options, and remove the default. That would save an override value for you in your .csproj.user file and provide the behavior you desired for debugging.

**Comment by RussKie** [comment]
I like the proposal to modify GitExtensions.csproj in addition to removing the code as proposed by this PR

**Comment by gerhardol** [comment]
I will change then

**Comment by gerhardol** [comment]
Rebased and changed as sharwell suggested
Suggest squash merge

**Comment by RussKie** [comment]
thank you

**Pull request merged**
