### PR TITLE
Correct label alignment

### LINKED ISSUE #9402: Push form: advanced options UI broken
## Current behaviour

UI broken when trying to display advanced options of Push form.

## Expected behaviour

The options are well displayed

## Steps to reproduce

1. Open Push form
2. Click on "Options" link
3. See that options are not displayed.

## Screenshots

GE_broken_push_options

## Did this work in previous version of GitExtensions

Yes. Last commit before dotnet 5 migration.
Broken in last `master` (Broken in portable version downloaded and custom version built).
Not tested in between.

## Environment

- Git Extensions 3.6.0.12349
- Build cd34d45c6a1d56e4497257898e2095dea70425a6 (Dirty)
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.8
- DPI 192dpi (200% scaling)

## Diagnostics

dotnet 5?

### PR DESCRIPTION
**Pull request by RussKie**
Closes #9402

## Screenshots 

- Build b426a9c4104dd80a07a6586edc40e8fc2b8319f9
- .NET 6.0.3
- DPI 144dpi (150% scaling)

### Before

Only "to" label appears to anchored incorrectly:
image
image

### After

image

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
@msftbot merge in 48 hours

**Comment by mdonatas** [comment]
At 200% scale the label position is correct although the row height is too high. This is probably an FYI... not sure if it warrants blocking this PR.

image

**Comment by RussKie** [comment]
Have you had a chance to test this change?

**Comment by mdonatas** [comment]
The screenshot was from this PR's branch

image

**Comment by RussKie** [comment]
I think that this PR will address the issue you're seeing.

**Comment by mdonatas** [comment]
> I think that this PR will address the issue you're seeing.

So sorry, I'm slow after Easter over-eating 🤦 I've made a screenshot using a build on a wrong commit.

Here's a build using this PR's branch.. I've double checked it this time :)

image

**Comment by RussKie** [comment]
Thank you for testing. I think it should be fixed now.

**Comment by mdonatas** [comment]
> Thank you for testing. I think it should be fixed now.

Perfect, can confirm it's fixed now. Thank you! 🙏

**Pull request merged**
