### PR TITLE
Update packages

### LINKED ISSUE #7385: "Invoke or BeginInvoke cannot be called on a control until the window handle has been created" exception after closing commit dialog opened from Windows Explorer
## Current behaviour

After closing the commit dialog opened from Windows explorer a "Git Extensions has stopped working" crash dialog is shown.

## Expected behaviour

No crash.

## Steps to reproduce

From the Windows Explorer context menu of a git-tracked file select File History. Click on the Commit tab. Close the window.

## Did this work in previous version of GitExtensions

Yes. Not sure, but fairly recent (definitely 3.x).

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

## Diagnostics

Exception details (from attaching Visual Studio):

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c__DisplayClass5_0.<Connect>b__0()
   at System.Reactive.Disposables.AnonymousDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.ObserveOnObserver`1.Dispose(Boolean disposing)
   at System.Reactive.ObserverBase`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at GitUI.CommitInfo.CommitInfoHeader.DisposeCustomResources()
   at GitUI.GitModuleControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

### PR DESCRIPTION
**Pull request by RussKie**
Closes #7385

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
How much soaking time do we need after this update?
It seem to fix at least one issue, but are new issues added?
I am not too worried, but we need a strategy.

**Comment by RussKie** [comment]
Good point, but I wouldn't worry too much about this one. If necessary
users can update local copy of PuTTY.
We should unbundle it as well.

**Comment by gerhardol** [comment]
> Good point, but I wouldn't worry too much about this one. If necessary
users can update local copy of PuTTY.

PuTTY I am OK with (the telemetry data maybe supports removing PuTTY as the default, which is a required step but not a point here).

This was for updating Reactive

**Comment by mstv** [comment]
The `Threading.dll` cannot be found when packaging the portable version.
```
MakePortableArchive.cmd : File not found - System.Reactive.Windows.Threading.dll
At C:\projects\gitextensions\Build\Prepare-Artifacts.ps1:32 char:1
+ & Setup\MakePortableArchive.cmd Release $env:APPVEYOR_BUILD_VERSION
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (File not found ...s.Threading.dll:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by RussKie** [comment]
Sorry I got confused.... I think we should be ok updating this package. But
happy to wait until after a release.

I know the build is failing, and needs attention.

**Comment by gerhardol** [comment]
> Sorry I got confused.... I think we should be ok updating this package. But
happy to wait until after a release.

I guess you are human, after all.

I just do not have any feeling of the risk here.

**Comment by RussKie** [comment]
> I guess you are human, after all.

Hahah, I am, I got me :)
I only get time close to midnight to look at GE atm, so I'm usually tired to do a lot of thinking.

**Pull request merged**
