### PR TITLE
feat: Configure ANSI background colors separately

### LINKED ISSUE #11821: [vNext] Diff colouring not enough contrast
### Environment

- Git Extensions 4.3.0.17872-mbjjveco
- Build 70184a4c7252b263427ed627f5004e288e51b4bb (Dirty)
- Git 2.45.2.windows.1

### Issue description

The colours need to have greater contrast ratio (IIRC, it has to be 4:1 or close to it), right now they are too faint
This is an accessibility issue.

image

### Steps to reproduce

1. Install **GitExtensions-x64-4.3.0.17872-70184a4c7.msi** from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50328130/artifacts
1. Click on a diff 1cd999e35bd4c7c0eb4cb28671927ddfcf7facad for tests/app/UnitTests/GitCommands.Tests/UserRepositoryHistory/RecentRepoSplitterTests.cs

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by gerhardol**
Supersedes #11824 
Fixes #11821

## Proposed changes

This PR has four serial parts, the last commit could be dropped.

- feat: ANSI PrintColors also in Release builds

Enable the routine to print the ANSI terminal colors also in release builds.
The colors are used to display e.g. git-diff.

- feat: Configure ANSI background colors separately

Specify foreground/background colors for the terminal separately,
to enable themes that work better with GE colors.

Apply theme colors for difftastic: Do not change background
for bold text, to improve readability.
Only reverse video for normal red/green.

- feat: GE theme ANSI terminal colors

Adjust the ANSI terminal colors to align with the GE theme.
The background/foreground colors are separate to improve the
display for the extremely bright GE colors.

The theme is somehow based on mintty Helmhotz, but heavily modified
especially for background (reverse video) to align with the
existing GE theme colors.

- feat: moved lines in diff as reverse

If GE theme colors are applied, set moved lines as
reverse video (colored background) to match the appearances

## Screenshots 

Yellow foreground is still not great, but not much used by git-diff
The background (reverse) are to most used with the last commit
image  image

#### Before

image

image

image

#### no reverse video

image

image

image

#### reverse video

Not convinced that this is better, but maybe more predictable

image

image

image

### Difftastic

Visibility is still not great, that need to be handled in difftastic itself

image

image

## Test methodology 

Tests are updated

## Merge strategy

- Rebase merge (PR submitter must change the commit message for the last commit).
I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
> Not convinced that this is better, but maybe more predictable
> 
> image
> 
> image

I'm finding the coloured background much easier on eyes. So, thank you.

**Review by RussKie — APPROVED** [review]
LGTM. 
Haven't run.

**Review by mstv — COMMENTED** [review]
+1 LGTM, have not reviewed in detail

**Comment by mstv** [comment]
FYI: git inconsistently highlights (leading whitespace of) removed and added moved lines:

grafik

```
[2;7;35m-	#def...[m
[2;7;34m+[m	[2;7;34m#def...[m[41m [m
```

**Comment by gerhardol** [comment]
There are still some potential palette issues.
I got the printout below on a Win11 setup with system-dark, app-bright but no intentional cusom setting.
Cannot reproduce though.

GetForeColorForBackColor() tries to get a color from some pairs, using HSL perceived luminance, that is obviously not always the best.
Not sure if colors or method should be tweaked.
Regardless, I do not consider this critical for a release.

unnamed

The pairs checked looks like this:

image

**Pull request merged**
