### PR TITLE
Hide statusbar of ConEmu - fixes #3172

### LINKED ISSUE #3172: Consider disabling status bar of ConEmu
Given this screenshot
b0cada1c-ebc4-11e5-91f0-38dfead54805

there is quite a bunch of numbers in that status bar and for each single one i have no clue what it should mean. additionally, it says "git" to tell us we're running git. also, the status bar protruding to the right below the scroll bar looks bad in my opinion. the only helpful part is "ssh.exe" but i don't think it's that important.

:)

### PR DESCRIPTION
**Pull request by larshg**
Fixes #3172 

edit: And btw. you can right click on the statusbar to add/disable lots of various informations.

### CODE REVIEW

**Comment by jbialobr** [comment]
To actually make it work we also have to change the conEmu default settings https://github.com/gitextensions/conemu-inside/commit/d25e0140a39eb45a4d5da636e704cfebe3227319

**Comment by larshg** [comment]
Hmm I did work at without having to change that part?

**Comment by jbialobr** [comment]
Yes, you are right. I forgot that I had tested it with [this](https://github.com/Maximus5/conemu-inside/pull/33) PR being merged. The case is that there is an error in conEmuInside (addressed by the mentioned PR) which causes that the default configuration is not being used. That is why it works for you.

**Comment by phillijw** [comment]
The status bar continues to be displayed when pulling down larshg/master (debug and release builds)

**Comment by phillijw** [comment]
I realized that I can right-click the status bar and uncheck "Show statusbar" and it hides it nicely.

**Comment by palver123** [comment]
Does it mean 2.49 is ready for release? :)

**Comment by phillijw** [comment]
Gosh I hope so!

**Comment by jbialobr** [comment]
Done in https://github.com/gitextensions/gitextensions/commit/4e5c21b21124b03587f4d613d73afe5b4e519385

**Pull request closed without merging**
