### PR TITLE
fix: Illegal characters in path

### LINKED ISSUE #6982: [NBug] Illegal characters in path.
##  Current behaviour
Git Extension fail to clone a github wiki repository, and crash when trying to stage changements on this repository.

Git can clone this repository without any issue.

## Expected behaviour
Git Extension should clone without any problem the repository.

## Steps to reproduce

Clone [https://github.com/SimpleGitVersion/SGV-Net.wiki.git](https://github.com/SimpleGitVersion/SGV-Net.wiki.git)

Close the Git Extensions dialog after the failed attempt.
Open the cloned repository with Git Extensions.
Stage all the changes.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass129_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

### PR DESCRIPTION
**Pull request by RussKie**
Closes #6982

## Proposed changes

- Do not crash the app if a repository contains illegal characters.

### Before

image

### After

image

## Test methodology 

- clone the reported repo and reproduce the issue
- apply the fix and confirm the app no longer crashes

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
I wonder in which way we could propose the user to ignore the file by using the 'skip-worktree' feature to be able to work in the repository without seeing the changes.

**Comment by gerhardol** [comment]
Similar issue should appear in at least Stash - (is this handled in Diff tab?)

**Comment by RussKie** [comment]
No, it is breaking deeper in the call stack, but it felt more appropriate to handle at this level.
```
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__130.MoveNext()
```



> Similar issue should appear in at least Stash

How?

> I wonder in which way we could propose the user to ignore the file by using the 'skip-worktree' feature to be able to work in the repository without seeing the changes.

Would it be correct though?
In this instance it is a markdown file, in other instance it could be a vital file that is needed (e.g. aux file in linux repo).
This feels like handling a specific edge-case, and I am not convinced it is something we should spend our energy on.

**Comment by gerhardol** [comment]
>>  Similar issue should appear in at least Stash

> How?

ViewCurrentChanges() is called from StashedSelectedIndexChanged().

> This feels like handling a specific edge-case, and I am not convinced it is something we should spend our energy on.

Agree, just dont crash

**Comment by RussKie** [comment]
But how would you stash invalid changes in the first place?

I just checked and I can push the error handling down the stack to `FileViewer` but this will require new strings and translations. We can do it after 3.2 is released.
```diff
diff --git a/GitUI/Editor/FileViewer.cs b/GitUI/Editor/FileViewer.cs
index 68a801872..b83e44964 100644
--- a/GitUI/Editor/FileViewer.cs
+++ b/GitUI/Editor/FileViewer.cs
@@ -427,11 +427,18 @@ private Task ShowOrDeferAsync(string fileName, Func<Task> showFunc)
 
             long GetFileLength()
             {
-                var file = GetFileInfo(fileName);
+                try
+                {
+                    var file = GetFileInfo(fileName);
 
-                if (file.Exists)
+                    if (file.Exists)
+                    {
+                        return file.Length;
+                    }
+                }
+                catch (Exception ex)
                 {
-                    return file.Length;
+                    MessageBox.Show(this, $"{ex.Message}{Environment.NewLine}{fileName}", "_error.Text", MessageBoxButtons.OK, MessageBoxIcon.Error);
                 }
```

**Comment by gerhardol** [comment]
> But how would you stash invalid changes in the first place?

Current directory changes
This is even less important than committing changes to these files.

> We can do it after 3.2 is released.

Changes like this should not be blocked by the translation, English i pop-ups must be OK

**Comment by RussKie** [comment]
Updated

**Comment by RussKie** [comment]
The tests are failing but they have nothing to do with this change.
We'll investigate the failing tests separately

**Pull request merged**
