### PR TITLE
Updates Dependencies (REUPLOAD)

### PR DESCRIPTION
**Pull request by CDAGaming**
Changes proposed in this pull request:
 - Updates Several Dependencies(Except for NUnit & System.IdentityModel.Tokens.Jwt, Compatibility Issues)

How did I test this code:
 - Tested by Running in a Normal Environment (Git Extensions is my Main Tool for GitHub)

Has been tested on (remove any that don't apply):
 - GIT 2.10 and above
 - Windows 7 and above
- .Net Framework 4.6.2 and Above

Related PRs:
- Externals/Git.Hub - PR Will be Available Soon

### CODE REVIEW

**Comment by CDAGaming** [comment]
Travis: .mdb > .pdb, Will fix this tomorrow

**Comment by CDAGaming** [comment]
Build Successfull, will begin Fixing Warnings and Optimizing Tomorrow

**Comment by EbenZhang** [comment]
Can someone using TFS (e.g. @kine @pmiossec ) verify that it didn't break the TFS integration? The upgrading of the Newtonsoft.json from v6 to v10 looks suspicious to me, not sure if the dlls that require lower version of json dll will still work or not. More specifically the `Microsoft.VisualStudio.Services.WebApi.dll` (using v8), `Microsoft.TeamFoundation.Work.WebApi` (using v6 via `System.Net.Http.Formatting`)

We may need to change the bindingRedirect in app.config to 

```xml
<dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
</dependentAssembly>
```

**Comment by pmiossec** [comment]
@EbenZhang I don't use anymore TFS at the moment and can't test it easily without creating a project in VSTS :( So I prefer if someone could do it because I don't have a lot of time...

>We may need to change the bindingRedirect in app.config to

but I think you're right, we have to update the binding redirect...

**Pull request merged**
