### PR TITLE
Updated Dependencies - WIP

### PR DESCRIPTION
**Pull request by CDAGaming**
Please Visit Externals/conemu-inside for the Associated PR - Arriving Soon

To-Do:
- Add conemu PR
- ReCheck Dependencies for any further Updates

### CODE REVIEW

**Comment by jbialobr** [comment]
We can not just upgrade to the latest versions. We have to ensure that all dynamically called methods exist and are compatible. Does anyone know if that can be done automatically?

**Comment by RussKie** [comment]
Unless methods called via reflection, the risk should be minimal - any missing methods or changed signature will break the build...

**Comment by jbialobr** [comment]
>the risk should be minimal - any missing methods or changed signature will break the build...

I am not able to run tfs plugin on my laptop but it works on my PC - it seems to depend on the GAC content.

**Comment by RussKie** [comment]
This sounds like a dependency issue.
You can probably try the fusion viewer to determine which assemlies are
missing...

**Pull request closed without merging**
