### PR TITLE
Fix RevisionLinkDefs persistence causes noise

### PR DESCRIPTION
**Pull request by RussKie**
As noted in https://github.com/gitextensions/gitextensions/commit/4ef89bf57d8e100ce6461a2dd64e9487a8478901#r28818307

### CODE REVIEW

**Comment by RussKie** [comment]
Has it reduced the noise for you? 
I don't have a problem with the namespace re-ordering, but I get re-ordered nodes in that bit of xml...

**Comment by jbialobr** [comment]
I also have nodes reordered:

```patch
diff --git a/GitExtensions.settings b/GitExtensions.settings
index d212214e0..c5a9f62ad 100644
--- a/GitExtensions.settings
+++ b/GitExtensions.settings
@@ -96,12 +96,7 @@
       <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
 &lt;ArrayOfGitExtLinkDef&gt;
   &lt;GitExtLinkDef&gt;
-    &lt;SearchInParts&gt;
-      &lt;RevisionPart&gt;Message&lt;/RevisionPart&gt;
-      &lt;RevisionPart&gt;LocalBranches&lt;/RevisionPart&gt;
-      &lt;RevisionPart&gt;RemoteBranches&lt;/RevisionPart&gt;
-    &lt;/SearchInParts&gt;
-    &lt;RemoteSearchInParts /&gt;
+    &lt;Enabled&gt;true&lt;/Enabled&gt;
     &lt;LinkFormats&gt;
       &lt;GitExtLinkFormat&gt;
         &lt;Caption&gt;Issue {0}&lt;/Caption&gt;
@@ -109,18 +104,18 @@
       &lt;/GitExtLinkFormat&gt;
     &lt;/LinkFormats&gt;
     &lt;Name&gt;GitHub - issues&lt;/Name&gt;
-    &lt;SearchPattern&gt;(?i)(?&amp;lt;!pull request |pr[ _]?)#\d+&lt;/SearchPattern&gt;
     &lt;NestedSearchPattern&gt;\d+&lt;/NestedSearchPattern&gt;
-    &lt;Enabled&gt;true&lt;/Enabled&gt;
-    &lt;UseOnlyFirstRemote&gt;false&lt;/UseOnlyFirstRemote&gt;
-  &lt;/GitExtLinkDef&gt;
-  &lt;GitExtLinkDef&gt;
+    &lt;RemoteSearchInParts /&gt;
     &lt;SearchInParts&gt;
       &lt;RevisionPart&gt;Message&lt;/RevisionPart&gt;
       &lt;RevisionPart&gt;LocalBranches&lt;/RevisionPart&gt;
       &lt;RevisionPart&gt;RemoteBranches&lt;/RevisionPart&gt;
     &lt;/SearchInParts&gt;
-    &lt;RemoteSearchInParts /&gt;
+    &lt;SearchPattern&gt;(?i)(?&amp;lt;!pull request |pr[ _]?)#\d+&lt;/SearchPattern&gt;
+    &lt;UseOnlyFirstRemote&gt;false&lt;/UseOnlyFirstRemote&gt;
+  &lt;/GitExtLinkDef&gt;
+  &lt;GitExtLinkDef&gt;
+    &lt;Enabled&gt;true&lt;/Enabled&gt;
     &lt;LinkFormats&gt;
       &lt;GitExtLinkFormat&gt;
         &lt;Caption&gt;PR {0}&lt;/Caption&gt;
@@ -128,16 +123,18 @@
       &lt;/GitExtLinkFormat&gt;
     &lt;/LinkFormats&gt;
     &lt;Name&gt;GitHub - PR&lt;/Name&gt;
-    &lt;SearchPattern&gt;(?i)(pull request |pr[ _]?)#?\d+&lt;/SearchPattern&gt;
     &lt;NestedSearchPattern&gt;\d+&lt;/NestedSearchPattern&gt;
-    &lt;Enabled&gt;true&lt;/Enabled&gt;
-    &lt;UseOnlyFirstRemote&gt;false&lt;/UseOnlyFirstRemote&gt;
-  &lt;/GitExtLinkDef&gt;
-  &lt;GitExtLinkDef&gt;
+    &lt;RemoteSearchInParts /&gt;
     &lt;SearchInParts&gt;
       &lt;RevisionPart&gt;Message&lt;/RevisionPart&gt;
+      &lt;RevisionPart&gt;LocalBranches&lt;/RevisionPart&gt;
+      &lt;RevisionPart&gt;RemoteBranches&lt;/RevisionPart&gt;
     &lt;/SearchInParts&gt;
-    &lt;RemoteSearchInParts /&gt;
+    &lt;SearchPattern&gt;(?i)(pull request |pr[ _]?)#?\d+&lt;/SearchPattern&gt;
+    &lt;UseOnlyFirstRemote&gt;false&lt;/UseOnlyFirstRemote&gt;
+  &lt;/GitExtLinkDef&gt;
+  &lt;GitExtLinkDef&gt;
+    &lt;Enabled&gt;true&lt;/Enabled&gt;
     &lt;LinkFormats&gt;
       &lt;GitExtLinkFormat&gt;
         &lt;Caption&gt;View on GitHub&lt;/Caption&gt;
@@ -145,9 +142,12 @@
       &lt;/GitExtLinkFormat&gt;
     &lt;/LinkFormats&gt;
     &lt;Name&gt;GitHub - commit&lt;/Name&gt;
-    &lt;SearchPattern&gt;.*&lt;/SearchPattern&gt;
     &lt;NestedSearchPattern /&gt;
-    &lt;Enabled&gt;true&lt;/Enabled&gt;
+    &lt;RemoteSearchInParts /&gt;
+    &lt;SearchInParts&gt;
+      &lt;RevisionPart&gt;Message&lt;/RevisionPart&gt;
+    &lt;/SearchInParts&gt;
+    &lt;SearchPattern&gt;.*&lt;/SearchPattern&gt;
     &lt;UseOnlyFirstRemote&gt;false&lt;/UseOnlyFirstRemote&gt;
   &lt;/GitExtLinkDef&gt;
 &lt;/ArrayOfGitExtLinkDef&gt;</string>
```

**Comment by RussKie** [comment]
I propose to sort definitions by name, this should provide some stability to the persisted form.

**Comment by jbialobr** [comment]
Thank you! There is no more noise when saving settings on my machine.

**Comment by RussKie** [comment]
Glad it worked

**Pull request merged**
