### PR TITLE
Avoid throwing a cancellation exception in MainThreadScheduler

### LINKED ISSUE #5376: TaskCanceledException when selecting files in Commit dialog
**Do you want to request a *feature* or report a *bug*?**
A major regression

**What is the current behavior?**
Attempts to select or deselect files in `FormCommit` take significant time (in order of seconds). At the same time `MainThreadScheduler` is choking on `System.Threading.Tasks.TaskCanceledException`

Here's the current master - here I click on single file, then do 'Select All' from keyboard and wait, and wait, and wait... it went on for about a minute after that VS crashed... The clip is much shorter, not to bore anyone:
v3-current

This is a tweaked version - it is still visibly slow, but much-much faster, on par with v2.5x.
Here I click on single file, then do 'Select All' from keyboard (do it three times):
v3-updated

The tweak is pretty much a rollback to the v2.5x version of the code:
```diff
diff --git a/GitUI/UserControls/FileStatusList.cs b/GitUI/UserControls/FileStatusList.cs
index 4b07dc8ca..0b9f227e0 100644
--- a/GitUI/UserControls/FileStatusList.cs
+++ b/GitUI/UserControls/FileStatusList.cs
@@ -947,8 +947,8 @@ void EnsureSelectedIndexChangeSubscription()
                             h => FileStatusListView.SelectedIndexChanged += h,
                             h => FileStatusListView.SelectedIndexChanged -= h)
                         .Where(x => _enableSelectedIndexChangeEvent)
-                        .Throttle(SelectedIndexChangeThrottleDuration, MainThreadScheduler.Instance)
-                        .ObserveOn(MainThreadScheduler.Instance)
+                        .Throttle(SelectedIndexChangeThrottleDuration)
+                        .ObserveOn(SynchronizationContext.Current)
                         .Subscribe(_ => FileStatusListView_SelectedIndexChanged());
                 }
             }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open GE repository at 3d01d8af5efd896e6879d9175c29f7baa97a33c2
* Open `CommitDialog`
* Set to show ignored files
* Select multiple files (e.g. CTRL+A)

**What is the expected behavior?**
The selection should be quick, if not instantaneous. At least be on par with v2.5x.

**Environment you encounter the issue:**
Current master @ 3d01d8af5efd896e6879d9175c29f7baa97a33c2

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #5376

### CODE REVIEW

**Comment by gerhardol** [comment]
@RussKie merge?

**Comment by RussKie** [comment]
I had a look at your fix, but was doing few other investigations where cancellation exceptions sort of helped to trace race conditions.

I'm planning to merge this for sure, just busy with life and work. If it is ok with you, let's leave it open for now.

**Comment by sharwell** [comment]
@RussKie No objection here, but keep in mind the specific exceptions this PR stops are not particularly actionable. It's an implementation detail of the way Reactive Extensions implements throttles, and wasn't intended to throw exceptions in practice.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
