### PR TITLE
Issue 2706 Open submodules with double click in file lists

### PR DESCRIPTION
**Pull request by glen-nicol**
Added setting that is off by default to open submodules with double click.
Added ability to open browse window to a specific commit message selected so that submodules open to the relevant commit.

### CODE REVIEW

**Comment by KindDragon** [comment]
Please also add command to context menu for that and would be nice if you also make item as default action (bold font) depending on new settings

**Comment by glen-nicol** [comment]
I don't get this error when compiling on my machine. How should I proceed?

**Comment by glen-nicol** [comment]
Finally!

**Comment by glen-nicol** [comment]
Has this been forgotten?

**Pull request merged**
