### PR TITLE
VS2019 msbuild

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

Prepare to build with VS2019

## Test methodology 
Build from commandline

## Test environment(s) 

VS2019 installed in addition to VS2017

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Do you know if it still builds with VS2017?

**Comment by gerhardol** [comment]
Awaiting discussions in upstream before removing WIP

**Comment by gerhardol** [comment]
hMSbuild 2.1.0 released
Tested with VS2019 on AppVeyor too

**Comment by RussKie** [comment]
do we need to update the appveyor script to target vs2019?

**Comment by RussKie** [comment]
sorry, wrong button 😊

**Comment by gerhardol** [comment]
AppVeyor explicitly targets vs2017 now. When we raise the requirement to use vs2019 appveyor.yml must be updated too.

**Pull request merged**
