### PR TITLE
Showing the real line num in diff

### PR DESCRIPTION
**Pull request by EbenZhang**
Some unrelated commits are showing in this pullrequst as I have to base on the pending combined diff branch.

Showing line numbers for combined diff is just partially supported, but i think it is good enough.

The code was oridinally copied/ported from my another MS-PL project(using the WPF version of ICSharpEditor -- AvalonEdit), but it's fine to contribute to GitExtensions as I am the author.

### CODE REVIEW

**Comment by EbenZhang** [comment]
Fixes #1328

**Comment by EbenZhang** [comment]
Screenshot:

reallinenumindiff

**Comment by EbenZhang** [comment]
Partially supported showing line number in combined diff
reallinenumincombineddiff

**Comment by Radrik5** [comment]
Looks great! Unfortunately, it's hard to review because the diff contains mix with combined diff changes. Maybe you will need to create separate pull request or update this one when combined diff get merged.

**Comment by EbenZhang** [comment]
I will rebase this one once the combined diff gets merged. Only the last two commits belong to this pr.

**Comment by Radrik5** [comment]
How does 'Go to line' work with new line numbers?

**Comment by EbenZhang** [comment]
It wouldn't work with new line numbers..., going to a line in the diff seems useless, do you have any suggestion?

**Comment by Radrik5** [comment]
I think we should either disable it for diffs or implement 'Go to left/right line'.

**Comment by spdr870** [comment]
Disable the goto line would be nice indeed.

I am currently reviewing the changes. I really like the line numbers. There is a strange bug that in some occasions the diff is not showing as a diff, with the red and green highlights.

diffbug

The changing marging/layout to show the line numbers are a bit annoying though. Not sure what to do about it yet, will do some testing to try and improve. Also, the design is little different than the normal line numbers. The dashed line (border?) between the numbers and the content is missing. This pull request seems required for pull request EbenZhang/EbenCompareToBranch, because the line numbers in the compare branch dialog are otherwise missing.

**Comment by EbenZhang** [comment]
> There is a strange bug that in some occasions the diff is not showing as a diff, with the red and green highlights.

I will fix the highlight issue in pull request #2866

**Comment by EbenZhang** [comment]
> I will fix the highlight issue in pull request #2866

I take my word back. It seems hard to do it on the old branch though; therefore I just fix that in this pull request.

Will disable the GotoLine function later this week hopefully.

**Comment by EbenZhang** [comment]
GoToLine is now disabled when showing diff.

**Comment by EbenZhang** [comment]
> The changing marging/layout to show the line numbers are a bit annoying though. Not sure what to do about it yet, will do some testing to try and improve. Also, the design is little different than the normal line numbers. The dashed line (border?) between the numbers and the content is missing.

@spdr870
I don't understand what is the problem here and what are you expecting. Also where is the dash line, do you mean the dots(spaces) between the num and the file content?

**Pull request merged**
