### PR TITLE
WIP - branch tree view

### PR DESCRIPTION
**Pull request by KindDragon**
Pull request just to simplify tracking progress on feature #538
- [ ]  [GitHub issues - bergerjac](https://github.com/bergerjac/gitextensions/issues)
- [ ]  [GitHub issues - gitextensions](https://github.com/gitextensions/gitextensions/issues?milestone=9&page=1&state=open)
- [ ]  [code TODOs](https://github.com/bergerjac/gitextensions/blob/ce422385e48d380aea1f15b44925ebb733b675dd/GitUI/RepoObjectsTree/ROT.ContextActions.cs#L75)
- [ ]  [`NotImplementedException`](https://github.com/bergerjac/gitextensions/blob/ce422385e48d380aea1f15b44925ebb733b675dd/GitUI/RepoObjectsTree/ROT.Nodes.Remotes.cs#L165)
- [ ]  Issue #1784

### CODE REVIEW

**Comment by timofonic** [comment]
@RussKie @KindDragon @jbialobr @bergerjac @gerhardol @Gua-naiko-che Any news about this? I'm sure you all are very busy, I'm just surprised this PR is opened since 2013 and not resolved. What happened?

**Comment by RussKie** [comment]
> What happened?

As you can see the code got stale... 
I have no idea what it is meant to do, but judging from the name of the PR a similar behavior is proposed by @EbenZhang in #3038. That PR was in flight for some time as well, but it's been kept current. I hope to get to review it at some point.

**Comment by EbenZhang** [comment]
mine was based on this.

**Comment by RussKie** [comment]
I'm closing this PR as it is outdated and @EbenZhang's work is based on this.

**Pull request closed without merging**
