### PR TITLE
Plugins/FindLargeFiles: Fix a bug when files to be deleted have spaces in its name

### LINKED ISSUE #2245: FInd large files plugin does not handle spaces in names
The 'File large files' plugin does not remove files which contain spaces in their paths. There is no feedback to indicate why the file is still present the next time the plugin is launched. It (silently) fails because the file name searched against is not quoted: 

``` bash
>"git" filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch doc/datasheets/file to remove.txt" --prune-empty -- --all 
                                                                            ^----   should be quoted    ----^
```

This will remove the file as expected:

``` bash
>git filter-branch --index-filter 'git rm -r -f --cached --ignore-unmatch "doc/datasheets/file to remove.txt"' --prune-empty -- --all
```

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 5.1.2600 Service Pack 3

### PR DESCRIPTION
**Pull request by DDuarte**
Fixes #2245.

Changes proposed in this pull request:
 - Fix a bug when files to be deleted have spaces in its name

I didn't have a chance yet to test this locally.

### CODE REVIEW

**Comment by RussKie** [comment]
Let's add tests to confirm your change is correct.
Please move command creation into a pubic method which we can then test. For example:

```
public sealed partial class FindLargeFilesForm : GitExtensionsFormBase
{
    // ...
    
    public string GetDeleteCommand(IEnumerable<string> paths)
    {
        if (objects == null) 
        {
            throw new ArgumentNullException(nameof(object));
        }
        
        StringBuilder sb = new StringBuilder();
        foreach (string path in paths)
        {
            sb.AppendLine(string.Format("\"{0}\" filter-branch --index-filter \"git rm -r -f --cached --ignore-unmatch {1}\" --prune-empty -- --all",
                _gitCommands.GitCommand, path));
        }

        sb.AppendLine(string.Format("for /f %%a IN ('\"{0}\" for-each-ref --format=%%^(refname^) refs/original/') DO \"{0}\" update-ref -d %%a",
            _gitCommands.GitCommand));
        sb.AppendLine(string.Format("\"{0}\" reflog expire --expire=now --all",
            _gitCommands.GitCommand));
        sb.AppendLine(string.Format("\"{0}\" gc --aggressive --prune=now",
            _gitCommands.GitCommand));
            
        return sb.ToString();
    }

    private void Delete_Click(object sender, EventArgs e)
    {
        if (MessageBox.Show(this, _areYouSureToDelete.Text, _deleteCaption.Text, MessageBoxButtons.YesNo) == DialogResult.Yes)
        {
            var command = GetDeleteCommand( _gitObjects.Where(gitObject => gitObject.Delete).Select(g => g.Path));
            _gitUiCommands.GitUICommands.StartBatchFileProcessDialog(command);
        }

        Close();
    }
}
```

Then you create a new test project under \UnitTests\Plugins called FindLargeFilesTests and create FindLargeFilesFormTests.cs in it.

**Comment by mast-eu** [comment]
@DDuarte : Are you still interested in this PR?

**Comment by DDuarte** [comment]
@mast-eu: yeah but I'm not able to add tests
If that's a requirement this PR can be closed

**Comment by mast-eu** [comment]
> I'm not able to add tests

Because you don't have necessary time or access to a suitable development environment?
Or because you are not sure how to do it exactly?
It the later case, you can always start and ask for help when you get stuck.

**Comment by GintasS** [comment]
This is an old PR and should be closed or set to a draft. @gerhardol

**Pull request closed without merging**
