### PR TITLE
Upgrade pkg SmartFormat to v3.0.0

### PR DESCRIPTION
**Pull request by axunonb**
Refers to https://github.com/gitextensions/gitextensions/discussions/9909#discussioncomment-2410663

## Proposed changes

- Upgrade package `SmartFormat` to v3.0.0, using the `Core` instead of the `Full` package, getting rid of unnecessary dependencies
- Brings higher performance in speed and memory footprint ([more details](https://github.com/axuno/SmartFormat/wiki/Why-Migrate))
- Fix: To achieve the same error behavior as in pre v2.5.0, formatter exceptions **and** parser exceptions must be set to "ignore". The latter was missing when migrating to v2.5.0

## Test methodology 

- Existing unit tests succeed with the updated package
- Manual, testing for English, French and German translations display okay (random samples)

## Test environment(s) 

- GIT 2.33.0.windows.2
- Windows 11 Pro

## Merge strategy

- I agree that the maintainer squash merge this PR
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
Thank you.
Works for my dev build.
I have not checked whether the installer is affected.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
You can test the installer: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/42996818/artifacts

**Comment by axunonb** [comment]
> You can test the installer: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/42996818/artifacts

The installer is working, too.

**Comment by RussKie** [comment]
Thank you.

**Comment by RussKie** [comment]
@axunonb have you installed the update?
I'm getting this error using the [latest build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/43040750/artifacts):

- Git Extensions 4.0.0.13624
- Build 9d7b5b6e9e02977599f29f35ffcfeb810c0eb62d (Dirty)
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.3
- DPI 96dpi (no scaling)
```
System.IO.FileNotFoundException: Could not load file or assembly 'SmartFormat.ZString, Version=3.0.0.0, Culture=neutral, PublicKeyToken=568866805651201f'. The system cannot find the file specified.
   at SmartFormat.Core.Output.ZStringOutput..ctor(Int32 capacity)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, IList`1 args)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args)
   at SmartFormat.Smart.Format(IFormatProvider provider, String format, Object[] args)
   at ResourceManager.TranslatedStrings.GetAuthor(Int32 value)
   at ResourceManager.TranslatedStrings.get_Author()
   at ResourceManager.CommitDataRenders.TabbedHeaderRenderStyleProvider..ctor()
   at GitUI.CommitInfo.CommitInfoHeader..ctor()
   at GitUI.CommitInfo.CommitInfo.InitializeComponent()
   at GitUI.CommitInfo.CommitInfo..ctor()
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent()
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, BrowseArguments args)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

**Comment by mstv** [comment]
`SmartFormat.ZString` is missing in the installer. (But it is contained in the portable version.)

**Pull request merged**
