### PR TITLE
Left panel - branch  tree view

### PR DESCRIPTION
**Pull request by EbenZhang**
Create a pull request just in case someone is doing (or will do) the same thing.

A preview version can be downloaded from [here](https://github.com/EbenZhang/gitextensions/releases/latest)

lefttreepanel

### CODE REVIEW

**Comment by KindDragon** [comment]
Hi. We have PR #1778 that do similar thing on feature #538

**Comment by EbenZhang** [comment]
My branch was created based on that feature branch, and also targeting to it.

**Comment by KindDragon** [comment]
Too many changes, it is hard to understand :smile:

**Comment by EbenZhang** [comment]
OK, I created a separate pull request to merge master into leftpanel. #3046 
So this one can be simplified.

**Comment by Nochdarus** [comment]
Wow, thanks for posting that one, I was just about to do the same thing :)

**Comment by Nochdarus** [comment]
@EbenZhang I added you temporarily as upstream, I hope you don't mind. And tried out your left-panel. Looks fine to me, only one question - is it intended to have in brackets number of nodes, not number of branches recursively? E.g. in your screenshot you have 24, though it is number of branches outside of folders + number of folders.

**Comment by EbenZhang** [comment]
The dragdrop is an incompleted feature added by the original author to replicate gittower.

I disabled the dragdrop, but probably you have found one that i'v missed.

The number of branches is a bug.

**Comment by Nochdarus** [comment]
@EbenZhang  you mean like described here https://www.git-tower.com/help/mac/faq-and-tips/tips-and-tricks#faq-01 ? (I myself never worked with that one, I don't have a Mac, only Linux and Windows)

 I think to disable it for now is wise. We can make it a separate feature request and a separate branch.

Apart from this - pretty cool, works fine. I merged it with my branch for playground in my fork (which is growing from the master of original gitextensions). I had to merge only Strings.cs in resources and GitUI.csproj, for obvious reasons.

**Comment by Nochdarus** [comment]
Just a visibility suggestion:
May be make no border for mainTree and backColor Control so that there is more space around?

And then it will be ok slightly increase the font size (either provide separate setting for the tree font or just take AppSettings.Font and increase it slightly for the tree)
may be make a separate font selection for the tree, or at least make it a little bit bigger (here I just lazily hard-coded +1.5f (temporarily solution, just to show), for instance):
noborder backcolor font

**Comment by Nochdarus** [comment]
Anyhow, we need also to apply AppSettings.Font to the tree (or explicitly to top-level nodes as well), not only to the populated nodes, otherwise in case of bigger application font you can end up with "Branches" and "Remotes" being smaller than branch-names:
incorrectfontsizes

**Comment by Nochdarus** [comment]
And probably it would be logical to have Rename in the context menu for local branches.But it is not critical at all.

**Comment by pmiossec** [comment]
I'm also really pleased by the feature and think it's a great move forward for GitExtensions.
The only thing I think is missing is to be able to hide it for those that don't want to use it or, like me sometimes when I need more place to display some data in the right panel (in the diff for example...)

**Comment by Nochdarus** [comment]
@pmiossec you can move the border between the left and right panels in the same way you can move it between lower panel and upper panel

**Comment by pmiossec** [comment]
I know, I did but that's not as elegant...

**Comment by vbjay** [comment]
Why not implement dock panels like Visual Studio?

**Comment by Nochdarus** [comment]
I am using this nice feature for quite some time in my fork (only with minor visibility adjustments) and it is fine.

So what about it being updated with the current master and eventually merged?

@EbenZhang  But recently I decided to update everything locally to be in sync with the current master and failed... Can you please update this branch so that it is easily mergable with the current master?
I got like 5 conflicting files and I couldn't resolve couple of the conflicts properly.

Thanks in advance!

**Comment by l-inc** [comment]
I'd love to use merge this pull-request locally, but unfortunately it doesn't work with mono:
```
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationCore' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationFramework' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'WindowsFormsIntegration' not resolved
```

**Comment by EbenZhang** [comment]
> I'd love to merge this pull-request locally, but unfortunately it doesn't work with mono:

Working on this, will be fixed soon. Refactoried the SearchWindow, currently testing.

**Comment by Nochdarus** [comment]
Do you plan to add also submodule and may be subtree overview in the left panel?

**Comment by EbenZhang** [comment]
> Do you plan to add also submodule and may be subtree overview in the left panel?

I don't have much time working on this project recently. (maybe after March/2017)

**Comment by EbenZhang** [comment]
Retargeted this branch to master.

**Comment by Nochdarus** [comment]
Thanks for syncing it with master! 
But are references to WPFToolkit and Controls.Input.Toolkit should be in Product.wxs?
I think it is not referenced anymore in the project itself.

**Comment by EbenZhang** [comment]
> But are references to WPFToolkit and Controls.Input.Toolkit should be in Product.wxs?

I forgot to revert it. now reverted.

**Comment by l-inc** [comment]
@EbenZhang 
> Working on this, will be fixed soon. Refactoried the SearchWindow, currently testing.
> Reusable SearchControl			e59a9fd
> Use the SearchControl to achieve autocompletion of branches tree			dfaece6

Thanks a lot. Just tested. The left panel works now in mono.

**Comment by gerhardol** [comment]
I have tried to review this PR.
Using it, I see no problem, it works as advertised. I miss a menu option to highlight the branch in the revision grid. There are probable a lot of other functionality tweaks that could be done.

Briefly reviewing the changes, I see only minor problems (like const instead static readonly in GitModule). There are a lot of code added though, it is hard to review.

It would be nice to see more reviews and opinions about this PR.

**Comment by EbenZhang** [comment]
dont think rebase is possible, toooooo many conflicts to solve. might be able to squash some merge commits

**Comment by gerhardol** [comment]
Merge master into this. We need to make a squash merge anyway with this history.
The downside with this is that the maintainer sets the merge message, default all commit messages. The PR description is probably better, a separate message could be provided in a comment.

If the history has no interest when reviewing, you could squash merge and force push yourself (I do not like that myself, normally want to keep the history in local branch also after merge).

**Comment by vbjay** [comment]
He can create a local work branch that keeps his history and squash this
one.

**Comment by EbenZhang** [comment]
See #4499 for the squashed and rebased one. Leave this pull request in case someone needs the history for troubleshoot/blame.

**Pull request closed without merging**
