### PR TITLE
Add mnemonics to every menu item in FormBrowse

### PR DESCRIPTION
**Pull request by Timwi**
## Proposed changes

- Added mnemonics to a lot of menu items in the main window (FormBrowse, FormBrowseMenus)

### Before

image

### After

image

## Caveats

**Main menu bar:** The “GitHub” menu still doesn’t have a mnemonic. This is because the property `IGitPlugin.Name` is used to generate the menu label. I will investigate this further and maybe propose a course of action in Discussions at a later point.

**View menu:** There are too many menu items to assign mnemonics to all. It could be argued that this menu doesn’t need mnemonics everywhere because most people will set the options once and then leave them. However, it would be a relatively simple fix: we can move the 7 options from “Show revision graph column” to “Show build status text” into a submenu named “Columns”. Perhaps another set of options could also be grouped into a submenu. Please indicate whether I have your go-ahead to do this.

----
I agree that the maintainer squash merge this PR (if the commit message is clear).

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by Timwi** [comment]
Is this build failure something I can address?

**Comment by Timwi** [comment]
> Yes, update the translation file, have a look at that:

I already did that, and doing it again made no additional changes to the file. Anything else?

**Comment by mstv** [comment]
You can check https://ci.appveyor.com/api/buildjobs/rnr6gv9b43ae8x0a/artifacts/English.xlf for differences.

**Comment by pmiossec** [comment]
Looking at the error message, I wonder if it's not a problem of end of line

**Comment by Timwi** [comment]
I’ve removed it and there’s still a build failure... what now?

**Comment by pmiossec** [comment]
> I’ve removed it and there’s still a build failure... what now?

You also rebased your PR on top of master if I guess well.
And master is failing due to an error introduced by a previous PR merged. Just wait for this build error to be fixed.

**Pull request merged**
