### PR TITLE
Don't lowercase URLs

### LINKED ISSUE #5409: Bug: remote urls are mangled to lowercase in ExternalLinkRevisionParser::ParseRemotes
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Revision links make URLs lowercase, which changes the meaning of the url (introduced along with the feature itself in 8ef3c779e119d21208b7b0b6136f84df5a8e1a3f):

https://github.com/gitextensions/gitextensions/blob/b210331fb67b2362cc1c666ad49911d4666d85e0/GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs#L61-L78

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Add a remote with uppercase characters in the path name like `example.com/TEST`. Emit the entire remote pattern as the "caption" of the revision link, and observe that it is lowercase.

**What is the expected behavior?**

The case should match that of the actual remote url, because `example.com/TEST` and `example.com/test` are not equivalent URLs.

### PR DESCRIPTION
**Pull request by eric-wieser**
Changing the case of the path segment of a URL changes its meaning

Fixes #5409

Changes proposed in this pull request:
- Remove `.toLower()`

Screenshots before and after (if PR changes UI):
- N/A

What did I do to test the code and ensure quality:
- Nothing

Has been tested on (remove any that don't apply):
- Nothing

### CODE REVIEW

**Comment by gerhardol** [comment]
Seem reasonable. I have no case sensitive file server to test to.

Note however that this will break existing revision links where users have not followed the URL casing. It seems like BitBucket Server at least uses case correct name occasionally and lowercase in other situations. This must be clearly described in the issue description, which is linked from Release Notes and the closest we have to describe breaking changes.

**Comment by eric-wieser** [comment]
Is bitbucket server case-sensitive?

**Comment by eric-wieser** [comment]
If compatibility is really a concern here, then we could prepend `(?i)` to every regex, and require users to opt-in with `(?-i)`.

I don't think this is really worth it though.

Can someone make clear what if anything is needed from me in order for this to be merged>

**Comment by vbjay** [comment]
No need for (?i).  Just use the regexoptions enum.  That way it could be
configurable.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options

**Comment by vbjay** [comment]
Instead of peppering with (?i) use the enum in building the regex.  It can be set per link even.  

```c#
using System;
using System.Text.RegularExpressions;

public class Test
{
    public static void Main ()
    {
        // Define a case-insensitive regular expression for repeated words.
        Regex rxInsensitive = new Regex(@"\b(?<word>\w+)\s+(\k<word>)\b",
          RegexOptions.Compiled | RegexOptions.IgnoreCase);
        // Define a case-sensitive regular expression for repeated words.
        Regex rxSensitive = new Regex(@"\b(?<word>\w+)\s+(\k<word>)\b",
          RegexOptions.Compiled);

        // Define a test string.        
        string text = "The the quick brown fox  fox jumps over the lazy dog dog.";
        
        // Find matches using case-insensitive regular expression.
        MatchCollection matches = rxInsensitive.Matches(text);

        // Report the number of matches found.
        Console.WriteLine("{0} matches found in:\n   {1}", 
                          matches.Count, 
                          text);

        // Report on each match.
        foreach (Match match in matches)
        {
            GroupCollection groups = match.Groups;
            Console.WriteLine("'{0}' repeated at positions {1} and {2}",  
                              groups["word"].Value, 
                              groups[0].Index, 
                              groups[1].Index);
        }
        Console.WriteLine();
        
        // Find matches using case-sensitive regular expression.
        matches = rxSensitive.Matches(text);

        // Report the number of matches found.
        Console.WriteLine("{0} matches found in:\n   {1}", 
                          matches.Count, 
                          text);

        // Report on each match.
        foreach (Match match in matches)
        {
            GroupCollection groups = match.Groups;
            Console.WriteLine("'{0}' repeated at positions {1} and {2}",  
                              groups["word"].Value, 
                              groups[0].Index, 
                              groups[1].Index);
        }
    }
}
// The example produces the following output to the console:
//       3 matches found in:
//          The the quick brown fox  fox jumps over the lazy dog dog.
//       'The' repeated at positions 0 and 4
//       'fox' repeated at positions 20 and 25
//       'dog' repeated at positions 50 and 54
//       
//       2 matches found in:
//          The the quick brown fox  fox jumps over the lazy dog dog.
//       'fox' repeated at positions 20 and 25
//       'dog' repeated at positions 50 and 54

```

Compiled would not be required.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
