### PR TITLE
fix FormGitIgnore layout and scroll

### PR DESCRIPTION
**Pull request by RussKie**
* GitIgnore form now has scrollbars when editing the list of ignores.
* Form layout update

screen shot 2017-05-13 at 8 49 53 am
screen shot 2017-05-13 at 8 50 47 am

### CODE REVIEW

**Comment by jbialobr** [comment]
Would be nice to autosize controls. This is how it looks on my PC:
commands

**Comment by RussKie** [comment]
Hmm, I thought it would...
I'll do another round of testing and fix it

**Comment by RussKie** [comment]
Quite peculiar... on Win7 with 150% scaling -  all looks good
screen shot 2017-05-15 at 8 25 49 pm

on Win10 at 100% scale - the Save button is squashed, but the labels are ok
screen shot 2017-05-15 at 8 26 10 pm

Looks like the grip indicator may be to blame...

@jbialobr what DPI/scale factor are you running at?

**Comment by jbialobr** [comment]
DPI: 96, scale: 100% but I have the app font size increased by 2 points.

**Comment by RussKie** [comment]
I think I fixed it

100% scaling with application font +2 (SegoeUI, 11)

screen shot 2017-05-15 at 9 07 28 pm

**Pull request merged**
