### PR TITLE
Commit tab: show more information for parent and child commits

### LINKED ISSUE #1929: Commit tab: show more information for parent and child commits
When there are several children and the graph is rather complex like in the following screenshot...

2013-06-24_21-06-52_gitextensions z_vbjay_commituser - git extensions -_ debug _-

...it would be nice if there were more information to be seen for each link except for the commit hash. For example relative date, author, part of commit message etc.

### PR DESCRIPTION
**Pull request by EbenZhang**
For #1929 and #3150

commitsubject

### CODE REVIEW

**Comment by Radrik5** [comment]
I think this is too verbose. Maybe add an info icon next to the commit hash and show details in the tooltip?

**Comment by vbjay** [comment]
Instead of a tooltip, Why not create a commit info dialog that will let us
show the standard commit detail and then advanced info like size, file
count, in pack or loose, ...Whatever metrics we can get.  Make the info
icon a small info button with an icon like these.
https://www.iconfinder.com/search/?q=information.  They can click the
button to bring up the dialog and get advanced information.

**Comment by hypersw** [comment]
TortoiseHg has this all under an expander, and if you expand it, the same view just shows more information.

**Comment by vbjay** [comment]
Frankly I don't like that idea.  I would want a summary control like it is
now with customizable fields and then a dialog with a property grid or
listview that we could load up with all kinds of metrics and data.

**Comment by KindDragon** [comment]
I don't like making CoomitInfo bigger by default. Maybe it's better in the end, add a link - Show more info, that will add information about child and parents?
We need to think about it

**Comment by EbenZhang** [comment]
> I don't like making CoomitInfo bigger by default.

But you have plenty of space there. Why not make it bigger

**Comment by hypersw** [comment]
Eventually, I would like to have a view which has both commit info and diff.
That's about all you want to know of the commit on a regular basis (file tree is for advanced scenarios).
In THG, these two (info and diff) are joined in the single view, and that's very convenient. With GitExt, I have to always switch tabs to see who did the change and what was changed.
That's how I would propose to utilize the space for better usability.

**Comment by KindDragon** [comment]
@EbenZhang Iuse sometimes GitExt on virtual machine with low resolution or through Remote Desktop, with big CommitInfo block it's almost impossible to use it properly

**Comment by KindDragon** [comment]
@hypersw We don't show CommitInfo on all tabs exactly for same reason

**Comment by KindDragon** [comment]
@hypersw Youm mean commit info with commit body?

**Comment by jbialobr** [comment]
I think that tooltip would be just enough - these are rare cases when you need that extra info.
Tooltip gives more space to be used for a single commit so there could be added other useful fields ( date, author, full commit message) as requested in #1929.

**Pull request closed without merging**
