### PR TITLE
Fix for #5005 - RTF round-trip bug causes System.ArgumentException: File format is not valid

### LINKED ISSUE #5005: RTF round-trip bug causes System.ArgumentException: File format is not valid
**Do you want to request a *feature* or report a *bug*?**
REPORT BUG

**What is the current behavior?**
EXCEPTION

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open GitExtensions with any repository

2. Double click on any commit

3. Exception thrown: System.ArgumentException: File format is not valid

**What is the expected behavior?**

SHOULD OPEN CHANGES

**Environment you encounter the issue:**

WINDOWS10

- GitExtensions version:
- GIT version: 2.51.02 and 3.0.0-beta
- OS version: WINDOWS10

**Did this work in previous version of GitExtensions (which)?**
YES

argument-exception

### PR DESCRIPTION
**Pull request by mwerle**
Fixes #5005 

Changes proposed in this pull request:
- convert "\urtf" to "\rtf" before assigning back to RichTextBox.SelectedRtf
 
Screenshots before and after (if PR changes UI):
image

What did I do to test the code and ensure quality:
- Basic tests against my repositories to ensure code works
- Created a branch using international characters (REMAINING BUG: RENDERS INCORRECTLY NOW)

Has been tested on (remove any that don't apply):
- Windows 10 1803

### CODE REVIEW

**Comment by gerhardol** [comment]
Any repo where this can be seen?

**Comment by mwerle** [comment]
> Any repo where this can be seen?

You mean, where this issue can be reproduced? No, it's not repo-specific, it's machine-specific. Basically it's a bug in the dotnet framework starting in 4.7.1.

KeePass encountered the same issue earlier this year. See [this thread](https://sourceforge.net/p/keepass/discussion/329221/thread/7788872f/).

**Comment by RussKie** [comment]
The diff looks good to me, but I have no means to test it.
I'm happy to merge it, if it works for you.

**Comment by mwerle** [comment]
Ack, just double-checked the diff and I checked in a couple of left over code fragments from my testing (commented out).  Let me add another cleanup commit, sorry.

But yes, "Works For Me".

**Comment by RussKie** [comment]
Would you please send a matching PR to 2.51 branch as well.

**Comment by mwerle** [comment]
> Would you please send a matching PR to 2.51 branch as well.

What's the workflow in Git(Hub) to do so?

**Comment by vbjay** [comment]
Create a new branch based off the branch you want to place your commits on.
INTERACTIVE rebase using your branch, removing any commits not wanted in
the todo. Test functionality and resolve conflicts. Alter as needed. Create
a new pull request.

**Comment by drewnoakes** [comment]
> What's the workflow 

Following @vbjay's comments. Check out the 2.51 branch locally. Hopefully you can cherry-pick the commit you made against master onto the 2.51 branch, though you may have to do some manual work. When done, push your branch and when creating the PR on GitHub just be sure to select the correct target branch (2.51).

**Comment by mwerle** [comment]
Ok cheers, I had tried the rebase before asking and it failed.  Cherry-picking worked.

Actually, in my Git, it looks like my "fix" branch wasn't merged into master, it looks like it was squashed and cherry-picked. I don't submit pull requests very often so is this the expected outcome?

image

**Comment by drewnoakes** [comment]
> it looks like my "fix" branch wasn't merged into master

GitHub offers a few different ways to merge pull requests.

- Merge (probably what you expected)
- Rebase merge (replay changes on top of target branch)
- Squash merge (compact all commits into a single commit and apply to target)

It looks like the last method was used for that PR. Looking at #5005 I see you had a few commits that were fixing earlier commits and merging from upstream, so a squash merge is a good way to keep the history clean.

So yes the PR was merged insofar as the changes were applied. But your branch and the upstream ended up in different places.

**Comment by RussKie** [comment]
Yes, I've squash-merged it because the PR had a merge commit. This makes
history non linear and, in my experience, harder to deal with later.
The diff was also clean and straight forward that made it a perfect
candidate for a squash. If, for whatever reason, we would need to roll it
back it would be easy to do.

**Comment by mwerle** [comment]
Ok, no worries, was just a little confused looking at the history :)  And I'm guessing this might be why the "rebase" didn't work in order to apply it to the v2.51 branch. Eh, as you said, it's a tiny well-contained diff so cherry-picking was easy enough.

**Pull request merged**
