### PR TITLE
About layout

### LINKED ISSUE #5731: AboutForm shouldn't dance about
**Do you want to request a *feature* or report a *bug*?**

Layout bug.

**What is the current behavior?**

The AboutForm's cycling contributor text can wrap and push the rest of the UI down. This made me miss the "copy to clipboard" button.

image

image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Looks like the label doesn't extend the full width of the form. I'm at 150% scaling.

**What is the expected behavior?**

Clickable items remain static on the page.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5731

Changes proposed in this pull request:
- Make sure ALL contributors are shown
- Make sure only one contributor at a time is shown in label
 
Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
- Changed code to get Philip Daniels entry (143) and made sure it didn't bounce and include Sam.

Has been tested on (remove any that don't apply):

### CODE REVIEW

**Comment by RussKie** [comment]
As a separate PR please

**Comment by vbjay** [comment]
Sure. What is the preferred DPI format?

I can make it whatever format is desired?

**Comment by drewnoakes** [comment]
I have some local changes for the DPI string formatting. Will try and get them up tomorrow.

**Comment by drewnoakes** [comment]
> Will try and get them up tomorrow.

https://github.com/gitextensions/gitextensions/pull/5762

**Pull request merged**
