### PR TITLE
Minor accessibility improvements

### PR DESCRIPTION
**Pull request by mrexodia**
## Screenshots

reset dialog

commit dialog

### CODE REVIEW

**Comment by mstv** [comment]
@mrexodia, could you use the complete PR template, please, as well as sign the contributors.txt file?

**Comment by mrexodia** [comment]
I deleted all the irrelevant parts of the template, because the change is so trivial. So the short answer is no for both.

**Comment by mrexodia** [comment]
See #5941 and #5097

**Comment by RussKie** [comment]
Please sign contributors.txt, without it the PR won't be merged.

**Comment by mrexodia** [comment]
Unfortunately I do not agree with the `contributers.txt` document, which is why I tried to get this trivial change merged without me signing it.

More specifically:

> By signing this agreement, you are warranting and representing that
> you have the right to release code contributions or other content free
> of any obligations to third parties and are granting Henk Westhuis and
> Git Extensions project contributors, henceforth referred to as
> The Git Extensions Project, a license to incorporate it into
> The Git Extensions Project or related works under the **MIT** license.

This is a CLA not a DCO, however you name it. If you change it to GPL I will happily sign it.

However I hereby release all my changes under public domain and if that does not work for you [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/). That means you can do anything with them (preferably help disabled users by integrating them without giving credit).

**Comment by RussKie** [comment]
We are in a process of changing it to MIT and that's why the need to sign off from all contributors.

**Comment by RussKie** [comment]
You can read the discussion pertaining to the re-licencing in https://github.com/gitextensions/gitextensions/issues/4737

**Pull request closed without merging**
