### PR TITLE
Blame settings: Auto size for checkboxes

### PR DESCRIPTION
**Pull request by gerhardol**
## Proposed changes

Add scaling to checkboxes

Settings added in #9801/d6bfff8cb434c1dea4d642783ca9848ee0bce20a

## Screenshots 

See PR #9801

## Test methodology 

Manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
Please dock each control inside the tablelayout too.

**Comment by gerhardol** [comment]
Also adjusted sizes and bottom padding
(I adopted to 17 used in General page, 22 is used in some settings too).

**Comment by RussKie** [comment]
I meant docking each individual control _inside_ TLP, so that they all aling uniformly. It also presumably works better with autosizing of controls and host containers.

**Comment by gerhardol** [comment]
> I meant docking each individual control _inside_ TLP, so that they all aling uniformly. It also presumably works better with autosizing of controls and host containers.

This does not seem to be used by any other settings.
Seem to be OK (tested 200% too).

**Review by RussKie — APPROVED** [review]

**Pull request merged**
