### PR TITLE
Cleanup `GitCommandHelpers`

### PR DESCRIPTION
**Pull request by RussKie**
## Proposed changes

A number of very much mechanical changes aiming to bring more cohesion to `GitCommandHelpers` and overall grouping of implementations of git commands.
Before the change a number of implementation for git commands existed in `GitCommandHelpers`, as well as in a number of separate files with types inheriting from `GitCommand` abstract type. All of these scattered across different folders and namespaces.

Furthermore, `GitCommandHelpers` appears to have been turned into a dumping ground for random implementations. This work was aimed to undo this, and either move functionality with more-or-less obvious common purpose into own types, or moved into types that had exclusive use of functionality in question.

It is recommended to review commit-by-commit. ❗ **Do not squash!**

- Fix CommitTemplateManager can reference incorrect git module
- Move stray command defs from GitModule to GitCommandHelpers
- Move git commands implementations under Git/Commands
- Break out SSH related into GitSshHelpers
- Break out GitItemStatusConverter.FromStatusCharacter
- Break out submodules related into SubmoduleHelpers
- Break out parsing of GitCommandHelpers.GetAllChangedFilesCmd output into GetAllChangedFilesOutputParser
- Break out process related extensions into ProcessExtensions
- Break out FormFileHistory related methods
- Break out GitModule related methods
- Move GitCommandHelpers under Git/Commands

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
Nice cleanup.
I have looked at the changes, most are very motivated. (A few goes a little longer than I would have done, but this is just personal, I do not oppose the changes.) 

However, the changes are too big to be approved without enthusiasm. Moved code is hard to review. (#8275 helps to some extent, but there is still a need to align diffs.)

I will use this (and sort branches PR) in my private builds and believe this can be merged in days, regardless if I approve or not.

Gerrit +1

**Comment by RussKie** [comment]
Awesome, thank you!

**Review by gerhardol — APPROVED** [review]
Not much extra review, but I feel confident to approve

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
