### PR TITLE
 	Feature #2460: Option to disable prompt when committing without a branch

### PR DESCRIPTION
**Pull request by m35**
image

### CODE REVIEW

**Comment by vbjay** [comment]
Knowing that you are orphaned can be very important. I doubt anybody would
want that option. If it warns during a rebase, we could put logic to
prevent that but otherwise I would want to know that I'm orphaned.

**Comment by m35** [comment]
Ah thank you for the feedback. It makes me realize that the wording might need adjusting to make the option clear. 

The intent is to, by default, maintain the existing behavior when in headless state, so those wishing for the dialog will still see it.

It only introduces the alternative behavior to not show a dialog when in headless state, for those desiring that behavior. This is similar in nature to the Amend configuration option, where the dialog can be disabled. 

It seems like a great win-win for those wishing for either behavior. 

I'll take another look at the wording to see if it can be improved.

**Comment by EbenZhang** [comment]
> If it warns during a rebase, we could put logic to
> prevent that but otherwise I would want to know that I'm orphaned.

The merged #3239 has done the job to prevent the dialog during an interactive rebase.

**Comment by jbialobr** [comment]
>I'll take another look at the wording to see if it can be improved.

Maybe to be consistent with the warning message, the title could be:
`Commit when not working on a branch.`

**Pull request merged**
