### PR TITLE
Generate .NET installer

### PR DESCRIPTION
**Pull request by RussKie**
⚠️ DO NOT SQUASH

## Proposed changes

- Resurrecting https://github.com/gitextensions/gitextensions/pull/9458 proposed by @GintasS.
- Update publish location for native artifacts
- Remove unnecessary files from the published components (e.g. xml, pdbs, etc.)
- A major clean up of the MSI definition, including
    * remove all .NET Framework and .NET Standard related references
    * remove all localised resources
    * rebuild the component list from the published files
- Update the installer to require full uninstall before install
- Rework how the setup project is built reusing the older version of MSBuild and .NET Framework v3.5
- Bump the version to 4.0.0

## Testing

* Building and inspecting the content of the generated zip and msi
* Comparing the content of the generated zip and msi against the published counterparts
* Manual testing locally generated builds for blocked upgrade from pre-4.x versions
    image
* Manual testing locally generated builds for successful upgrades from 4.x_+ versions

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
@gitextensions/git-extensions-team do I have anyone brave to test the new installer?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41384454/artifacts

**Comment by RussKie** [comment]
Outstanding:

* [ ] Extra files in the portal archive
* [ ] Plugins renamed, e.g. instead of `\Plugins\DeleteUnusedBranches.dll` -> `\Plugins\GitExtensions.Plugins.DeleteUnusedBranches.dll`

**Comment by RussKie** [comment]
Latest build: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41432845/artifacts

**Comment by gerhardol** [comment]
Installed on top of a 3.5 version.
No startup
Event viewer

```
Description: A .NET application failed.
Application: GitExtensions.exe
Path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe
Message: Error:
  An assembly specified in the application dependencies manifest (GitExtensions.deps.json) was not found:
    package: 'ExCSS', version: '4.1.0'
    path: 'lib/net5.0/ExCSS.dll'
```

**Comment by RussKie** [comment]
Were you installing from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41432845/artifacts?

**Comment by RussKie** [comment]
New artifacts https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41434186/artifacts

**Comment by RussKie** [comment]
> Installed on top of a 3.5 version.

I've blocked that in the latest installer. There's too much difference between the versions, and it is impractical to try to implement an upgrade.

**Comment by gerhardol** [comment]
> Were you installing from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41432845/artifacts?

yes



> New artifacts https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41434186/artifacts

Uninstall required, works
(I did not uninstall the .net5 installations I have explicitly)

**Comment by RussKie** [comment]
It's kind of difficult to do an extensive testing in this area (e.g. it is time consuming).

I think these are the major use cases:
* [ ] brand new install
* [ ] manual upgrade from 2.x/3.x
* [ ] in-app auto upgrade from  2.x/3.x

There's also `choco upgrade` but I'll leave it for the Chocolatey maintainers/community to tackle.

**Comment by gerhardol** [comment]
Not releated to the installer but issues in master

Branch in titlebar requires a refresh
image

Several commands runs when starting to dashboard
May occur in 3.5 too
(git --version runs twice too, but once is for the settings check so that may be OK)
image

**Comment by gerhardol** [comment]
@RussKie Could you include #9386 with this PR?
They could be tested together.

**Comment by RussKie** [comment]
Sure

**Comment by RussKie** [comment]
I propose to merge this first, then pile on any further tweaks separately.

**Pull request merged**
