### PR TITLE
4485 fix

### LINKED ISSUE #4485: Find in the Diff tab fails to find text
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the Diff tab of the lower pane, the Find feature (searching across files) fails to find text that definitely exists in the diffs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Select a commit where multiple changed files contain the same text.
2. Go to the Diff tab in the bottom pane of the main window and make sure you can see the changes.
3. Right-click in the diff and choose Find to bring up the Find dialog.
4. Search for text that appears in more than one of the changed files.
5. Keep hitting Find Next. It will skip over many of the occurrences of the search text.

**What is the expected behavior?**
It finds every occurrence of the text in the diffs.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, in version 2.50.02.

### PR DESCRIPTION
**Pull request by jbialobr**
Keep only one path of loading diff into fileviewer control and await for diff being loaded.

Fixes #4485.
Relates to #4540 

What did I do to test the code and ensure quality:
Tested manually.
async/await occurrences need to be aligned with solution that will get worked out in #4501

Has been tested on (remove any that don't apply):
 - GIT 2.10 and above
 - Windows 7 and above

### CODE REVIEW

**Comment by RussKie** [comment]
Awesome work!

**Comment by RussKie** [comment]
AppVeyor builds are currently queued... no idea why or how to force them

**Comment by RussKie** [comment]
Once it builds, feel free to merge.
I'm done for the day.

**Comment by gerhardol** [comment]
> Now we need to back-patch 2.51 with the same fix....

@RussKie 
This PR handles async handling better in addition to fixing the problem. #4540 does not handle merge commits, but there are many other situations where merge commits are not handled correctly, that is not a regression.

**Comment by RussKie** [comment]
We still need to address the issue for 2.51 release, which we haven't.

**Pull request merged**
