### PR TITLE
Remove redundant await

### PR DESCRIPTION
**Pull request by ivangrek**
## Proposed changes

- Remove redundant await where is no needed

## Test methodology 

- Manually

## Test environment(s) 

- Git Extensions 33.33.33
- Build 22f3b681ffff7beec4a789bda7e9fa915cd62d45
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
@msftbot merge in 48 hours

**Review by drewnoakes — APPROVED** [review]
This kind of change:
- Avoids allocating some `Task` objects, but also
- Can make debugging more difficult as it means intermediate methods will not appear in stack traces.

**Comment by ivangrek** [comment]
It also avoids creating a state machine

**Comment by drewnoakes** [comment]
The overhead is minimal so I only recommend making this change in hot paths. It can be much harder to debug async code that is missing stack frames. This guidance has come out in other places too.

**Pull request merged**
