### PR TITLE
2141 simplify calling prune remote branches

### PR DESCRIPTION
**Pull request by martinwilkerson-scisys**
Adds a checkbox to the pull form which when selected will append --prune to the command line:

2141-simplify-calling-prune--fetch-selected

When Merge is selected, the prune checkbox is still enabled:

2141-simplify-calling-prune--merge-selected

When Rebase is selected, the prune checkbox is disabled and --prune will not be appended:

2141-simplify-calling-prune--rebase-selected

### CODE REVIEW

**Comment by martinwilkerson-scisys** [comment]
This pull request is intended to fulfil #2141.

**Comment by riccimatic** [comment]
Hi Martin,
 i think that the suggested change is very usefull, especially if the development is performed using a new branch for each issue to fix or to every new feature.

Thanks for your code.

**Comment by jbialobr** [comment]
>When Merge or Rebase is selected, the prune checkbox is disabled and --prune will not be appended:

What is the reason for that?

**Comment by KindDragon** [comment]
@jbialobr `git pull` doesn't support `--prune` option, but we can call `git remote prune origin` after `pull`
or even we can always use `git remote prune origin` for consistency

**Comment by jbialobr** [comment]
It does support. The support is not explicitly documented, but git runs internally git fetch followed by git merge/rebase in order to perform git pull.

**Comment by martinwilkerson-scisys** [comment]
I have just tested, and `git pull origin --prune` does indeed perform a prune as you would expect. With rebase prune is an unrecognised option. I will update this pull request so that prune can also be called during a pull. Thank you @jbialobr for pointing this out.

**Comment by RussKie** [comment]
Please squash

**Comment by jbialobr** [comment]
>With rebase prune is an unrecognised option.

It works with rebase as well. I use git 2.10.

**Pull request merged**
