### PR TITLE
Remove use of git:// protocol in GitHub plugin

### LINKED ISSUE #10867: GitHub "View Pull Requests..." > "Fetch to pr/ branch" only works for HTTPS repos
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Trying to manage github pull requests through gitextensions. While the initial windows successfully lists all the PRs, all the commands on the "View Pull Requests..." dialog fail to connect to github.com unless the repo is an HTTPS repo. All normal functions are working under a SSH repo.

Tried with multiple repos and PRs.

ssh Repo:
```
"C:\Program Files\Git\bin\git.exe" fetch --no-tags --progress git://github.com/tshirt102/dsfix.git master:pr/n44_master
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Unknown error

Done

Press Enter or Esc to exit...
```

HTTPS Repo:
```
"C:\Program Files\Git\bin\git.exe" fetch --no-tags --progress https://github.com/tshirt102/dsfix.git master:pr/n44_master
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 3 (delta 1), reused 1 (delta 1), pack-reused 2
Unpacking objects: 100% (3/3), 985 bytes | 46.00 KiB/s, done.
From https://github.com/tshirt102/dsfix
 * [new branch]      master     -> pr/n44_master
Done

Press Enter or Esc to exit...
```

Manually running the same fetch command with "git@github.com:" works

```
$ git fetch --no-tags --progress git://github.com/tshirt102/dsfix.git master:pr/n44_master
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Unknown error


djc5166@Rukia MINGW64 /i/src/dsfix[PeterTH] (master)
$ git fetch --no-tags --progress git@github.com:tshirt102/dsfix.git master:pr/n44_master
From github.com:tshirt102/dsfix
 * [new branch]      master     -> pr/n44_master
 ```

So I guess the question is where it gitextensions getting git:// from? Or is this a GitHub issue?

### Steps to reproduce

- Add SSH github repo (with active PRs) to gitextensions
- Select GitHub>"View Pull Requests..."
- Select a PR
- Select "Fetch to pr/ branch"
- git fetch command reports it fails to connect to github.com

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by pmiossec**
as it is no more supported by GitHub

https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

Use ssh instead...

Fixes #10867

Depends on https://github.com/gitextensions/Git.hub/pull/21

## Test methodology 

- Not tested 😢 (as I don't use ssh). Hope that @djc5166 will be able to test it...

## Test environment(s) 

- Git Extensions 33.33.33
- Build 7dc4416813cc2d37cbdfab7b3dca932b8e61fae2 (Dirty)
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
PR for GitHub submodule first please... (that change is fine for me)

**Review by gerhardol — COMMENTED** [review]
+1
But submodule to be updated first

**Review by RussKie — APPROVED** [review]

**Comment by pmiossec** [comment]
@djc5166 Can you test the portable version for this fix and confirm that it is working well for you? It's there: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46764408/artifacts

**Comment by djc5166** [comment]
> @djc5166 Can you test the portable version for this fix and confirm that it is working well for you? It's there: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46764408/artifacts

Works, thanks for the fix.

**Comment by pmiossec** [comment]
> Works, thanks for the fix.

Thanks for the test 😉

**Pull request merged**
