### PR TITLE
Extract "Revision Diff" control from FormBrowse

### PR DESCRIPTION
**Pull request by RussKie**
The source moved almost verbatim from FormBrowse to the new control.
Minimal changes to facilitate the plumbing. It is something to revisit at a later stage.

### CODE REVIEW

**Comment by RussKie** [comment]
@gerhardol FYI

**Comment by gerhardol** [comment]
OK, will keep my PRs open until I create new.
I looked at the code, but as it is a cutout, nothing to say.

**Comment by RussKie** [comment]
You may wish to rebase

**Comment by gerhardol** [comment]
I will make new PRs to reimplement the changes affecting FormBrowse. May take some time to clean this up.

**Pull request merged**
