### PR TITLE
Remove the old Visual Studio addin project (GitPlugin)

### LINKED ISSUE #4752: Remove support for VS addin prior to .vsix
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
GE supports building VS addin. In 2015/2017 the .vsix format is used primarily, but older MSVS can only use the old plugins.

The VS addins are ditributed in the installer.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Drop support for addin format (remove the GitPlugin project, not related to the GE plugins).

Considered but dropping from the issue:
The .vsix build should be published on AppVeyor and for GitHub releases too, currently it is only updated occasionally to Microsoft for users that do not build the vsix plugin explicitly. (Current version is 2.50.02)

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
unknown status for the addin

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #4752

Changes proposed in this pull request:
The VS addin is used in VS2010/2012/2013 and handled by the installer. 
 * Usage is low, probably not at all by any GE developers as VS2017 is required to build. (The vsix plugin can be adapted to work in 2012/2013 too though.)
 * The name of the project is GitPlugin which can be confused with the GE plugins
 * The VS addin gave me problems building some time ago, old references to VS 2005. (Solved by updating VS2017 to latest patch release). So the addin has maintenance issues, even if it unchanged.

What is not done:
 * Uninstall existing VS addons (they may be incompatible with updated GE).
 * Merge GitPluginShared into the VSIX plugin (also a confusing name). 

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by gerhardol** [comment]
There has been no reaction to the issue, I suggest to await merging this for another week or so still
The removal at this stage is clean, but if we make changes to GitSharedPlugin it will be difficult to undo the removal.

**Comment by RussKie** [comment]
Please resolve MC and merge it in, thanks

**Comment by RussKie** [comment]
@gerhardol bump, when you have a spare moment, thanks

**Comment by gerhardol** [comment]
I have not tried uninstalling yet. Need access to special computer with older Visual Studio.
Removed wip too quickly!

**Comment by RussKie** [comment]
I don't think we should support anything older than 2015.
We should make the old plugin available for download and remove any traces
of it from our codebase.

**Comment by gerhardol** [comment]
The problem is that the old addin has been installed by previous installers, we should remove it when updating GE.
Most functionality should work, but we may want to change GE interfaces that the plugin/addin uses...

**Pull request merged**
