### PR TITLE
Updated Putty to version 0.70 x86

### PR DESCRIPTION
**Pull request by andrey-helldar**
Update Putty plugins to 0.70 version for x86

### CODE REVIEW

**Comment by RussKie** [comment]
Is this x86 or x64 version?

**Comment by jbialobr** [comment]
It may be worth checking if the https://github.com/gitextensions/gitextensions/issues/3686 is fixed.

**Comment by andrey-helldar** [comment]
@RussKie It's a x86 version.

**Comment by andrey-helldar** [comment]
Downlpaded from [official website](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)

**Comment by gerhardol** [comment]
What tests have you done, what usage?
(I do not use PuTTY in GE myself)

**Comment by andrey-helldar** [comment]
The test is simple - I use puttygen and the pageant outside the Git Extensions build. And the fact that the developers of this program updated version 2017-07-08 means that it is ready for release. And in the current Git Extensions build, the package data version is old - 0.67 from 2016-03-05.

I can also provide a [changelog](https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html) showing which changes have been made since version 0.68:

### These features are new in 0.70 (released 2017-07-08):
* Security fix: the Windows PuTTY binaries should no longer be vulnerable to hijacking by specially named DLLs in the same directory, even a name we missed when we thought we'd fixed this in 0.69. See [vuln-indirect-dll-hijack-3](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-indirect-dll-hijack-3.html).
* Windows PuTTY should be able to print again, after our DLL hijacking defences broke that functionality.
* Windows PuTTY should be able to accept keyboard input outside the current code page, after our DLL hijacking defences broke that too.

### These features were new in 0.69 (released 2017-04-29):
* Security fix: the Windows PuTTY binaries should no longer be vulnerable to hijacking by specially named DLLs in the same directory, even the names we missed when we thought we'd fixed this in 0.68. See [vuln-indirect-dll-hijack-2](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-indirect-dll-hijack-2.html).
* Windows PuTTY should work with MIT Kerberos again, after our DLL hijacking defences broke it.
* Jump lists should now appear again on the PuTTY shortcut in the Windows Start Menu.
* You can now explicitly configure SSH terminal mode settings not to be sent to the server, if your server objects to them.

### These features were new in 0.68 (released 2017-02-21):
* Security fix: an integer overflow bug in the agent forwarding code. See [vuln-agent-fwd-overflow](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-agent-fwd-overflow.html).
* Security fix: the Windows PuTTY binaries should no longer be vulnerable to hijacking by specially named DLLs in the same directory (on versions of Windows where they previously were). See [vuln-indirect-dll-hijack](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-indirect-dll-hijack.html). WARNING: this fix turned out to be incomplete. 0.69 made further fixes in this area.
* Windows PuTTY no longer sets a restrictive process ACL by default, because this turned out to inconvenience too many legitimate applications such as NVDA and TortoiseGit. You can still manually request a restricted ACL using the command-line option `-restrict-acl`.
* The Windows PuTTY tools now come in a 64-bit version.
* The Windows PuTTY tools now have Windows's ASLR and DEP security features turned on.
* Support for elliptic-curve cryptography (the NIST curves and 25519), for host keys, user authentication keys, and key exchange.
* Support for importing and exporting OpenSSH's new private key format.
* Host key preference policy change: PuTTY prefers host key formats for which it already knows the key.
* Run-time option (from the system menu / Ctrl-right-click menu) to retrieve other host keys from the same server (which cross-certifies them using the session key established using an already-known key) and add them to the known host-keys database.
* The Unix GUI PuTTY tools can now be built against GTK 3.
* There is now a Unix version of Pageant.

**Comment by gerhardol** [comment]
> The test is simple - I use puttygen and the pageant outside the Git Extensions build

Thanks the motivation I wanted.
This is a good time to update, approving.

**Comment by gerhardol** [comment]
All: As the installer is not distributed until next RC, please test this manually too.

**Comment by EbenZhang** [comment]
The new putty works for me. @jbialobr @KindDragon  the speed limit issue seems also solved.

**Comment by BlythMeister** [comment]
@gerhardol since without this putty git extensions will not run against GitHub any chance we can get a early release or backport to current stable version as a hotfix?

**Comment by jbialobr** [comment]
@EbenZhang Great news. Thank you!

**Comment by RussKie** [comment]
Chris, as I mentioned on the PR - we will look into back-patching 2.51.

**Comment by gerhardol** [comment]
@RussKie Can you push to the 2.51 branch or should this be handled with a PR?

**Comment by RussKie** [comment]
Just cherry-pick and push

**Comment by gerhardol** [comment]
> Just cherry-pick and push

No privileges, builds not done...

**Comment by RussKie** [comment]
done

**Comment by RussKie** [comment]
Thank you all

**Comment by andrey-helldar** [comment]
Starting from February 28, 2018, the githab refuses to accept the key generated by the "SSH-2 RSA" method, returning an error:
```
FATAL ERROR: Couldn't agree a key exchange algorithm
(available: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,
ecdh-sha2-nistp521)
```

And offers one of the following types of keys:
```
Begins with 'ssh-rsa', 'ssh-dss', 'ssh-ed25519', 'ecdsa-sha2-nistp256',
'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'
```

The key with type `ED25519` can be generated in puttygen 0.70.

I think this will speed up the process of releasing the patch for the program. Maybe.

2018-03-01 09-29-42 process c openserver domains andrey-helldar sitemap
2018-03-01 09-28-44 add new ssh keys - google chrome
2018-03-01 09-29-06 putty key generator
2018-03-01 09-29-22 putty key generator

**Comment by RussKie** [comment]
Technically you don't need to wait for a fix from us.
There is nothing stopping you to update putty yourself - just copy them to your local installation folder
C:\Program Files (x86)\GitExtensions\PuTTY

**Comment by andrey-helldar** [comment]
Yes, I immediately updated the files.
Hurried with the statement. I apologize.

**Comment by vbjay** [comment]
I altered the settings to use my putty installation and use ninite.com to
keep it and all updated.

**Comment by RussKie** [comment]
@vbjay: anything to share with the rest of us?

**Comment by vbjay** [comment]
No.  Just went to the settings in GE and changed path to my installed putty
from ninite.  Ninite updated putty for me.

**Pull request merged**
