### PR TITLE
Enforce translations

### PR DESCRIPTION
**Pull request by RussKie**
## Proposed changes

- Update/cleanup appveyor.yml
- Enforce update to translations as part of a PR

I've tweaked the script to do the following:

* stage *.xlf files - this way we ignore EOL issues,
* check if there are any xlf files are modified, and if so:
    - capture and publish the diff for the xlf files as git-diff-xlf.txt
    - break the build
image

### CODE REVIEW

**Comment by pmiossec** [comment]
Could we fix the ` .\Build\transifex\UpdateLocalEnglishTranslations.ps1` script in this PR?

I think there is a `popd` command in the script.
When I run the script, the current directory is changed to be `.\Build\transifex\` and that is boring.
I would like the script to not change the current directory (to be able to launch the script multiple times without being obliged to return to the git repo root folder).

**Comment by RussKie** [comment]
> I think there is a `popd` command in the script.
> When I run the script, the current directory is changed to be `.\Build\transifex\` and that is boring.

Sorry, you've lost me here...
The script changes its working directory and, when it is done, changes it back to the original.
Why is this a problem?

**Comment by pmiossec** [comment]
>The script changes its working directory and, when it is done, changes it back to the original.
>Why is this a problem?

The problem is that it is also what I want but it is not working for me.
Adding a 'popd' at the end of the script fixes the bad behavior.

**Comment by RussKie** [comment]
Sorry, I have just realised, the script pushd's twice, and popd's once...
Thanks for pointing that out!

**Comment by RussKie** [comment]
> Howcome there is a Appveyor branch build too?

I think this is because I (accidentally) pushed to the main trunk and not into my fork.

**Comment by pmiossec** [comment]
Could the 'Git Status.txt' file contains the 'git diff' of the English.*.xlf files? To better see what is missing?

**Comment by mstv** [comment]
Perhaps a litte bit off topic: Though `GitUI/Translation/English.Plugins.xlf` is out of date and seems to have inconsistent line ends.

**Comment by mstv** [comment]
`Build\transifex\UpdateLocalEnglishTranslations.ps1` produces the inconsistent line ends.

**Comment by RussKie** [comment]
I've tweaked the script to do the following:
- stage *.xlf files - this way we ignore EOL issues, 
- check if there are any xlf files are modified, and if so:
  - capture and publish the diff for the xlf files as `git-diff-xlf.txt`
  - break the build

**Pull request merged**
