### PR TITLE
[wip] Summary of changes in revision grid for artificial commits

### PR DESCRIPTION
**Pull request by gerhardol**
Implements #4281

This is a wip on a the gigantic #5087 (not a wip any more but will be updated). The reason to not wait with submitting until #5087 is merged is that that PR changes the presentation slightly, I want to improve on that change and want to have the impression reviewed together.

Changes proposed in this pull request:
- Show changed/new/deleted files and changed/dirty submodules
- Use --porcelain=2 to enable presenting dirty/updated submodules without starting subtasks. This will be a separate PR

Only changes >0 are shown. ~~The changed/new/deleted files are always shown. Submodule changed/dirty is shown if there are submodules (this is changed from the first version).~~ (Index never have dirty submodules).  (dirty submodules will not be available for Git < 2.11) (The icon for submodules with changed commits is always Down, could be a separate icon).
 
Screenshots before and after (if PR changes UI) (0 changes is not shown in latest version):
- 
image

The following is fixed in the latest commits, will be a separate PR. Note that the screenshot exposes a bug also with the current version that appears together with unmerged, README.md is listed twice in Diff. 

What did I do to test the code and ensure quality:
- Manual
- Added tests for several scenarios - will be a separate PR.

Has been tested on (remove any that don't apply):
- GIT 2.17
- Windows 10

### CODE REVIEW

**Comment by jbialobr** [comment]
I prefer the prev version where there was no indicators for change type with 0 count. It was clear then at a glance what has changed, now I have to analyze and and filter out uninterested zeros. The zeros introduce only a visual noise.

**Comment by RussKie** [comment]
Do we need to show zeros (e.g. "- 0")?

**Comment by gerhardol** [comment]
> Do we need to show zeros (e.g. "- 0")?

No (I never liked them myself). Removed in latest update.
See the discussion with jbialobr (hidden in all drew's commits).

**Comment by RussKie** [comment]
Yes, I thought I saw it in the myriad of emails :)

**Comment by gerhardol** [comment]
This branch is now merged to v3-ux, the master-to-be branch.
I can keep this open for review purposes but do not plan to push more changes.

**Comment by drewnoakes** [comment]
Here's a screenshot from the `v3-ux` branch:

image

**Comment by drewnoakes** [comment]
After DPI scaling the image padding:

image

The avatar image padding needed scaling as well.

**Comment by drewnoakes** [comment]
image

Threw a quick tooltip on the column. Not sure what the text should say. Will get it pushed up tomorrow for your review. It's late here now.

**Comment by gerhardol** [comment]
@drewnoakes 
Aligning: Good, but as you indicate, decrease margin a little. 5?

ToolTip: I want to have something that adds value in the tooltip, this is what you see already. (There is a point in consistency both here and for non-overflow messages though so you get a tooltip for all rows.)

Something like the following would fit me well, listing up to three files in each category and a summary if exceeding.
(Eventually we want details for submodules too, like commits before/after but I suggest that is done later.)

Changed:
 file.cs
file2.cs
 file3.cs
Total 10 files changed

Added:
temp.tmp
temp2.tmp
file4.cs

Modified submodules:
Externals/ConEmu

**Comment by drewnoakes** [comment]
Margins: I tweaked things and came up with (at 200% scaling):

image

Tooltips: At first I didn't know what the number meant -- lines changed, files changed, ...

I added details of the changed files. How does this look?

image

**Comment by vbjay** [comment]
Just watch out for massive file list of changes. Might want to limit the count so you don't create a tooltip that covers the screen.

**Comment by drewnoakes** [comment]
@vbjay thanks, yeah, it does that. I just didn't have many files modified.

**Comment by vbjay** [comment]
Add to the commit tab the full info that the tooltip would say. Use ... in tooltip. This would allow user to select and copy whatever they want from that info.

**Comment by drewnoakes** [comment]
Took me a minute to understand your meaning. I think you mean to include this text here:

image

Seems like a good idea.

**Comment by vbjay** [comment]
Collapsable, scrollable, readonly textbox.

**Comment by vbjay** [comment]
You got it.

**Comment by RussKie** [comment]
I like the visualisation, but are we _really_ adding value with the tooltip? A picture paints a thousand words, they say. 
In day to day job (and here) I see a lot of PRs span dozens of files, I can't see the tooltip adding much value beyond what the visuals do...

**Comment by gerhardol** [comment]
> I like the visualisation, but are we really adding value with the tooltip? A picture paints a thousand words, they say.

Yes, this adds value.
Just seeing if submodules are changed is a big difference. If I switch branch, it is quick to see that there are submodules to update. Not something I want to do by default, it can take up to 30s with many levels of submodules.
However, I still have to select the worktree commit, then the diff tab (still hating that the filetree is visible) to see the actual changes. The tooltip makes this step unnecessary.

With many changes, you still have to go to the Diff tab.
(I believe 3 files are sufficient here.)

**Comment by drewnoakes** [comment]
The first time I saw these icons, I intuitively moved the mouse over them to see what they meant. If the tooltip just helps someone understand what each of the icons means, it's done its job.

I'm less fussed about adding the file names, though I can imagine they might be useful if, for example, you weren't expecting to see any changes and wanted to quickly see what they were. Opening the commit form or diff tab is likely to be slower than a quick tooltip reveal.

**Comment by gerhardol** [comment]
Closed in #5087

**Pull request closed without merging**
