### PR TITLE
RevisionGrid: Show more informative tooltips

### LINKED ISSUE #4990: RevisionGrid: Show more informative tooltips
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

1. tooltip with commit hash of wrong lane
grafik

2. missing tooltip at truncated/multi-line text and at truncated commit hash (ellipsis missing as well)
grafik

**What is the expected behavior?**

1. commit hash, [**to be discussed**: branches contained in / being at] and commit heading of lane under mouse
grafik
grafik
grafik

2. tooltip with truncated/multi-line text
grafik
grafik
grafik
grafik

**Environment you encounter the issue:**

- GitExtensions version: any (master)
- GIT version: N/A (2.17.0)
- OS version: N/A (Windows 7)

### PR DESCRIPTION
**Pull request by mstv**
Show lane information in tooltip for RevisionGrid.GraphDataGridViewColumn.
Show tooltips for RevisionGrid *always* if text has been truncated.

Fixes #4990.

Screenshots before and after (if PR changes UI):
- see issue, please

What did I do to test the code and ensure quality:
- manual testing with several repositories
- found that the **IsMessageMultilineDataGridViewColumn** has been **broken** during the last week (didn't have time to investigate it yet, but I'm going to) 

Has been tested on (remove any that don't apply):
- GIT 2.17.1.2
- Windows 7

### CODE REVIEW

**Comment by drewnoakes** [comment]
> found that the IsMessageMultilineDataGridViewColumn has been broken during the last week

In what way was it broken?

As part of the revision loading changes in #4988, populating this column no longer requires calling `git.exe` for every row just to work out whether there was more than one line in the commit message. Please let me know how it is broken and I'll be happy to fix it.

**Comment by mstv** [comment]
>> found that the IsMessageMultilineDataGridViewColumn has been broken during the last week

> In what way was it broken?

The column text "[...]" is not set anymore.
expecting grafik

**Comment by drewnoakes** [comment]
Bisecting shows the bug was introduced in dd6c20d88ca9ad62413e847263b56e7cb1f1b67d. I'll investigate.

**Comment by drewnoakes** [comment]
This PR looks good. There are a few small things to tidy up, but I'm going to merge this and do that tidying as part of other RevisionGrid work I'm doing. Getting this in now to prevent merge conflicts.

> The column text "[...]" is not set anymore.

The fix is merged. Thanks for flagging the issue.

**Comment by mstv** [comment]
Thank you for bugfixing the IsMessageMultilineDataGridViewColumn that quickly, @drewnoakes.
But the tooltip for this column (and the identical one for the MessageDataGridViewColumn) doesn't work correctly again yet:
It is empty if the revision's body has not been loaded yet. The row must be selected once to load the body. I haven't understood yet why this is necessary because the body has already been read to find out whether it is multiline or not.

There's another issue if the IsMessageMultilineDataGridViewColumn is hidden, i.e. AppSettings.ShowIndicatorForMultilineMessage == false.
Then there will be no tooltip for the MessageDataGridViewColumn.

I'll create a bug report for the second one now and solve it after you have finished the work on the RevisionGrid.
Shall I open new bug report for the first one? Or will you solve it with the other tidying?

**Pull request merged**
