### PR TITLE
CommitInfo: Workaround for `Show all tags`

### LINKED ISSUE #9934: Show all `Contained in tags` broken since .NET 5
### Environment

- Git Extensions 33.33.33
- Build bcd0c2617bdd4c842c9a707888f951af07c65ecd
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

### Issue description

RichTextBox seems to be unable to distinguish hyperlinks with the same description text.

grafik

### Steps to reproduce

Select an old commit, which is contained in many tags.
Open CommitInfo.
Click `[ Show all ]` in the `Contained in tags:` section.
--> The branches list is expanded instead of the tags list.

### Did this work in previous version of GitExtensions?

3.5.4
most likely broken since .NET 5
does not work with .NET 6 either

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9934

## Proposed changes

- Show both all branches and all tags regardless of which `[ Show all ]` link is clicked 

### Before

grafik

### After

grafik

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build b855fa621dd5ab924621b61a52f5633f39ab0230
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
...or we can modify the label to be "Show all tags".

**Review by gerhardol — APPROVED** [review]
OK for me
(may await other comments)

**Comment by RussKie** [comment]
@mstv I pushed an alternative fix that addresses the root cause, and retains the existing behaviour.

**Review by mstv — COMMENTED** [review]
👍 🚀
+2 (cannot approve "my" PR)

**Review by RussKie — APPROVED** [review]

**Pull request merged**
