### PR TITLE
Fixing #4264: added simplify-merges option when enabling full-history.

### LINKED ISSUE #4264: Add --simplify-merges when showing file full history
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When selecting "Show Full History" from the context menu in the File History form, the log command is extended with a "--full-history" option.
This includes every merge commit performed on the current file.

**What is the expected behavior?**
I would like to include an extra option: "--simplify-merges". This option retains the full history of the file, but cleans up the merges without commits. See https://git-scm.com/docs/git-log for further information about the option.

### PR DESCRIPTION
**Pull request by alberto-chiesa**
Fixes #4264 adding the simplify-merges flag.

Changes proposed in this pull request:
 - Add simplify-merges along full-history.
 
How did I test this code:
 - I built the project on my machine (Windows 8.1) and tested the output shows up as expected. The change is really straightforward.

Before:
image

After:
image

### CODE REVIEW

**Comment by RussKie** [comment]
Can you please add a toolstrip button, say, after the refresh button which acts as a switch for the feature?
I'm guessing we should persist the user choice in the `AppSettings` as well.

**Comment by alberto-chiesa** [comment]
I can try. Do you have any indications for `AppSettings` usage (i.e. code to salvage)?

**Comment by RussKie** [comment]
Have a look at AppSettings class and any boolean settings (e.g. `HighlightAuthoredRevisions`).

**Comment by RussKie** [comment]
Looks good.
There's one little problem - the toolstrip button does not reflect enabled state - open the file history form, click ShowFullHistory toolbar button, close and re-open the form. 
Expected: the button is toggled
Current: the button isn't toggled

**Comment by alberto-chiesa** [comment]
Ok! I just uploaded a fix for that. Should be ok, now.
I was evaluating if there is a use case for a simple --full-history without merge simplification, but I think that in a UI the --simplify-merges option is the way to go.

Let me know if there is something else you think is needed, and thanks for all the effort that goes into this wonderful piece of software.

**Comment by RussKie** [comment]
thank you

**Pull request merged**
