### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nhance**
Removes dragons because they are not real and have no basis in nature. Have you ever seen a dragon skeleton? There is no way a dragon can support its weight and there is no way the bones for the wings fit into the normal skeletal pattern of actual animals that exist.

## Proposed changes

- Removes dragons.
- They are not real.
- Some people dislike them.

## Test methodology 

- Question: Can you picture a dragon skeleton?
- Answer: No.

## Test environment(s) 

- Earth
- Reality

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by vbjay — CHANGES_REQUESTED** [review]
Dragons are real. You just have to believe. Have faith and be a dragon slayer.  Instead of taking away from our menagerie, add an animal.

**Comment by gerhardol** [comment]
What about unicorns?

**Comment by vbjay** [comment]
Frankly I think this is a poor way to become a contributing member. The whole point of it is to point out there are dev steam issues abound. Complaining over using dragons is silly. Instead tackle an open issue and slay away.

**Comment by RussKie** [comment]
I appreciate the effort, however, it carries no value.

**Pull request closed without merging**
