### PR TITLE
Update vs-threading analyzers and fix new diagnostics

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by RussKie** [comment]
@msftbot merge if @mstv approves

**Comment by RussKie** [comment]
@msftbot merge if @mstv approves

**Comment by mstv** [comment]
Thank you, Sam! I'll have a look at the details this evening.
There are still `ThreadAbortExceptions` after tests of the ROT (left panel):
[log with ex](https://ci.appveyor.com/api/buildjobs/b9c9y3seag0j4n51/artifacts/TestResult%236.2err.UI.IntegrationTests.log)
[build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/30672315)

**Comment by sharwell** [comment]
@mstv Due to the complexity of #7730, it's difficult for me to rule it out as the _cause_ of the hangs. Do you have a way for me to reproduce the failure with minimal to no changes to the code already in the master branch?

**Comment by mstv** [comment]
These hangs also happen without #7730! I extra pointed to the master commit d5a4408 and its build.
This build is displayed "green" (because of the unfinished switch to Arcade build) but one test hung.
Reproduction is difficult because it seems to depend on the testcases run before.

In #7730, I've added printf debugging in order to find out where it hangs.
BTW: Do you have better solution to merge several unfinished branches and test them together?

**Comment by sharwell** [comment]
I was able to reproduce the hang locally by changing the signature of the test:

```patch
-[Test]
-public void RepoObjectTree_moving_node_across_hidden_trees_skips_them()
+[Test, Combinatorial]
+public void RepoObjectTree_moving_node_across_hidden_trees_skips_them([Range(0, 100)] int iteration)
```

The failures did not appear to be influenced by tests running prior to the test in question (and this is a near guarantee provided for all tests by our `AfterTest` handler for the JoinableTaskFactory).

**Pull request merged**
