### PR TITLE
Feature/stash before rebase

### PR DESCRIPTION
**Pull request by minidfx**
Add the functionalities to stash or reset pending files before a Rebase and restore them after it whether the files have been stashed.

### CODE REVIEW

**Comment by Radrik5** [comment]
Could you please provide screenshots?

**Comment by minidfx** [comment]
Yes sure. I used the controls than the FormCheckoutBranch.
gitextensions

**Comment by minidfx** [comment]
The currently behavior is you can't make a rebase whether you have pending files and you have to close the rebase window to stash or reset them and reopen the rebase window.

When you work every day with this tool, It's a very helpful functionality.

**Comment by Ashod** [comment]
Great feature, thanks.

Q: What if you don't have any pending changes, would those options be visible? Disabled? We don't want to confuse the user into thinking they are doing something that isn't true. Best to be hidden, or disabled (better).

Suggestion (for a different PR): Add a "commit now" button that would open the commit dialog to stage and commit. This would also make the workflow seamless in case we are good to commit. I wouldn't mind if "commit now" closed the rebase dialogue and opened the commit dialogue instead (just to keep things simple and clean).

**Comment by minidfx** [comment]
Currently the stash is only done whether the local repo is dirty before the rebase, so I will disable the groupbox Local changes when the local repo is clean too.

**Comment by Radrik5** [comment]
Please consider using '--autostash' option of 'git rebase'.

**Comment by minidfx** [comment]
I used the argument --autostash instead of a push before and pop after the rebase, good tip!

I applied these modifications:
- New argument (bool)autostash to the RebaseCmd and RebaseRangeCmd.
- Change the way for generating arguments of the Rebase command.

Question: Can I apply the second modification to the entire GitCommandHelpers or I remove it to keep the previous way for generating arguments?

**Comment by Radrik5** [comment]
I'm not a maintainer of the project but I don't like the idea of yielding separate arguments. It gives me wrong feeling that the arguments are escaped correctly.

For example, each of the lines should add one argument:
yield return filename; // can contain spaces
yield return "--format=\"%H %P\"" // contains double quotes

**Comment by Radrik5** [comment]
Is it really helpful to have the 'reset' option without knowing what changes will be reset?
Maybe it's better to have only "Autosquash" check box next to the "Autostash" check box?

**Comment by minidfx** [comment]
Currently there is no filename as argument in my modifications and I think we should have 2 services for building a git command:
- 1 service for returning arguments of a command (yielded), for instance: rebase with optional argument
- 1 service for building arguments received, it responsible to build argument with space or not, depends the argument.

And the equivalent way is already used in the GitCheckoutBranchCmd.cs

Currently, I will not make too many changes because the issue is only to stash pending files before a rebase, I will revert the modifications of the method that use the yield keyword.

Yes I think the reset option is good. In our case, we like the behavior in the checkout form with the options stash or reset before the checkout. Sometime we have files that we don't need to commit or stash before a rebase.

**Comment by minidfx** [comment]
What about the PR @Ashod ? I won't remove the yield keyword because the I think the code is more comprehensible with this way.

**Comment by KindDragon** [comment]
Hi. I don't think we need "Reset" option in this dialog.
Maybe add only "Auto stash" checkbox like in Pull dialog

**Comment by minidfx** [comment]
I refactored my modifications, that should be more simple and reliable without the **Reset** option.

**Comment by KindDragon** [comment]
Thank you. Can you rebase on top of master to squash old changes and I will merge it.

**Comment by minidfx** [comment]
I'm on the Master branch and I merged the latest commits in my branch, I've just 3 files as diff. I've really need to Rebase on the master and force push the new one?

**Comment by KindDragon** [comment]
Yes, it would be nice if you rebase to remove merge commits

**Comment by minidfx** [comment]
Ok, I will.

**Comment by minidfx** [comment]
Done.

**Pull request merged**
