### PR TITLE
Check Before script failure to abort action

### PR DESCRIPTION
**Pull request by JuPrgn**
Follow #9001 to apply script failure detection to others `Before` events as suggested : https://github.com/gitextensions/gitextensions/pull/9001#issuecomment-801801009

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
@JuPrgn just FYI (and for subsequent PRs 😁), that's a good practice to do the PR from another branch than 'master'.

**Comment by JuPrgn** [comment]
Ok I will create new branch next time with feature name

**Comment by JuPrgn** [comment]
@pmiossec to squash my commits here I use "Force push with lease" on this branch is there another clean way to do this ?

**Comment by pmiossec** [comment]
> @pmiossec to squash my commits here I use "Force push with lease" on this branch is there another clean way to do this ?

No, that's the normal way to do it.

**Comment by JuPrgn** [comment]
I successfully tested `BeforePush`, `BeforePull`, `BeforeCheckout`, `BeforeMerge` and `BeforeFetch` using a script with :
- `exit 1` action is aborted
- `exit 0` action is done

It would be great to add a setting on script settings to let user select if he want do enable/disable abort on script failure. I don't know enough C# to add it myself but this could be a usefull feature.

**Review by gerhardol — COMMENTED** [review]
Only looked at the changes, seem to be what is expected

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
