### PR TITLE
GitExtensionsDoc for 3.00

### LINKED ISSUE #5693: GE documentation update for 3.0
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The documentation on https://git-extensions-documentation.readthedocs.io/en/latest/
describes 2.x right now, all functionality is not described though.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Update the screenshots (at least) to the 3.0 visual
New functionality (later 2.x and 3.0) should be described too.

**Environment you encounter the issue:**
n/a

**Did this work in previous version of GitExtensions (which)?**
Documentation is incomplete for later 2.x, was probably quite up to date in early 2.4x

### PR DESCRIPTION
**Pull request by gerhardol**
Point to 'master' for the doc subrepo

For the doc link in the app (FormBrowse), point to 'master' build of the doc repo
Update set_version_to.py to set the doc version link in FormBrowse, so it is not forgotten

Note: When merging release branches or running set_version_to.py on master, the explicit 'master' pointer will be lost.
This should not be critical

Closes #5693 

Screenshots before and after (if PR changes UI):
- n/a

What did I do to test the code and ensure quality:
- no code changes

Has been tested on (remove any that don't apply):

### CODE REVIEW

**Comment by gerhardol** [comment]
Documentation is updated in 3.00 but the minor script change is in master 3.1.0

**Comment by RussKie** [comment]
CodeFactor isn't particular happy with your PySkills 🤣

**Comment by gerhardol** [comment]
> CodeFactor isn't particular happy with your PySkills

I considered changing this (also before the CodeFactor warning) but kept the same design pattern as the existing code. I can change the existing too if that is preferred.

**Comment by RussKie** [comment]
I don't have a great deal of an opinion about python as I don't write in
it. Leaving it up to your discretion.

**Comment by gerhardol** [comment]
Will merge this tomorrow

**Comment by RussKie** [comment]
Thank you

**Comment by RussKie** [comment]
Do we need to port this to release/v3 as well?

**Comment by gerhardol** [comment]
Not needed in release, the version to point at should not change.

**Pull request merged**
