### PR TITLE
Browse Diff Submodule menu options for unstaged commit

### PR DESCRIPTION
**Pull request by gerhardol**
Similar the menu alternatives for uncommitted submodules in Commit popup

Part of #4031 

Changes proposed in this pull request:
 - Menu options
 
Screenshots before and after (if PR changes UI):
- This PR is related to #4089, the toolstrip separator is shared
image

How did I test this code:
 - Manual tests

Has been tested on (remove any that don't apply):
 - GIT 2.14 (no new Git operations)
 - Windows 7 and Win10

### CODE REVIEW

**Comment by RussKie** [comment]
Personally I find the new menu "too busy" and somewhat unorganised.

* Why is the second entry in bold?
* Does "save as..." for a submodule make sense?
* Does "reset to" for a submodule make sense?
* Does "cherrypick" for a submodule make sense?

**Comment by gerhardol** [comment]
> Personally I find the new menu "too busy" and somewhat unorganised.
I tried to not remove anything useful right now, starting with was obviously not working
The toolstrip after submodules is not visible here, shared with #4089.
>    Why is the second entry in bold?
This is a "special addition" inserted from FileStatusList, the handling is not changed.

For the other changes limiting what is visible, see #4083 
That removes some of the clutter too

I have tried to separate pull requests so they can be reviewed but they are very much related.

Some responses here:
>    Does "save as..." for a submodule make sense?
No

>    Does "reset to" for a submodule make sense?
Yes, you will reset to the commit you rest too. No automatic update though.

>    Does "cherrypick" for a submodule make sense?
> No, neither do Blame.

**Comment by jbialobr** [comment]
>Why is the second entry in bold?

It indicates the action to be performed on double click.

**Comment by RussKie** [comment]
> It indicates the action to be performed on double click.

I'm not sure I have seen anything like this anywhere else, seems unconventional.
It would probably confuse users more than help.

**Comment by vbjay** [comment]
Making the menu bold when it is the default is standard UI practice.  It is
not confusing.  Right click on any file in file explorer.

**Comment by RussKie** [comment]
I take it back - indeed there is a bold menu item, though it seems to be always the first one...
I gotta get more sleep....

**Pull request merged**
