### PR TITLE
Git for Windows updated to version 2.5.3

### LINKED ISSUE #2925: Please release a new version bundled with git 2.8
Git 2.5 is finally available on Windows. https://git-scm.com/download/win

### PR DESCRIPTION
**Pull request by linquize**
Git for Windows updated to version 2.5.3
Closes #2925

### CODE REVIEW

**Comment by Radrik5** [comment]
Why Git 64 bit? Git Extensions is 32 bit.

**Comment by linquize** [comment]
KDiff is also 64-bit

**Comment by vbjay** [comment]
It shouldn't matter. Git runs as its own process.

**Comment by KindDragon** [comment]
It's matter for 32-bit OS

**Comment by vbjay** [comment]
True. In that case we could detect the architecture and install the correct
msysgit. The installer will have to include both. Frankly. I don't see why
we can't have a small installer that downloads the correct one from git
scm.

**Comment by KindDragon** [comment]
> I don't see why we can't have a small installer that downloads the correct one from git scm.

Because no one have time to do that :smile:

**Comment by karyon** [comment]
so, what do we do? we could probably always bundle the 32-bit version, that would work, but is not so cool. bundling both and deciding at runtime bloats installer size. anything that is better and doesn't require downloading stuff in the installer?

**Comment by karyon** [comment]
actually, since previously the bundled git was 32-bit only as well, there is nothing getting worse by keeping it that way for now...

**Comment by KindDragon** [comment]
Updated to latest 43-bit version

**Pull request closed without merging**
