### PR TITLE
Fix exception thrown GitModule.GetRemotes on an invalid git directory

### LINKED ISSUE #6093: System.Exception opening an existing repository
## Current behaviour

1. Open one of my local repositories
after the repository is opened I got a System exception:
```
Unable to parse git command output.

Target System: System.Collections.Generic.IReadOnlyList`1[GitCommands.Remote] <GetRemotes>g__ParseRemotes|154_0(System.Collections.Generic.IEnumerable`1[System.String]) @ GitCommands.GitModule
```
Application: GitExtensions.exe [3.00.00.4433]

NBug: 3.00.rc2

CLR: 4.0.30319.42000

Please note that thes exception happens *only* when the left panel (the one enumerating branches and remotes) is visible. 
If I hide the the left panel, no exception arises.

## Expected behaviour

No exceptions opening a repo.

## Steps to reproduce

See Current behaviour section above

## Did this work in previous version of GitExtensions

Yes it works fine in GitExtensions-2.51.05

## Environment

- GitExtensions version: GitExtensions-3.00.00.4433
- GIT version: $ git --version
git version 2.20.1.windows.1

- OS version: Windows 7 Pro 64 bit
- .NET version: 4.0.30319.42000

### PR DESCRIPTION
**Pull request by amaiorano**
Fixes #6093 

## Proposed changes

- GitModule.GetRemotes no longer throws an exception if the module opened isn't a valid Git module; rather, it returns an empty list.
- Opening and closing Settings dialog doesn't throw an exception if a valid module isn't open.

## Test methodology 

- Manual testing

## Test environment(s) 

- GIT version 2.19.1.windows.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by amaiorano** [comment]
Looks like I broke some tests. Will take a look tomorrow.

**Comment by amaiorano** [comment]
I added review comments to the diffs directly. They don't show up here on the Conversation page, though...

**Comment by amaiorano** [comment]
@RussKie For clarity, there are 3 commits:

* Fix exception thrown from GitModule.GetRemotes on an invalid git directory
* Fix exception thrown when opening then closing Settings dialog on an invalid git repo
* Possibly better fix for GitModule.GetRemotes

The last commit provides an alternative to the first one. It might be easier to look at each commit separately, and let me know which one you prefer.

**Comment by RussKie** [comment]
I would opt for the initial approach you took.
Whilst the approach in eaf14dc may look simpler, it does create a coupling between this method and a `GitModule` implementation.

I would like to go the opposite way and break down the monolith of `GitModule` into smaller (preferably SOLID) classes that we can reason about.

This method is also only used in the ROT, and it is causing a bit of noise (e.g. #6093). All other access to remotes is done via `IGitRemoteManager`.
Looking through the use, we only need the information to display tooltips and the icon. I'm pretty certain we can get all the same information from .gitconfig.

I think we need to sit down and do a bit of API clean/make up. 
E.g. `IGitRemoteManager` is only interacts with configured remotes in .gitconfig it should probably be renamed to `IUserConfiguredRemotes` etc.
I'll open a ticket about it.

Right now I'm learning more towards that we need to completely remove `IGtiModule.GetRemotes` method.

**Comment by amaiorano** [comment]
> This method is also only used in the ROT, and it is causing a bit of noise (e.g. #6093)

Yes, this PR addresses that issue.

> I would like to go the opposite way and break down the monolith of GitModule into smaller (preferably SOLID) classes that we can reason about.

I agree with you, @RussKie. Do you think we should go with the first commit, get this in, and work towards getting rid of the remote functions on IGitModule afterwards?

**Comment by gerhardol** [comment]
Seem OK to me.

**Comment by RussKie** [comment]
Yes, lets get a minimal fix first and do a clean up as a follow up
Thank you

**Comment by amaiorano** [comment]
Removed the last commit.

**Comment by amaiorano** [comment]
Will merge in a few hours if no objections...

**Comment by amaiorano** [comment]
> Will merge in a few hours if no objections...

Oh, sorry @RussKie, I thought you had already approved. I didn't mean to presume. Thanks for approving!

**Pull request merged**
