### PR TITLE
Improve the clarity of tooltips for Rebase UI date options

### LINKED ISSUE #7708: new UI option for Rebase window - "ignore-date"
##  Feature description
1. add to the "rebase" window a new checkbox: "ignore-date"
2. add the same option to the context menu on a commit ("Rebase current branch on ...")

When checked/selected, it will apply "git rebase --ignore-date" which will change the dates of the rebased commits

also, take into account that this flag is incompatible with some other flags - [see here](https://git-scm.com/docs/git-rebase#_incompatible_options)
also, see [this question in StackOverflow](https://stackoverflow.com/questions/1579643/change-timestamps-while-rebasing-git-branch)

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by ADTC**
Fixes #7708 (latest comments about the tooltip clarity)

## Proposed changes

- Improve the clarity of tooltips for Rebase UI date options:
  - Ignore date
  - Committer date is author date
- Also, shorten the width of the tooltip by breaking text somewhere in the middle.

### Before

image
image

### After

image ~13% narrower
image ~19% narrower

## Test methodology

- Open the Rebase UI using Commands > Rebase...
- Hover on the two mentioned check boxes (date options).
- Observe the tooltips.

## Test environment(s)

- Git Extensions 4.1.0.14867
- Build 2c3150d01d9c76bd13c72a742c26ceafcbf9eb64 (Dirty)
- Git 2.33.0.windows.1 (recommended: 2.35.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.6
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

CC: @gerhardol for your review please.

### CODE REVIEW

**Comment by pmiossec** [comment]
> Sorry I didn't actually build the app on my system. I don't have the necessary tools right now. The change is a simple change of text strings only. It would be faster if someone who already builds this app regularly to help me with the screenshots. Thanks.

Watch for the artifacts of your PR build and you should have a portable version that you will be able to test
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/44248649/artifacts

**Comment by ADTC** [comment]
@pmiossec Perfect! Thanks for the tip. I have updated the screenshots and the versions.

**Comment by ADTC** [comment]
@pmiossec BTW: why is the artifact version 4.1.0 but we haven't had any release after 3.5.4? _Help > Check for updates_ says _No updates found_.

**Comment by RussKie** [comment]
> why is the artifact version 4.1.0 but we haven't had any release after 3.5.4? _Help > Check for updates_ says _No updates found_.

4.0 hasn't been released.

**Comment by pmiossec** [comment]
> @pmiossec BTW: why is the artifact version 4.1.0 but we haven't had any release after 3.5.4? _Help > Check for updates_ says _No updates found_.

I think that's because master is for v4.1 and release branch has been created ` release/4.0` but still not released.
But your commit will be backported to this branch if team decide it makes sense.
 
> Can I safely install the MSI file from the artifacts? 😆

It's an alpha version so 🤷‍♂️

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
> Can I safely install the MSI file from the artifacts? 😆

Yes.

**Comment by ADTC** [comment]
@RussKie thanks for the approval 🙂 

Regarding the MSI, it says I have to uninstall 3.5 first before I can install it. Would that mean I would lose all my settings and preferences?

**Review by gerhardol — APPROVED** [review]
Note: These tooltips are missing from the translation. The tooltip should be using a translation string. Same issue for several other tooltips. TT are not urgent. No request for change here.

**Comment by gerhardol** [comment]
> Regarding the MSI, it says I have to uninstall 3.5 first before I can install it. Would that mean I would lose all my settings and preferences?

The update is using .NET6 (instead of .NET4) and require an uninstall. User data is not removed.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
