### PR TITLE
Some work to sanitise colours for dark operating system themes.

### LINKED ISSUE #1947: Unreadable texts in dark theme
gitext
--- GitExtensions2.44, 1.8.1.2, Linux 3.8.0.25 with XFCE4 and mono 2.10.8.1

See the attachment.

### PR DESCRIPTION
**Pull request by mwerle**
Partially Fixes #1947 ?
(NB: Have limited time to contribute, but this seems to fix the worst of the issue)

Changes proposed in this pull request:
 - Change main listview background to use system colours
 - Various changes to control text to use system colours
 - Change system-colour to hard-coded colour for various items which have hard-coded background colours
- TODO: More colour fixes
 
Screenshots before and after (if PR changes UI):
- Before (NB: previously used a different dark theme which made the text completely invisible, as per the original bug report):
image

-After:
Default Windows 10 theme:
image

Dark Windows 10 theme:
image

How did I test this code:
 - Tried new code on Windows 10 with borth standard and dark theme installed.
 - TODO: Test on Linux/other platforms

Has been tested on (remove any that don't apply):
 - GIT 2.9.2
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
@mwerle how do you set dark theme in w10?

**Comment by mwerle** [comment]
@RussKie Basically you'll need to install the "UXThemePatcher" hack (and optionally a couple of others), as well as a theme pack. Be aware that installing these sorts of hacks -could- stuff up your system and/or introduce malware, so try at your own risk.

The following page has instructions and links:
http://www.makeuseof.com/tag/5-dark-themes-windows-10/

**Comment by RussKie** [comment]
Thanks Michael, I'll give that a go.
Mine is a throw-away system installed for this very purpose

**Comment by mwerle** [comment]
You might also want the "Stylish" plugin for your web-browser which will allow you to override the styles for web sites. Most popular sites have dark styles available.

**Pull request merged**
