### PR TITLE
Improved text and icon on StageAll and commit when Filter active #8596

### PR DESCRIPTION
**Pull request by keco2**
Followup on #8596 

The change affects only visual elements (i.e. no behavioural change) and is related only to the CommitForm when there are no staged files and the filefilter is active.

## Proposed changes

- 2 misleading texts updated to display either "All" or "Filtered" words based on the filter:
  -  if the Filter is empty (i.e. inactive), use the "All" word
  - otherwise use the "Filtered" word
- change the icon on the StageAll button interactively based on the filefilter:
  -  if the Filter is empty (i.e. inactive), use the classic StageAll picture
  - otherwise use another (new) picture with funnel

### Before

image
image

### After

StageAll (TooltipText/icon) - without filefilter:
image

StageAll (TooltipText/icon) - with filefilter:
image

OnCommitClick (message) - without filefilter:
image

OnCommitClick (message) - with filefilter:
image

## Test methodology 

- change of text in the MessageBox on Commit: Manual
- change of ToolTipText on StageAll button: Manual and 1x IntegrationTest
- change of StageAll picture: Manual

## Test environment(s) 

- GIT 3.4.2.9999+
- GIT 2.30.0.windows.1
- Windows 10 20H2

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
I was looking at your and wanted to warn you about some things but you created the PR in the mean time :(

So here it is:

1. (GitHub rule) Never create a PR from the `master` branch. Always create a branch. I think you could create your branch, push it and edit the PR to change the branch you want to merge from.
2. (Most of the projects rule) Prefer doing a `rebase` instead of a `merge` to sync with the upstream `master` branch. So it would be great if you could remove this merge commit.
3. You need to update the translation file to fix the build: https://github.com/gitextensions/gitextensions/wiki/Translations#v34-and-newer
4. Please create a new PR to update the `contributors.txt` file.
5. There is no real added values at having multiple commits because in your case changes are pretty straightforward, so, please, squash all the commits.

**Comment by pmiossec** [comment]
I just think about one thing: all what you did for "Stage All" should also be done for "Unstage All", no!?

**Comment by keco2** [comment]
Thanks for the feedback! Good point! But I am not sure - just tested the behaviour and it seems it was inconsistent even before my change:
* **StageAll** if filefilter is active: **only** the filtered files are getting staged.
* **UnstageAll** if filefilter is active: **all** the files staged are getting unstaged.

Now 3 questions popped into my mind:
- Should they behave the same way? Probably yes.
- Which one is the "correct" one? I prefer the StageAll behaviour but I am open to whatever decision.
- If so - is it a bug? Should be fixed within this issue or should I/someone create an issue for that?

**Comment by gerhardol** [comment]
>     * If so - is it a bug? Should be fixed within this issue or should I/someone create an issue for that?

Fix it here. I suggest you change it to what you suggested for Stage.
(I do not really consider the original problem to be an issue, but changing it is not a problem.)

GE is a community project, it is not all functionality that is consistent.

**Comment by keco2** [comment]
The other things, related to my PR - Thanks! I will do so. I changed to draft for now and will work on that..

**Comment by pmiossec** [comment]
Yes, "Stage All" must take the filter into account because that is really needed when you have a lot of files changed and only want a subset.

And staging all the files is just 2 clicks away (one to remove filter and one to stage).

The unstage all is a lot less used so it's less important but I also think that consistency could add value here. 

Side note: another solution could  have been to add new buttons for "stage/unstage filtered" but I don't know if it will end in a better UI. If someone thinks it is better, he should say it...

**Comment by keco2** [comment]
> (GitHub rule) Never create a PR from the master branch. Always create a branch. I think you could create your branch, push it and edit the PR to change the branch you want to merge from.

I've tried to edit the PR and change the source branch but it was not possible (only the target branch can be changed), so I've reset my master branch (force push from gitextensions/gitextensions ) but that caused my original PR being closed.  
Should I reopen it and somehow fix the source branch or just create a new PR?
Or just rebase the commit (from my feature branch) into the master and that way the PR reopens automatically?

I've created the
* new feature branch **feature/issue8596_stageall** with only one commit as suggested
* and a new branch **contributors_txt** for the separate PR (I'm not sure if that's the way it should be done)

Thx for any advice in advance!

**Comment by pmiossec** [comment]
I think the easiest for you is to create a new PR. That's not a problem because we didn't invest too much in this PR.
Just add in the description of the new PR a link toward this one saying that it superseded this one... (so that we are able to find it and read comment easily if needed)

**Comment by keco2** [comment]
Great, thank you!

**Pull request closed without merging**
