### PR TITLE
Added "Open With Git Extensions"

### PR DESCRIPTION
**Pull request by careri**
Add context menu item for the file tree to open a sub module. Reused the logic from double clicking a submodule.

### CODE REVIEW

**Comment by careri** [comment]
Is there any way to get information about the Compilation error?

**Comment by glen-nicol** [comment]
I get the same error on TC for my pull request. Not sure how to proceed because I can't see any more detail without an account.

**Comment by KindDragon** [comment]
Can you rebase your PR on latest changes?

**Comment by glen-nicol** [comment]
This is my first pull request. Can I just force push the rebased branch and will the pull request pick it up correctly? Or is there a way to change the branch to another?

**Comment by KindDragon** [comment]
Force push should be enough

**Comment by jbialobr** [comment]
Cherry-picked.

**Pull request closed without merging**
