### PR TITLE
Added tooltip for Commit&Push button showing push destination

### LINKED ISSUE #6118: Show push destination in commit dialog
## Feature description

The commit window allows to click "Commit & push". Unfortunately one does not see to where the commit is pushed. One has to go to: Main windows -> Repository menu -> Remote repositories -> tab: Default pull behavior -> find concerning branch.

I would be much nicer if the push destination branch was shown directly next to the  "Commit & push" button. Being able to change the tracked remote branch there would also be most awesome.

## Environment

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI X:100,00 % Y:100,00 %

### PR DESCRIPTION
**Pull request by LukeOwlclaw**
Fixes #6118 in the least invasive manner I could think of.

## Proposed changes

- Hint (tooltip) push destination for "Commit & Push" button
- Warn user when no tracked remote branch is configured:
  - If no tracked remote is configured, it seems that is defaults to "origin".
  - If no MergeWith configured, it seems that the local name is also used as remote branch name.
    - I did not try to understand in detail what happens internally. I think it is safer when the user does not use this option then. Maybe we even want to to disable the button then, but that's a different topic!

## Screenshots

image

image

### Before

There was no tooltip.

## Test environment(s) 

- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

### CODE REVIEW

**Comment by vbjay** [comment]
Tooltips have had issues in the past.  They love to stick around sometimes and hide when you want them.  I agree, add it to the statusbar.

Push To:....

**Comment by vbjay** [comment]
Ok.  I created a new branch and made goofy work and committed by hitting commit and push.  It pushed to origin and asked me questions about pushing to a new branch.  So don't disable button.  See if you can figure out where it will push to and put that value in.  

image

**Comment by vbjay** [comment]
git remote names run on a defacto standard.  

origin: where you cloned from (usually your forked repo that you will put your work in) vbjay/gitextensions for me.
upstream: the repo that you will send pull requests to by default, or the forked repo. gitextensions/gitextensions.

This is why we default to origin.  It is a defacto standard.

**Comment by pmiossec** [comment]
>One alternative could have been the status bar, where the branch is shown

I agree with that and an idea could be to display something like `release/3.00 -> origin/release/3.00`

**Comment by RussKie** [comment]
Good suggestions!

We can take it even further - a user could click on the status bar cell and
choose a desired remote.
We don't have to it now.

On Jan 19, 2019 9:45 AM, "Philippe Miossec" <notifications@github.com>
wrote:

One alternative could have been the status bar, where the branch is shown

I agree with that and an idea could be to display something like release/3.00
-> origin/release/3.00

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/pull/6128#issuecomment-455712373>,
or mute the thread

**Comment by LukeOwlclaw** [comment]
@gerhardol Very good idea to include it in the status bar. However, I could not follow what to show when no remote tracking branch in configured.

**Comment by RussKie** [comment]
Show nothing or "No remotes configured"

**Comment by LukeOwlclaw** [comment]
Closing in favor of https://github.com/gitextensions/gitextensions/pull/6158

**Pull request closed without merging**
