### PR TITLE
Fix SA1629 Documentation text should end with a period

### PR DESCRIPTION
**Pull request by drewnoakes**
While making recent changes for nullable reference types (#8771, #8776) SA1629 started appearing in the error list.

Just adding some punctuation. Nothing exciting here.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Can someone re-run the AppVeyor leg or let me know how to do it? I can't see why it'd fail with these changes.

**Comment by RussKie** [comment]
> Can someone re-run the AppVeyor leg or let me know how to do it?

## one way

1. Go to AppVeyor
image
2. Login
3. You should be able to rebuild 
image


## another way

1. close the PR
2. re-open the PR

**Comment by drewnoakes** [comment]
@RussKie thanks very much.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
