### PR TITLE
Added UWP wrapper for deploying GitExtension to Microsoft Store

### LINKED ISSUE #4498: Adding UWP wrapper project for deploying GitExtension to Microsoft Store
I think we need to upload this application to Microsoft Store. For this issue we have to make  wrapper app  in solution, what adapted WinForms apps for Store.

### PR DESCRIPTION
**Pull request by Jammer77**
I added a UWP wrapper, now we can deploy this app to Microsoft Store

Closes #4498

### CODE REVIEW

**Comment by gerhardol** [comment]
Please add an issue too:
https://github.com/gitextensions/gitextensions/wiki/Project-Workflow#new-features

**Comment by Jammer77** [comment]
https://github.com/gitextensions/gitextensions/issues/4498

**Comment by gerhardol** [comment]
Close/open the issue to get the AppVeyor build restarted

**Comment by RussKie** [comment]
The build is reported as successful yet it is failing
image

**Pull request closed without merging**
