### PR TITLE
Change text in settings for artificial commits

### PR DESCRIPTION
**Pull request by gerhardol**
Part of #4031
(Only #4209 remains)

Changes proposed in this pull request:
 - Change settings text to better explain the functionality
 
Screenshots before and after (if PR changes UI):
- 
image

Has been tested on (remove any that don't apply):
 - Windows 7 and above

### CODE REVIEW

**Comment by RussKie** [comment]
Argh... I just regenerated the localisable artifacts and pushed them to the Transifix....

We'll get this in for 2.51 if we agree quickly on #4247 and it is merged for 2.51.

**Comment by gerhardol** [comment]
Yes, I find this more important for #4247 Since @jbialobr was negative, I assume this will wait.

**Comment by RussKie** [comment]
Please don't take it as "negative". Perhaps, "less supportive" of the
immediate change.
The changes you've made are going in, just with a delay.

PS: My dashboard change has gone cold too and will need some serious
re-heat.

**Comment by gerhardol** [comment]
@RussKie No problem at all. If I do not submit changes, the changes may never happen. Thanks for the great job you are doing (and other before you). I will not always have the same opinion. I will adopt mostly, but not always....

I should have submitted this earlier but were awaiting the final PRs for  #4031 first (I considered other changes but dropped them). 

Next version or future.

**Comment by RussKie** [comment]
Since we are re-publishing the strings, we'll include this one too.

**Pull request merged**
