### PR TITLE
Rewrite git log parsing for revision grid/graph

### LINKED ISSUE #4813: Lingering git processes on rapid refresh
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Many `git.exe` processes lingering on the computer as children of `GitExtensions.exe`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Press the 'refresh' button in the browse form about once a second, for five to ten seconds.

image

image

**What is the expected behavior?**
These processes should not linger.

**Environment you encounter the issue:**

- GitExtensions version: `master` and `2.51.01`
- GIT version: 2.16.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
I don't know.

### PR DESCRIPTION
**Pull request by drewnoakes**
I'm working towards improving how we get data out of git processes. There's some stuff in flux on my `git-executable` branch that follows on from the ideas discussed in #4643. 

Design goals for that work are:

- Easy to use
- No duplication of effort / clear responsibilities
- Easier unit testing
- Great performance when we need it

The API that's forming on that branch so far addresses the first three criteria pretty well. This PR is the result of exploring ways to achieve the final point: great performance when reading from git processes.

The diff is pretty big but it's easy to follow commit-by-commit so long as you have the interest. I'll describe some key points here to assist in review and set the context for discussion.

---

At a high level, when you load/refresh the revision grid, a `git log` command is fired off that returns every reachable commit in the repository. For GitExtensions that's ~18,000 commits (depending upon your remotes). You can use the _Git Command Log_ to see the exact command GE uses. In 2.51.01 with no filters it is:

```
git log -z --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --all --boundary --not --glob=notes --not  --max-count="100000"
```

Let's time this and pump it through `wc` to see how many bytes we have:

```bash
$ time git log -z --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --all --boundary --not --glob=notes --not  --max-count="100000" | wc
 217503  520403 7060173

real    0m0.489s
user    0m0.171s
sys     0m0.108s
```

Git outputs 7,060,173 bytes of data in just under 0.5 seconds. I ran this a few times and the duration was pretty consistent.

In GE the class `RevisionGraph` (renamed to `RevisionReader` in this PR) is responsible for running the command, parsing the output and emitting `GitRevision` objects to whoever made the original request. Putting a `Stopwatch` around this activity and disabling the emitting of revisions allows us to measure how long it takes GE to consume all this data excluding UI activity.

## Results

We know the lower limit is around 500ms from earlier tests, which appears to be the lower limit that `git.exe` establishes.

Current `master` takes ~1400ms (900ms overhead). This PR takes ~700ms (200ms overhead).

With the UI wired up to receive revisions, `master` takes ~2300ms to complete. This PR takes ~830ms. I believe this difference is due in large part to a reduction in GC activity across threads.

On `master`, refreshing the revisions without UI updates allocates ~4 million objects, pushing ~320 MB through the GC (both allocated and collected during this time). This PR reduces allocations by an order of magnitude to ~400k objects, pushing ~38 MB through the GC.

## Optimisations

Quite a few techniques were used to reduce the number of allocations. I'll go through them in turn here.

Above we saw the `--pretty=format:"..."` argument passed to `git log`. This controls the fields git returns, their order and separators.

Here's an example:

```
<(__BEGIN_COMMIT__)>
1960c0626bd49962a298ae3ca21a1501b13bdb4f\n
9038f0abc23669e4053f4cb7204a14e0aeabcd02\n
bac5727139109b1ccb81a5cd5202276c6ef139a4\n
Drew Noakes\n
git@drewnoakes.com\n
1523796618\n
Drew Noakes\n
git@drewnoakes.com\n
1523990449\n
\0
Convert fields to properties\0
Convert fields to properties\0
```

- There's a special marker `<(__BEGIN_COMMIT__)>`.
- The SHA-1 lines are the commit ID, parent ID(s), tree ID. If there were multiple parents, they'd be on the one line separated by space.
- Next we have author name, email, timestamp, followed by the same again for committer.
- Then the encoding (a null-terminated string, blank in this case).
- Finally the subject, and the body.

There was a preprocessor that read the process's output stream into a string, then chunked that string up based on `\0` separators. A single message had potentially multiple separators, so there was a state machine to keep track of where the parser was. The string was decoded by the suspiciously named 'lossless' encoding, then split at `\n`, and parsed based on index. Strings were then turned _back_ into byte arrays (using the lossless encoding), before being _re-encoded_ based on the expected log output encoding, or the advertised encoding if present.

This process produces many temporary strings. Each byte was copied four or five times through encoding, splitting, re-encoding, trimming and so forth.

The approach in this PR rearranges the fields in a way that's less human-oriented but more sympathetic to the poor computer hardware.

```
%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b
```

This brings the total bytes output by `git.exe` down from 7,060,173 to 5,673,239. The time is not noticably different.

```
225851d3769171556b1a549f9b90b753ede0e89479599cd499ab02a21dce5a26a947244a1d7afb50753dd7ca94aeac47ddc1fdbf9ee027d0be1ac29e\n
1523990577\n
1523990577\n
\n
Drew Noakes\n
git@drewnoakes.com\n
Drew Noakes\n
git@drewnoakes.com\n
Commit summary message here\n
\n
With the longer form description here\n
potentially spanning multiple lines.\0
```

The SHA-1 hashes, encoding name and timestamps are all in ASCII. So it's possible to parse `%H%T%P%n%at%n%ct%n%e%n` directly from the byte stream without allocating a single string. That saves quite a bit of memory.

The parent IDs now appear after the tree ID. This ordering makes parsing easier. 40 bytes for commit ID. 40 bytes for tree ID. Then zero or more parent IDs until you see `\n`.

Parsing a UNIX timestamp directly from ASCII bytes required a helper method, but is pretty straightforward.

After this we get into strings that require decoding (via UTF-8 or whatever is specified) via `%aN%n%aE%n%cN%n%cE%n%s%n%n%b`.

One observation is that any repo has a limited set of committer/author names/emails. Once you've parsed a given byte sequence into a string, the next time you see the same bytes you could just return the same string without any further allocation. This is what the `StringPool` class does. It makes a big difference. For 18,000 commits, each having four strings, the pooling strategy reduces 292,000 string objects down to 806. So we save a lot of allocations and reduce the working set accordingly, as these would otherwise be retained.

The duplicate summary was removed along with the need for a special marker at the beginning of each log item.

Another subtle difference is that there's only a single `\0` and it marks the end of the log item. This removes the need for the state machine and makes it possible to parse a log item in its entirety.

The code that reads null-terminated chunks from the process's output stream (`ReadNullTerminatedChunks`) re-uses a byte array buffer for every revision (expanding it if necessary due to super-long commit messages) which cuts down on allocations considerably too.

The SHA-1 data is loaded into `ObjectId` which is a class wrapping five 32-bit integers (160 bit), which reduces memory consumption considerably relative to `string`.

- `string` hashes are 112 bytes each (40 UTF-16 characters + 26 overhead + 6 alignment on x64)
- `ObjectId` hashes are 48 bytes each (5 * 4 + 24 overhead + 4 alignment on x64)

So we save 64 bytes per item. That's a whole cache line freed up for useful work.

If we have 18,000 revisions and assume an average of 1.5 parents, then we have 63,000 hashes in memory. Using `ObjectId` saves 4 MB alone. And the type is more compact than string due to its fixed size, so there's less indirection and less heap fragmentation.

Performance/memory improvements due to `ObjectId` will arise as we use it in more places and avoid conversion to strings at the frontier of its adoption.

Other changes include:

- Using Rx to stream revisions back, rather than multiple events.
- Moving observation of that Rx stream to another thread.
- Use of `JoinableTaskFactory` / `CancellationTokenSource`
- Fixing lingering git.exe processes when rapidly refreshing the UI (Fixes #4813)
- Adding `GitRevision.HasMultiLineMessage` and populating it in `RevisionReader` while the information is available (the full body is set to null to reduce memory consumption, and is only retrieved to facilitate client-side querying). This means the option for a visual indicator of longer commit messages in the revision grid has no overhead any more.
- Plenty of unit tests around these new capabilities

## Summary

This PR is the result of a deep dive into how might want to process data received from `git.exe` in cases where there is potentially a lot of data. The result is quite promising. There is still more that can be done to improve load/refresh performance (MEF is throwing a lot of exceptions, we probably run more git commands than necessary, and we could start the `git log` command a bit earlier) but they can be added later. For now we have much snappier parsing code, better memory utilisation and some useful tools to apply in my next major PR related to git process execution.

## What did I do to test the code and ensure quality

- Plenty of memory/CPU profiling to find hot spots
- Lots of manual testing in related areas
- Additional unit tests

Has been tested on:
- GIT 2.16
- Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
I haven't looked at the code yet, but the write-up along is extremely exciting.

**Comment by crypto-rsa** [comment]
What a great post!

**Comment by RussKie** [comment]
Do we need to pull commit text (i.e. `%B`) at all? 
In the grid we show only the subject, is it worth loading subjects (i.e. `%s`) during batch-load only?

**Comment by drewnoakes** [comment]
The body text is sometimes used for revision filtering in memory. It's presence also sets a flag that can be displayed in the graph when commits have descriptions beyond the summary.

If we weren't using that flag and there was no filter condition then perhaps we could skip it in such cases.

**Comment by RussKie** [comment]
I have one major problem with this PR - its size.... 
I've gone through the diff - some changes look benign, some aren't so, some things looked hardcore 💪. But the sheer size of the PR makes almost impossible to digest the proposal in its entirety.

It looks to me there are a number of orthogonal problems being addressed, which collectively make this PR.
Can we break it down to something more reviewable? E.g. `ObjectId`-related changes, `RevisionGraph` refactors etc...

**Comment by gerhardol** [comment]
What a great change and description. 
As Russkie said, difficult to review. I do consider recommending merging without a review...

Splitting in pieces will increase burden for Drew, as the pieces may not work individually. I have a proposal:
 * Keep this PR open wip. All testing is done to this branch only, also the branch to be merged
 * Split the contents in chewable commits with pull requests to a temporary branch in this repo. Then piece by piece be merged. The pieces do not have to possible to even compile, just for review.
 * Compare this PR branch with the resulting branch to make sure all changes in the accepted PRs are included before merging (so no strict discipline is needed when updating).

**Comment by RussKie** [comment]
Merging in, but please try to make more concise targeted refactors.

**Comment by drewnoakes** [comment]
Cheers RussKie. And sorry for not getting back to the comments from a few days ago. I did fixup, reorder and tidy this PR quite a lot before submitting it (including splitting out #4986), but from this state it became really hard to split it further without conflicts. The development process here was iterative, responding to whatever appeared to be allocating the most memory at a given step, which changed over time and moved around the code base.

> Can we break it down to something more reviewable? E.g. ObjectId-related changes, RevisionGraph refactors etc...

I did actually have the `ObjectId` stuff in its own PR for a while, but without actual usage and benchmarks/stats to back it up I can understand why reviewers found it hard to justify merging.

The git executable/process stuff is next on my radar and I'll endeavour to keep the PR(s) smaller.

**Comment by RussKie** [comment]
I've come across [an interesting article](https://dev.to/indy_singh_uk/strings-are-evil-9f9), which is in some way relevant to the work Drew's done. 
The article talks how they managed to optimise a CVS file reading from 7.5G memory allocation to just 32Kb!

**Comment by drewnoakes** [comment]
Cheers @RussKie, that is an interesting article. The GitHub repo for the code the author uses was one of the [top C# repos](https://github.com/vitalets/github-trending-repos/issues/19#issuecomment-397499447)) last week. There are several versions beyond what the article covers that are worth checking out.

There's some nice stuff in .NET Core 2.1 around `Span<T>` and `System.Memory` which will make these APIs clearer, and remove some of the custom parsing code for example. Technically we can use them now via a NuGet package, and I did try this, but without special support from the runtime we use the so called 'slow' three-field `Span<T>` it was unfortunately a fair bit slower than using unsafe code.

Hopefully in future we move to .NET Core 3, and then our parsing code can be made nicer across the board and with much fewer allocations and fully safe code.

Good introductions to the new System.Memory stuff [here](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx?f=255&MSPPError=-2147217396) and [here](http://adamsitnik.com/Span/).

**Pull request merged**
