### PR TITLE
Fixup localization verification

### LINKED ISSUE #9273: Repair Translation Check
The translation check has regressed again: fails, if the master has newer translations.

STR:

- PR with translation change
- concurrent merge with translation change to `master`
- build PR

### PR DESCRIPTION
**Pull request by mstv**
Fixes #9273

## Proposed changes

- Restore the working loc verification from 8da72f42cf02b377fbdb9ccccf1747f1b3f53e46
- Stage all files which have been modified by the build process, a.o. by `set_version_to.py`

## Test methodology 

- CI build

## Test environment(s) 

- AppVeyor

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
I've been thinking overnight - we want to build with the has of the original PR. So perhaps we want to run the loc check first, and only if it passes perform soft reset and build. This way we don't need to do gymnastics of resetting back, etc.
What do you think?

**Comment by mstv** [comment]
It is not about resetting but about having committed the `.xlf` files, which have been merged with the master.

Building twice is also gymnastics and will take too much time IMO.

So rather make the script which injects the git info, aware of the CI build and override the hash with the `APPVEYOR_PULL_REQUEST_HEAD_COMMIT`.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
It is working, though is giving strange output
image

**Comment by mstv** [comment]
> It is working, though is giving strange output

That's why I must reset `LASTEXITCODE`.

**Pull request merged**
