### PR TITLE
Added setting to enable/disable autocompletion in commit dialog.

### PR DESCRIPTION
**Pull request by chrischu**

### CODE REVIEW

**Comment by chrischu** [comment]
I updated the pull request to the newest master-version and also tested it.

I'm not quite sure how localization works in GitExtensions though. How would I go about making the text of the checkbox in the settings dialog localizable?

**Comment by drauch** [comment]
GitExtensions is localized using the crowd-translator platform Transifex ( https://www.transifex.com/git-extensions/git-extensions/ ).

**Comment by chrischu** [comment]
Well I meant more how it's technically done with GitExtensions/Windows Forms :). 

I just checked and it seems to me that Windows Forms supports localization out of the box and the translation has to be done after the pull request has been merged apparently.

**Comment by vbjay** [comment]
image

https://github.com/gitextensions/gitextensions/commit/0a5c5e2129156f0a345b30b2bae57082713a75c2

**Pull request merged**
