### PR TITLE
Update release version to AppVeyor release build

### PR DESCRIPTION
**Pull request by gerhardol**
Changes proposed in this pull request:
- Update version to AppVeyor release builds, so manual builds matches the release

Note: master should be updated with a 3.01.00.0 version, no merge
 
Screenshots before and after (if PR changes UI):
- n/a

What did I do to test the code and ensure quality:
- n/a

Has been tested on (remove any that don't apply):

### CODE REVIEW

**Comment by gerhardol** [comment]
> Should this be directed at release/3.00 branch, and have master branch updated to have "3.01.*"?

Yes
The intention with the branches and where to send patches is at least clear to me then

**Comment by RussKie** [comment]
I redirected this to release/3.00

**Comment by gerhardol** [comment]
I will merge and open a new PR for master

**Comment by RussKie** [comment]
:+1:

**Pull request merged**
