### PR TITLE
Do not delay Dashboard start for invalid Git repos

### PR DESCRIPTION
**Pull request by gerhardol**
There has been related issues before, that has been addressed somehow.
I saw this issue after adding some repos to WSL and an USB stick,
Dashboard would require about 1:30 to open.

This could be included in 4.1, but I do not want to delay the release.

## Proposed changes

Add the repos to the lists without any I/O to check if the repo is invalid or not (to set the icon).
Perform the check if a repo has a valid Git dir async, together with branch name retrieval and set the invalid icon then instead.

Rendering of branch name failed if the item was rendered before the branch name was set.
This had a much higher probability to occur after the item creation was changed.

Menu item to remove invalid repos was only set from favorite repos, as _hasInvalidRepos was overwritten.

## Test methodology 

Manual.

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
I observed a significant dashboard slowness, and I almost raised an issue for it at one point but I was unable to replicate the issue in debug builds. I've taken few memdumps, and looking at those I think your suggested fix may be right on target:
image

I'm going to take your change for a spin before I provide more feedback.

**Review by RussKie — APPROVED** [review]
🚀 
Thank you

**Comment by gerhardol** [comment]
Then I will rebase this to 4.1 tonight.

Some notes I should have added to the description:

There may be ways to improve the detection time as well but this should be the big change. It should primarily affect the slow repos (start wsl?), Showing the status for other. (Wsl branch names are occasionally missing.)

We are probably creating two GitModule in the async code. Some Ms per repo added.

**Review by mstv — APPROVED** [review]
Looks sensible, have not run

**Comment by gerhardol** [comment]
> There may be ways to improve the detection time as well but this should be the big change. It should primarily affect the slow repos (start wsl?), Showing the status for other. (Wsl branch names are occasionally missing.)

I do not find an obvious way to check the path for network including wsl any faster.

> We are probably creating two GitModule in the async code. Some Ms per repo added.

No, this is fine, only one module.

**Pull request merged**
