### PR TITLE
Cleanup string extensions

### PR DESCRIPTION
**Pull request by RussKie**
* Fix namespace
* Remove QuoteNE() method merging the functionality into Quote()
* Rename AddParenthesesNE() -> AddParentheses()
* Remove IsNotNullOrWhitespace()
* Remove unused methods

### CODE REVIEW

**Comment by jbialobr** [comment]
Can you describe your motivation for each kind of your changes?

**Comment by RussKie** [comment]
I was looking at something else when I come across these extension methods.

- Namespace wasn't correct so I fixed it

- There were several methods which weren't used so I removed them. If/when they will be required they can be brought back. Having APIs which aren't used is an overhead. 

- `IsNotNullOrWhitespace` is removed because is not a real value-add. A lot of people seem to be (mis-)using extension methods quite liberally, often unnecessary. In my opinion this is a perfect example.
If we consider .NET framework (not .NET Core) as model for API design where a lot of thought and consideration had been put in API design, then there is `string.IsNullOrEmpty()` method and there is no `string.IsNotNullOrEmpty()` method. 
In v4.0 they brought in a new method `string.IsNullOrWhiteSpace()` without a negating companion. They could probably have called it `string.IsNullOrEmptyOrWhiteSpace()` but then it probably wouldn't really make the method intent any clearer.
`IsNotNullOrWhitespace` didn't have an extensive use across the codebase either, so its departure doesn't have a great effect.

- Several methods had unclear names (i.e. `QuoteNE` and `AddParenthesesNE`). Without looking at the code I found it difficult to guess what their purpose was. These names also troubled Re#.
There were other problems to them to:
  - I checked the use of these methods and found few possible NRE (arguably edge cases, but none the less).
I've added unit tests first, to capture their current behavior. While doing that I found[ one of the possible NREs](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitCheckoutBranchCmd.cs#L59), so I had to fix `QuoteNE` to return `""` instead of a `null`. And added a unit test for [CollectArguments_should_set_branchName_if_null](https://github.com/gitextensions/gitextensions/pull/3638/files#diff-dc78e0db0b966fbad59913874c44d63fR51).
At the same time I separated other tests to test one code path per test.
  - Whilst there were `Quote()` and `QuoteNE()` methods there was no `AddParentheses()` method, so it looked inconsistent. So I renamed `AddParenthesesNE` -> `AddParentheses` and updated the xml-doc and added unit tests. 
  - `AddParentheses` suffered from the same issue as `QuoteNE` did, it could lead to NRE in hands of sloppy developer. So I fixed to return `""` instead of a `null`.
  - As said above `QuoteNE` name is very poor. Its use also indicated the API may not been understood well by the developers, and could result in NREs. 
In my opinion, combining `Quote` and `QuoteNE` into one method with a parameter indicating whether an empty string should be quoted makes the API much more sensible and the intent clearer. 
The unit tests written at the start helped to validate no regressions added.

**Comment by jbialobr** [comment]
Thank you for the thorough explanation. 

>Namespace wasn't correct so I fixed it

OK.

>There were several methods which weren't used so I removed them.

They were introduced in the feature/left-panel branch. I find it a good practice to merge up front changes not specific to the new feature when working on a feature that takes a lot of work and time to implement it. It is because such a way decreases number of conflicts that have to be resolved when periodically the master branch is merged into the feature branch.

>IsNotNullOrWhitespace

You know that it is very subjective what a misuse is and what it is not. I don't want to start a discussion about what is right and what is not. I would focus on that name gives a good description of what the function does. There are so many contributors, and there is almost as many different opinions on how the perfect code should look like. For me it is enough to be easy to understand what id does, correct and easy to maintain.
I miss a single word that could denote `NullOrEmptyOrWhitespace` perhaps `Blank` could be used.
Other solution could be to assume that when used in a method name:
* x.IsNull - means `x == null`
* x.IsEmpty - means `x.IsNull || x.Equals(string.Empty)`
* x.IsWhitespace - means `x.IsEmpty || x.Trim().Equals(stirng.Empty)`

>Several methods had unclear names (i.e. QuoteNE and AddParenthesesNE). 

Yes, I agree. But Quote(false) is not any better (again subjective). I would rename it to `QuoteIfNotEmpty`.
According to NREs, I agree that it is more safe to return string.Empty for null input.


I am also not a big fan of using `var` everywhere where possible. It decreases readability and sometimes makes impossible to the compiler to find bugs introduced while refactoring.

**Comment by RussKie** [comment]
> They were introduced in the feature/left-panel branch. I find it a good practice to merge up front changes not specific to the new feature when working on a feature that takes a lot of work and time to implement it. It is because such a way decreases number of conflicts that have to be resolved when periodically the master branch is merged into the feature branch.

My opinion is that all changes should as part of a commit they belong, and the commit must be atomic and self-contained. 
Few reasons:
- if necessary, the commit can be rolled back entirely,
- if changes are split across several commits and one of the subsequent commits is never merged in, you suddenly have some unused functionality. I hope we can agree that it is a very undesirable outcome.

Just yesterday I browsed through the list of pending commits, some of which are now 3-4 years old. So imagine if they added functionality in hope for their now-pending commits to be merged in...
**(Off topic)** It is also a pretty sad outcome for the people who spent their time. Granted that not all of the commits meet the necessary level of quality nor all of them followed up by the authors, but not all of them.

> You know that it is very subjective what a misuse is and what it is not.

I'd rather approach the issue pragmatically.
* `IsNotNullOrWhitespace` used 8 times
* `string.IsNullOrEmpty` used 246 times
* `!string.IsNullOrEmpty` used 200 times
I think it is a good indication that the value-add of `IsNotNullOrWhitespace` is minimal (3.85%). There are a few developers contributing to the project, and the vast majority of them uses the MS's API.

Personally I don't think it is a good idea to create one line methods at all. Unless you get paid per line or a depth of your stack :)

> But Quote(false) is not any better (again subjective). I would rename it to QuoteIfNotEmpty.

This introduces ambiguity. If there is  `QuoteIfNotEmpty`, does `Quote` quote when empty? Look at the code and find that it is not quite the case...
That's why I proposed `Quote(bool quoteEmptyString = true)` signature.

> I am also not a big fan of using var everywhere where possible. It decreases readability and sometimes makes impossible to the compiler to find bugs introduced while refactoring.

I was there too. However it seems that is the direction MS and the whole development community is going. Here is [one example](https://github.com/NuGet/Home/wiki/Coding-Guidelines#usage-of-the-var-keyword), Resharper is another.
Some things are easier to accept than fight (e.g. I had to accept underscoring private variables and not use `this.`).

**Comment by RussKie** [comment]
> x.IsWhitespace - means x.IsEmpty || x.Trim().Equals(stirng.Empty)

I think it is wrong. To me _whitespece_ means `" "` or `\t` and _not_ `null` or `""`.

**Comment by pmiossec** [comment]
On 'var' use, I prefer this code style (from Microsoft too...) :

>We only use var when it's obvious what the variable type is (i.e. var stream = new FileStream(...) not var stream = OpenStandardInput()).

Found on [dotnet repository](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

**Comment by jbialobr** [comment]
>My opinion is that all changes should as part of a commit they belong, and the commit must be atomic and self-contained.

There is no disagreement here. It was added in such a way 606de5e14fd13282b7c408a90456c95215628238.

>I'd rather approach the issue pragmatically....

I assume that somebody added this extensions because he found it more readable. Since it meets all my acceptance conditions I don't see any reason to reject it. If I don't like it I will not use it, but I don't want to act as the whole code base should look like it was written be myself. There should be room for tolerance. (People used to think that the earth is flat, so I don't buy the majority argument at all). It is a community project, more than a half of all the commits were made by contributors not belonging to the core team. 

>Personally I don't think it is a good idea to create one line methods at all. Unless you get paid per line or a depth of your stack :)

Oh, you can not be further from the truth (again subjective). 

>does Quote quote when empty?

Yes it does.
```csharp
            string q = string.Empty.Quote();
            Assert.That(q.Equals("\"\""));
            string qq = string.Empty.Quote(":");
            Assert.That(qq.Equals("::"));
```
> I had to accept underscoring private variables

So, do I. But there the information was added - not lost, and there were no risk factors.

**Comment by RussKie** [comment]
@pmiossec Back in the days where we didn't have strong types and IDEs were very intelligent we had to write types explicitly, but these days, I think, it's greatly irrelevant. 
It is rather difficult to confuse the compiler to think your type is not what the compiler thinks it is (yes, of course we have dynamics, but even then). 
So if the code compiles it - it is a good indication your types match.

Back to the discussion - if MS folks can't settle on one standard, what chance do we have? :)

**Comment by RussKie** [comment]
> There is no disagreement here. It was added in such a way 606de5e.

With respect, the code which has been added 4 years ago and hadn't received much use from the contributors, and we are debating whether it could be deprecated... :confused: 
I personally see _code deleted_ as a positive event on any codebase. 

Again, these are my personal views, I respect your position and I agree to disagree.
Ultimately it is your prerogative to accept or decline this PR.

**Pull request closed without merging**
