### PR TITLE
GitExtensions -> Git Extensions

### PR DESCRIPTION
**Pull request by oriash93**
Regarding  gitextensions/GitExtensionsDoc#95

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by illfated** [comment]
Looks like AppVeyor fails in
`GitUITests.CommandsDialogs.CommitDialog.FormCommitTests.Should_display_branch_and_no_remote_info_in_statusbar`
and therefore not caused by this PR.

**Comment by RussKie** [comment]
Please send your sign off to contributors.txt

**Comment by RussKie** [comment]
> Looks like AppVeyor fails

Please see https://github.com/gitextensions/gitextensions/pull/6273

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
