### PR TITLE
fix reset file menu item text

### PR DESCRIPTION
**Pull request by pmiossec**
When in English, every time the reset file menu items are displayed,
the commit message was appended ending wrong....

Adding "English" translation files
(Other way to solve problem presented in #3412)

### CODE REVIEW

**Comment by pmiossec** [comment]
Now, you can choose  ;)

**Comment by jbialobr** [comment]
Thank you. I cherry-picked the changes into 2.49.

**Comment by KindDragon** [comment]
BTW Setup.exe doesn't install English.xlf

**Comment by pmiossec** [comment]
> BTW Setup.exe doesn't install English.xlf

Indeed, that should be included if we want that this fix fix something ;)

**Pull request closed without merging**
