### PR TITLE
Add missing languages from Transifex

### PR DESCRIPTION
**Pull request by Pavuucek**

### CODE REVIEW

**Comment by Pavuucek** [comment]
No problem. Should I resize all of them while I'm at it?

**Comment by KindDragon** [comment]
I rechecked, all flags shouldn't be bigger than 225 x 150. Please reduce sizes of all images and update English.gif with bigger image.

**Comment by KindDragon** [comment]
225 x 150 it's ok too

**Comment by KindDragon** [comment]
Squash commits with flags and I merge PR

**Pull request closed without merging**
