### PR TITLE
JTF testing update

### PR DESCRIPTION
**Pull request by sharwell**
* Make sure `ThreadHelper.JoinableTaskFactory` is usable in tests not marked with `STA`, provided `SwitchToMainThreadAsync` is not used
* Make sure thread exceptions (e.g. from `FileAndForget`) cause tests to fail

:memo: This pull request is the first two commits originally from #4757, but was updated to avoid the need to use `IDisposable` or `SemaphoreSlim`.

### CODE REVIEW

**Comment by sharwell** [comment]
The following tests will now fail:

### Fail on thread exception

```csharp
[Test]
public void FailOnThreadException()
{
  ThreadHelper.JoinableTaskFactory.RunAsync(() => throw new Exception()).FileAndForget();
}
```

<details><summary>Expand to see output</summary>

```
Test Name:	FailOnThreadException
Test FullName:	GitUITests.ThreadHelperTests.FailOnThreadException
Test Source:	D:\dev\github\gitextensions\UnitTests\GitUITests\ThreadHelperTests.cs : line 29
Test Outcome:	Failed
Test Duration:	0:00:00.347

Result StackTrace:	
at GitUITests.ThreadHelperTests.<>c.<FailOnThreadException>b__2_0() in D:\dev\github\gitextensions\UnitTests\GitUITests\ThreadHelperTests.cs:line 30
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass12_0.<<FileAndForget>b__0>d.MoveNext() in D:\dev\github\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommonTestUtils.ConfigureJoinableTaskFactoryAttribute.AfterTest(ITest test) in D:\dev\github\gitextensions\UnitTests\CommonTestUtils\ConfigureJoinableTaskFactoryAttribute.cs:line 68
   at NUnit.Framework.Internal.Commands.TestActionCommand.<>c__DisplayClass0_0.<.ctor>b__1(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestActionCommand.cs:line 54
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 72
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 59
Result Message:	System.Exception : Exception of type 'System.Exception' was thrown.
```

</details>

### Fail on `SwitchToMainThreadAsync` with MTA

```csharp
[Test]
[Apartment(ApartmentState.MTA)]
public async Task FailOnMTASwitchToMainThread()
{
  await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
}
```

<details><summary>Expand to see output</summary>

```
Test Name:	FailOnMTASwitchToMainThread
Test FullName:	GitUITests.ThreadHelperTests.FailOnMTASwitchToMainThread
Test Source:	D:\dev\github\gitextensions\UnitTests\GitUITests\ThreadHelperTests.cs : line 60
Test Outcome:	Failed
Test Duration:	0:00:00.137

Result StackTrace:	
at CommonTestUtils.ConfigureJoinableTaskFactoryAttribute.DenyExecutionSynchronizationContext.ThrowFailedTransferExceptionForCapture() in D:\dev\github\gitextensions\UnitTests\CommonTestUtils\ConfigureJoinableTaskFactoryAttribute.cs:line 159
   at CommonTestUtils.ConfigureJoinableTaskFactoryAttribute.DenyExecutionSynchronizationContext.Post(SendOrPostCallback d, Object state) in D:\dev\github\gitextensions\UnitTests\CommonTestUtils\ConfigureJoinableTaskFactoryAttribute.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommonTestUtils.ConfigureJoinableTaskFactoryAttribute.DenyExecutionSynchronizationContext.ThrowIfSwitchOccurred() in D:\dev\github\gitextensions\UnitTests\CommonTestUtils\ConfigureJoinableTaskFactoryAttribute.cs:line 111
   at CommonTestUtils.ConfigureJoinableTaskFactoryAttribute.AfterTest(ITest test) in D:\dev\github\gitextensions\UnitTests\CommonTestUtils\ConfigureJoinableTaskFactoryAttribute.cs:line 62
   at NUnit.Framework.Internal.Commands.TestActionCommand.<>c__DisplayClass0_0.<.ctor>b__1(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestActionCommand.cs:line 54
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 72
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 59
Result Message:	System.InvalidOperationException : Tests cannot use SwitchToMainThreadAsync unless they are marked with ApartmentState.STA.
```

</details>

**Comment by sharwell** [comment]
I've asked @jnm2 to take a look at the above two test cases and see if we can write them in an equivalent passing form.

These tests fail due to a safeguard this pull request adds to the test setup that intentionally causes tests to fail if they do certain "bad things". However, the protection mechanism sits at a higher level than the test code in a single method, making it difficult to write a test. You can't, for example, simply wrap the body of the test in `Assert.Throws`, because the exception is thrown after the method returns.

**Comment by jnm2** [comment]
@sharwell 

#### First example
```cs
ThreadHelper.JoinableTaskFactory.RunAsync(() => throw new Exception()).FileAndForget();
```

This looks like it throws an exception on a background thread. NUnit has never had a concept of correlating exceptions from other threads with one of the currently executing tests. One fundamental problem is parallelization.
Even with `[NonParallelizable] on the test, there is simply no way in general to catch an exception on a user-created thread. It takes down the process unless the threadstart takes the initiative to catch all exceptions and provide them to the other threads via some API. For example, Application.ThreadException for the WIndows Forms message loop or AppDomain.UnhandledException for the thread pool.

Since this varies so wildly from threadstart to threadstart, it's your responsibility to figure out a way to make your NUnit test wait long enough to know whether the background thread you started is finished and what the result was. We're always open to suggestions for how to get rid of boilerplate, but if you can't _in principle_ write a test that does this with NUnit _today_, then NUnit cannot in principle do anything to help with this.

**Comment by jnm2** [comment]
Oops, commented sooner than I meant to.

### Fail on SwitchToMainThreadAsync with MTA

I'll be away for a few hours, back this afternoon.

**Comment by sharwell** [comment]
> This looks like it throws an exception on a background thread. NUnit has never had a concept of correlating exceptions from other threads with one of the currently executing tests. One fundamental problem is parallelization.

If you expand the Output section, you can see how I caught this case and triggered a test failure. It's actually part of [`ConfigureJoinableTaskFactoryAttribute.AfterTest`](https://github.com/gitextensions/gitextensions/blob/5c82356758a1576900db53b8dfb39987fd4b3671/UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs#L68) which is applied [to the assembly](https://github.com/gitextensions/gitextensions/blob/22f54fd898a28e67ba76a9c2ef0ec02e5126417e/UnitTests/GitUITests/Properties/AssemblyInfo.cs#L38).

Rephrasing my original question: now that I have implemented functionality that causes tests to fail for the two bad practices shown in the sample tests, how do I write a *passing* test which asserts that tests will fail if they do something like the above? For example, if I could apply an `[ExpectedException]` to a test that applied itself outside the `ITestAction` applied to the assembly, it would be able to catch the exception thrown in `AfterTest`.

> Since this varies so wildly from threadstart to threadstart, it's your responsibility to figure out a way to make your NUnit test wait long enough to know whether the background thread you started is finished and what the result was.

This is also handled in `ConfigureJoinableTaskFactoryAttribute.AfterTest`:

https://github.com/gitextensions/gitextensions/blob/22f54fd898a28e67ba76a9c2ef0ec02e5126417e/UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs#L46

**Comment by jbialobr** [comment]
@sharwell I wonder if it is correct to perform assertions not ensuring before that async/backgroud tasks have finished. See this incorrect test as an example:
```csharp
[Test]
public void Test1()
{
  var form = ...
  form.x = 1;
  ThreadHelper.JoinableTaskFactory.RunAsync(async() => 
    await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
    form.x = 3;
  ).FileAndForget();
  Assert.AreEqaul(1, from.x);
}
```

**Comment by sharwell** [comment]
@jbialobr No, that is not a correct test. But that's also not really a case we can/should be dealing with at this layer.

**Comment by jbialobr** [comment]
So, what the test should look like? Is this correct:

```csharp
[Test]
public void Test1()
{
  var form = ...
  form.x = 1;
  ThreadHelper.JoinableTaskFactory.RunAsync(async() => 
    await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
    form.x = 3;
  ).FileAndForget();

  ThreadHelper.JoinableTaskFactory.Run(() => ThreadHelper.JoinPendingOperationsAsync());

  Assert.AreEqaul(3, from.x);
}
```

If it is, it means that `AfterTest` should fail the test if there are any pending async operations, doesn't it?

**Comment by sharwell** [comment]
:bulb: Tests should not use fire-and-forget (aside from tests to verify `FileAndForget` works correctly). This change is about detecting errors in cases where *production* code uses this style of open-ended asynchronous operation.

**Comment by jbialobr** [comment]
I am sorry it was a mental shortcut. Is it more clear:

```csharp
[Test]
public void Test1()
{
  var form = ...
  form.SyncMethodThatRunsAsyncOperation(); //runs async call and files it and forgets

  ThreadHelper.JoinableTaskFactory.Run(() => ThreadHelper.JoinPendingOperationsAsync());

  Assert.AreEqaul(3, from.x);
}
```

The case is we test a method that runs an async call in a fileAndForget fashion.

**Comment by jnm2** [comment]
@sharwell Ah, now I'm catching up. If failure is not detected until [the AfterTest line](https://github.com/gitextensions/gitextensions/blob/22f54fd898a28e67ba76a9c2ef0ec02e5126417e/UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs#L46), the AfterTest logic would have to know when to use `Assert.Throws` to invert the result for certain tests. Maybe an attribute argument?

Or, just do as @jbialobr since this is a special case and bring the AfterTest line into the test method itself?

**Comment by jbialobr** [comment]
>Or since this is a special case, just do as @jbialobr mentions and bring the AfterTest line into the test method itself?

These are two separate things. My concern here is that the `AfterTest` should act a little bit different. I am not trying to solve @sharwell's problem about how to write a test for ConfigureJoinableTaskFactoryAttribute.

> Maybe an attribute argument?

Yes, but it should be handled by another ITestAction - not by ConfigureJoinableTaskFactoryAttribute, otherwise ConfigureJoinableTaskFactoryAttribute would have too much responsibility.
To achieve that we would have to be able to enforce the order of ITestAction execution.

**Comment by jbialobr** [comment]
>My concern here is that the AfterTest should act a little bit different.

That is:
If a test while its execution performs directly or indirectly async operations, it should explicitly await for pending operations before performing assertions. If there was no such awaiting then the `AfterTest` should fail the test. Filed exceptions should be thrown as a part of this awaiting for pending operations - if there was an error during the test execution the assertions may be false negatives due to the exception, so the failure message can be misleading about the real cause of the failure.

**Comment by jbialobr** [comment]
@jnm2 Thanks. I verified that if there is a failing assertion in the test and AfterTest throws an exception, the test is reported as failing with the exception thrown in AfterTest. That means the message is not misleading but if test is run in debugger it will stop first on the failing assertion.

**Comment by jnm2** [comment]
@jbialobr Awesome! I'm glad that works well enough. I'm not quite happy with what you described though, so hopefully we'll make it better in 3.11: https://github.com/nunit/nunit/issues/2797.

**Comment by sharwell** [comment]
@jbialobr Are we good to merge this incremental improvement? It (at least the second commit) addresses a specific request you made in the original review to move to vs-threading. 😄

**Comment by jbialobr** [comment]
d16afbd27798a24cc4f36b3d02892e842bfc0901 is good to go.
5c82356758a1576900db53b8dfb39987fd4b3671 is better than nothing, so we can merge both. I will raise a new issue later to discuss my concerns.

**Pull request merged**
