### PR TITLE
Provide capability to generate git -c calls in git commands

### LINKED ISSUE #5179: Git config log.showSignature breaks revision grid
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
```git config log.showSignature true``` breaks the listing of all branches.  I have a few branches in my repo and when I set it, only master showed.  This is because develop had signed commits.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- ```git config log.showSignature true```
- Load repo in GE

**What is the expected behavior?**
Signed commits should still show in GE.
**Environment you encounter the issue:**

- GitExtensions version:2.51.04
- GIT version: git version 2.18.0.windows.1
- OS version: Microsoft Windows [Version 6.3.9600]
- .NET version: mscorlib	DomainNeutral, Native	C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\be2b233163fe3b9af2d68b10d4798ef2\mscorlib.ni.dll

**Did this work in previous version of GitExtensions (which)?**
Probably not

### PR DESCRIPTION
**Pull request by vbjay**
Fixes #5179

Changes proposed in this pull request:
- Add --no-show-signature option to log calls
 
Screenshots before and after (if PR changes UI):

What did I do to test the code and ensure quality:
- Signed a commit and made sure it showed in revision grid.  
- Verified log calls were not broken

Has been tested on (remove any that don't apply):
- GIT 2.18 and above

### CODE REVIEW

**Comment by vbjay** [comment]
Still need to commit the change of all log calls. Pushing that out when I get home.

**Comment by vbjay** [comment]
Also looks like a whitespace change snuck in.

**Comment by vbjay** [comment]
Ready for review.

**Comment by sharwell** [comment]
💭 This seems like something we could leave as-is in the 2.x branch.

**Comment by vbjay** [comment]
Try setting the config value to true and see how many commits you see in
this very repo.

**Comment by sharwell** [comment]
> Try setting the config value to true and see how many commits you see in this very repo.

Development slows down on the old branches over time. At some point, we'll switch from "bugs that have workarounds get fixed" to "bugs that have workarounds have workarounds". When that transition arrives, this issue will fall into the latter - the workaround is to set the config value to false.

**Comment by vbjay** [comment]
You are going to say they have to have the value set to a specific value.
Git extensions should handle the value. I fixed it so that it will work in
spite of the settng. I would think if a user doesn't want to always add
--show-signature to their log calls, they configure it, as I did.  Noticed
the problem.  I don't think you get the point. They should becable to
configure it and get show ALL commits. It is a big failure that is easily
prevented.

**Comment by sharwell** [comment]
@vbjay We are talking about two totally different things. 😄

**Comment by RussKie** [comment]
I don't plan to release any more 2.51 fixes unless it is fundamentally broken, and I don't see it is.
As pointed there is a workaround - disable showing signatures. And because it isn't something a user can set by accident via the UI, I trust the user to be experienced with git and, thus, the user can unset the flag.

**Comment by vbjay** [comment]
Before this is merged do you want me to change it to be like #5182? See
latest commits in that pull request.

**Comment by RussKie** [comment]
I haven't reviewed the other one yet.
If they are equivalent, sure, why not.

**Comment by vbjay** [comment]
Ok. I will do that tonight.

**Comment by vbjay** [comment]
I'll squash when the new changes have been approved

**Comment by vbjay** [comment]
Ready to merge

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
