### PR TITLE
ShellExtension: rename item in the setting form with same name it have in shell extension menu

### PR DESCRIPTION
**Pull request by pmiossec**
4 years later followup of #5117

Shell menu since #5117:

image

### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build b78e768d55af39e5d79310d8f1b7e772cefcf30a (Dirty)
- Git 2.35.1.windows.2 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.8
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]

**Comment by pmiossec** [comment]
Looking at the Shell Extension code, I have a question: 

The shell extension menu is not translated because the strings are hard-coded in the cpp project (and so don't benefit of the translation strings).
So, does that makes sense to have the strings translated in the "Context menu preview" (here in french) whereas in fact the user will never have it in his language?
image

My point of view is that we should prevent the strings to be translated.

**Comment by gerhardol** [comment]
> The shell extension menu is not translated because the strings are hard-coded in the cpp project (and so don't benefit of the translation strings). So, does that makes sense to have the strings translated in the "Context menu preview" (here in french) whereas in fact the user will never have it in his language?

Seem to be better to drop the translation if the shell extension is not translated
(__NO_TRANSLATION prefixes)

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
> Looking at the Shell Extension code, I have a question:
> 
> The shell extension menu is not translated because the strings are hard-coded in the cpp project (and so don't benefit of the translation strings). So, does that makes sense to have the strings translated in the "Context menu preview" (here in french) whereas in fact the user will never have it in his language? image
> 
> My point of view is that we should prevent the strings to be translated.

Good point. For consistency we can drop the translations.

**Comment by pmiossec** [comment]
> Good point. For consistency we can drop the translations.

Done.

**Review by gerhardol — APPROVED** [review]

**Review by mstv — APPROVED** [review]

**Review by RussKie — APPROVED** [review]

**Pull request merged**
