### PR TITLE
[WIP] Update submodules to use vs-threading

### PR DESCRIPTION
**Pull request by sharwell**
* [x] Update conemu-inside (per gitextensions/conemu-inside#6)
* [x] Update Git.hub (per gitextensions/Git.hub#6)
* [x] Update NBug (per gitextensions/NBug#7)

📝 If accepted, please do not rebase or squash this pull request during the merge.

### CODE REVIEW

**Comment by vbjay** [comment]
Sending in pull requests to these submodules would be a good thing.

**Comment by sharwell** [comment]
Sorry I forgot to update the PR title before merge 😦 

> Sending in pull requests to these submodules would be a good thing.

I'm not sure they would be receptive to this change, since it would require more work for downstream users to adopt. This especially applies to conemu-inside, where a core feature was eliminated because we weren't using it and it didn't work well with the threading approach.

**Comment by vbjay** [comment]
They may not. However, I think sending the request would be a good idea to
not only help us deal with merge changes down the road but alsoz we
improved their product. They can make the determination.

**Comment by jbialobr** [comment]
I have send once a PR to conemu-inside but got no reaction...
Before sending any PR, I would like to know it works for us correctly for a longer period of time.

**Comment by vbjay** [comment]
Sure. Just getting the idea out there. I feel it's right to send in pull
requests to at least let the forked repos know so they benefit from this
repo's work if they desire.

**Pull request merged**
