### PR TITLE
Reworking old PR to the current state of project

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
the old PR was
https://github.com/gitextensions/gitextensions/pull/2716

reworking was neccesary because it was partially accepted here
https://github.com/gitextensions/gitextensions/pull/3007

### CODE REVIEW

**Comment by ArsenShnurkov** [comment]
I don't see MONO define in https://github.com/gitextensions/gitextensions/blob/3bdd0b2ab7a25a38ae00eac73fcd494dd9ce0f8c/Setup/BuildInstallers.Mono.cmd

**Comment by ArsenShnurkov** [comment]
moreover, i don't use .cmd files on linux

**Comment by ArsenShnurkov** [comment]
http://stackoverflow.com/questions/33562881/how-to-set-define-in-msbuild-script-for-linux

**Comment by KindDragon** [comment]
> I don't see MONO define in https://github.com/gitextensions/gitextensions/blob/3bdd0b2ab7a25a38ae00eac73fcd494dd9ce0f8c/Setup/BuildInstallers.Mono.cmd

XBuild automatically will add MONO define

**Comment by KindDragon** [comment]
> may be try to use __MonoCS__ for this?
> http://stackoverflow.com/questions/329043/how-can-i-conditionally-compile-my-c-sharp-for-mono-vs-microsoft-net/329072#329072
> 
> But mono can work on windows too. So It is necessary to check is it linux or windows. Or (even better), is TFS available or not

Yes we have this check in some places, it depend on what you want.

**Comment by ArsenShnurkov** [comment]
awww, it's merged too early...

**Comment by ArsenShnurkov** [comment]
I want to avoid the exception, when TFS is not available. I don't want to build TFS-library on linux (And I avoid this by patching sources before building to exclude that library from build). Probably the simplest solution will be to patch this code out in .ebuild too, instead of merging checks to the project

**Pull request closed without merging**
