### PR TITLE
GitStatusMonitor: CancelToken to limit multiple commands

### LINKED ISSUE #6731: [NBug] ConEmuCD was not loaded.
## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   在 ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   在 ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   在 ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   在 ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   在 GitUI.FormStatus.Done(Boolean isSuccess)
   在 GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   在 GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 120dpi (125% scaling)

### LINKED ISSUE #6732: Too much CPU and RAM usage
## Current behaviour
GitExtensions comsumes 4GB RAM, 100% CPU and spawns a lot of git.exe proceses, some of them don't quit.
With 3 GitExtensions windows opened and 3 VS I had 32 GB (100%) RAM usage..
I could kill all ~1000 living processes, there was one with PID of 190000 !

## Expected behaviour
Not consume so much resources.

## Steps to reproduce
I have a project of 1000 C++ files, compiling it while GitExtensions is opened seems like causing a problem.

## Did this work in previous version of GitExtensions
Don't know

## Environment
- GitExtensions version: 3.1
- GIT version: 2.21
- OS version: Windows 10
- .NET version:  4.8

## Diagnostics
Next time it happens I'll try making a dump but the machine was so slow this time that I barely could run cmd

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #6732
Based on #6834 

## Proposed changes

GitStatusMonitor should only run more than one command when a refresh is requested.
The cancelled command should not schedule a new command though.
The PR also adds lock() to _commandIsRunning, this should not have any real world effect.

## Test methodology 

Manual, refresh in linux repo repeatedly, only one git-status for the commit status at a time

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
I reverted one change and removing WIP.

**Comment by RussKie** [comment]
As noted in another PR related to the area, I am very concerned that we have no tests to ensure/reduce risks of regressions.
I've looked at the change and it looks acceptable, though I'm having a hard time fully understanding it.

**Comment by mstv** [comment]
I successfully tested this PR, which also includes #6834, under heavy load this morning; two parallel builds of different repos in parallel.
`git status` was run with the expected delays. In case of very long Git runtime, it paused for 5 minutes.

Both Git command logs looked similar. Extract:
```
2019-06-24T09:47:31.7261902+02:00       17308   UI      C:\Program Files\Git\git-bash.exe       D:\ls\
2019-06-24T09:47:46.3571902+02:00   405 9292    UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:47:49.4091902+02:00   6713    38916   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:52:56.3052126+02:00   1837    45840   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:57:58.2200835+02:00   870 47144   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:01.2806955+02:00   774 36356   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:04.3368066+02:00   686 39160   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:07.9395270+02:00   705 32164   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:11.0036397+02:00   576 22192   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:15.0389466+02:00   710 6284    UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:18.0970581+02:00   621 56860   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:21.1571700+02:00   652 38272   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:24.2122809+02:00   929 32564   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:27.2698923+02:00   693 19264   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:30.3310044+02:00   758 51952   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:33.4196220+02:00   655 32688   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:36.4757331+02:00   723 50932   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:40.0809540+02:00   759 39932   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:43.1365650+02:00   816 25956   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T09:58:47.7229821+02:00   1999    8492    UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T10:02:42.1263534+02:00   117 46860       0   git ls-files -z --unmerged  D:\ls\
2019-06-24T10:03:42.0288315+02:00   92  36704       0   git ls-files -z --unmerged  D:\ls\
2019-06-24T10:03:49.8433941+02:00   681 46852   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T10:03:52.8985050+02:00   1626    33264   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T10:08:54.5781417+02:00   937 16728   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
2019-06-24T10:08:57.6247509+02:00   2520    51852   UI  0   git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none  D:\ls\
```

**Comment by gerhardol** [comment]
> In case of very long Git runtime, it paused for 5 minutes.

That should only occurs in the event of errors. 
If you have the log it could be interesting.
However, I am not much concerned as long as it occasionally occurs in high load situations. The user can force refresh too.

> As noted in another PR related to the area, I am very concerned that we have no tests to ensure/reduce risks of regressions.

These type of problems are extremely difficult to catch in tests. #6834 exception was a surprise for me.
The problem seen here was something partly considered, should have repaired by itself. When rewriting this together with someone I will not blame, this was simplified too much, the cancelToken should have stayed.

**Comment by gerhardol** [comment]
Plan to merge this tomorrow, unless there are objections

**Pull request merged**
