### PR TITLE
Add keyboard hotkeys to one menu and one dialog

### PR DESCRIPTION
**Pull request by Timwi**
## Proposed changes

Added a few keyboard hotkeys to one menu and one dialog.

### Before

image
image

### After

image
image

I agree that the maintainer squash merge this PR (if the commit message is clear).
----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
>The pull request shows AppVeyor reporting a build failure. It builds fine for me, and it’s extremely far-fetched to think that my changes would cause the build failure. Any help?

The build does not only building the solution. Did you had a look to the build report (the "Details" link)?

There you will see an error:

image

So yes, that's your changes that make the build failed for a good reason.

Because you touched strings of the UI, you need to update the english translation file:
https://github.com/gitextensions/gitextensions/wiki/Translations#how-to-update-english-translations

**Comment by RussKie** [comment]
> image 

"Create branch" mnemonic doesn't align:
image

Would be good to align the label too while we're at it.

> image

Why did you choose to do "Mi&xed" and not "&Mixed"?

**Comment by pmiossec** [comment]
@Timwi You seems to have updated the english.xlf file. If you did it manually, please us the command line to do it. Otherwise, perhaps it's a problem of end of line characters. And we will have to add a line for `xlf` files in the `.gitattributes` file so that does not happened anymore...

**Comment by Timwi** [comment]
@RussKie I’m afraid I don’t know what you mean by `"Create branch" mnemonic doesn't align`. I didn’t touch anything called “Create branch”. I chose Mi&xed over &Mixed because the latter would clash with &Merge.

@pmiossec Thank you for your patient explanations. I hope this should be fine now.

**Comment by RussKie** [comment]
> I chose Mi&xed over &Mixed because the latter would clash with &Merge.

Going top to bottom "Mixed" is the first candidate for a "&M" not "Merge".

> I’m afraid I don’t know what you mean by `"Create branch" mnemonic doesn't align`. I didn’t touch anything called “Create branch”.

Ah, missed it on the original screenshot. Please update it as well.

**Comment by Timwi** [comment]
> > I chose Mi&xed over &Mixed because the latter would clash with &Merge.
> Going top to bottom "Mixed" is the first candidate for a "&M" not "Merge".

I’m not sure why that is such an important criterion? I thought `x` for `Mixed` would be a better mnemonic than `e` for `Merge`. If you really insist though I guess I’ll change it.

> > I’m afraid I don’t know what you mean by `"Create branch" mnemonic doesn't align`. I didn’t touch anything called “Create branch”.
> Ah, missed it on the original screenshot. Please update it as well.

Sorry, update what? I’m very confused.

**Comment by pmiossec** [comment]
> I’m not sure why that is such an important criterion? I thought `x` for `Mixed` would be a better mnemonic than `e` for `Merge`. If you really insist though I guess I’ll change it.


I also prefer `x`.


Could you rebase your PR on top of last upstream `master`? I think it will fix the build.

**Comment by RussKie** [comment]
The tests are fixed by #9607.

**Comment by Timwi** [comment]
That is now done. Thank you for your patience!

**Comment by RussKie** [comment]
Thank you

**Comment by gerhardol** [comment]
`M` should have been used for the most common option that is Mixed.
I have never seen a need for Merge` and `Keep`.

**Pull request merged**
