### PR TITLE
Changed GPG tab setting to show by default

### LINKED ISSUE #5527: Default GPG tab to show
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The setting defaults to off.  Setting is kind of buried.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Show GPG tab by default.  Let user hide it if desired.
**Environment you encounter the issue:**

- GitExtensions version:master
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
no

### PR DESCRIPTION
**Pull request by oriash93**
Fixes #5527

## Proposed changes
- Changed the GPG tab setting to show by default.
- Added a description that a restart is required for the change to take place.

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Could you please elaborate why it is needed to be visible by default?

The reasons for me not to show it by default are:
* it creates more visual clutter
* it would generate more background calls and thus affect the performance of the app

**Comment by vbjay** [comment]
Nobody will find the setting. It doesn't slow down the app.

**Comment by RussKie** [comment]
Ok, so is it about making settings more discoverable then?

**Comment by gerhardol** [comment]
Translation text should be updated to see the changed text.
There has been some discussions about this. I have updated the wiki, hope that @RussKie and @vbjay are approving
https://github.com/gitextensions/gitextensions/wiki/Guidelines:-contributor

**Comment by vbjay** [comment]
Only modify the english xlf files.  The rest will be translated.

**Comment by RussKie** [comment]
@gitextensions/git-extensions-source any thoughts on this?

**Comment by amaiorano** [comment]
> @gitextensions/git-extensions-source any thoughts on this?

I don't even know what this feature is. Can we get screenshots of before/after? In any case, sounds like everyone is in agreement that this change is fine.

**Comment by RussKie** [comment]
By enabling this you'll get a new tab that shows gpg information, if a ref is signed

**Comment by amaiorano** [comment]
> By enabling this you'll get a new tab that shows gpg information, if a ref is signed

Okie dokie, sounds good to me!

**Comment by RussKie** [comment]
https://github.com/gitextensions/gitextensions/pull/3835#issuecomment-345511094
https://github.com/gitextensions/gitextensions/pull/4390

**Comment by amaiorano** [comment]
> [#3835 (comment)](https://github.com/gitextensions/gitextensions/pull/3835#issuecomment-345511094)
> #4390

Thanks for the screenshots! Nice feature :)

**Pull request merged**
