### PR TITLE
PathUtil.GetDirectoryName did not accept root dirs

### LINKED ISSUE #7086: GE fails to identify .git folder at root of drive from cmd line
## Current behaviour

When using GITExtension's explorer context menu on a repository that is located at the root of a drive on a file or folder that is NOT at the root, it fails to find the .git folder and issue the following message instead:

`The current directory is not a valid git repository.`

## Expected behaviour

The repository should be found even if at the root of the drive.

## Steps to reproduce

Use any local repository that contains sub-folders. 
Map it to a new drive using either subst or net use. 
Navigate to the newly mapped drive letter, go inside a folder (any folder).
Right-click on any file in the repo and select "File history..." (or any other GE option, really).

## Screenshots

image
image
image

## Did this work in previous version of GitExtensions

No

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #7086

## Proposed changes
 * Use .NET Path.GetDirectoryName instead of PathUtil to also detect root directories

The existing function could have been adapted (by removing a few lines), but the standard function should be used. 

## Test methodology 
Manual

## Test environment(s) 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
Suggesting merge in 3.3

**Comment by Kryptos-FR** [comment]
Unlikely to be correct since `Path.GetDirectoryName` can return `null` but `ToPosixPath` expects a non-`null` `string`.

**Comment by gerhardol** [comment]
> Unlikely to be correct since Path.GetDirectoryName can return null but ToPosixPath expects a non-null string.

Path.GetDirectoryName returns null when called with null or root path. This is not the case in these situations.

However, it possible to get an exception with a call like 'GitExtensions.exe filehistory "n:/"' 
Pushing an update (so just ignoring "files" that consists of only whitespace).
This code is unrelated to the original change though.

**Comment by gerhardol** [comment]
To fix exceptions for 'GitExtensions.exe filehistory "x:/"' where filehistory can be most any command and x:/ do not contain a .git dir, many changes are needed:
 * Handle trailing " (see https://github.com/gitextensions/gitextensions/issues/3489)
 * Handle that the filename is not in a Git repo and that it may be empty

Not really worth it

**Pull request merged**
