### PR TITLE
fix: Remove duplicate resource reference

### PR DESCRIPTION
**Pull request by RussKie**
77.png was referenced under both "Settings" and "Icon_77".

### CODE REVIEW

**Comment by jbialobr** [comment]
Why did you choose the Icon_77 over the Settings icon? Isn't the second name better?

**Comment by RussKie** [comment]
Heh, initially I had it the other way :)

The reason I chose to keep the number was - there are a number of other
numbered icons, which correlate with physical files.

...and I am also planning to use icon 78.png, and it kind of felt logical
to keep the number.

**Comment by jbialobr** [comment]
>The reason I chose to keep the number was - there are a number of other
numbered icons, which correlate with physical files.

Still, I think it is better to keep the Setting icon.

**Comment by RussKie** [comment]
As you wish

**Comment by jbialobr** [comment]
Thanks.

**Pull request merged**
