### PR TITLE
Support for building GitExtensions in Visual Studio 2015

### PR DESCRIPTION
**Pull request by DanRigby**
* Add support for building GitExtensions with just Visual Studio 2015 (no VS 2013 installed, etc).
* This Pull Request has dependencies on PR #2893 and PR #2885.

### CODE REVIEW

**Comment by DanRigby** [comment]
If this PR is successfully merged, we still need to update the WIX installer to handle the new VSIX file.

**Comment by sharwell** [comment]
This pull request further increases the complexity of a solution/project structure which was already too complex. After #2885 is merged, I recommend using the approach in [sharwell/consolidate-solutions](https://github.com/sharwell/gitextensions/tree/consolidate-solutions) rather than the approach used here. I plan to send a pull request as soon as #2885 is merged.

**Comment by DanRigby** [comment]
The single solution approach is definitely better. I'm going to close this PR. Thanks @sharwell!

**Comment by sharwell** [comment]
I'm glad we are on the same page. :smile: I was in a dilemma because I didn't want to give *you* (@DanRigby the person) a :-1:.

**Comment by DanRigby** [comment]
Sure. My current system only has VS Community 2015 on it, so I can test this later. I created the new 2015 solution mainly just so I could build GitExtensions locally. I didn't know there was a better way to just use one set of solutions and projects using conditionals. :wink:

That's also how my other Pull Request was born. Right now we're using the .NET 3.5 version of ResGen.exe so GitExtensions won't build on a clean install of Windows 10 / VS 2015 despite all of the GitExtensions code targeting the .NET 4.0 Client Profile. :smile:

**Comment by jbialobr** [comment]
> I plan to send a pull request as soon as #2885 is merged.

@sharwell The #2885 is merged.

**Comment by vbjay** [comment]
Mine builds fine.  Watch that you don't have an environment variable with
the name platform.  HP likes to do this.

**Pull request closed without merging**
