### PR TITLE
Various forms: limit menu options for artificial and submodule

### PR DESCRIPTION
**Pull request by gerhardol**
The menu options primarily for the Browse Diff has currently a lot of unusable combinations, especially for artificial commits and submodules. One example is cherry pick and blame for submodules.

This is not intended to be a final cleanup, there are some combinations with diff that is not working in this commit. There are at least some cherry-pick with FileHistory for submodules.
There are also no tests added. 
There are more changes related to this coming from #4031 (where this change also origins). It is however very hard to completely separate the changes and to still have something that can be reviewed.

One option to handle this is to approve but not merge to master and keep related changes on top of this. But it will be harder to review.

Changes proposed in this pull request:
 - Hide or disable menu options that are irrelevant for submodules and artificial commits. This primarily affects Browse, but also FileHistory and RevisionGrid (general)
 - Some caching of artificial commit outputs has been suppressed
 - FileHistory Blame tab hidden for submodules and artificial
 - Artificial guid is not displayed in revision grid
 - Browse Diff Reset did not handle Reset properly

Screenshots before and after (if PR changes UI):
- TBD, a few new only right now
image
image
image
image

How did I test this code:
 - Manually

Has been tested on (remove any that don't apply):
 - GIT 2.14 - not affecting Git (should be less Git usage as options are hidden).
 - Windows 7 and Win10

### CODE REVIEW

**Comment by RussKie** [comment]
I've run this change and something isn't right - going from normal revision takes about 2.5s, whilst going from the artificial commit to the normal one is almost instant

image

there are a lot of background threads being spawn to the artificial commit which seems to be very taxing.

here're my settings:

image

**Comment by RussKie** [comment]
Also as soon as I ticked "Show revision details next to revision list" the UI changed to this, which is bad:

image

**Comment by gerhardol** [comment]
For performance:
Switching to "artificial" commit will check for files checked out etc. Nothing about that is changed by this commit. It primarily changes what menu alternatives that are shown/enabled and a few GUI tweaks. (There is one caching for diff removed in a specific situation too.)
For me I can see that normal->artificial is slower though only if I concentrate though.

How is the performance for you without any patch? It should be the same.
What is in your gitlog when seeing this? Are the "Commit button update" queuing other commands too?
If so, the problem will be improved with the proposals in #4069.
The caching can be improved, both the CommitButton and here. That will increase complexity though.

For UI:
I cannot recreate the empty panel. I get an empty form though which is ugly enough. This is not changed by this commit, it is like that before. I could add everything in one big PR, but that would be impossible to review...
Hiding the empty panel is handled in #4096.

**Comment by RussKie** [comment]
Steps to reproduce the empty panel:

1. Start with normal layout:
image

2. Enable different layout:
image

3. Apply and... Bang!
image

**Comment by gerhardol** [comment]
> I haven't verified, but I think this is caused by bf66cbb
I was looking at the artificial commits...
Without testing myself, I believe this is caused by the update in panel vs tab is just changed at restart. If the comment "requires restart" is insufficient, I will have to add some code to activate this after restarts only (maybe store a static variable). Is it worth the extra checks?

**Comment by RussKie** [comment]
No, I don't think that would be a good idea. There should be sufficient
information for us to make determination....

Thinking out loud - wouldn't you only expand it if the setting is set to
show?

**Comment by RussKie** [comment]
Send it tooo hastily.... scratch that.

I will have to think about it myself :)

**Comment by gerhardol** [comment]
Merged 'origin/master' into feature/n4031-formbrowse-diffmenu-artificial-submodule

This basically drops the changes in GitUI/CommandsDialogs/FormBrowse.cs (and Designer)
"Commit Panel" handling in #4096 (I removed that manually from this commit)
Other changes will be handled in a new PR, so DiffPanel menu is not yet updated

**Comment by gerhardol** [comment]
Any other comments, now when #4096 is separated?
This PR makes the conditions for the menu slightly more complex, but not as for #4106 etc, so I suggest refactoring is done later.

**Comment by gerhardol** [comment]
What can be done to merge this PR? Split it up in several?
The UI and performance issues in the review are not related to this issue.
This and the related issues should be merged to find the remaining "menus displayed when they should not be".
I suggest refactoring to *Controller classes is done after the improvements are merged.

**Comment by RussKie** [comment]
I'll bump it up on my todo list

. . .

image
Does it make sense to show disabled items at all?

**Comment by vbjay** [comment]
Sure. I like knowing I can't do something because of state and knowing the
option is there.

**Comment by RussKie** [comment]
Then, following your statement, all menus should have all the same options :)

**Comment by RussKie** [comment]
It doesn't look the code is working as expected. Perhaps it is outdated...
image

One of the issues - this PR adds `DiffContextMenuOpening` method which isn't wired whilst there is an existing wired `DiffContextMenu_Opening` method.

Please make sure the code is working as expected and squash/rebase on top of master for further review.

**Comment by vbjay** [comment]
Lol. Not exactly. My point is that seeing the option disabled is better
than, Where did the option go?

**Comment by gerhardol** [comment]
Note: FormDiff is not working at all, also for master (the change in FormDiff is limited)

The problem appeared around the time for refactoring of RevisionDiff

**Comment by gerhardol** [comment]
If an action is not relevant at all like Blame for a submodule, it should not be visible.
If an action is relevant but not relevant like Difftool BtoLocal where B is local, the option should be disabled.

The exact rules are hard to set. For instance, I added stage/unstage for artificial commits in #4087. Those actions are only available for the relevant artificial commit to limit clutter even if the options could be visible for all files.

I consider this to be an initial cleanup, the options should be reviewed when all relevant commits are merged (or rejected). This is just a step.
(Maybe RussKie's refactoring to *Controller should be done too in the eventual cleanup, as I am not so entusiatic about it it will take time if I am to do something here...)

**Comment by RussKie** [comment]
Can you please rebase, thanks

**Pull request merged**
