### PR TITLE
FormPull: fix button size

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes https://github.com/gitextensions/gitextensions/issues/9402#issuecomment-1024391529

### Before

image

### After

image

## Test methodology 

- Manual

## Test environment(s) 
- Git Extensions 33.33.33
- Build b38de85f8a58d980ffaa2e640e142632dc3c43b3
- Git 2.34.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.13
- DPI 192dpi (200% scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by mstv — APPROVED** [review]
non-obvious solution 👍

**Comment by RussKie** [comment]
Do we set min dimensions for other buttons? I'm curious what's causing the
buttons to shrink

**Comment by pmiossec** [comment]
> Do we set min dimensions for other buttons?

I don't know if that's the reason why the fetch/pull button at the right is well displayed (it will need investigation to check) but, yes, I took it from it. 

> I'm curious what's causing the buttons to shrink

If you find, I will be happy to understand also 😁

Side note (which makes things a little painful and limit what I could do) : the Winforms designer is not loading in my VS2022 (don't know if linked to .net5... ). So I'm limited to editing of designer.cs files manually 😕

**Review by gerhardol — COMMENTED** [review]
+1

**Comment by RussKie** [comment]
Proposing an alternative :)

* 100%
image
image

* 125%
image

* 200%
image

(built on top of the .NET 6 branch)

**Review by RussKie — APPROVED** [review]

**Pull request merged**
