### PR TITLE
Fixup FormResetAnotherBranch ComboBox handling

### LINKED ISSUE #11644: Reset branch: Dropdown opens on press of `Alt` key
### Environment

vNext

### Issue description

FormResetBranch: Dropdown of combobox "Reset local branch" opens on presss of `Alt` key

### Steps to reproduce

- "Reset other branch to here"
- try to press `Alt+F`

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #11644

## Proposed changes

- Do not open dropdown on special keys (`Alt` = `Menu` and `Escape`) 
- Preserve text and selection
- Open dropdown in `KeyUp` instead of `KeyDown`
- Fixup `TabIndex` and `TabStop` in order to make mnemonics work

## Screenshots 

N/A

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by berrs** [comment]
Seems to work.   There is another problem though - the alt+b shortcut on the dropdown doesn't work. Looks like that's due to bad tab indices (the label should have tab index 1, and the rest would follow with higher numbers). I would suggest a change here but I don't know how that works in github.

**Comment by mstv** [comment]
> Looks like that's due to bad tab indices (the label should have tab index 1, and the rest would follow with higher numbers).

👍 I noticed it, too. But I hesitated to fiddle around with the Designer.

BTW: Is there an option to preload the out-of-process Designer?

**Comment by berrs** [comment]
> 👍 I noticed it, too. But I hesitated to fiddle around with the Designer.

I can fix it in a separate PR if desired.

> BTW: Is there an option to preload the out-of-process Designer?

No idea actually. I don't work that much with WinForms.

**Review by berrs — APPROVED** [review]

**Comment by mstv** [comment]
@berrs, thank you for the review.
(I am not sure whether you have noticed that I applied your suggestion regarding `TabIndex` in https://github.com/gitextensions/gitextensions/pull/11656/commits/1cde4ab85c1d505c8d49e4f24973f0474cb21933, i.e. no need for another PR.)

**Comment by RussKie** [comment]
> BTW: Is there an option to preload the out-of-process Designer?

Could you please elaborate?

**Review by RussKie — APPROVED** [review]

**Comment by berrs** [comment]
> @berrs, thank you for the review. (I am not sure whether you have noticed that I applied your suggestion regarding 

No I didn't notice actually. Thanks for pointing it out.

**Comment by mstv** [comment]
Off-topic discussion:

> BTW: Is there an option to preload the out-of-process Designer?

The out-of-process Designer should be started in the background with low priority without a Form yet, after a solution has been loaded.
"You can continue working..." is not true if I deliberately started it.

designer

(And if I mistakenly open the Designer by double clicking or by image, I dislike the pretty busy VS. Anyway, there should be added another option to open the code by default.)

**Comment by pmiossec** [comment]
>Anyway, there should be added another option to open the code by default.

Yes, that's one of the default VS config that I change to never open the designer by default:
image

**Pull request merged**
