### PR TITLE
EditNetSpell: Don't open auto-complete when moving

### LINKED ISSUE #5770: Do not open autocomplete when moving in the commit message editor
**Do you want to request a *feature* or report a *bug*?**
UX improvement

**What is the current behavior?**
The autocompletion list pops up and consumes further navigation key presses ([Page]Up/Down, Home/End) when moving through the commit message.

(I know that the list can be closed using Escape and that it can be switched off completely.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- type an identifier from a modified file into the Commit Message Editor
- use the Up/Down keys to position the caret outside and back in this identifier
- further navigation keys will change the autocomplete selection

**What is the expected behavior?**
The autocompletion list shall pop up only when typing a word or on request (Ctrl+Space).
Caret positioning shall work without interruption.

**Environment you encounter the issue:**
3.x, 2.51.05

**Did this work in previous version of GitExtensions (which)?**
no

### PR DESCRIPTION
**Pull request by mstv**
Fixes #5770

Changes proposed in this pull request:
1. Do not open the auto-completion list when moving in the commit message editor (both by keyboard and by mouse). The auto-completion list pops up only when typing a word or on request (Ctrl+Space).
2. Make auto-completion popup when typing a word at a line end.
 
Screenshots before and after (if PR changes UI):
1. n/a
2. before: no popup at line end
after:
grafik

What did I do to test the code and ensure quality:
- manual testing

Has been tested on (remove any that don't apply):
- Git Extensions 3.00.rc2
- Build 876903cf464aebd11d09a01a9849ea87043d4803
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

### CODE REVIEW

**Comment by drewnoakes** [comment]
I haven't tested this change but I'm hugely in favour of the concept. I find the auto completion popup really annoying. It regularly replaces words I want with words I don't want.

**Comment by RussKie** [comment]
I disabled it completely

**Comment by drewnoakes** [comment]
I hadn't considered disabling it. Would be more discoverable with #5559.

**Comment by drewnoakes** [comment]
With this PR merged I _think_ we could also remove the option. If auto-complete is an explicit operation via Ctrl+Space, then why would we need the option?

Fewer options, it's the dream... 😄

**Comment by mstv** [comment]
> With this PR merged I think we could also remove the option. If auto-complete is an explicit operation via Ctrl+Space, then why would we need the option?

Maybe "only via Ctrl+Space" is the better approach. Currently, it pops up, too, when entering an identifier character (and some more -- I was just restricting it to Ctrl+Space and only idenfier characters).

Con: The hotkey Ctrl+Space is nearly invisble.

**Comment by vbjay** [comment]
I love the identifier logic. It's great when I start a class name and it
suggests the rest. Ctrl space is pretty much ubiquitous. So yes it's hidden
but not hard to find. A defacto standard. Almost as a standard of Ctrl c.

**Comment by drewnoakes** [comment]
Oh I misunderstood.

Once the popup is open it captures normal navigation. It also prohibits Ctrl+Enter from working.

I find it opens when I'm writing non-completion words and then completes them for me on space. That's frustrating, as it's an interruption and takes some work to clean up. That's why I would turn it off (now I know that's an option).

The other annoying scenario is that it pops open when moving around text with the arrow keys, which is what you're fixing here, right? That's an improvement for sure.

I would like it to be Ctrl+Space only. Has this backfired and now we need _more_ options?

**Comment by mstv** [comment]
I've just pushed an improved version, which
- explicitely checks for identifier characters and Ctrl+Space,
- allows Ctrl+Space everywhere,
- makes the RichTextBox's Undo work (by using `TextBox.SelectedText = completionWord.Word;` instead of replacing the whole `.Text`).

> I would like it to be Ctrl+Space only. Has this backfired and now we need more options?

Understood. I am not sure yet whether I prefer "open auto-complete only on Ctrl+Space".
We should not need more options: Ctrl+Space should work always and would not disturb anybody.
The existing option could either be removed, or slightly modified to enable auto-complete on identifier characters.

> I love the identifier logic.

I guess, Jay voted against "open auto-complete only on Ctrl+Space"?

@others: Thoughts?

**Comment by gerhardol** [comment]
It seems reasonable that Ctrl-Space always works and that automatic identifier handling can be disabled

I vote to keep the automatic handling on, as is in the PR

**Pull request merged**
