### PR TITLE
Fix FormRebase DPI issues

### LINKED ISSUE #11606: Rebase Form has multiple high-dpi scalling issues
### Environment

- GitExtensions version: master
- OS version: Windows 11
- .NET version: 8

### Issue description

When comparing Scaling of 100% and 200% several differences are clearly visible
1. The buttons seem to be scaled twice. i.e. they are enlarged 4x rather than 2x when going from 100% to 200%
2. The image explaining effects of rebase is not scaled. Just compare one of commit bubbles with a checkbox to the right, their proportions are clearly different between two scaling options.

100% scaling
image

200% scaling
image

### Steps to reproduce

Switch between low/high DPI and produce a merge conflict with interactive rebase. Compare the form visually.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mdonatas**
Fixes #11606

## Proposed changes

- Use `Font` scaling. Tests with .net framework 4.7.2, .net6 and .net8 have shown that `Dpi` scaling mode doesn't work properly for controls which are placed in container controls. This [SO question](https://stackoverflow.com/questions/22735174/how-to-write-winforms-code-that-auto-scales-to-system-font-and-dpi-settings) has helped a lot.
- Adjust `Commit hash` column to fit the header text without wrapping
- Fix Help image scaling.. And as for `FormMerge` it was sad to find out that even the text above the image turns out has always been clipped

### Before

100% scaling
FormRebase-100p-master

200% scaling
FormRebase-200p-master

### After
100% scaling
FormRebase-100p-fixed

200% scaling
FormRebase-200p-fixed

## Test methodology 

- Checked `FormRebase` and `FormMerge` manually at 100% 150% and 200% scaling

### Before
200% scaling
FormMerge-200p-master

### After
200% scaling
FormMerge-200p-fixed

## Test environment(s) 

- Windows 11
- 100% 150% and 200% scaling

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
>Adjust Commit hash column to fit the header text without wrapping

Personal preference: rename column header to just "Hash".

And while we are at it, I will move the hash column to the last position ( because it's not a really useful data here to understand where we are in the rebase and as a consequence, it will be consistent with revision grid...)

Others point of view?

**Comment by mdonatas** [comment]
It does look better being at the end IMO. But as for renaming it to just say "Hash" I wouldn't do that since there are more places in the app where we say "Commit hash" and it's better to be consistent.

With `Commit hash` at the end
image

**Comment by RussKie** [comment]
My biggest concern is the font scaling.

We're using the dpi scaling across all forms and controls. The font scaling
can be unpredictable in some scenarios (I can't remember which one), that's
we don't use it.

IIRC, AutoScaleDimensions property may be the reason of the scaling issues,
and should be removed completely. E.g., are we using this property in other
forms/controls that are good?

**Comment by mstv** [comment]
`dotnet build /p:RunTranslationApp=true` needs to be run

**Comment by mdonatas** [comment]
@RussKie first of all, thank you! You helped me challenge my assumptions that auto-scaling in flex containers simply doesn't work for `Dpi` mode. It does, but is kinda a bit pain-in-the-elbow ;]

I've compared extensively `FormRebase` with `FormClone` which looks OK in 200% Dpi and found the main cause.

First of all, here's a visual diff of the most recent commit between 100% and 200% scaling, pretty good I think.
FormRebase-100-200-dpi-diff

One "must have" thing is `button.AutoSizeMode = AutoSizeMode.GrowAndShrink`. Without it or with `GrowOnly` buttons blow-up.
A second an almost-must-have is to set the `MinimumSize` to be equal to the `Size` otherwise the buttons shrink too much (especially visible on the `Abort` button). Without `MinimumSize` 👇
FormRebase-200p-fixed-dpi-mode

**Comment by mdonatas** [comment]
> `dotnet build /p:RunTranslationApp=true` needs to be run

@mstv I've ran it but no changes were introduced. To clarify, I haven't changed the title of `Commit hash` column, just moved it, that shouldn't introduce changes to translation.. or should it?

**Comment by pmiossec** [comment]
> > `dotnet build /p:RunTranslationApp=true` needs to be run
> 
> @mstv I've ran it but no changes were introduced. To clarify, I haven't changed the title of `Commit hash` column, just moved it, that shouldn't introduce changes to translation.. or should it?

I think it doesn't change the values but the order is changed in the file and so the check in the CI fail. So you will have to update it unfortunately...

**Comment by mdonatas** [comment]
🤦 when moving the `Commit hash` column I've also played with renaming it to `Hash` and left the rename by accident. Fixed (reverted) in the latest commit.

**Review by mstv — COMMENTED** [review]
yep, AppVeyor build succeeded

**Review by RussKie — APPROVED** [review]
🚀

**Pull request merged**
