### PR TITLE
MSysGit updated to version 1.9.5-preview20141217

### PR DESCRIPTION
**Pull request by linquize**
#2574

### CODE REVIEW

**Comment by cniweb** [comment]
Fix please and rollout a new Version!

**Comment by linquize** [comment]
It is not my fault! The master branch is also failing to build using TeamCity.

**Comment by cniweb** [comment]
Who can fix this?

**Comment by cniweb** [comment]
@KindDragon can you fix it, plaese?

**Comment by linquize** [comment]
The last known successful build is c5e3aea4ecc9.
The next commit just updates markdown file, But TeamCity starts to fail since 20 Dec 2014.

**Pull request merged**
