### PR TITLE
Make it possible to open difftool on multiple unstaged files as we ca…

### PR DESCRIPTION
**Pull request by amaiorano**
…n with staged

### CODE REVIEW

**Comment by amaiorano** [comment]
As the commit messages says, with this change, we can open the diff tool (F3) on multiply selected unstaged files, just like we can with staged. I use Beyond Compare, which opens each diff in a separate tab, so this is a very useful feature for me when reviewing my diffs.

I added the wait cursor and a half second sleep so that when we press F3, we get visual feedback that something is going to happen. Without this, hitting F3 looks like it did nothing, and sometimes it can take a while for the external diff tool to open, so you end up pressing F3 a few more times, which ends up opening the same diff multiple times as well.

**Comment by amaiorano** [comment]
Hello, I know you're really busy, but can I have a quick review of this change? Thanks :)

**Comment by jbialobr** [comment]
I would like to encourage everyone to do code review. You don't have to be a GitExtensions team member to do so. GitExt team lacks of maintainer workforce.
Please, find two other pull requests, review them and ask the authors of these pull request to review your pull request.

**Comment by amaiorano** [comment]
Ah okay, that's an interesting way to do this. Thanks.

**Comment by amaiorano** [comment]
I'm closing this PR and will open a new one with a better change.

**Comment by amaiorano** [comment]
New PR: https://github.com/gitextensions/gitextensions/pull/3556

**Pull request closed without merging**
