### PR TITLE
fix reset file menu item text

### PR DESCRIPTION
**Pull request by pmiossec**
When in English, every time the reset file menu items are displayed,
the commit message was appended ending wrong....

Before appending the commit message text, we restore to the original version

### CODE REVIEW

**Comment by jbialobr** [comment]
This happens because English.xlf is not present in the installation dir.

**Comment by pmiossec** [comment]
Yes, indeed, that's a side effect because there is no English.xlf file.

So what should we do? Accept this fix or provide the `English.xlf` and `English.plugin.xlf` files? Because they properties are at "Do not copy" in the directory output....

**Comment by jbialobr** [comment]
We should include the English translation files - this way we do not need the excess code.

**Comment by KindDragon** [comment]
> We should include the English translation files - this way we do not need the excess code.

Previously in similar situations, we saved original text and then restore it back.

**Comment by jbialobr** [comment]
Thanks, I accepted the other PR.

**Pull request closed without merging**
