### PR TITLE
VSIX build and packaging updates

### PR DESCRIPTION
**Pull request by sharwell**
* Updated the Visual Studio SDK and reference assemblies
* Add `[ProvideBindingPath]`¹, which is possibly a fix for #4708
* Add the `TextChanges` command flag for `gitExtCommitCommand`, which is possibly a fix for #4117 
* Simplify package and command registration
    * Use cast instead of `as` for required success
    * Pass event handlers to `OleMenuCommand` constructor instead of registering them afterwards
    * Style cleanup in `GitExtensionsPackage`
    * ~~Remove the use of `[ProvideAutoLoad]` (Visual Studio will load the packages when the command information is needed)~~ https://github.com/gitextensions/gitextensions/pull/4747#issuecomment-379253790

¹ This is not the recommended approach, but the preferred attribute `[ProvideCodeBase]` requires the target assembly have a strong name.

### CODE REVIEW

**Comment by gerhardol** [comment]
This seem to affect the old vs plugins too. What testing is needed? What do wegnwant to support? (are the old plugins even distributed officially)

**Comment by sharwell** [comment]
> This seem to affect the old vs plugins too. 

This should not have any impact on the old plugin.

> What testing is needed?

I'm not sure. I don't use the plugin and couldn't reproduce the issues mentioned. The changes are based on outcomes of similar situations I've observed in the past.

**Comment by RussKie** [comment]
I've built a VSIX, uninstalled the existing one, installed the new one and for the most part it seems to work as expected - I didn't see any duplicated icons. However the commit button no longer shows the current branch...

**Comment by sharwell** [comment]
> I've built a VSIX, uninstalled the existing one, installed the new one and for the most part it seems to work as expected - I didn't see any duplicated icons. However the commit button no longer shows the current branch...

I have a feeling this is caused by removing the `ProvideAutoLoad` entries. I need to replace them with the more modern alternative.

**Comment by sharwell** [comment]
@RussKie I restored the original behavior so we can deal with the use of `ProvideAutoLoad` later.

**Comment by sharwell** [comment]
I merged **master** into this branch to preserve the complete and clean build history for this PR.

**Comment by gerhardol** [comment]
A new update needed after merge of #4799 
Should this be merged now?

**Comment by RussKie** [comment]
I've finally got around to this, apologies for the delay.

I've uninstalled the extension from my instance of VS and restarted the IDE. I've built the branch in Debug mode, set GitExtensionsVSIX project as a start-project and run it:
image

All buttons in the toolbar and the menu are clickable and operate as expected.

Duplicate toolbar icons go away after the toolbar is reset (little dropdown icon at the end of the toolbar > Add or Remove Buttons > Reset)

**Comment by RussKie** [comment]
I installed the built extension but I am still not seeing the current branch in toolbar.
I have toggled "Show current branch in VS" setting off and on but it is still not showing.... I'm not sure how to troubleshoot this unfortunately

**Comment by sharwell** [comment]
@RussKie I'm going to submit a minimal set of updates that doesn't change any of the registration behavior, and we can deal with whatever's happening to the text separately.

**Pull request closed without merging**
