### PR TITLE
Unit tests restructure

### PR DESCRIPTION
**Pull request by RussKie**
Unit tests restructured to provide 1-to-1 mapping between main projects (i.e. production code) and their test projects.
This allows simpler maintenance, less coupling and reduce risk of writing integration tests instead of unit tests.

### CODE REVIEW

**Comment by RussKie** [comment]
There are no functional changes - I have created few new projects, moved files around and adjusted namespaces in unit test projects.

**Comment by jbialobr** [comment]
>This allows simpler maintenance

For me it looks more complex. Writing a single test for a plugin require to create a new project add dependencies, configure nuget. We will have 2 times more projects - this can affect VS performance (reloading) and build time.

I would prefer to have one project for unit tests and one for integration tests (if we need a separate one).

**Comment by vbjay** [comment]
Why not create a plugin unit test project for all the plugins, nother for
main app.

**Comment by jbialobr** [comment]
@vbjay What do we gain by splitting unit tests project into these two?

**Comment by vbjay** [comment]
Instead of what you said

Writing a single test for a plugin require to create a new project add
dependencies, configure nuget

We could reorg with main app unit tests. Project tests does the git
functionality work. Then we could test plugin functionality separately.

**Comment by jbialobr** [comment]
Sure, but what is the added value? Have you ever wanted to do so? If yes, why?

**Comment by vbjay** [comment]
The added value is keeping plugin testing separate not bloating with tons
of pluginX test project like you complained about.  The plugins are
separate and should be separated in testing too.

**Comment by jbialobr** [comment]
Sorry, I was asking about the added value comparing to single project for all the unit tests.

**Comment by RussKie** [comment]
I should have said "_This allows simpler **code** maintenance_", but as you rightly pointed it may being a slight overhead on a solution level.

Over the years I tried various scenarios - tests alongside the production code, tests in one big test project and 1-1 map.
There is no industry guideline or definite agreement on what is better "a single unit project vs 1-1 map", however after a bit of research it seems that generally people prefer 1-1 map, as do I.

Personally, having worked on large complex projects, I prefer 1-1 mapping since it provides me with the following benefits:
* it forces you to reference only the assembly you are testing, otherwise there is an inherent risk of  accidentally turning your tests into integration tests or worse (I've seen this happen, it is not pretty). It helps to ensure separation of concerns.
* a nice test structure which mirrors the production structure, which in turn provides clarity for finding things. If project is removed/renamed, it is easy to remove/rename all associated tests.
* I don't have to compile the whole solution if I am changing/testing a particular project - this helps with efficiency. I can even unload all unnecessary projects at this point.

If we are concerned with solution load time, then perhaps we should consider moving plugins out of the solution as well.

**Comment by jbialobr** [comment]
>it forces you to reference only the assembly you are testing, otherwise there is an inherent risk of accidentally turning your tests into integration tests or worse (I've seen this happen, it is not pretty). It helps to ensure separation of concerns.

As I understand, separating unit tests from integration tests is desired because the first have to run fast while the second can run longer. Regardless of type both have to pass. Nowadays I rarely run unit tests locally. I prefer to create a private branch and push my changes to the remote to let the CI server to run the tests. Even if it happened to put an integration test to unit tests, it is easy fix to move the tests to the integration tests project. 

>a nice test structure which mirrors the production structure, which in turn provides clarity for finding things. If project is removed/renamed, it is easy to remove/rename all associated tests.

The same we can achieve with folders.

>I don't have to compile the whole solution if I am changing/testing a particular project - this helps with efficiency. I can even unload all unnecessary projects at this point.

From my point of view it is wasting my resources running tests locally unless I have to debug a test.
So it counts as a plus for your approach. Perhaps it would be better to apply a hybrid solution:
1. Start with a single project with folder structure reflecting the projects structure.
2. When some folder gets big enough that it become an issue, then move it to a separate project.
Doing it that way we avoid creating a project for a single unit test file.

**Comment by RussKie** [comment]
> Nowadays I rarely run unit tests locally. I prefer to create a private branch and push my changes to the remote to let the CI server to run the tests. Even if it happened to put an integration test to unit tests, it is easy fix to move the tests to the integration tests project.

I often work offline, so I run unit tests locally.
I also use NCrunch to help with coverage.

> Doing it that way we avoid creating a project for a single unit test file.

...or you can view it as an invitation to add more tests :)

**Comment by RussKie** [comment]
> separating unit tests from integration tests is desired because the first have to run fast while the second can run longer

_Unit tests_ test the component in isolation (hence specifying dependencies via interfaces, which can be easily stubbed), whereas _integration tests_ test how components work together - here you generally use the concrete implementations.
Naturally they have different objectives - the former would verify parameters (e.g. "_throw if parameter is null_") whilst the latter won't be doing such tests and would be testing things like "_if call database service I expect to receive the required record_".

One is not substitute for the other, if anything they compliment each other.

**Comment by jbialobr** [comment]
>or you can view it as an invitation to add more tests :)

I am ready to create an empty unit test and integration test project for each production project if that would help:) 
But seriously, after all your changes are not destructive, if we encounter any problems we always can restructure tests again.

**Comment by RussKie** [comment]
A codebase restructure keeps the codebase alive 😆

**Pull request merged**
