### PR TITLE
Fix 8122 Update Atlassian.SDK package to latest version

### LINKED ISSUE #8089: [NBug] Could not load file or assembly 'RestSharp, Version=106.1.0...
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileLoadException: Could not load file or assembly 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at Atlassian.Jira.Jira.CreateRestClient(String url, String username, String password, JiraRestClientSettings settings)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.UpdateJiraSettings()
   at JiraCommitHintPlugin.JiraCommitHintPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

## Additional information
I've just started GitExtensions via the Explorer context menu "GitExt open repository". I did it on a directory 1-leve into the repository.

## Environment
- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.7.3610.0
- DPI 96dpi (no scaling)

### LINKED ISSUE #8122: Jira Commit Hint throws exception for some Jira issues
## Current behaviour
We use cloud Jira and for some issues Jira Commit Hints fails to return list of issues in commit window. Instead it returns stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Atlassian.Jira.Remote.SingleObjectCustomFieldValueSerializer.FromJson(JToken json)
   at Atlassian.Jira.Remote.RemoteIssueJsonConverter.<GetCustomFieldValuesFromObject>b__9_1(JProperty field)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Atlassian.Jira.Remote.RemoteIssueJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Atlassian.Jira.Remote.IssueService.<>c__DisplayClass19_0.<GetIssuesFromJqlAsync>b__0(JObject issueJson)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.<GetMessageToCommitAsync>d__32.MoveNext()
```

## Expected behaviour
Jira Commit Hint should return list of Jira issues.

## Steps to reproduce
In Jira Commit Hint plugin set
- JQL Query: `assignee in (currentUser()) AND gh.sprint.customfield.default.name in openSprints() ORDER BY updatedDate`

Than some issue cannot be deserialized see screenshot.

## Screenshots
image

## Did this work in previous version of GitExtensions
I think bug is related to Atlassian.SDK

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by haldyr**
Fixes #8122 
Fixes #8089

## Proposed changes

- Updated Atlassian.SDK package to latest version

### Before
- some Jira issues could not be deserialized

### After
- updated Atlassian.SDK dependency fixes problem

## Test methodology 

- tested manualy in commit window (before change it didn't work, after change it is OK)

## Screenshots

Before
image

After
image

## Test environment(s) 
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
This has dependency on RestSharp 106.10.1, so more updates needed?

**Comment by haldyr** [comment]
Updated RestSharp to latest version.

Locally I have corresponding changes to Git.hub submodule (which uses RestSharp as well), not sure how to push it. I'll try to figure it out later (probably separate PR to that repo?).

**Comment by gerhardol** [comment]
> Locally I have corresponding changes to Git.hub submodule (which uses RestSharp as well), not sure how to push it. I'll try to figure it out later (probably separate PR to that repo?).

Yes separate PR, need to be merged together with this PR

Did you test BitBucket after the change?

**Comment by RussKie** [comment]
Please send a PR to https://github.com/gitextensions/Git.hub before we can merge this

**Comment by haldyr** [comment]
Created new PR in Git.hub repo: https://github.com/gitextensions/Git.hub/pull/16

I not able to test BitBucket plugin since I have no access to BitBucket Server. But I successfully tested exact same change in Git.hub repo - see PR above.

**Comment by gerhardol** [comment]
Plan to test BitBucket, Jira tomorrow

**Comment by gerhardol** [comment]
Can you squash and rebase?
@RussKie probably wants to merge in release/3.4 first, so rebase on that and edit the PR to target the release branch

I cannot 'test' today. The AppVeyor build fails due to something with the GH submodule and the build I prepared myself was incorrect (should maybe have cleaned first, the Rest ref was incorrect).
But I do not expect to see any issues, if it worked for you.

**Comment by gerhardol** [comment]
Please squash and rebase on release/3.4 so it can be merged - we can do it but you may want to set proper commit messages

**Comment by gerhardol** [comment]
@haldyr 
Git.hub is merged, can you please squash and rebase so this can be merged?

**Comment by pmiossec** [comment]
>The submodule must point to 3ebf19b8fc2ab8a24f54aab64921c88577fff05d

&

>Please squash and rebase on release/3.4 so it can be merged

Done. Waiting to be merged in 3.4 😉

**Comment by gerhardol** [comment]
Thanks

**Comment by haldyr** [comment]
Thanks!

**Pull request merged**
