### PR TITLE
Update required software

### PR DESCRIPTION
**Pull request by pmiossec**
To celebrate release 2.49.RC1  :tada:

I think that we should update to the last version for the release ;)

- Git to 2.10.1
- KDiff to 0.9.98

### CODE REVIEW

**Comment by vbjay** [comment]
That would entail testing all of git functionality and fixing any broken
features. I say after the release. It's not that hard to test. You just
install that version and point gitextensions to the right path.

**Comment by KindDragon** [comment]
> KDiff to 0.9.98

No, I deliberately fell back to 0.9.97. 98 does not work on some computers

**Comment by pmiossec** [comment]
>No, I deliberately fell back to 0.9.97. 98 does not work on some computers

Ok, I didn't know and the changelog seemed not too alarming :(
I removed the kdiff update to keep just git update. Feel free to merge or close...

**Comment by vbjay** [comment]
Frankly I think p4 merge is WAY better.
https://www.perforce.com/product/components/perforce-visual-merge-and-diff-tools.

**Comment by pmiossec** [comment]
>Frankly I think p4 merge is WAY better.

+1000
That's the 3-way merge tool I use too and that I advice to use. Never been able to use kdiff3...
But I don't think that we could redistribute it :(
Even if I think that we will give a big gift to the user if we could install it instead of kdiff3.
Perhaps find a way to download and install it during GitExtensions install.

**Comment by vbjay** [comment]
Wouldn't hurt to ask. They have a Linux and windows version.

**Comment by KindDragon** [comment]
There is two type of merge tools (with 3 way merge support) something like Meld (p4merge, araxis merge) or like kdiff3(Beyond Compare). I prefer tools with the same number of lines in all the panels, so that the text scrolling was everywhere identical.

**Comment by vbjay** [comment]
P4 merge syncs the scrolling but yes the merge result us on the bottom.

**Comment by pmiossec** [comment]
>I prefer tools with the same number of lines in all the panels, so text scrolling was everywhere identical.

Never thought about that! So that's a matter of taste, I'm OK with that ;)

**Comment by ghanique** [comment]
I tried p4 again and I remember why I prefered WinMerge.

With Winmerge lines that haven't changed are aligned side by side. New
lines on one side create a gray box on the other side.
In p4 both sides display the content as it would appear in a text editor,
which also means: not vertically aligned. A small bar in the middle
visualises the transition.
Focus on the VOLUME section in the screenshots below.
(The same goes for kdiff3).

The other thing is that WinMerge has considerably more options than p4. p4
surely is more aesthetically pleasing though.
[image: Screenshot - 20161019-091720.png]
[image: Screenshot - 20161019-090453.png]

**Comment by KindDragon** [comment]
> With Winmerge lines that haven't changed are aligned side by side. New
> lines on one side create a gray box on the other side.
> In p4 both sides display the content as it would appear in a text editor,
> which also means: not vertically aligned. A small bar in the middle
> visualises the transition.

This is what I mean 👍

**Comment by pmiossec** [comment]
The fact that winmerge (which is quite good indeed) doesn't support the 3
way merge exclude it for me because it's, for me, essential to understand
changes done by others when merging. 2 way merge make merge a lot harder.

What *I* dislike in kdiff , that's the order in which the files are
displayed. I highly prefer to have the BASE file in the middle to easy
comparison between BASE and my changes or BASE and their changes.

But I admit that all that is a matter of taste and habits ;-)

**Pull request merged**
