### PR TITLE
Fix #5944 by fixing --follow and revision reading

### LINKED ISSUE #5944: History no longer shown for renamed files
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
History is not shown for files before their rename (but blame correctly identifies commits)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Take a file with history, rename it, perform additional commits after changing it.

**What is the expected behavior?**
History is shown for the file before it got renamed (as it currently works for Blame)

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

(In settings "Follow renames in History" is enabled, "Follow exact renames and copies only" has been tried as both disabled and enabled - the files have 100% similarity".)

**Did this work in previous version of GitExtensions (which)?**

I recall the history being shown correctly for the renamed files in Version 2.5x

### PR DESCRIPTION
**Pull request by gerhardol**
This is a cherry-pick of #6807 for master
Author unchanged from @fschmied (cla signed)

Quickfix for #5944 based on release/3.1, no tests, no big refactoring.

Intended as a placeholder until #6132 is done.

## Proposed changes

See #6807 - restore follow rename files

### Before

image

### After

image

## Test methodology 

Manual

Note:
If test cases must be added to merge this, someone else should drive this PR

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by mstv** [comment]
Very good, the file history does not end on rename anymore.
Though neither diff nor blame are displayed for merge commits (empty or cycling forever, respectively).
Is this a know limitation of this quickfix?

**Comment by mstv** [comment]
With `Show Full History` on and `Simplify Merges` off (BTW inconsistent capitalization), I get blames also for merge commits after I restarted GE.
(I can understand that the diff is empty because it is not clear which one to display, i.e. to which one of the multiple parents.)

**Comment by RussKie** [comment]
How can we test it?

**Comment by gerhardol** [comment]
This is just a stop-gap until #6132 is done by @vbjay to show the history for the most common scenario
One situation that is not handled for instance is to view the file history for a file that no longer exists in the current directory.

> How can we test it?

If FormFileHistory.cs is refactored a little we can add a test that the command contains " --follow ". That will help if we refactor to GitArgumentBuilder2 if the interface is kept the same (so not if we start to use libgit or similar).

A test that test the logic is unchanged is quite complex, will require some more effort than to make the proper functionality. That test would involve parsing a git repo to find the structure. I agree that would be useful but the effort will be quite high.

**Comment by gerhardol** [comment]
@gitextensions/git-extensions-source @vbjay 
This restores the functionality to 2.x. There are still issues, the "follow rename" will never work perfectly in Git anyway.
I am voting to include this in master now.

**Pull request merged**
