### PR TITLE
Sort branches alphabethical/lastAccess (#6310)

### LINKED ISSUE #6310: Sort branches alphabethical/lastAccess was removed
## Current behaviour

In 2.51, it was possible to order branches in Browse by either alphabethical or last access order.
This possibility was removed in 9c7c76fb619480429cbe02e11ce889b00423eac2 (likely #5087)

## Expected behaviour

Change of sorting was useful, even little hard to find.
Sort could be restored or we decide that it should not be possible.

## Steps to reproduce

       public static BranchOrdering BranchOrderingCriteria
        {
            get { return GetEnum("BranchOrderingCriteria", BranchOrdering.ByLastAccessDate); }
            set { SetEnum("BranchOrderingCriteria", value); }
        }

## Screenshots

image

## Did this work in previous version of GitExtensions
2.51

## Environment

- Git Extensions 3.1.0
- Build d753f4a7e0c175529d7c6ecffa7f297ea239faf3
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Fixes #6310

Note: These changes are mostly copied from a previous PR #4124 which has been merged and the changes removed later.

## Proposed changes
- Add a configuration setting to choose the ordering criteria of the branches in the dropdown: by date (default) or alphabetically. It affects the branch list in the top bar menu and the repo objects side panel.

### New settings sub-menu

image

## Test methodology 
Manually tested:
- Check the branches are shown in date order by default in the top bar menu
- Check the branches are shown in date order by default in the repo objects side panel
- Change the setting to alphabetical
- Check the branches are shown in alphabetical order in the top bar menu
- Check the branches are shown in alphabetical order in the repo objects side panel
- Change the setting to last access date
- Check the branches are shown in date order in the top bar menu
- Check the branches are shown in date order in the repo objects side panel

## Test environment(s) 

- GIT 2.24
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Reverting to the original implementation would not be quite correct.
This would be the commit to revert to 9c7c76fb619480429cbe02e11ce889b00423eac2. 

@drewnoakes could you please clarify what was broken about the feature?

**Comment by pouleyKetchoupp** [comment]
@RussKie It seems the feature that was broken was a different one also using some sorting mechanism, and by removing all alphabetical ordering, the simple branch list sorting was removed too, as a side effect.
Could we decide to come back to the simpler, original implementation? What's wrong with it?

**Comment by RussKie** [comment]
> It seems the feature that was broken was a different one also using some sorting mechanism,

No, it wasn't. 
I have re-written the original feature because it didn't meet a wider set of requirements such as sorting tags.

**Comment by pouleyKetchoupp** [comment]
Do you need more feedback from me?

**Comment by RussKie** [comment]
As I said earlier the proposed change is not correct, and it won't be accepted in the current state.

**Comment by pouleyKetchoupp** [comment]
This wasn't handled in a professional way. I wasn't given any constructive feedback to address the problem in order to execute the feature in a "correct way" that was never explained.

**Comment by RussKie** [comment]
I'm sorry you feel this way.
However you decided to fix something without discussing it first. I told you that what you did was not correct, and pointed to the correct commit to revert. You ignored it nor tried to understand why it was so.

**Comment by RussKie** [comment]
Fixed in #8427

**Pull request closed without merging**
