### PR TITLE
Allow highlight branch by ALT+Click in the grid

### PR DESCRIPTION
**Pull request by RussKie**
## Proposed changes

Expose the same behaviour as "Highlight selected branch" in the revision grid via <kbd>ALT</kbd>+<kbd>Left Click</kbd>, similar to the default hotkey <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>.

image

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
Change is fine (much easier to use than (<kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>), but I would like to sync with the discussion in #8452 (maybe #8414 too).

**Comment by RussKie** [comment]
> but I would like to sync with the discussion in #8452
<https://github.com/gitextensions/gitextensions/pull/8452>

Were you thinking of some other issue?

**Comment by gerhardol** [comment]
> but I would like to sync with the discussion in #8452
> > Were you thinking of some other issue?

No - see my edit of the description too

**Comment by RussKie** [comment]
> > but I would like to sync with the discussion in #8452
> > > Were you thinking of some other issue?
> 
> No - see my edit of the description too

Sorry you've lost me.  This is #8452. 
I think https://github.com/gitextensions/gitextensions/issues/8441 is relevant to this proposal though.

**Comment by ivangrek** [comment]
`ALT`+`Left Click` is bette than `CTRL`+`Shift`+`B`.

Because `Left Click` used for selecting, `CTRL`+`B` for creating new branch.
`CTRL`+`Shift`+`B` breaks the general logic.

**Comment by RussKie** [comment]
Aye, I could never remember this shortcut and found it awkward to invoke too.

**Comment by gerhardol** [comment]
> 
> 
> > > but I would like to sync with the discussion in #8452
> > > > Were you thinking of some other issue?
> > 
> > 
> > No - see my edit of the description too
> 
> Sorry you've lost me. This is #8452.
> I think #8441 is relevant to this proposal though.

Correct...

**Comment by GintasS** [comment]
This is an old PR and should be closed. @RussKie

**Comment by RussKie** [comment]
No, this is a draft. It is still on agenda.

**Review by mstv — COMMENTED** [review]
+1

Though `ToggleHighlightSelectedBranch` is misleading and should be renamed to `HighlightSelectedBranch`.

`Alt+Click, ` should be prepended to the ShortCutString of the item in the `View` menu.

**Comment by gerhardol** [comment]
Rebased, applied review comments.
Made Alt-LButton independent of other modifiers, Ctrl-Alt-Click will both add to selection and Highlight branch.

**Review by gerhardol — APPROVED** [review]

**Pull request merged**
