### PR TITLE
[#6147] Sign developer certificate of origin

### LINKED ISSUE #6147: inverted diffs after refresh
## Current behaviour

Under certain circumstances, the diffs shown in the Diff tab can be inverted just by refreshing the GUI.
I.e. when showing the differences from _<some_old_commit>_ to _<some_new_commit>_ and refreshing the GUI, the Diff tab shows the differences from _<some_new_commit>_ to _<some_old_commit>_ instead.

## Expected behaviour

Diffs shall not be shown as inverted, no matter whether the GUI is refreshed or not.

## Steps to reproduce

1. Load any repository in GitExtensions and click on the Diff tab.

2. Select any commit, except the latest one in your revision graph.
bugdiffrefresh1

3. Hold the CTRL key and select another commit, which is **after** the first one (i.e. more top-wards in the revision graph). It doesn't have to be on the same branch and it doesn't have to be a direct child commit. It may also be one of the artificial commits (if enabled).
It is important, however, that the second commit is shown above the first one in the revision graph.
bugdiffrefresh2

4. Press F5 or click on the Refresh icon.
bugdiffrefresh3

## Did this work in previous version of GitExtensions

Yes, GitExtensions 2.51.05 is not inverting the diffs.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by ignacioerrico**
Signing the _developer certificate of origin_ as specified in [`CONTRIBUTING.md`](https://github.com/gitextensions/gitextensions/blob/master/CONTRIBUTING.md), since I'm making my first contribution to the project with code that attempts to fix #6147.

### CODE REVIEW

**Comment by illfated** [comment]
Looks like you need to rebase this PR on current master, to solve the file conflict.
(`contributors.txt` was updated in commit 750ccac 2 days ago)

**Comment by RussKie** [comment]
Please rebase and resolve the MC and we'll have it merged. Thank you

**Comment by ignacioerrico** [comment]
Merge conflict resolved. My fork was behind master.

**Comment by mast-eu** [comment]
I know I'm nitty-picky 🙄 , but you should rebase your branch **on top of** gitextensions/master and force push (i.e. overwrite git history), not merge gitextensions/master **into** your branch.
This will keep the revision history much more readable.

**Comment by illfated** [comment]
👍 Thank you for mentioning that, @mast-eu . I know it can be tricky to understand the difference between `merge` and `rebase` for beginners, because I received a fair share of mentions about that same topic in other repositories.

**Comment by ignacioerrico** [comment]
Nitty-picky? Not at all! I've been using Git for at least six years. I didn't mistake a rebase for a merge, I just made it complicated. Thanks for pointing that out and explaining the correct workflow!

**Pull request merged**
