### PR TITLE
Multi select in resolve conflict window

### PR DESCRIPTION
**Pull request by rasane**
Hi This pull request has the progress bar now.. It allows multi select and enables and disables some commands in menus based on whether single or multiple rows are selected.. thanks..

### CODE REVIEW

**Comment by KindDragon** [comment]
Please rebase on latest master

**Comment by rasane** [comment]
making a clean fork, so closing this for now..

**Comment by vbjay** [comment]
Do you not know how to rebase?

**Comment by rasane** [comment]
Hi vbjay, 

I do know how to rebase. The issue was that after doing the rebase the delta under review appeared bigger than my change should have been. Incidentally, I followed the steps here to update a commit email id: https://help.github.com/articles/changing-author-info/. This worried me that something unintended had changed, so took the option to redo, since it is not a major change.. The updated pull request here: https://github.com/gitextensions/gitextensions/pull/2834. 
Thanks, rasane

**Pull request closed without merging**
