### PR TITLE
Add tests for GitModule.GetSortedRefs()

### PR DESCRIPTION
**Pull request by mstv**
Adds tests for #6451

## Proposed changes

- add tests

## Test methodology 

- NUnit tests

## Test environment(s) 

- Git Extensions 3.1.0
- Build 3a3430ce54636ddb5a6c9d558ca06ba756571c80
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by RussKie** [comment]
Looks good. Could the tests be moved to `GitModuleTests` please?

Looks like we have `MockExecutable` implementation too, that provides a mechanism to mock git output.

**Comment by mstv** [comment]
The tests are right after GitModuleTest now.
Or did you mean to integrate them into GitModuleTest.cs?

**Comment by RussKie** [comment]
Yes, the test folder/file structure should mirror the production code.
If `GetSortedRefs()` is defined in `GitModule.cs` and tests should be located in `GitModuleTests.cs`

**Comment by mstv** [comment]
Done.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
