### PR TITLE
Extract copy to clipboard submenu from revision grid; add copy to clipboard to file history form context menu

### LINKED ISSUE #4877: "Copy to clipboard" context menu items missing in File History
**Do you want to request a *feature* or report a *bug*?**
A feature.

**What is the current behavior?**
The context menu on commits in the File History window is missing the _Copy to clipboard_ submenu which is present in the Browse window.

**What is the expected behavior?**
It would be useful to have the ability to copy the information related to the commit in the File History window, too. This includes commit hash, message, author, date and names of tags and branches (if any correspond to the selected commit).

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.17.0.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
No.

### PR DESCRIPTION
**Pull request by szaliszali**
Fixes #4877

Disclaimer: I don't mean to be rude with @deepak--sharma (the author of #4906) and "race" against his PR, but I was practicing some refactoring yesterday and accidentally selected the same submenu as my target. So I thought that this PR may be useful, because it was very easy to add the same menu to the history form after extracting the component.

Changes proposed in this pull request:
- extracted the Copy to clipboard submenu from RevisionGrid
- separated logic from UI component logic (see `CopyContextMenuViewModel`)
- made the items displayed in the submenu more flexible by replacing hardcoded menu items with dynamically created ones
 
Screenshots before and after (if PR changes UI):
- before 
image
- after 
image

What did I do to test the code and ensure quality:
- manual verification

Has been tested on (remove any that don't apply):
- GIT 2.16.1 and above
- Windows 8.1

### CODE REVIEW

**Comment by pmiossec** [comment]
Once again (because I already said it in the other PR ;-)), I think that the menu should be in the first part of the menu, with the other actions...

**Comment by RussKie** [comment]
I agree, it feels a bit odd at the bottom

**Comment by szaliszali** [comment]
@pmiossec and @RussKie I agree, pushed an update

image

**Comment by pmiossec** [comment]
👍 

Et l'impression d'écran m'a permit de voir qu'une des traductions est foireuse... 😃 et donc corrigée!

**Comment by deepak--sharma** [comment]
@szaliszali ok no worries, I would have done that too but I was looking for a quick starter. Unable to give more time to it. Anyways if u were also working on the same piece u should have commented on the PR before picking it up (I read it in the contribution guidelines). Looks like my delays in closing this PR bought you more time.

Cheers.

**Pull request merged**
