### PR TITLE
Fix patch header parse bug

### LINKED ISSUE #4827: Invalid patch header: diff --combined GitUI/CommandsDialogs/FormBrowse.cs
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

```
   at GitCommands.Patches.PatchProcessor.CreatePatchFromString(String[] lines, Encoding filesContentEncoding, Int32& lineIndex) in C:\d\projekty\gitextensions\GitCommands\Patches\PatchProcessor.cs:line 103
   at GitCommands.Patches.PatchProcessor.<CreatePatchesFromString>d__1.MoveNext() in C:\d\projekty\gitextensions\GitCommands\Patches\PatchProcessor.cs:line 52
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitCommands.GitModule.GetCombinedDiffContent(GitRevision revisionOfMergeCommit, String filePath, String extraArgs, Encoding encoding) in C:\d\projekty\gitextensions\GitCommands\Git\GitModule.cs:line 3876
   at GitUI.CommandsDialogs.RevisionDiff.<ShowSelectedFileDiffAsync>d__35.MoveNext() in C:\d\projekty\gitextensions\GitUI\CommandsDialogs\RevisionDiff.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.FindAndReplaceForm.<FindNextAsync>d__27.MoveNext() in C:\d\projekty\gitextensions\GitUI\Editor\FindAndReplaceForm.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitUI.FindAndReplaceForm.<btnFindNext_Click>d__26.MoveNext() in C:\d\projekty\gitextensions\GitUI\Editor\FindAndReplaceForm.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Fetch jbialobr fork.
2. Select ffdfbaccc8710c2a2d4aebdc65313791ac02a08a in revision grid
3. Go to the Diff tab
4. Select FormBrowse file in the CombinedDiff

- GitExtensions version: 08a69150e35861e9cfc363629b57176afc444352

**Did this work in previous version of GitExtensions (which)?**
Yes: 2.50.02

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #4827 

Changes proposed in this pull request:
- Correctly identify a combined diff
- Add some more contract annotations
- Improve parsing logic for clarity, reliability and perf
 
What did I do to test the code and ensure quality:
- Manual testing

Has been tested on:
- GIT 2.16.2
- Windows 10

### CODE REVIEW

**Comment by jbialobr** [comment]
For untracked files the header is: Invalid patch header: diff --git b/Setup/MyLogFile.txt a/Setup/MyLogFile.txt

**Comment by drewnoakes** [comment]
For headers like `diff --git b/Benchmarks/App.config a/Benchmarks/App.config` (i.e. `b` comes first, then `a`) do you know if we have to swap `fileNameA` and `fileNameB` in code to match the prefixes, or the order they appear in?

**Comment by jbialobr** [comment]
No, we don't need to swap them. I don't know why they come inverted. I think it is save to match both a and b files against the same regex like: `abiwco12`

**Comment by jbialobr** [comment]
Consider adding both headers to test cases
`diff --combined GitUI/CommandsDialogs/FormBrowse.cs`
`diff --git b/Benchmarks/App.config a/Benchmarks/App.config`

**Comment by gerhardol** [comment]
> For headers like diff --git b/Benchmarks/App.config a/Benchmarks/App.config (i.e. b comes first, then a) do you know if we have to swap fileNameA and fileNameB in code to match the prefixes, or the order they appear in?

Yes, that is needed to compare to staged and working directory, "the other way", i.e. working dir first, then HEAD

**Comment by drewnoakes** [comment]
> Yes, that is needed to compare to staged and working directory, "the other way", i.e. working dir first, then HEAD

I found bug #4849 while testing this PR. @gerhardol you seem to understand what good behaviour looks like in this area. Does this look right to you? Is it related to what you wrote above?

**Comment by gerhardol** [comment]
> I found bug #4849 while testing this PR. @gerhardol you seem to understand what good behaviour looks like in this area. Does this look right to you? Is it related to what you wrote above?

Commenting separately on #4849 , I believe that is separate and this PR can be merged.

_git-diff -R COMMIT_ is required for comparing WorkingDir -> COMMIT
(It would probably have been better to contribute _git-diff WORKING_DIR..COMMIT_ in Git itself.... My contribution has been to clean up this handling.)
The options are manipulated in gitcommands\git\revisiondiffprovider.cs

**Comment by drewnoakes** [comment]
> Consider adding both headers to test cases

I've fixuped tests for both cases.

> Is this something we can test?

I believe the tests are adequately expanded to cover the two cases seen here.

**Pull request merged**
