### PR TITLE
Copy SHA via Ctrl+C broken

### LINKED ISSUE #5735: Copy SHA via Ctrl+C broken in 3.0 RC1
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Ctrl+C copies junk, or (worse) the SHA of a **wrong commit**!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Start GE fresh.
2. Select a commit.
3. Press Ctrl+C
4. The clipboard is filled with something like:

```text
  | Hide submodule toolbar button when not needed |   | Drew Noakes | 2 days ago |   | -- | -- | -- | -- | -- | -- | --
```

5. Right click the commit and open the "Copy" submenu (don't click any menu items)
6. Click away then select a different commit
7. Ctrl+C 
8. Clipboard will contain the SHA-1 of the **wrong commit**

Specifically, Ctrl+C copies the SHA-1 of the commit for which the context menu's copy submenu was last opened.

**What is the expected behavior?**

Ctrl+C always copies the SHA-1 of the selected commit.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**

Yes.

### PR DESCRIPTION
**Pull request by spdr870**
Fixes #5735

Changes proposed in this pull request:
- Remove the hotkey ctrl-c from the context menu. It breaks more then it fixes.
 
What did I do to test the code and ensure quality:
- Manual testing

Has been tested on (remove any that don't apply):
- GIT 2.19
- Windows 10

### CODE REVIEW

**Comment by drewnoakes** [comment]
Does this stop the Ctrl+C behaviour from working altogether?

**Comment by spdr870** [comment]
No, only the ctrl-c in the context menu

**Comment by RussKie** [comment]
@spdr870 - tests are failing.
@drewnoakes could you please test the change

**Comment by RussKie** [comment]
Thank you. The fix will go into the next release. 
I guess after the root cause is established and fixed we can reinstate the shortcut.

**Comment by drewnoakes** [comment]
Copying SHA-1 via Ctrl+C is reinstated via: #5745

**Pull request merged**
