### PR TITLE
Replaced contains with IndexOf fixing the issue #4014

### LINKED ISSUE #4014: Filter branch combobox is case sensitive
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The searching at the moment is case sensitive and hence fails to search properly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Create a branch named feature/TESTBRANCH

2) switch to a different branch and try searching for testbranch. The dropdown remains empty

**What is the expected behavior?**

The dropdown should display feature/TESTBRANCH

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version:  NA
- OS version: NA

**Did this work in previous version of GitExtensions (which)?**
NA

### PR DESCRIPTION
**Pull request by joshia89**
Fixes #4014.

### CODE REVIEW

**Comment by vbjay** [comment]
If you don't space the # and the issue number, it will actually link. Like
so.

#4014

**Comment by RussKie** [comment]
Do you hope to have fixed it or you have actually fixed it?

**Comment by joshia89** [comment]
@RussKie, poor choice of words in the commit. It has been fixed

**Comment by RussKie** [comment]
It is still not quite right - `FilterBranchHelper` is not filtering it correctly.

image



@jbialobr `FilterBranchHelper`'s UI seems redundant now.
With #4016 the dropdown opens whenever the user click on it. Its filter kicks in when the user starts typing.

**Comment by jbialobr** [comment]
I don't know what is going on there. I think only the first list (this larger) should be shown.

**Comment by RussKie** [comment]
Actually I was wrong, this line seems to cause the second little window:

```
this.toolStripBranchFilterComboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
```

If you remove it, the second window disappears

**Comment by joshia89** [comment]
@RussKie Didn't feel right to make a UI fix here so I have done it as part of the issue #4016 in the pull request #4021

**Pull request merged**
