### PR TITLE
Add myself as contributor

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #

## Proposed changes

- 
- 
- 

## Test methodology 

- 
- 
- 

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by vbjay** [comment]
@RussKie   does the release build tooling not do this?

**Comment by RussKie** [comment]
Thank you!

> does the release build tooling not do this?

No. One of the reasons why we want to join .NET Foundation.

**Comment by vbjay** [comment]
So something like
https://github.com/gitextensions/gitextensions/blob/dca061a6c65c89343697f94b60b086edc7e44dcc/Setup/Prepare-Release.ps1#L81
is not being done anymore?

**Comment by gerhardol** [comment]
> So something like ... is not being done anymore?

The signoff is done to ack the license, related to #4737

**Pull request merged**
