### PR TITLE
Feature #2897: No Checkout on Clone

### PR DESCRIPTION
**Pull request by hypersw**
Implemented #2897 by modifying the branch selection combo: added two synthetic items, "(default: remote HEAD)" and "(none: don't checkout after clone)".

The latter causes --no-checkout option to be passed.
And the former just tells explicitly what happens by default if you do not specify any branch.

Clone dialog, no branch selection made:

untitled20150817231546

Branch combo dropped down, branches have been loaded async:

untitled20150817231559

### CODE REVIEW

**Comment by hypersw** [comment]
NOTE: goes on top of the feature/2289-sparse-checkout branch because they hit the same lines; after that's merged, there will be just two commits.

**Comment by hypersw** [comment]
Fixed TC tests.

**Comment by KindDragon** [comment]
Please fix conflicts and I'm ready to merge :+1:

**Comment by hypersw** [comment]
I'll update the remaining PRs later tonight to the fresh master.

**Comment by hypersw** [comment]
@KindDragon: Is it OK that Travis has failed? Looks like a technical issue.

**Comment by KindDragon** [comment]
Yeah, travis/mono is very unstable

**Pull request merged**
