### PR TITLE
Mark all files that we inject version number into as clean

### PR DESCRIPTION
**Pull request by RussKie**
Mark all files that we inject version number into as clean

### CODE REVIEW

**Comment by RussKie** [comment]
@vbjay what do you think?
Is there a better way?

**Comment by gerhardol** [comment]
I would prefer to commit (and push) the changes instead

**Comment by RussKie** [comment]
The build number is a dynamic value, we cant determin it before hand.
Pushing it from the build server doesnt seem correct either, and it would
trigger a cascade of never ending builds...

**Comment by vbjay** [comment]
That's fine but if a submodule needs more changes you will have to go into the submodule twice. One to do the assemblyInfo and then cd into the path again to add another file. Why I had the cd then skipworktree then cd.. 

Yes could have used pushd/popd.

**Pull request merged**
