### PR TITLE
Surround access to plugin collection with a `lock()`

### LINKED ISSUE #6924: [NBug] Collection was modified; enumeration operation may not exec...
## Current behaviour

Not sure what has happened. I've opened Git Exensions and selected a recent repository on a dashboard window, then Git Extensions crashed. 

## Expected behaviour

I guess it should not crash.

## Steps to reproduce

I wasn't able to reproduce it unfortunately. Hope the exception details will help.

## Error Details
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by pmiossec**
as we already did it in `PluginRegistry.Initialize()` to populate the collection

Should fix #6924, #7813, ...

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 3.3.0
- Build 398d29d61eb3260555fd0c187dccef1b881b3c13 (Dirty)
- Git 2.25.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 192dpi (200% scaling)

### CODE REVIEW

**Comment by gerhardol** [comment]
> LGTM. But there are further references to Plugins in FormBrowse and FormSettings.

The stacktrace in #6924 points to FormBrowse, so I assume that a change there is required

**Comment by gerhardol** [comment]
@pmiossec 
Is the lock required in FormBrowse and FormSettings?

**Comment by pmiossec** [comment]
I would say no because we load the plugins once and after that the
collection should not change.

But I could add it because I must admit that I don't really understand why
it is crashing at the moment.

So it is not bad to be too precocious...

**Comment by pmiossec** [comment]
@gerhardol done.

**Comment by RussKie** [comment]
:shipit:

**Comment by pmiossec** [comment]
@msftbot merge in 1 day

**Pull request merged**
