### PR TITLE
Artificial commits: Invalidate rowcache when inserting

### PR DESCRIPTION
**Pull request by gerhardol**
Followup to #9393

## Proposed changes

Inserting artificial commits first if HEAD was not added to the grid was added in #9393.
In some situations the grid would not be refreshed correctly, requiring a manual scroll.
This normally would occur for bigger repos only.
When working with the PR, I could not get a stable repro and could not address it.
This is a follow up to invalidate the row cache properly to refresh the graph in the grid.

### Before

image

### After

The normal commits are being displayed while the git-log output is created, so initially the artificial commits are not shown.
After a few seconds the graph is updated as below (that would require a scroll before).

image

## Test methodology 

manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
I don't have a deep understanding of the functionality. The changes look sensible...

**Review by GintasS — COMMENTED** [review]
Same here, apart from the ! negation, couldn't pick on anything, no knowledge here.

**Review by GintasS — APPROVED** [review]

**Review by mstv — APPROVED** [review]
> I don't have a deep understanding of the functionality. The changes look sensible...

same for me

**Comment by gerhardol** [comment]
> 
> 
> > I don't have a deep understanding of the functionality. The changes look sensible...
> 
> same for me

You know this better than me...

But I tried to add comments with what I know.

Will squash merge

**Pull request merged**
