### PR TITLE
Fix different problems around FileHistory/Blame

### LINKED ISSUE #6458: History not shown for a new file in a different branch
## Current behaviour
When trying to show the history of a file which has been added in a different branch than the current one, nothing is shown.

## Expected behaviour
The history is shown regardless of whether the file actually exists in the working directory.

## Steps to reproduce
1. Create a new branch
2. Create a file `new.txt`
3. Change the contents of the file in a few commits
4. Switch to a different branch
5. Open the history form for `new.txt`

## Did this work in previous version of GitExtensions
Yes, before commit 08737aa147bcc6e5917f370910ca64a4a47bb6a7. There, the full path is retrieved through `FormFileHistoryController.TryGetExactPath`. However, it returns `null` if the given file does not actually exist - which obviously fails for new files from a different branch.

## Environment

- Git Extensions 3.1.0
- Build 9ff970ca36007056992f90db1dcc0f46edcc5fd4 (the last one where it works)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by pmiossec**
Fixes #6458, #6892 and #6815

Alternative for #6893 (like discussed in https://github.com/gitextensions/gitextensions/pull/6893#issuecomment-509390885 )

## Proposed changes

- Fix FileHistory/Blame for files not existing in the working directory

The bad behavior comes from the fact that `TryGetExactPath()`
changes the path to the file system path (if not existing, the path is cleared)
- Improve readability of unit tests on `TryGetExactPath()`

/cc @gerhardol  @RussKie

### CODE REVIEW

**Comment by pmiossec** [comment]
Thanks  @gerhardol for the commit "ready made"! 😉 

I have included the commit where I have improved the readability of tests on TryGetExactPath() because I think it can't hurt 😉

**Comment by gerhardol** [comment]
> Alternative for #6893

The refactoring and new tests in #6893 are probably OK, even if I am a little hesitant to approve the changes close to a release (my vote is not the most important, but I still raise my opinion).
That PR should be rebased on master after this is merged, for 3.3.

**Comment by pmiossec** [comment]
This PR is better than #6893 because it fixes 3 issues where #6893 only fixes 2...

**Comment by RussKie** [comment]
Merge at will

**Comment by gerhardol** [comment]
One note regarding the change: It does not fix #6815 when starting from the commandline if the path is not case correct, for instance for Plugins\Github3\GitHubRepo.cs (Should be Plugins\GitHub3\GitHubRepo.cs)
That is a limitation I believe we can live with, you can view the history from the application.

**Comment by pmiossec** [comment]
>One note regarding the change: It does not fix #6815 when starting from the commandline if the path is not case correct

I don't know if it could be interesting to mitigate the issue by looking for the good case path in the filetree.

**Pull request merged**
