### PR TITLE
Prioritize main as master in CommitInfo

### LINKED ISSUE #8811: Support "main" branch
## Feature description

A number of repos (including high profile like [Microsoft .NET org](https://github.com/dotnet/announcements/issues/172)) are renaming "master" branch into "main". We must update the code to include "main" alongside "master".

### PR DESCRIPTION
**Pull request by gerhardol**
Fixes #8811

## Proposed changes

sort main branch first as master

## Test methodology 

Manual

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by pmiossec** [comment]
We could imagine some other names : Trunk, stable, dev,...

So what do you think of reading `init.defaultBranch` setting and adding also to the list (if different of main or master)

**Comment by gerhardol** [comment]
> So what do you think of reading `init.defaultBranch` setting and adding also to the list (if different of main or master)

should probably be done

but I would prefer to prioritize branches in more situations (matching a pattern)

This was mostly submitted to show that are not much to do by default

**Review by RussKie — APPROVED** [review]
Thank you!

I'm genuinely surprised we have only 2 instances in the code (plenty in comments).

**Comment by RussKie** [comment]
> > So what do you think of reading `init.defaultBranch` setting and adding also to the list (if different of main or master)
> 
> should probably be done
> 
> but I would prefer to prioritize branches in more situations (matching a pattern)
> 
> This was mostly submitted to show that are not much to do by default

Thank you @pmiossec for the suggestion. It can be a good FR.

**Pull request merged**
