### PR TITLE
Add missing plugin files to the portable archive

### LINKED ISSUE #4466: MakePortableArchive should contain all Windows files
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
MakeMonoArchive.cmd was used to create a portable for Windows in Appveyor in addition to the Mono packages.
When Mono was removed in #4430 the script was renamed to MakePortableArchive.cmd and Mono specifics was removed. However, some files that only were usable in Windows were not added.
This includes for instance AppVeyor and Jenkins build integrations.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Include all files relevant in a portable archive. (Maybe skip some "difficult" plugins like TFS build with many dlls.)

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
No

### PR DESCRIPTION
**Pull request by gerhardol**
Resolves #4466
Tfs plugin is not included

Changes proposed in this pull request:
 - Include missing pluginsin archive
 
What did I do to test the code and ensure quality:
 - Build the portable archive.

No tests with the portable zip

Has been tested on (remove any that don't apply):
 - Windows 10

### CODE REVIEW

**Comment by RussKie** [comment]
As an idea, how about we read the sln file and enumerate all "Plugin" projects (i.e. those in Plugin folder) and for each project copy its content to the target folder?
This way we can probably minimise maintenance when plugins are added/renamed/removed.

I also think this may be easier to achieve with a Powershell script (I am a bit more proficient with PS than good ol' batch scripting :))
Happy to lend a hand.

**Comment by vbjay** [comment]
Amen.  Seen too many issues of plug-in x not included.

**Comment by gerhardol** [comment]
I suggest to add all in GitExtensions/bin and remove unwanted instead.
Using Product.wxs and a script is an alternative. Maybe the installer can generate that too?
(Setup.wixproj has some references to 2015 only, may need an update. Maybe update WIX too.)

**Comment by gerhardol** [comment]
> I also think this may be easier to achieve with a Powershell script (I am a bit more proficient with PS than good ol' batch scripting :))

If I do it, I would use bash/perl. DOS is not an option.... (and PS I have never used.)

I suggest this is merged as a temporary solution, keep 4466 open.

**Pull request merged**
