### PR TITLE
Optionally show EOL markers as glyph instead of textually

### PR DESCRIPTION
**Pull request by mstv**
## Proposed changes

- Add option to toggle end-of-line markers between glyph and text
- Focus `Type to find` field on open of FormSettings

### Before / After

image image

### Before

image

### After

image

## Test methodology 

- manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 26a3cdb1d3e0f7ffc04158423e36b3357f85a279
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer **squash merge** this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
+1
But I want the checkbox on a separate line

**Comment by RussKie** [comment]
>
> +1
> But I want the checkbox on a separate line
>

👍

**Comment by mstv** [comment]
> But I want the checkbox on a separate line

I can do that. But this setting only applies to views using the "Code font".

**Comment by mstv** [comment]
> > But I want the checkbox on a separate line
> 
> I can do that. But this setting only applies to views using the "Code font".

Do you still want an unrelated CheckBox on a separate line?

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
> Do you still want an unrelated CheckBox on a separate line?

Yes, maybe some separating line or group box.
But +1 from me still applies, if you do not bother, please merge.

**Pull request merged**
