### PR TITLE
Update .NET references

### LINKED ISSUE #10177: Cannot build after .NET update
### Environment

- .NET version: 6.0.8

### Issue description

The .NET SDK 6.0.400 seems to not match the requested version in `global.json`:
```
{
    "sdk": {
       "version": "6.0.201",
       "rollForward": "feature"
    }
}
```

### Steps to reproduce

- install .NET 6.0.8 (6.0.7 enforced by GE)
- build GE

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by mstv**
Fixes #10177

## Proposed changes

- Use any installed .NET SDK 6.0 for building GE
- Set RuntimeFrameworkVersion for DotnetRuntimeBootstrapper to the same version 6.0.8 as on the release branch

## Screenshots 

N/A

## Test methodology 

- build GE

## Test environment(s) 

- Git Extensions 33.33.33
- Build 8ccac05c4667d48169db44a0ab5ec3b2ee67faa4
- Git 2.35.2.windows.1 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.8
- DPI 96dpi (no scaling)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
AppVeyor build fails due to this change.
set version to .400?

**Comment by RussKie** [comment]
I just tried building the current master (56b9828d01a9b99c43b4c8ff106cbdd319183b6e) and observed no issues:

```
PS D:\Development\gitextensions> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  D:\Development\gitextensions\global.json

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

PS D:\Development\gitextensions> git clean -xdf

PS D:\Development\gitextensions> dotnet build
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  Restored D:\Development\gitextensions\Plugins\GitUIPluginInterfaces\GitUIPluginInterfaces.csproj (in 996 ms).
  Restored D:\Development\gitextensions\Plugins\BuildServerIntegration\AppVeyorIntegration\AppVeyorIntegration.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\Plugins\Bitbucket\GitExtensions.Plugins.Bitbucket.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\UnitTests\Plugins\BuildServerIntegration\AppVeyorIntegration.Tests\AppVeyorIntegration.Tests.csproj (in 1.14 sec).
  Restored D:\Development\gitextensions\BugReporter\BugReporter.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\UnitTests\Plugins\BuildServerIntegration\AzureDevOpsIntegration.Tests\AzureDevOpsIntegration.Tests.csproj (in 1.14 sec).
  Restored D:\Development\gitextensions\Plugins\ReleaseNotesGenerator\GitExtensions.Plugins.ReleaseNotesGenerator.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\Plugins\BuildServerIntegration\AzureDevOpsIntegration\AzureDevOpsIntegration.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\UnitTests\GitUI.Tests\GitUI.Tests.csproj (in 1.04 sec).
  Restored D:\Development\gitextensions\Plugins\Statistics\GitImpact\GitExtensions.Plugins.GitImpact.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\Plugins\Statistics\GitStatistics\GitExtensions.Plugins.GitStatistics.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\Plugins\BackgroundFetch\GitExtensions.Plugins.BackgroundFetch.csproj (in 1.1 sec).
  Restored D:\Development\gitextensions\Plugins\GitHub3\GitExtensions.Plugins.GitHub3.csproj (in 34 ms).
  Restored D:\Development\gitextensions\Plugins\FindLargeFiles\GitExtensions.Plugins.FindLargeFiles.csproj (in 63 ms).
  Restored D:\Development\gitextensions\Plugins\CreateLocalBranches\GitExtensions.Plugins.CreateLocalBranches.csproj (in 61 ms).
  Restored D:\Development\gitextensions\Plugins\AutoCompileSubmodules\GitExtensions.Plugins.AutoCompileSubmodules.csproj (in 82 ms).
  Restored D:\Development\gitextensions\Plugins\DeleteUnusedBranches\GitExtensions.Plugins.DeleteUnusedBranches.csproj (in 43 ms).
  Restored D:\Development\gitextensions\Plugins\GitFlow\GitExtensions.Plugins.GitFlow.csproj (in 37 ms).
  Restored D:\Development\gitextensions\TranslationApp\TranslationApp.csproj (in 55 ms).
  Restored D:\Development\gitextensions\ResourceManager\ResourceManager.csproj (in 44 ms).
  Restored D:\Development\gitextensions\UnitTests\BugReporter.Tests\BugReporter.Tests.csproj (in 141 ms).
  Restored D:\Development\gitextensions\Plugins\ProxySwitcher\GitExtensions.Plugins.ProxySwitcher.csproj (in 39 ms).
  Restored D:\Development\gitextensions\IntegrationTests\BugReporter.IntegrationTests\BugReporter.IntegrationTests.csproj (in 140 ms).
  Restored D:\Development\gitextensions\Plugins\Gource\GitExtensions.Plugins.Gource.csproj (in 45 ms).
  Restored D:\Development\gitextensions\UnitTests\Plugins\GitUIPluginInterfaces.Tests\GitUIPluginInterfaces.Tests.csproj (in 102 ms).
  Restored D:\Development\gitextensions\GitCommands\GitCommands.csproj (in 30 ms).
  Restored D:\Development\gitextensions\UnitTests\Plugins\ReleaseNotesGenerator.Tests\ReleaseNotesGenerator.Tests.csproj (in 177 ms).
  Restored D:\Development\gitextensions\GitExtUtils\GitExtUtils.csproj (in 18 ms).
  Restored D:\Development\gitextensions\UnitTests\CommonTestUtils\CommonTestUtils.csproj (in 60 ms).
  Restored D:\Development\gitextensions\Plugins\BuildServerIntegration\JenkinsIntegration\JenkinsIntegration.csproj (in 31 ms).
  Restored D:\Development\gitextensions\Plugins\BuildServerIntegration\TeamCityIntegration\TeamCityIntegration.csproj (in 40 ms).
  Restored D:\Development\gitextensions\IntegrationTests\UI.IntegrationTests\UI.IntegrationTests.csproj (in 176 ms).
  Restored D:\Development\gitextensions\Plugins\JiraCommitHintPlugin\GitExtensions.Plugins.JiraCommitHintPlugin.csproj (in 138 ms).
  Restored D:\Development\gitextensions\UnitTests\ResourceManager.Tests\ResourceManager.Tests.csproj (in 128 ms).
  Restored D:\Development\gitextensions\UnitTests\GitExtUtils.Tests\GitExtUtils.Tests.csproj (in 130 ms).
  Restored D:\Development\gitextensions\GitUI\GitUI.csproj (in 50 ms).
  Restored D:\Development\gitextensions\UnitTests\GitCommands.Tests\GitCommands.Tests.csproj (in 138 ms).
  Restored D:\Development\gitextensions\UnitTests\Plugins\DeleteUnusedBranches.Tests\DeleteUnusedBranches.Tests.csproj (in 179 ms).
  Restored D:\Development\gitextensions\GitExtensions\GitExtensions.csproj (in 62 ms).
  4 of 43 projects are up-to-date for restore.
  SpellChecker -> D:\Development\gitextensions\Externals\NetSpell.SpellChecker\bin\Debug\net6.0-windows\SpellChecker.dll
  Git.hub -> D:\Development\gitextensions\Externals\Git.hub\Git.hub\bin\Debug\netstandard2.0\Git.hub.dll
  ConEmuWinForms -> D:\Development\gitextensions\Externals\conemu-inside\ConEmuWinForms\bin\net6.0-windows\ConEmuWinForms.dll
  GitExtUtils -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtUtils\net6.0-windows\GitExtUtils.dll
  GitUIPluginInterfaces -> D:\Development\gitextensions\artifacts\Debug\bin\GitUIPluginInterfaces\net6.0-windows\GitUIPluginInterfaces.dll
  GitCommands -> D:\Development\gitextensions\artifacts\Debug\bin\GitCommands\net6.0-windows\GitCommands.dll
  ResourceManager -> D:\Development\gitextensions\artifacts\Debug\bin\ResourceManager\net6.0-windows\ResourceManager.dll
  GitExtensions.Plugins.AutoCompileSubmodules -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\AutoCompileSubmodules\GitExtensions.Plugins.
  AutoCompileSubmodules.dll
  AppVeyorIntegration -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\AppVeyorIntegration\AppVeyorIntegration.dll
  GitExtensions.Plugins.BackgroundFetch -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\BackgroundFetch\GitExtensions.Plugins.BackgroundFe
  tch.dll
  GitExtensions.Plugins.ReleaseNotesGenerator -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\ReleaseNotesGenerator\GitExtensions.Plugins.
  ReleaseNotesGenerator.dll
  JenkinsIntegration -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\JenkinsIntegration\JenkinsIntegration.dll
  TeamCityIntegration -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\TeamCityIntegration\TeamCityIntegration.dll
  GitExtensions.Plugins.JiraCommitHintPlugin -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\JiraCommitHintPlugin\GitExtensions.Plugins.Ji
  raCommitHintPlugin.dll
  GitExtensions.Plugins.GitFlow -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\GitFlow\GitExtensions.Plugins.GitFlow.dll
  GitExtensions.Plugins.GitHub3 -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\GitHub3\GitExtensions.Plugins.GitHub3.dll
  GitExtensions.Plugins.Bitbucket -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\Bitbucket\GitExtensions.Plugins.Bitbucket.dll
  GitExtensions.Plugins.CreateLocalBranches -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\CreateLocalBranches\GitExtensions.Plugins.Crea
  teLocalBranches.dll
  GitExtensions.Plugins.GitImpact -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\GitImpact\GitExtensions.Plugins.GitImpact.dll
  GitExtensions.Plugins.ProxySwitcher -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\ProxySwitcher\GitExtensions.Plugins.ProxySwitcher.dl
  l
  AzureDevOpsIntegration -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\AzureDevOpsIntegration\AzureDevOpsIntegration.dll
  BugReporter -> D:\Development\gitextensions\artifacts\Debug\bin\BugReporter\net6.0-windows\BugReporter.dll
  ICSharpCode.TextEditor -> D:\Development\gitextensions\Externals\ICSharpCode.TextEditor\Project\bin\Release\net6.0-windows\ICSharpCode.TextEditor.dll
  GitUI -> D:\Development\gitextensions\artifacts\Debug\bin\GitUI\net6.0-windows\GitUI.dll
  GitExtensions.Plugins.DeleteUnusedBranches -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\DeleteUnusedBranches\GitExtensions.Plugins.De
  leteUnusedBranches.dll
  TranslationApp -> D:\Development\gitextensions\artifacts\Debug\bin\TranslationApp\net6.0-windows\TranslationApp.dll
  GitExtensions.Plugins.FindLargeFiles -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\FindLargeFiles\GitExtensions.Plugins.FindLargeFiles
  .dll
  GitExtensions.Plugins.Gource -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\Gource\GitExtensions.Plugins.Gource.dll
  GitExtensions.Plugins.GitStatistics -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\Plugins\GitStatistics\GitExtensions.Plugins.GitStatistics.dl
  l
  GitExtensions -> D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net6.0-windows\GitExtensions.dll
  CommonTestUtils -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\CommonTestUtils\net6.0-windows\CommonTestUtils.dll
  AppVeyorIntegration.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\AppVeyorIntegration.Tests\net6.0-windows\AppVeyorIntegration.Tests.dll
  BugReporter.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\BugReporter.Tests\net6.0-windows\BugReporter.Tests.dll
  AzureDevOpsIntegration.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\AzureDevOpsIntegration.Tests\net6.0-windows\AzureDevOpsIntegration.Tests.dll
  ReleaseNotesGenerator.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\ReleaseNotesGenerator.Tests\net6.0-windows\ReleaseNotesGenerator.Tests.dll
  ResourceManager.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\ResourceManager.Tests\net6.0-windows\ResourceManager.Tests.dll
  DeleteUnusedBranches.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\DeleteUnusedBranches.Tests\net6.0-windows\DeleteUnusedBranches.Tests.dll
  GitUIPluginInterfaces.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\GitUIPluginInterfaces.Tests\net6.0-windows\GitUIPluginInterfaces.Tests.dll
  GitCommands.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\GitCommands.Tests\net6.0-windows\GitCommands.Tests.dll
  BugReporter.IntegrationTests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\IntegrationTests\BugReporter.IntegrationTests\net6.0-windows\BugReporter.IntegrationTests.
  dll
  GitExtUtils.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\GitExtUtils.Tests\net6.0-windows\GitExtUtils.Tests.dll
  UI.IntegrationTests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\IntegrationTests\UI.IntegrationTests\net6.0-windows\UI.IntegrationTests.dll
  GitUI.Tests -> D:\Development\gitextensions\artifacts\Debug\bin\tests\UnitTests\GitUI.Tests\net6.0-windows\GitUI.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:48.92

```


Could there be something wrong with your configuration or environment, @mstv?

**Comment by gerhardol** [comment]
I can build too.
But it seems like AppVeyor uses the exact version in the manifest to download.
The version check is probaböy later.
So this PR makes sense to bump the AppVeyor environment.

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
> Generally, I have no problem bumping the version since 6.0.8 is a MSRC release. Mind you, there will be 6.0.9 released shortly :)

If 6.0.9 has changes ge benefits from, we should use that version. 

Should sdk version be set in appveyor.yml specifically instead?

**Comment by RussKie** [comment]
I don't remember but if 6.0.9 is an MSRC release we should bump it up, as
it would help our users to stay current.

**Comment by RussKie** [comment]
Btw, we should bump this too
https://github.com/gitextensions/gitextensions/blob/21c293d80011d08e04f3df9a1fc558ba3589fbec/scripts/RepoLayout.props#L10

**Review by gerhardol — APPROVED** [review]

**Comment by vbjay** [comment]
Is there a cli to get sdk to runtime match?

image

Like here 6.0.400 is tied to 6.0.8.  So can we run dotnet ... and pass in 6.0.8 and get the latest or all sdk versions tied to that version?  If so, we could run a powershell script to get the 6.0.8 or whatever version and it puts in the right values where needed.

**Comment by RussKie** [comment]
I'm not aware of any mechanisms to achieve this.

**Comment by gerhardol** [comment]
The SDK may introduce incompatibilities and should be fixed for the release builds on AppVeyor. There are several brances too, 6.0.108, , 6.0.303, 6.0.400 for .NET 6.0.8, not much description of what has been changed.
The original request should have set version to 6.0.3, the dependency was not clear to me. This version is to my knowledge just used by the bootstrapper.
So while the .NET Runtime version can be determined from the .NET SDK version (the reason why #10075 occurred in the first place?), they have to be updated by pair anyway.
The comment in [RepoLayout.props](https://github.com/gitextensions/gitextensions/pull/10180/files#diff-4f67e7a17c26512aefc632599798e2dc494405bd4fe667a379e17969218b1088) should refer to global.json.

**Comment by vbjay** [comment]
```powershell
param ( [string]$version = "6.0")

$pth = Split-Path $MyInvocation.MyCommand.Path -Parent


$uri = "https://raw.githubusercontent.com/dotnet/core/main/release-notes/$version/releases.json"

$R = Invoke-WebRequest -Uri $uri -ContentType "application/json"   -Method Get -UseBasicParsing
$x = $R.Content | Out-String | ConvertFrom-Json 

#update global.json file
$globalJson = [System.IO.Path]::Combine( $pth, "..\global.json")
$globalJson = Resolve-Path $globalJson
$json = Get-Content $globalJson | ConvertFrom-Json
$json.sdk.version = $x.'latest-sdk'
$json | ConvertTo-Json -in > $globalJson

#update RepoLayout.props
$propsPth = [System.IO.Path]::Combine( $pth, "RepoLayout.props")
[xml]$props = Get-Content -Path $propsPth
$nd = $props.SelectSingleNode("/Project/PropertyGroup/RuntimeFrameworkVersion")
$nd.'#text' = $x.'latest-runtime'
$nd.OwnerDocument.Save($propsPth)

```

so if saved in scripts\Update-DotnetVersion you could run 

```.\Scripts\Update-DotnetVersion```

OR
```.\Scripts\Update-DotnetVersion 7.0```

**Comment by mstv** [comment]
@vbjay, could you create a separate PR with your script, please?

**Comment by vbjay** [comment]
Sure.

**Comment by gerhardol** [comment]
(test failed due to test issue suppressed in #10190, rebuilding)
Merge, push to release/4.0 too, set milestone to 4.0

**Comment by vbjay** [comment]
See #10191 for the script change.

**Comment by vbjay** [comment]
@gerhardol  https://github.com/dotnet/core/blob/main/release-notes/RunApiDiff.md

**Comment by gerhardol** [comment]
Time to update to sdk 6.0.401 / 6.0.9

**Comment by vbjay** [comment]
> Time to update to sdk 6.0.401 / 6.0.9

@gerhardol So run script.  #10191 and commit the needed changes after script run.

**Comment by vbjay** [comment]
image

**Comment by vbjay** [comment]
Also to test 7.0, can do this.

image

**Comment by gerhardol** [comment]
@vbjay please open a PR, I need to sleep and have no time to take this for a spin

**Comment by vbjay** [comment]
Sure.  I can do that.  

By the way 

```bash
git diff -U0 -w --no-color --ignore-blank-lines | git apply --cached --ignore-whitespace --unidiff-zero --
```
After running script to stage the meat of the changes.

**Comment by vbjay** [comment]
@gerhardol  https://github.com/gitextensions/gitextensions/pull/10229

**Pull request merged**
