### PR TITLE
fix5972 size dialog "clone"

### LINKED ISSUE #5972: Size dialog "Clone"
Inaccuracy in calculating the size of the "Сlone" dialog box or the location of its elements.
Occurs when using the "Russian" translation.
The screenshots, erroneous (marked in red) and normal view.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

The screenshots:
- Error (marked red)
   dialogclone_ru_er
- Normal view
   dialogclone_en_ok

### PR DESCRIPTION
**Pull request by hankyulhyun**
Fixes #5972

## Proposed changes
in v3.0, add "Use LFS extension" option and it is too long to write one line in russian
so stretch clone form slightly to make options in one line
 

### Before
image

### After
image

## Test methodology 
Manual

## Test environment(s) 
- Windows 10, No scaling

### CODE REVIEW

**Comment by RussKie** [comment]
I'm not entirely convinced this is a proper fix, more like a temporary patch. 
For example, if in another language these three labels take even more space we'll have the problem again...

**Comment by hankyulhyun** [comment]
@RussKie
yes. i fully agree to your comment!
but i dont have good idea to make adaptive winform in this problem

could i get good solution for this?
if i get, i wanna apply on my company works!
>> frankly, im not goot at csharp and winform =)

**Comment by illfated** [comment]
Would it be possible to allow the dialog box to expand downwards, in cases of extra long label names?

**Comment by RussKie** [comment]
I won't be able to look at it for at least another two weeks.

It is all about adaptive layouts, you'll need to play with AutoSize=true,
AutoSizeMode and Docking, and use table layouts.

There are some examples in the codebase.

**Comment by RussKie** [comment]
@hankyulhyun thank you for your effort, but #6041 rendered your PR obsolete.
Whilst technically the other PR didn't address the core problem either, by hiding one of the options it rendered it non-event for more recent versions of git.

**Pull request closed without merging**
