### PR TITLE
should not remember the dangerous action preference.

### PR DESCRIPTION
**Pull request by EbenZhang**

### CODE REVIEW

**Comment by KindDragon** [comment]
I think we should remake this group box. This will be very frustrating if some settings not saved.

**Comment by KindDragon** [comment]
Maybe make only checkbox autostash and show another taskdialog (with buttons `reset local changes`, `merge local changes` and `cancel`) if checkout failed or if we detect changes in working copy.

**Comment by EbenZhang** [comment]
The idea to popup for 'reset local changes' and 'merge' sounds great.

**Comment by EbenZhang** [comment]
Hi @KindDragon,

I've changed its behavior as per your suggestion, will you be able to do a review?

**Comment by EbenZhang** [comment]
See new pull request #2927

**Pull request closed without merging**
