### PR TITLE
conemu-inside: No trace output in release build

### PR DESCRIPTION
**Pull request by mstv**
## Proposed changes

`GetInfoRoot.QueryAsync`: No trace output in release build (`Debug.WriteLine` instead of `Trace.`)
in order to suppress output like:

```
[ROOT]: <Root
	State="NotStarted"
	Name="git.exe"
/>

[ROOT]: <Root
	State="Running"
	Name="git.exe"
	PID="19884"
	ExitCode="259"
	UpTime="0"
/>

[ROOT]: <Root
	State="Exited"
	Name="git.exe"
	PID="19884"
	ExitCode="0"
	UpTime="1832"
/>
```

## Test methodology 

- manual

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
PR in conemu first?

**Comment by mstv** [comment]
I had opened a PR and since there was no reaction, I took another look: PRs are always opened in the official conemu repo.

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
> I had opened a PR and since there was no reaction, I took another look: PRs are always opened in the official conemu repo.

That is because maximus repo is upstream. Same for all submodules, even for doc. Target must be changed.

**Comment by gerhardol** [comment]
@mstv Can you make a PR in the subrepo too?
(should be done before the merge)

**Comment by mstv** [comment]
Tried several times. GH always redirects to maximus repo.
If you know how to change this, please do.
(Because of such issues, I avoid sub-repos wherever possible. ;-)

**Comment by gerhardol** [comment]
https://github.com/gitextensions/conemu-inside/pull/35

sub repos is a great way to share code in many application repos

**Comment by mstv** [comment]
I have pushed the `master` branch to this commit.

> sub repos is a great way to share code in many application repos

I know. But one needs to live with the drawbacks of it, and the UX is not sound.

**Pull request merged**
