### PR TITLE
PathUtilTest mono support.

### PR DESCRIPTION
**Pull request by jbialobr**

### CODE REVIEW

**Comment by RussKie** [comment]
I think we need to step back and re-assess `PathUtils` in general. 
Tests are certainly very important but looking at the class some of your efforts may be in vain.

1. `DirectoryExists` is used only once in https://github.com/gitextensions/gitextensions/blob/594c54e8ca9711498eab3022ded27766735e69bb/GitCommands/Git/GitModule.cs#L423
So the method can be removed and its call can be replaced with `Directory.Exists`.
Ideally it would injectable (via `IFileSystem` or alike) but it is a separate discussion. This applies to everything else that follows.

2. `PathExists` is not used outside the class, so it can be made private. Ultimately it can replaced with `File.Exists`. There is also no reason to create new objects.

3. `GetValidPaths(IEnumerable<string>)` is not used outside the class and is only called by `GetEnvironmentValidPaths()`. It can be removed.

4. `GetEnvironmentValidPaths` is not used outside the class, so it can be made private.

5. `IsValidPath` is not used outside the class, so it can be made private.
However, looking at the way it is used it can be completely removed.
Unless I am missing something, `TryFindFullPath` gets the list of paths defined in environment (`GetEnvironmentValidPaths`) and checks whether the given file exists at any of these paths. `GetEnvironmentValidPaths` by calling `GetValidPaths` checks that every environmental path is valid.
This is very inefficient.
Getting the list of environmental paths and calling `File.Exists(Path.Combine(envPath, fileName))` would be simpler and more efficient.

6. `GetFileName` is used 3 times, with the high degree of probability it can be replaced with `Path.GetFileName` which is used 23 times across the codebase.

7. `GetDirectoryName` is used 5 times, with the high degree of probability it can be replaced with `Path.GetDirectoryName` which is used 28 times across the codebase.

8. `Equal` is only used by `PathEqualityComparer.Equals`, so it can be removed and its functionality moved into `PathEqualityComparer`.

9. I can't see any reason why `PathEqualityComparer` is private and resides in `PathUtil` class. I can be made public and instantiated when required, as a result `CreatePathEqualityComparer` can be removed.

I am quite happy to help with this work.

**Comment by jbialobr** [comment]
We can discuss this in another issue. For now I would like to make all tests make green ASAP in order to not make contributors to wonder why the tests are not passing. If you don't see any false assumptions in the introduced tests, I am going to merge this in. 

Could you take care of GravatarTests and GitBranchNameNormaliserTest? The rest I have corrected though not pushed yet.

**Comment by RussKie** [comment]
Apart from the comment I made earlier it all looks good.
I'll make sure gravatar and branch normaliser tests work

**Comment by RussKie** [comment]
I don't particularly like the current organisation of these unit tests -
each test tests many things, instead of many tests testing one thing. But
we can look at it once it is all working.

**Comment by jbialobr** [comment]
Thanks.

**Comment by RussKie** [comment]
this is probably a better way to decorate tests for x-plat -
https://github.com/nunit/docs/wiki/Platform-Attribute

**Comment by jbialobr** [comment]
>I don't particularly like the current organisation of these unit tests -
each test tests many things, instead of many tests testing one thing. But
we can look at it once it is all working.

Agree.

>this is probably a better way to decorate tests for x-plat -

Thanks, it is a better way. We can apply it while splitting the tests.

**Pull request merged**
