### PR TITLE
Add form to configure some useful git settings...

### PR DESCRIPTION
**Pull request by pmiossec**
Screenshots before and after (if PR changes UI):

Add a button:
image

that permit to configure some git settings quite useful that most beginners don't know.

image

What do you think of that?
Other settings to add?

### CODE REVIEW

**Comment by RussKie** [comment]
I think it is better to have on a separate page instead of a form.
Are these settings specific to some git version?

**Comment by gerhardol** [comment]
I would prefer to have this in the installer instead.

**Comment by vbjay** [comment]
Why can't it be in the settings page and the installer?

**Comment by gerhardol** [comment]
> Why can't it be in the settings page and the installer?

Sure it can. But the "master" position should be in a normal page, secondly in the installer and third as a separate popup.
(I do not want to shhot down innovation, but would like to have an intention where to go.)

**Comment by vbjay** [comment]
I don't see the need for a pop up form at all. Just settings like all the
other settings, and installer to allow initial global settings.

**Comment by pmiossec** [comment]
>I think it is better to have on a separate page instead of a form.

That's what I thought first, then changed my mind to the popup (but not 100% convienced).
Then changed again my mind thinking about it again after creating the PR. So, I will do it....

>Are these settings specific to some git version?

Yes, indeed (old ones). But what do you have in mind?
Just displaying it in the label? disabling if the feature is for more recent than installed?

I didn't want to bother test the version since GitExtensions is bundled with a much recent version...

**Comment by pmiossec** [comment]
>I would prefer to have this in the installer instead.

@gerhardol 
I'm not sure with that...
There are more than 50 git settings. I selected some that I find useful in a daily workflow (among the one useful when using GitExtensions) giving them some visibility.

But we could surely add some more that make sense (but I don't see one at the moment).

I don't think we must obliged users to configure git and a lot of settings that he doesn't understand during install. If it would have been important, they would have been added in the git installer.
 
And I don't know well wix installer (and how to run git command from it) ;)

**Comment by pmiossec** [comment]
Transformed in a setting page ;)

image

**Comment by RussKie** [comment]
Could we, perhaps, make it subnode of "Git config"?

+- Git Config
| |
| +- Advanced
|

**Comment by RussKie** [comment]
> Yes, indeed (old ones). But what do you have in mind?
> Just displaying it in the label? disabling if the feature is for more
recent than installed?

No, I wouldn't want to introduce some version-specific configurations as
this becomes a tech debt. Give it some short time and no-one will remember
about these, and we'll have some dead code.


> And I don't know well wix installer (and how to run git command from it)
;)

It looks like a black art... I spent a day looking at how to make it
per-user (as oppose to per-machine) installation and I failed to make a
working prototype.
So I wouldn't want to make the installer any more complicated than
absolutely necessary

**Comment by pmiossec** [comment]
>Could we, perhaps, make it subnode of "Git config"?

Very good idea! done ;)

**Comment by gerhardol** [comment]
OK for me.Since this is tagged "Next version", I assume that there is a little time to find out new settings...

**Comment by pmiossec** [comment]
> I assume that there is a little time to find out new settings...

Yes, I let the list here ;) If someone can't sleep at night 😄 
 
https://git-scm.com/docs/git-config#_variables

**Comment by RussKie** [comment]
> Since this is tagged "Next version"...

This will be merged in once 2.51 is released, so it will go into v3 (or whatever the next version number we decide)

**Pull request merged**
