### PR TITLE
Update links to application dependencies wiki page

### PR DESCRIPTION
**Pull request by RussKie**
I've renamed and updated the wiki page to talk about the application's dependencies - https://github.com/gitextensions/gitextensions/wiki/Application-Dependencies.
The code is updated to reflect the change.

### CODE REVIEW

**Comment by vbjay** [comment]
Change choco commands to use upgrade instead of install.  Upgrade will install if not installed.

**Comment by RussKie** [comment]
I think the wiki can be edited by everyone :wink:

**Comment by vbjay** [comment]
LOL!  Oops.  Done.

**Comment by RussKie** [comment]
I installed 4 weeks ago without any dramas whilst setting up a computer at
a new client. Perhaps it got fixed....

**Comment by pmiossec** [comment]
@RussKie I'm happy to here that!

**Comment by gerhardol** [comment]
Note: Do not delete pages that we refer to from the app without a redirect. GitHub wiki has no information about old pages (like for instance Confluence where renaming is OK).

**Comment by RussKie** [comment]
I think we need to add this text as a header and/or footer to all wiki
pages we reference

**Comment by pmiossec** [comment]
>GitHub wiki has no information about old pages (like for instance Confluence where renaming is OK).

You still could retrieve the page from the history due to the fact that the wiki is a git repository.

>I think we need to add this text as a header and/or footer to all wiki pages we reference

Or, as an alternative, manage these special pages in the Gitextensions repository, so that they only could be updated with PR. The rendering is quite the same. 

FYI, In my other project, we only manage doc inside the repository. That has some advantages and disadvantages.

Advantages :
* changes are made through PR and so could be reviewed
* we could ask for doc update in a PR
* Every one could contribute (without putting the wiki public). But perhaps it could discourage, too... 

Disadvantages:
* you don't have the Table of contents, nor the page list where you could search.
* perhaps users are more used to look at doc in the wiki (personally, I'm more used to look at the README.md on GitHub so I prefer when doc is accessible through the main page)

 But, for pages we want to protect, I think it make sense...

**Comment by gerhardol** [comment]
I prefer to trust users to improve, break and fix here.

**Comment by RussKie** [comment]
Thank you Philippe, it is good to know.

**Pull request merged**
