### PR TITLE
Fix layout form remotes

### PR DESCRIPTION
**Pull request by pmiossec**
* longer textfields and combobox (better support of form resize)
* higher remotes list

### CODE REVIEW

**Comment by jbialobr** [comment]
The right side of the dialog is cut off (resizing doesn't help):
2016-07-15 12_34_46-gitextensions master - git extensions -_ debug _-

The problem was introduced by this PR.

**Comment by pmiossec** [comment]
That's really strange because I don't have that.
I decided to fix the layout because on every computers that I used since quite some years, I have all the times saw broken design.
But it seems it was not broken for everyone and that my fix broke the layout for those (the few,  I think... ) where it was working well :-(

I don't know where it  could come from...
Do you have high dpi?

I will have a look. But you could revert because that's more annoying the broken layout for you than it was for me....

FYI, how it is rendered after my PR
2016-07-15 13_09_33-remote repositories_after

and how it was before my PR (url textbox was always to short, that's what I tried to fix :( )
2016-07-15 13_10_16-remote repositories_before

**Comment by jbialobr** [comment]
That is strange, when I opened this form in designer it looked perfectly fine. The VS designer made some changes. I saved them and pushed into https://github.com/jbialobr/gitextensions/tree/jb/formRemotes. Can you check how it looks on your computer?

**Comment by pmiossec** [comment]
For me, the layout looks broken like before the PR :(

**Comment by pmiossec** [comment]
Looks good in the designer, like you but not when running :(

**Comment by pmiossec** [comment]
FYI, Building with 2013 or 2015 change nothing...
Running on Win7 with CLR 4.0.30319 64bits.

**Comment by pmiossec** [comment]
Really good! :tada: :+1: :fireworks:

**Comment by jbialobr** [comment]
Thx. I will squash and merge it.

**Pull request merged**
