### PR TITLE
Translate ToolTips

### LINKED ISSUE #8755: Translate UserControls.Settings.SettingsCheckBox.ToolTipText
## Current behaviour

The `ToolTipText` of the `UserControls.Settings.SettingsCheckBox` is ignored by the Translation.
Noticed in https://github.com/gitextensions/gitextensions/pull/8700#issuecomment-759842825 but other instances are ignored, too.

## Expected behaviour

Tooltips of AppSettings are translated.

## Steps to reproduce

`ToolTipText` added in `GitUI\CommandsDialogs\SettingsDialog\Pages\DiffViewerSettingsPage.Designer.cs` of #8700 but not in `English.xlf`

## Did this work in previous version of GitExtensions

I think no - `SettingsCheckBox` is quite new.

## Environment

#8700

### PR DESCRIPTION
**Pull request by mstv**
Fixes #8755

## Proposed changes

- Fixup the check in `AddTranslationItemIfNotExist` whether the `ToolTipText` differs from `Text`
- Update `English.xlf`

## Test methodology 

- `build -loc`
- check `English.xlf`

## Test environment(s) 

- Git Extensions 33.33.33
- Build f0a3df68a26e5521ea7e879c01e35706eae58ba6
- Git 2.27.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]

**Comment by pmiossec** [comment]
You will be hated by the translators 😁

**Review by pmiossec — APPROVED** [review]
Thanks (and this is the real fix for #3745)

**Review by RussKie — APPROVED** [review]
:shipit:

**Comment by mstv** [comment]
> You will be hated by the translators

Wait until I add more mnemonics! Which should really be done.
Though we could strip the regarding `&` from the translation `Source` strings.

**Pull request merged**
