### PR TITLE
Fix issue  #5496

### LINKED ISSUE #5496: Test "PathUtilTest.TryGetExactPathName()" fails
- GitExtensions version: Current master (commit ID 96b7ed6ba385a698ce8547a0e62639a93a012910)
- OS version: Windows 10 1803 64 Bit
- .NET version: 4.6.1
- Visual Studio version: VS Community 2017 15.8.5

The test `PathUtilTest.TryGetExactPathName()` fails as only test (all other run green). It fails at the point when the path `..` is tested.

In this case, the path is determined as the parent directory of the current directory and in my environment, the current directory is `C:\WINDOWS\System32`. But this current directory has another casing as the existing `C:\Windows\System32` and the test fails because of that.

I suggest to set `Environment.CurrentDirectory` to a defined value as preparation.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

### PR DESCRIPTION
**Pull request by c3er**
Fixes #5496

Changes proposed in this pull request:
- Set `Environment.CurrentDirectory` to a defined state. To be exact: the Assembly location will be used.

What did I do to test the code and ensure quality:
- Ran all the automatic tests again

Has been tested on (remove any that don't apply):
- Windows 10 1803 64 Bit

### CODE REVIEW

**Comment by gerhardol** [comment]
I would prefer to make a case insensitive compare. See #5406

**Comment by c3er** [comment]
#5406 regards only the drive letter. You suggest that the whole path should be tested case insensitive?

**Comment by RussKie** [comment]
Relying on presence of particular files or folders outside the test's control is not a good idea...
Personally I think the test needs to be re-written completely, to something like:

```
        [TestCase("Folder1\\file1.txt", true, true)]
        [TestCase("FOLDER1\\file1.txt", true, false)]
        [TestCase("Folder2\\file1.txt", false, false)]
        public void TryGetExactPathName_should_check_if_path_matches_case(string relativePath, bool resolved, bool match)
        {
            using (var repo = new GitModuleTestHelper())
            {
                // create a file
                var notUsed = repo.CreateFile(Path.Combine(repo.TemporaryPath, "Folder1"), "file1.txt", "bla");
                var expected = Path.Combine(repo.TemporaryPath, relativePath);

                Assert.AreEqual(resolved, PathUtil.TryGetExactPath(expected, out string exactPath));
                Assert.AreEqual(match, exactPath == expected);
            }
        }
```

**Comment by c3er** [comment]
@RussKie I think your approach is really better as the old one and also as my suggestion. I tried it and it ran green on my environment. How shall we proceed? Shall I push your suggested code to this Pull Request?

All I want is a green test environment to have a little more confidence changing the code.

**Comment by RussKie** [comment]
My snippet isn't exhaustive in terms of use case coverage, and I don't have sufficient time right now to do more.
You can certainly add it to the existing test suite and mark the one you've modified with a `TODO: needs rework/refactor`. Then we can look at it at a later stage.

**Comment by c3er** [comment]
I added the test case `[TestCase("fOLDER1\\file1.txt", true, false)]` and made some changes to your snippet that makes it a bit more readable for my taste.

Shall I squash the four published quite messy commits into one? I just read [in the wiki](https://github.com/gitextensions/gitextensions/wiki#committing) that a PR should consist of only one commit.

Can someone say how to fix this "Codecov" error that just appeared? The commits before the current one seem not to caused any problems.

**Comment by gerhardol** [comment]
> Can someone say how to fix this "Codecov" error that just appeared? The commits before the current one seem not to caused any problems.

Someone with privileges is looking at the problem

**Comment by RussKie** [comment]
Yes, please squash.

**Comment by RussKie** [comment]
Thank you.
In the future I suggest to avoid working directly off the main trunk, as you will find yourself in a world of pain when the remote moves.

**Comment by c3er** [comment]
Thanks for the suggestion. I had already some trouble with my other PRs because of this and will not do anything on the master branch the future.

**Pull request merged**
