### PR TITLE
Disable CLS compliance

### PR DESCRIPTION
**Pull request by drewnoakes**
Following discussion in #4710, here's a PR that disables CLS compliance for all projects.

---

@sharwell pointed out that CLS checking is extra work for the compiler and slows the build. I wondered by how much, so ran some tests.

```base
$ time msbuild GitExtensions.sln /target:rebuild
```

### Before this PR

51.216s
51.640s
52.049s

### After this PR

47.102s
47.043s
47.101s

### CODE REVIEW

**Comment by RussKie** [comment]
I would move this attribute into CommonAssemblyInfo.cs, so it is applied universally to all from one place

**Comment by drewnoakes** [comment]
> I would move this attribute into CommonAssemblyInfo.cs, so it is applied universally to all from one place

Great idea. Done.

I also removed `[CLSCompliant(false)]` attributes from two types as they're no longer needed.

**Comment by drewnoakes** [comment]
Many of the `AssemblyInfo.cs` files just contained `[ComVisible(false)]`, so I moved that to `CommonAssemblyInfo.cs` in the last commit, removing a further 150 LOC.

**Comment by sharwell** [comment]
@drewnoakes Some of the projects don't use the common assembly info file (e.g. the spell checker project). Aside from the externals projects (which are in other repositories), can you verify that the projects not using the common assembly info still explicitly list this attribute?

**Comment by drewnoakes** [comment]
> Some of the projects don't use the common assembly info file

I only removed attributes after verifying the project referenced the common file.

**Pull request merged**
