### PR TITLE
fix: LeftPanel - inconsistent remotes management

### LINKED ISSUE #4832: LeftPanel - inconsistent remotes management
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Starting "Remotes management" dialog from the left panel does not refresh the revision graph when the dialog closed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Right click on a remote in the left panel and select "Manage remotes"
* Rename an active remote
* Close the dialog

**What is the expected behavior?**
The revision graph supposed to refresh to display the update remote name

**Environment you encounter the issue:**

- GitExtensions version: 08a69150e35861e9cfc363629b57176afc444352

/cc: @EbenZhang

### PR DESCRIPTION
**Pull request by RussKie**
* Pass the selected remote to the Remotes Management dialog for preselection
* Use the established mechanics to refresh the UI after the Remotes Management dialog is closed

Fixes #4832

### CODE REVIEW

**Comment by jbialobr** [comment]
What about OnRemoteXXX events?  They are no longer needed.

**Comment by RussKie** [comment]
I think they are.
I don't think the left panel is refreshed automatically

**Comment by jbialobr** [comment]
>I think they are.
I don't think the left panel is refreshed automatically

It is refreshed on each repo refresh. `StartRemotesDialog` will trigger one after the form is closed.

**Comment by RussKie** [comment]
ok,  I'll disable the events and try again

**Comment by RussKie** [comment]
@jbialobr you're right 👍 
I've removed all related events and handling and it works as expected.

**Pull request merged**
