### PR TITLE
Cleanup GitModule

### PR DESCRIPTION
**Pull request by RussKie**
House keeping, trying to add some order to `GitModule`

### CODE REVIEW

**Comment by sharwell** [comment]
Looks good through 2023be1ac3c4ccabb51f6f240801ddedb0c05db9

**Comment by vbjay** [comment]
For the large pieces that have to stick with git module, we could use partial to split into sections.
```c#
partial class Git module
{
// Diffs
} 

partial class Git module
{
// Refs
} 
```
Each one in a file nested under git module.cs

All code can be accessed but it would be easier to focus on the specific area.

**Comment by RussKie** [comment]
> Thanks for making this reviewable...

I'm learning too  😄 

> Sidenote: For reviewing PRs like this, #5729 (#3600) would be useful...

I'm still not entirely sold on that UX (my _personal_ preference). It very much like the GH's UX and it is shocking...

**Comment by RussKie** [comment]
Merging as is, will have more clean up in follow up submissions

**Pull request merged**
