### PR TITLE
Avoid a 200ms delay when RunBackgroundAsync is cancelled

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by sharwell** [comment]
> (I can't resist - nit: old using syntax.)

It's not possible to implement this using the new syntax without producing a larger diff than necessary to implement this feature.

**Comment by RussKie** [comment]
Could you please explain what will it to now?
Right now under a debugger I get a constant flood of OCE, will this change make it better/worse/no change?

**Comment by sharwell** [comment]
> Right now under a debugger I get a constant flood of OCE, will this change make it better/worse/no change?

It shouldn't have any impact on that scenario. I do have some tricks for dealing with that though.

**Comment by sharwell** [comment]
📝 Waiting until #7753 is merged before merging this one. The reduced delay increases the chances of hitting the failure that #7753 fixes.

**Comment by RussKie** [comment]
> I do have some tricks for dealing with that though.

That would be good :)

**Pull request merged**
