### PR TITLE
Remove BinaryFormatter. Fixes #9150

### LINKED ISSUE #9150: Resolve SYSLIB0011 / replace `BinaryFormatter`
## Current behaviour

We use the `BinaryFormatter` which is deprecated in .NET 5.0. The obsoletions are currently suppressed with [SYSLIB0011](https://docs.microsoft.com/dotnet/core/compatibility/syslib-warnings/syslib0011), and ultimately must be addressed by replacing the BF with a more appropriate serialiser (e.g. xml, json, etc.).

https://github.com/gitextensions/gitextensions/blob/d488e497cc6244483794abedb8e4779495ba861c/GitCommands/CommitTemplateItem.cs#L93

A cursory look suggest the BF was used in early versions of the app, and exists for a backwards compatibility purposes. A deeper investigation is in order, but very likely it can be just removed.

## Expected behaviour

No `BinaryFormatter` references and no SYSLIB0011 suppressions.

### PR DESCRIPTION
**Pull request by GintasS**
Fixes #9150

## Proposed changes

- Removed BinaryFormatter code after @pmiossec discovery.
- 
- 

## Test methodology 

- Current tests were used.
- 
- 

## Test environment(s) 

GIT 2.21.0.windows.1
Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by GintasS** [comment]
Same tests fail on this one too locally, so I'm going to disregard them.

image

**Review by RussKie — APPROVED** [review]

**Review by pmiossec — APPROVED** [review]
I wonder only on the commit message that I find misleading.

Is something like that better?

"Remove no more used BinaryFormatter for commit template"

**Comment by GintasS** [comment]
> I wonder only on the commit message that I find misleading.
> 
> Is something like that better?
> 
> "Remove no more used BinaryFormatter for commit template"

Done.

**Comment by GintasS** [comment]
Should I commit something or how can I rerun a AppVeyor build?

**Comment by pmiossec** [comment]
> 
> 
> Should I commit something or how can I rerun a AppVeyor build? Seems to fail for no reason, at least not in regards to this PR.

I have re-launched the build of the PR. Failed again.

I don't know if it is linked to https://github.com/gitextensions/gitextensions/issues/9273#issuecomment-876870135

If that is the case, could you rebase your work on top of master.

Note: to trigger again a build, you could close and then reopen the PR.

**Comment by GintasS** [comment]
> > Should I commit something or how can I rerun a AppVeyor build? Seems to fail for no reason, at least not in regards to this PR.
> 
> I have re-launched the build of the PR. Failed again.
> 
> I don't know if it is linked to [#9273 (comment)](https://github.com/gitextensions/gitextensions/issues/9273#issuecomment-876870135)
> 
> If that is the case, could you rebase your work on top of updated master.
> 
> Note: to trigger again a build, you could close and then reopen the PR.

Will try. Thanks!

**Comment by pmiossec** [comment]
It seems to have worked. I think we are good to merge it...

**Pull request merged**
