### PR TITLE
perf(FormResetAnotherBranch): Use quicker command

### LINKED ISSUE #12035: The "Reset another branch to here..." option hangs in a large repo
### Environment

- GitExtensions version: 5.1.1.17970
- GIT version: Git 2.47.0.windows.2
- OS version: Microsoft Windows NT 10.0.22631.0
- .NET version: 8.0.10

### Issue description

Background: We have a multi-GB repo, and we typically use multiple worktrees, partial clone and sometimes shallow clone. As far as I know, the only relevant consideration to this issue is the *size* of the repo, which on clients is normally 5-10GB

When we use "Reset another branch to here..." in this repo, the `git push` command that Git Extensions uses internally hangs... possibly forever, or possibly just a really long time.

### Steps to reproduce

* Have a very large (multi-GB) repo
* In the commit list, right-click a commit, choose "Reset another branch to here...", select a branch, check the "Force reset for a non-fast-forward reset" checkbox, and hit "OK"
* In the resulting git command dialog, the push command hangs, seemingly forever.

### Did this work in previous version of GitExtensions?

(unknown)

### Diagnostics

The same `git push` command also hangs outside Git Extensions - the problem is not the Git Extensions environment, but rather the use of `git push` as a "strategy" to reset non-checked-out branches.

FWIW, with `GIT_TRACE=2` set, the trace looks something like this:

```
$ GIT_TRACE=2 "C:\Program Files\Git\bin\git.exe" push . "285b5c7faf1a1d136f8c2e05090686a9e9c48ee4:refs/heads/t/us/our-feature-branch" --force
10:29:29.973108 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:29:29.990476 git.c:479               trace: built-in: git push . 285b5c7faf1a1d136f8c2e05090686a9e9c48ee4:refs/heads/t/us/our-feature-branch --force
10:29:30.004591 run-command.c:667       trace: run_command: unset GIT_DIR GIT_PREFIX; 'git-receive-pack '\''.'\'''
10:29:30.004591 run-command.c:928       trace: start_command: 'C:/Program Files/Git/usr/bin/sh.exe' -c 'git-receive-pack '\''.'\''' 'git-receive-pack '\''.'\'''
10:29:30.114677 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:29:30.114677 git.c:479               trace: built-in: git receive-pack .
10:29:30.146019 run-command.c:667       trace: run_command: 'C:\myhooks\githooks/pre-push' . .
10:29:30.146019 run-command.c:928       trace: start_command: 'C:\myhooks\githooks/pre-push' . .
Some message from the hook.
10:29:30.209260 run-command.c:667       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
10:29:30.209260 run-command.c:928       trace: start_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
10:29:30.226093 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:29:30.240649 git.c:479               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
10:29:30.303687 run-command.c:667       trace: run_command: GIT_ALTERNATE_OBJECT_DIRECTORIES=C:/myrepo/objects GIT_OBJECT_DIRECTORY=C:/myrepo/objects/tmp_objdir-incoming-a48352 GIT_QUARANTINE_PATH=C:/myrepo/objects/tmp_objdir-incoming-a48352 git unpack-objects --pack_header=2,0
10:29:30.303687 run-command.c:928       trace: start_command: git unpack-objects --pack_header=2,0
remote: 10:29:30.335276 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
remote: 10:29:30.335276 git.c:479               trace: built-in: git unpack-objects --pack_header=2,0
```

I'm not sure offhand what a better (better-scaling) strategy for performing this operation might be. The best I've come up with so far is a bash one-liner:
`target_branch=t/us/our-feature-branch new_hash=285b5c7faf1a1d136f8c2e05090686a9e9c48ee4; [[ $(git worktree list --porcelain) == *"refs/heads/$target_branch"* ]] && echo "Aborting; Branch checked out in a wortktree!" || git update-ref "refs/heads/$target_branch" $new_hash`

### PR DESCRIPTION
**Pull request by mstv**
Fixes #12035

## Proposed changes

- FormResetAnotherBranch: Use quicker command "update-ref"
- Enable the `OK` button using a dry-run of the previous command "push" 

## Screenshots 

N/A

## Test methodology 

- add testcase

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
@pmiossec update-ref was discussed when the command was added. Do you remember why it was not used?

**Comment by mstv** [comment]
> @pmiossec update-ref was discussed when the command was added. Do you remember why it was not used?

https://github.com/gitextensions/gitextensions/issues/12035#issuecomment-2471703842

**Comment by pmiossec** [comment]
> @pmiossec update-ref was discussed when the command was added. Do you remember why it was not used?

I have not found such discussion and from what I remembered it was from the beginning using 'push' because I remembered that it was a clever use of it to have this security check.

But I might be wrong because I didn't remembered that *I* contributed this very useful feature 😅
Pretty sure because the original idea was from @mdonatas .
Maybe he will remember better.

I still have to find some time* to have a look at the PR but it seems to be a clever move as the security check is still there.

If the dry-run deliver the perf improvement, it's great.
I still don't get why the push is slower than the update-ref but if the improvement is there I think it is a good comprise.

I wanted to have a look at it to be sure we don't have a regression at the security check because it is a very important point for me. But I was really waiting for the perf improvement feedback from the user and as far as I known we still not have it...

*: and it will maybe be difficult in the near future due to some health problems taking some time and energy to settle...

**Comment by mdonatas** [comment]
This was done so long ago that I have no clue. But it's very likely that I didn't know of the `update-ref` existence at the time.

**Review by pmiossec — APPROVED** [review]

**Pull request merged**
