### PR TITLE
Flatpak package

### LINKED ISSUE #6208: Standalone packages for Linux
Hi,

It would be great if we have installation options like:

- standalone package (portable)
- snap (snapcraft.io)
- appImage
- nix package (nixos.org/nix)
- flatpak

Thanks in advance

### PR DESCRIPTION
**Pull request by Murmele**
This pull request includes a flatpak manifest to build a flatpak package.
Fixes #6208

TODO:
- create flatpak ref for flathub
- testing

How do I create a mono package for a newer version, because I just found the mono package for 2.5.1

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

### CODE REVIEW

**Comment by gerhardol** [comment]
This PR should probably be targeted to release/2.51 as master is not working in mono

**Comment by Murmele** [comment]
Yes I see. Hopefully it is easy to adapt to 3.x when Mono supports C#7 :)

**Comment by gerhardol** [comment]
Another way back to multi platform is .NET Core 3 and if someone ports WinForms (recently open sourced) to *nix. Not much happened to WinForms support in mono the last 10 years.

**Comment by RussKie** [comment]
Once WinForms .NET Core is shipped, we can consider moving to it.

I've seen people already started building WinForms on OSX.

**Comment by RussKie** [comment]
Closing as stale.

**Pull request closed without merging**
