### PR TITLE
Improve fixup commits

### PR DESCRIPTION
**Pull request by pmiossec**
Changes acted on issue #3256

* Change the labels
* Add some docs on modifying git history
* Add a contextual menu item to open the manual at the right place

### CODE REVIEW

**Comment by pmiossec** [comment]
I couldn't have tested the generated doc and I don't know a lot in restructuredtext synthax, so I hope it is good...

**Comment by jbialobr** [comment]
Can you create a PR to the doc repo?

**Comment by pmiossec** [comment]
ok. I will do it...

**Comment by pmiossec** [comment]
done

**Pull request merged**
